-- ============================================================
-- API Testing Masterclass — Module 10 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/istqb-module10.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$Scrum for Testers$L$, $L$14 minute read$L$, $L$Agile delivery changes when and how testing happens. Scrum is the most common framework you will meet, so before anything else you need a clear picture of the tester's role inside a Scrum team.$L$, array[$L$Describe the core Scrum roles, events and artefacts$L$, $L$Explain how the tester works within a cross-functional Scrum team$L$, $L$Contrast the tester’s role in Agile with a traditional sequential lifecycle$L$], $L$## Scrum in one paragraph
Scrum is an Agile framework that delivers software in short, fixed-length **iterations** called sprints (typically one to four weeks). Work is pulled from a prioritised **product backlog**, planned into a **sprint backlog**, and delivered as a potentially releasable **increment** each sprint.

## The three roles
- **Product Owner** — owns and prioritises the backlog; decides *what* is built.
- **Scrum Master** — a servant-leader who removes impediments and protects the process.
- **Development Team** — a cross-functional group that builds the increment. In Scrum there is **no separate "test team"**; testers are members of the development team.

## Where the tester fits
In Agile the tester is **embedded** in the team, not a downstream gate. Testing is a **whole-team responsibility**: the tester brings a quality mindset, builds test automation, pairs with developers, and helps clarify requirements *before* code is written. Testing happens continuously, not in a phase at the end.

## Key mindset shift
Quality is built in, not inspected in. The tester coaches the team on quality, champions early feedback, and treats every backlog item as testable only when it is well understood.$L$, $L$A three-person team pulls the story "customer can reset password" into a two-week sprint. On day one the tester joins the developer to agree what "done" looks like, drafts test ideas from the acceptance criteria, and automates the happy path as the code appears — so by the sprint review the story is already tested, not queued for a later "test phase".$L$, $L$- Treating the tester as a separate QA gate at the end of the sprint
- Assuming "Agile means no documentation or no testing"
- Waiting for a finished build before starting any test activity$L$, $L$In a healthy Scrum team the tester is involved from the first conversation about a story. If you only see the work when it is "ready for test", you are already too late to influence quality cheaply.$L$, $L$In two or three sentences, describe how a tester's day differs in a Scrum team compared with a traditional sequential project.$L$, $L$In Scrum, is testing the job of a separate test team or of the whole development team?$L$, $L$In Scrum, whose responsibility is testing? (Answer: the whole cross-functional development team — there is no separate test team)$L$, array[$L$I can name the three Scrum roles$L$, $L$I can explain where the tester fits in a Scrum team$L$, $L$I understand testing as a whole-team responsibility$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$Agile Ceremonies$L$, $L$15 minute read$L$, $L$Scrum is held together by five recurring events. Each one is an opportunity for the tester to shape quality — if you know what to contribute to it.$L$, array[$L$Name the five Scrum events and their purpose$L$, $L$Describe the tester’s contribution to each ceremony$L$, $L$Explain why backlog refinement matters for testability$L$], $L$## The five events (from a QA view)
1. **Sprint Planning** — the team agrees what it will deliver this sprint. The tester challenges vague stories, estimates test effort, and raises risks and testability concerns early.
2. **Daily Scrum (stand-up)** — a short daily sync on progress and impediments. The tester reports test progress, flags blocked items, and surfaces defects that put the sprint goal at risk.
3. **Sprint Review** — the team demonstrates the increment to stakeholders and gathers feedback. The tester helps show working, tested software and confirms acceptance criteria are met.
4. **Sprint Retrospective** — the team inspects *how* it worked and agrees improvements. The tester raises quality trends, flaky tests, and process friction.
5. **Backlog Refinement** — an ongoing activity to clarify, estimate and split upcoming items. This is the tester’s best chance to make stories **testable** before they enter a sprint.

## Why this matters
Ceremonies are not overhead — they are the feedback loops that let the team inspect and adapt. A tester who shows up prepared turns each event into a chance to catch ambiguity and risk before it becomes a defect.$L$, $L$During backlog refinement the tester reads a story: "user can search products." She asks: search by what fields? What about no results, special characters, or 10,000 matches? The story is split into three smaller, testable stories with clear acceptance criteria — preventing a vague, untestable item from ever reaching sprint planning.$L$, $L$- Treating ceremonies as status meetings the tester passively attends
- Skipping backlog refinement, then discovering stories are untestable mid-sprint
- Using the retrospective to blame rather than to improve the process$L$, $L$Backlog refinement is the single highest-leverage ceremony for a tester. Fixing an ambiguous requirement there costs a sentence; fixing it after coding costs a defect, a fix and a re-test.$L$, $L$Pick one ceremony and write down two concrete things a tester should bring to it.$L$, $L$Which ceremony gives the tester the best opportunity to influence the testability of a story before it is built?$L$, $L$Which Scrum event is the tester’s best chance to make upcoming stories testable before a sprint? (Answer: backlog refinement)$L$, array[$L$I can name the five Scrum events$L$, $L$I can describe the tester’s role in each$L$, $L$I understand why refinement matters for testability$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$User Stories$L$, $L$14 minute read$L$, $L$In Agile, requirements usually arrive as user stories. A well-formed story is testable; a poor one is a trap. The INVEST model tells you which is which.$L$, array[$L$Explain the standard user story format$L$, $L$Apply the INVEST criteria to assess a story$L$, $L$Explain the tester’s role in the "three Cs" of a story$L$], $L$## The user story format
A user story captures a requirement from a user’s perspective, usually as:

> **As a** [type of user], **I want** [some goal], **so that** [some benefit].

It is a placeholder for a conversation, not a complete specification.

## The three Cs
- **Card** — the short written story.
- **Conversation** — the discussion that fleshes out the detail (testers are essential here).
- **Confirmation** — the acceptance criteria that confirm it is done.

## INVEST — the quality checklist for a story
- **I**ndependent — can be built and tested on its own.
- **N**egotiable — not a rigid contract; details emerge in conversation.
- **V**aluable — delivers value to a user or customer.
- **E**stimable — the team can size it.
- **S**mall — fits comfortably in a single sprint.
- **T**estable — you can define how to prove it is done.

## The tester’s role
Testers are the guardians of the **T** in INVEST. If you cannot describe how you would test a story, it is not ready — push back during refinement.$L$, $L$A story reads: "As a shopper, I want to filter products, so that I find items faster." The tester asks: filter by what? Combined filters? What if nothing matches? These questions expose that the story is not yet **Small** or **Testable**, and it is split into "filter by price" and "filter by category", each with clear confirmation criteria.$L$, $L$- Treating the story card as a complete specification and skipping the conversation
- Accepting stories that are too big to finish or too vague to test
- Forgetting the "so that..." — losing the *why* that guides testing$L$, $L$The Testable in INVEST is your veto. If you genuinely cannot say how you would confirm a story is done, that is objective evidence it is not ready — and a far stronger argument than "it feels vague".$L$, $L$Take a feature you know and write it as a user story in the "As a… I want… so that…" format, then check it against all six INVEST letters.$L$, $L$Which INVEST letter is most directly the tester’s responsibility, and why?$L$, $L$In INVEST, which letter means you can define how to confirm the story is done? (Answer: T — Testable)$L$, array[$L$I can write a story in the standard format$L$, $L$I can apply all six INVEST criteria$L$, $L$I understand the three Cs and the tester’s role in them$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$Acceptance Criteria$L$, $L$15 minute read$L$, $L$Acceptance criteria turn a user story into something you can objectively confirm. Written well — often in Given/When/Then — they are the tester’s most powerful tool for removing ambiguity.$L$, array[$L$Define acceptance criteria and their purpose$L$, $L$Write acceptance criteria in the Given/When/Then format$L$, $L$Use acceptance criteria to derive acceptance tests$L$], $L$## What acceptance criteria are
**Acceptance criteria** are the conditions a user story must satisfy to be accepted by the user, customer or Product Owner. They are the **confirmation** part of the three Cs — the objective, agreed definition of "done for this story".

## Two common styles
1. **Scenario-based (Given/When/Then)** — borrowed from Behaviour-Driven Development (BDD):
   - **Given** some initial context,
   - **When** an event occurs,
   - **Then** an expected outcome should result.
2. **Rule-based** — a simple checklist of conditions (e.g. "password must be at least 8 characters").

## Why testers love Given/When/Then
The format maps almost directly onto test cases: the **Given** is your precondition and test data, the **When** is your action, and the **Then** is your expected result. A story with good acceptance criteria is a story that has already sketched its own tests.

## Acceptance test-driven development (ATDD)
When the team agrees acceptance criteria *before* coding, developers know exactly what to build and testers know exactly what to check. This collaborative, up-front approach is the essence of ATDD.$L$, $L$Story: "As a customer, I want to reset my password." One acceptance criterion becomes:
**Given** I am on the reset page and my account exists,
**When** I submit my registered email,
**Then** I receive a reset link within 60 seconds.
That single scenario tells the tester the precondition, the action, and the exact expected result — a ready-made acceptance test.$L$, $L$- Writing criteria so vague they can’t be objectively passed or failed
- Only covering the happy path and ignoring negative and edge scenarios
- Writing acceptance criteria *after* the code, so they merely describe what was built$L$, $L$Insist that acceptance criteria are agreed before development starts. Criteria written after the code just rubber-stamp whatever was built — they lose their power to catch a misunderstanding early.$L$, $L$Write one Given/When/Then acceptance criterion for a "log in with email and password" story, then add one for the wrong-password case.$L$, $L$In Given/When/Then, which clause maps to the tester’s expected result?$L$, $L$In a Given/When/Then acceptance criterion, which clause states the expected outcome? (Answer: the Then clause)$L$, array[$L$I can define acceptance criteria$L$, $L$I can write criteria in Given/When/Then$L$, $L$I can turn criteria into acceptance tests$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Definition of Done$L$, $L$14 minute read$L$, $L$Acceptance criteria say when *one story* is finished. The Definition of Done says when *any* piece of work meets the team’s quality bar. Confusing the two is one of the most common Agile mistakes.$L$, array[$L$Define the Definition of Done and its purpose$L$, $L$Distinguish the Definition of Done from acceptance criteria$L$, $L$Explain how the Definition of Done supports quality and transparency$L$], $L$## What the Definition of Done is
The **Definition of Done (DoD)** is a shared, team-wide checklist of the conditions that *every* backlog item (and often the whole increment) must meet before it can be called complete. It is a quality gate the team agrees and applies consistently.

A typical DoD includes: code reviewed, unit tests written and passing, acceptance criteria met, automated regression passing, no known critical defects, and documentation updated.

## DoD vs acceptance criteria — the crucial distinction
- **Acceptance criteria** are **specific to one story** — they describe *what* that story must do.
- **Definition of Done** is **common to all stories** — it describes the *quality bar* every story must clear (testing, review, standards).

A story can meet its acceptance criteria yet still fail the DoD — for example, if it works but has no automated tests or was never code-reviewed.

## Why it matters
The DoD creates a shared, honest understanding of "done" and prevents the classic trap of work being "done" but not really finished. It supports **transparency**: everyone — developers, testers and stakeholders — knows exactly what "done" guarantees.$L$, $L$A developer says a story is "done" because the feature works on their machine. The team’s DoD, however, requires code review, passing unit tests and a green regression run. None of those are complete — so despite meeting the story’s acceptance criteria, it is **not done**. The DoD stops half-finished work being declared complete.$L$, $L$- Confusing acceptance criteria (per story) with the Definition of Done (team-wide)
- Declaring work "done" when it only meets acceptance criteria but not the quality bar
- Having a DoD that exists on paper but is never actually enforced$L$, $L$A Definition of Done that isn’t enforced is just wishful thinking. The value is in the discipline of refusing to call anything "done" until every item on the list is genuinely ticked.$L$, $L$Write down four items you would put in a Definition of Done for a web-application team.$L$, $L$Which is specific to a single story — acceptance criteria or the Definition of Done?$L$, $L$Which applies to every backlog item as a shared quality bar rather than to just one story: acceptance criteria or the Definition of Done? (Answer: the Definition of Done)$L$, array[$L$I can define the Definition of Done$L$, $L$I can distinguish it from acceptance criteria$L$, $L$I can list realistic DoD items$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 6, $L$Exploratory Testing in Agile$L$, $L$18 minute read$L$, $L$Scripted tests confirm what you expect; exploratory testing discovers what you didn’t. In Agile’s fast cycles, structured exploratory testing — driven by charters and time-boxed sessions — is one of the tester’s most valuable techniques.$L$, array[$L$Define exploratory testing and where it fits in Agile$L$, $L$Explain session-based test management and test charters$L$, $L$Contrast exploratory testing with scripted testing$L$], $L$## What exploratory testing is
**Exploratory testing** is an approach where test design, test execution and learning happen **simultaneously**. The tester actively explores the software, using the results of each test to guide the next. It is structured and purposeful — not random "clicking about".

## Why it suits Agile
Agile delivers change quickly and often with lightweight documentation. Exploratory testing thrives here because it needs little up-front scripting, adapts instantly to new builds, and is excellent at finding the defects that scripted tests — which only check what you already anticipated — will always miss.

## Session-based test management (SBTM)
To keep exploration accountable, testers use **session-based test management**:
- Work is organised into **time-boxed sessions** (typically 60–90 minutes, uninterrupted).
- Each session is guided by a **test charter** — a short mission statement saying *what* to explore and *why* (for example: "Explore the checkout with invalid discount codes to discover pricing errors").
- The tester records findings, coverage and questions in **session notes**, then **debriefs** with the team.

## Exploratory vs scripted
Both have their place. Scripted testing gives repeatable, auditable coverage of known cases; exploratory testing finds the unknown unknowns. In Agile you typically combine them: automate the scripted regression, and spend human time exploring.$L$, $L$A tester is given a charter: "Explore the new file-upload feature to discover how it handles unusual files, time-box 60 minutes." Within the session she tries a 0-byte file, a 2 GB file, a file with an emoji in the name, and a .exe renamed to .jpg — finding two crashes no acceptance criterion had mentioned. The charter kept her focused; the freedom let her find the surprises.$L$, $L$- Confusing exploratory testing with unstructured, undocumented "ad-hoc clicking"
- Running exploratory sessions with no charter, so coverage can’t be reasoned about
- Relying only on scripted tests and never leaving time to explore$L$, $L$A charter plus a time-box turns "have a play with it" into a professional, accountable activity. You can report exactly what you explored, what you found, and what you still have questions about — which is what earns exploratory testing its place in the plan.$L$, $L$Write a test charter for exploring a login feature: state what you’ll explore, why, and a time-box.$L$, $L$In exploratory testing, what happens at the same time that is normally separated in scripted testing?$L$, $L$In exploratory testing, which activities happen at the same time? (Answer: test design, test execution and learning happen simultaneously)$L$, array[$L$I can define exploratory testing$L$, $L$I can write a test charter and run a time-boxed session$L$, $L$I can contrast exploratory with scripted testing$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

