-- ============================================================
-- API Testing Masterclass — Module 3 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/api-module3.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$JSON Structure & Data Types$L$, $L$12 minute read$L$, $L$JSON is the format almost every modern API speaks. Before you can assert on a response, you need to read its shape and know exactly what data types it uses.$L$, array[$L$Describe the two JSON container types$L$, $L$Name the six JSON value types$L$, $L$Tell a string from a number, boolean and null$L$], $L$## What JSON is
**JSON** (JavaScript Object Notation) is a lightweight text format for structured data. It is human-readable, language-agnostic, and the default body type for REST APIs.

## Two containers
- **Object** — an unordered set of key/value pairs inside `{ }`. Keys are always double-quoted strings: `{ "name": "Ada" }`.
- **Array** — an ordered list inside `[ ]`: `[ "a", "b", "c" ]`.

## Six value types
1. **String** — always double quotes: `"hello"`
2. **Number** — no quotes, integer or decimal: `42`, `3.14`
3. **Boolean** — `true` or `false` (no quotes)
4. **Null** — `null` (means "no value", not the same as `0` or `""`)
5. **Object** — nested `{ }`
6. **Array** — nested `[ ]`

## Why type matters
`"42"` (string) and `42` (number) are different values. A test that expects a number but gets a string will — or should — fail. Reading types correctly is the foundation of every JSON assertion you'll write.$L$, $L$A user response: `{ "id": 7, "name": "Ada", "active": true, "nickname": null, "roles": ["admin","qa"] }`. Here `id` is a **number**, `name` is a **string**, `active` is a **boolean**, `nickname` is **null**, and `roles` is an **array of strings**. Five different types in one small object.$L$, $L$- Treating `"42"` (string) and `42` (number) as the same value
- Thinking `null` means `0` or an empty string
- Forgetting JSON keys and strings must use double quotes, never single$L$, $L$The most common JSON bug in the wild is a field that switches type between builds — an `id` that was a number quietly becomes a string. Assert on the type, not just the value.$L$, $L$Take the JSON `{ "price": 9.99, "inStock": false, "tags": ["sale"], "note": null }` and write down the data type of each of the four values.$L$, $L$Why is `"42"` not the same value as `42` in JSON?$L$, $L$Which two JSON types are containers that hold other values? (Answer: object and array)$L$, array[$L$I can name the two JSON containers$L$, $L$I can name the six JSON value types$L$, $L$I can tell a string from a number, boolean and null$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 3
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$Navigating Nested JSON$L$, $L$13 minute read$L$, $L$Real API responses are rarely flat — objects contain objects, and arrays contain more objects. This lesson teaches the path notation you'll use to reach any value.$L$, array[$L$Use dot notation to reach nested object fields$L$, $L$Use bracket notation to reach array elements$L$, $L$Combine both to reach deeply nested values$L$], $L$## Dot notation for objects
To reach a field inside an object, chain keys with dots. Given `{ "user": { "address": { "city": "Leeds" } } }`, the path to the city is `user.address.city`.

## Bracket notation for arrays
Arrays are **zero-indexed** — the first element is `[0]`. Given `{ "roles": ["admin","qa"] }`, `roles[0]` is `"admin"` and `roles[1]` is `"qa"`.

## Combining the two
Most paths mix both. Given an `orders` array of objects, the first order's total is `orders[0].total`; the second item on the first order is `orders[0].items[1]`.

## A note on the root
Some responses are an array at the **top level**: `[ { "id": 1 }, { "id": 2 } ]`. Then the first id is simply `[0].id` — there's no wrapping key.

## Why this matters
Every JSON assertion and every JSON Schema you write starts by naming a path. Get the path wrong and the test fails for the wrong reason — a "missing" field that was really one bracket away.$L$, $L$Response: `{ "user": { "name": "Ada", "orders": [ { "id": 1, "items": ["mug"] }, { "id": 2, "items": ["pen","pad"] } ] } }`. Path `user.name` → `"Ada"`. Path `user.orders[1].id` → `2`. Path `user.orders[1].items[0]` → `"pen"`.$L$, $L$- Starting arrays at `[1]` — JSON arrays are zero-indexed, so the first element is `[0]`
- Using dot notation on an array (`orders.0`) instead of a bracket (`orders[0]`)
- Forgetting the response root can itself be an array, so paths start with `[0]`$L$, $L$When a path fails, paste the response into a JSON viewer that shows the exact path on hover. It turns "why is this null?" into a five-second answer.$L$, $L$Given `{ "data": { "items": [ { "sku": "A1" }, { "sku": "B2" } ] } }`, write the path that returns `"B2"`.$L$, $L$What is the index of the first element in a JSON array, and why does it matter?$L$, $L$In the object `{ "user": { "roles": ["admin","qa"] } }`, what does the path `user.roles[1]` return? (Answer: "qa")$L$, array[$L$I can reach object fields with dot notation$L$, $L$I can reach array elements with bracket notation$L$, $L$I can combine both to reach a deeply nested value$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 3
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Asserting on JSON Responses$L$, $L$25 minutes$L$, $L$Reading JSON is passive; asserting on it is testing. In this hands-on lesson you write real Postman tests that check status, values and types in a JSON response.$L$, array[$L$Write a Postman test that asserts a JSON field value$L$, $L$Assert on a nested field and its data type$L$, $L$Explain why a specific assertion beats a vague one$L$], $L$## The three things worth asserting
1. **Status** — did the request succeed? `pm.response.to.have.status(200)`
2. **Value** — is a field what you expect? `expect(body.id).to.eql(7)`
3. **Type** — is it the right kind of value? `expect(body.id).to.be.a('number')`

## Writing tests in Postman
Postman's **Tests** tab runs JavaScript after the response arrives. Parse the body once, then assert:
```
const body = pm.response.json();
pm.test('id is 7 and a number', () => {
  pm.expect(body.id).to.eql(7);
  pm.expect(body.id).to.be.a('number');
});
```

## Nested and array assertions
Use the paths from Lesson 2: `body.user.orders[0].id`. Assert on what actually matters — the values a real user or downstream system depends on.

## Specific beats vague
`expect(body).to.exist` passes on almost anything. `expect(body.status).to.eql('active')` fails the moment the value is wrong. A good assertion is a **narrow** one.$L$, $L$For `GET https://jsonplaceholder.typicode.com/users/1`, the Tests tab: `const b = pm.response.json();` then `pm.test('user 1', () => { pm.expect(pm.response.code).to.eql(200); pm.expect(b.id).to.eql(1); pm.expect(b.name).to.be.a('string'); pm.expect(b.address.city).to.exist; });`. This checks status, a value, a type and a nested field in one test.$L$, $L$- Asserting only `to.exist` when you could assert the exact value
- Calling `pm.response.json()` many times instead of parsing once into a variable
- Checking the value but never the type, so a `"7"` string slips past$L$, $L$Write assertions a future teammate can read. `pm.test('order total includes VAT', ...)` documents intent far better than `pm.test('test1', ...)`.$L$, $L$In Postman, send `GET https://jsonplaceholder.typicode.com/users/1` and add a test that asserts the status is 200, `id` equals 1, and `name` is a string. Confirm all assertions pass.$L$, $L$Why is asserting an exact value more useful than asserting only that a field exists?$L$, $L$In a Postman test, which method parses the response body into a JSON object? (Answer: pm.response.json())$L$, array[$L$I wrote a Postman test that asserts a field value$L$, $L$I asserted on a nested field and a data type$L$, $L$All my assertions passed against a live response$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 3
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$JSON Schema Validation$L$, $L$14 minute read$L$, $L$Checking fields one by one doesn't scale. JSON Schema lets you validate the whole shape of a response — its fields, types and required keys — in a single assertion.$L$, array[$L$Explain what a JSON Schema describes$L$, $L$Read the key schema keywords (type, properties, required)$L$, $L$Validate a response against a schema in Postman$L$], $L$## What a schema is
A **JSON Schema** is itself a JSON document that describes the *expected structure* of another JSON document — which fields exist, their types, and which are mandatory. It's a contract you can test against automatically.

## The core keywords
- `type` — the expected type (`"object"`, `"array"`, `"string"`, `"number"`, `"boolean"`, `"null"`)
- `properties` — the fields of an object and each field's own schema
- `required` — an array of keys that **must** be present
- `items` — the schema every element of an array must match

## A minimal schema
```
{
  "type": "object",
  "properties": {
    "id":   { "type": "number" },
    "name": { "type": "string" }
  },
  "required": ["id", "name"]
}
```

## Why schemas beat field-by-field checks
One schema catches a missing field, a wrong type and an unexpected shape all at once. When an API changes its contract, a schema test goes red immediately — which is exactly the early warning you want.$L$, $L$In Postman's Tests tab: define the schema above as `const schema = {...}`, then `pm.test('matches schema', () => { pm.expect(pm.response.json()).to.be.jsonSchema ? null : null; });`. In practice Postman ships `tv4`/`ajv`: `const v = pm.response.to.have.jsonSchema(schema);` — if `id` comes back as `"7"` (string), validation fails because the schema demands a `number`.$L$, $L$- Confusing the schema (the contract) with the data (the response it validates)
- Leaving `required` empty, so a schema passes even when key fields are missing
- Writing a schema so loose (`type: object` only) that it never catches anything$L$, $L$Keep the schema in version control next to the tests. When it changes, the diff tells the whole team the API contract has moved — a conversation you want to have before release, not after.$L$, $L$Write a JSON Schema for `{ "id": 1, "email": "a@b.com" }` where both fields are required, `id` is a number and `email` is a string.$L$, $L$What does adding a key to the `required` array change about how a schema validates a response?$L$, $L$Which JSON Schema keyword lists the fields that must be present? (Answer: required)$L$, array[$L$I can explain what a JSON Schema describes$L$, $L$I can read type, properties and required$L$, $L$I validated a response against a schema in Postman$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 3
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Working with XML$L$, $L$13 minute read$L$, $L$JSON dominates modern APIs, but XML is far from dead — SOAP services, banking, government and older enterprise systems still use it. This lesson gives you the essentials to read and assert on XML.$L$, array[$L$Read the anatomy of an XML document$L$, $L$Compare XML and JSON structurally$L$, $L$Use a basic XPath expression to select a node$L$], $L$## XML anatomy
XML uses nested **elements** with opening and closing tags: `<user><name>Ada</name></user>`. Elements can carry **attributes**: `<user id="7">`. Unlike JSON, there is a single **root element** wrapping everything, and order is significant.

## XML vs JSON
- JSON has typed values; XML is text by default (`<id>7</id>` is a string until something parses it).
- JSON uses `{ }` and `[ ]`; XML uses tags and nesting.
- XML has attributes *and* elements for data; JSON has only keys/values.
- XML is more verbose but supports namespaces and schemas (XSD).

## Selecting nodes with XPath
**XPath** is to XML what dot/bracket paths are to JSON. Given `<order><item>mug</item><item>pen</item></order>`:
- `/order/item` selects both `item` elements
- `/order/item[1]` selects the first (XPath is **one-indexed**, not zero)
- `//item` selects every `item` anywhere in the document
- `/user/@id` selects the `id` attribute

## In Postman
Postman parses XML with `xml2Json(pm.response.text())`, turning it into a JSON-like object you can then assert on with the same techniques from Lesson 3.$L$, $L$A SOAP-style response: `<order id="99"><customer>Ada</customer><total>19.99</total></order>`. XPath `/order/@id` returns `"99"`; `/order/total` returns the element whose text is `19.99`. In Postman: `const x = xml2Json(pm.response.text()); pm.expect(x.order.customer).to.eql('Ada');`.$L$, $L$- Assuming XPath is zero-indexed — it is **one-indexed**, so the first node is `[1]`
- Treating XML element text as typed — `<total>19.99</total>` is a string until you parse it
- Ignoring namespaces, which can make an otherwise-correct XPath select nothing$L$, $L$If you're handed a SOAP service, ask for its WSDL/XSD first. It's the contract — it tells you every element, type and namespace before you send a single request, saving hours of guesswork.$L$, $L$In Postman, send a request to any XML endpoint (or paste a sample response into the body), use `xml2Json` in the Tests tab, and assert on one element value. If you have no XML API handy, use the sample `<order id="99"><total>19.99</total></order>`.$L$, $L$Name one structural feature XML has that JSON does not, and why it can complicate XPath.$L$, $L$In XPath, what index is the first element — 0 or 1? (Answer: 1 — XPath is one-indexed)$L$, array[$L$I can read the anatomy of an XML document$L$, $L$I can compare XML and JSON structurally$L$, $L$I can write a basic XPath expression$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 3
on conflict (module_id, lesson_number) do nothing;

