-- Combined Playwright Automation enhancements (all 12 modules). Requires lesson-enhancements-schema.sql. Idempotent.

-- ▶ Module 1
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 1.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module1.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A team ran a 200-check regression by hand before every release — two days of effort, and bugs still slipped through from fatigue. Automated, the same suite ran in 15 minutes on every pull request, catching breakages the same day. That shift is why teams automate.","davidTip":"Sell automation as risk reduction and fast feedback, not \"fewer testers\". In real teams, automation handles the repetitive regression so humans spend time on exploratory and risk-based work — that framing is what gets buy-in.","miniChallenge":"List three checks in an app you know that are run repeatedly and would be strong automation candidates, and one that would not be.","modelAnswer":"## Example\nAutomate: login, checkout happy path, key API endpoints (run every release, stable). Don't automate: a brand-new screen redesigned weekly, or one-off exploratory checks.","portfolioBuilder":"Your capstone is a public automation framework. Start thinking now about which journeys you'll automate — the \"what and why\" reasoning is part of what employers assess."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 1 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"A suite of 300 slow UI tests took two hours and was always flaky. Most checks could have been unit or API tests running in seconds. The pyramid is the model that stops automation becoming top-heavy and unreliable.","visualAid":{"type":"comparison","title":"The test automation pyramid","headers":["Layer","Amount","Speed / stability"],"rows":[["Unit","Most","Fastest, most stable"],["Integration / API","Some","Fast, stable"],["UI / End-to-end","Fewest","Slow, more brittle"]]},"davidTip":"When a check can live at a lower layer, put it there. UI tests are the most expensive to build and maintain — reserve them for critical journeys that truly need the browser.","miniChallenge":"Take five checks for a feature and assign each to a layer (unit/API/UI) with a one-line justification.","modelAnswer":"## Example — discount feature\nDiscount maths → unit. API applies discount → API. Invalid code rejected → API. End-to-end \"apply code at checkout\" → UI. Field validation message → unit/UI (cheapest that proves it).","resourcePreview":{"name":"Automation Best Practices Checklist","purpose":"A quality bar for what (and where) to automate.","whenToUse":"Use it when deciding scope and layer for tests.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 1 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"A login smoke test ran 30 times a week and took 5 minutes by hand. Automated in a few hours, it paid for itself within a fortnight. ROI is how you decide what is worth automating — and how you justify it to stakeholders.","davidTip":"Frame automation decisions as ROI: time saved × runs, minus build and maintenance. High ROI = run often + stable + high value. It turns \"automation is expensive\" into \"this suite saves X hours per release and protects our critical flow\".","miniChallenge":"Pick one test and estimate its ROI: how often it runs, time saved per run, and rough maintenance cost. Worth automating?","modelAnswer":"## Example\nCheckout smoke test: runs ~30×/week, saves ~5 min each (~2.5 hrs/week), built in ~3 hours, low maintenance (stable flow). Clear positive ROI — automate it."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 1 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A team automated 300 UI tests with brittle CSS selectors and fixed sleeps. Within months half were flaky, red builds got ignored, and a real bug shipped because \"the tests always fail anyway\". A flaky suite is worse than none.","badGood":{"label":"a waiting strategy","bad":"await page.waitForTimeout(3000); // hope it's loaded","good":"await expect(page.getByText('Saved')).toBeVisible(); // auto-waits"},"davidTip":"Guard trust ruthlessly. The big killers are flakiness, brittle locators and no maintenance. A small, reliable suite people act on beats a large flaky one they ignore — fix or quarantine flaky tests immediately.","miniChallenge":"Write down two reasons automation suites lose trust, and one thing you'd do to prevent each.","modelAnswer":"## Example\nFlakiness → replace fixed sleeps with web-first assertions and fix root causes. Brittle locators → use role/label locators that survive markup changes."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 1 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"Two engineers learned Playwright. One added tests constantly without pruning; the suite bloated and slowed. The other treated reliability and value as the goal, deleting and consolidating as readily as adding. The lean, trusted suite won.","davidTip":"Adopt an automation mindset before syntax: reliability over quantity, the right layer, readable and independent tests, value-driven. Ask \"should this be automated, and where?\" before \"how do I automate it?\"","miniChallenge":"Write your personal three-rule automation manifesto (e.g. \"reliable over many\"). You'll revisit it at the end of the course.","modelAnswer":"## Example\n1) Reliable over many. 2) Right layer for each test. 3) Readable, independent, value-driven. I'll delete or consolidate tests as readily as I add them.","portfolioBuilder":"This mindset shows up in your capstone: a focused, reliable framework with clear reasoning impresses far more than a large flaky one."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 1 and l.lesson_number = 5;


-- ▶ Module 2
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 2.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module2.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A vague ticket \"add login\" led to three different interpretations across the team and a rebuild. Rewritten as \"Given a registered user, When they enter valid credentials, Then they see their dashboard\", everyone agreed exactly what to build and test. That alignment is the real value of BDD.","davidTip":"BDD's payoff is the conversation it forces before coding — shared understanding between business, dev and test. The feature files are a by-product of getting everyone aligned on behaviour first.","miniChallenge":"Rewrite a vague requirement you've seen as a single Given/When/Then sentence.","modelAnswer":"## Example\nVague: \"the cart should update.\" BDD: \"Given an item in the cart, When the user changes its quantity to 3, Then the cart total updates to reflect 3 units.\""}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 2 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"A story said \"users can search\" and shipped with no handling for no-results or special characters — because the acceptance criteria never mentioned them. Strong, testable criteria are where BDD scenarios (and defects avoided) come from.","badGood":{"label":"acceptance criteria","bad":"\"Search should work well and be fast.\"","good":"\"Given a catalogue, when a user searches a term, then matching results appear within 2s; an empty term shows a prompt; a no-match shows a friendly 'no results' message.\""},"davidTip":"Treat vague acceptance criteria as a defect in the requirement. \"Should work well\" is untestable — push for specifics. Each clear criterion becomes one or more Gherkin scenarios.","miniChallenge":"Take \"As a user I can reset my password\" and write three testable acceptance criteria (include one negative).","modelAnswer":"## Example\n- Given a registered email, when I request a reset, then I get a link within 2 minutes.\n- Given an unregistered email, then I see the same confirmation (no account disclosure).\n- Given an expired link, when I use it, then I'm told it expired and offered a new one."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 2 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"A tester wrote feature steps as \"click #login-btn\" — brittle and unreadable. Switching to behaviour-level steps (\"When they sign in\") made the feature file readable by the product owner and stable against UI changes. Gherkin done well is living documentation.","visualAid":{"type":"comparison","title":"Core Gherkin keywords","headers":["Keyword","Role"],"rows":[["Feature","The capability described"],["Scenario","One concrete example of behaviour"],["Given","Starting context / pre-conditions"],["When","The action / event"],["Then","The expected outcome"]]},"davidTip":"Keep steps at the behaviour level (\"When they sign in\"), not the click level (\"click #login-btn\"). Behaviour-level steps are reusable, readable, and survive UI changes — the clicks belong in step definitions.","miniChallenge":"Write a feature file with one Feature and two scenarios (a success and a failure) for a sign-up form.","modelAnswer":"## Example\nFeature: Sign up\n  Scenario: Successful sign up\n    Given a visitor on the sign-up page\n    When they submit valid details\n    Then their account is created and they're logged in\n  Scenario: Duplicate email\n    Given an email already registered\n    When they submit it\n    Then they see \"email already in use\""}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 2 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A feature file had eight near-identical scenarios for different discount codes. Collapsed into one Scenario Outline with an Examples table, it became concise and easy to extend — adding a case is now a one-line data change.","visualAid":{"type":"comparison","title":"Scenario Outline — discount codes","headers":["code","result"],"rows":[["SAVE10","10% discount applied"],["EXPIRED","code has expired"],["INVALID","code not recognised"]]},"davidTip":"Reach for a Scenario Outline when the same steps run with different data — it's perfect for boundary and equivalence sets. Keep the table focused; huge tables hide intent.","miniChallenge":"Convert two similar scenarios into a single Scenario Outline with an Examples table.","modelAnswer":"## Example\nScenario Outline: Applying a discount code\n  When the user applies \"<code>\"\n  Then they see \"<result>\"\n  Examples: | code | result | (one row per case above)"}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 2 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"A product owner read the checkout.feature file and confirmed the rules were correct — without seeing a line of code. That is BDD working as living documentation, and it only happens when scenarios are written to be read.","davidTip":"The readability test: could a non-technical colleague read your feature file and confirm the behaviour is right? Consistent vocabulary, one behaviour per scenario, business language — that's the bar.","miniChallenge":"Review a feature file you wrote and improve it: consistent wording, one behaviour per scenario, plain language.","modelAnswer":"## Example\nBefore: a scenario testing login AND redirect AND a welcome message. After: split into focused scenarios, each asserting one behaviour, with consistent \"signs in\" wording throughout.","portfolioBuilder":"Clean, readable feature files in your capstone repo signal that you understand BDD as collaboration and documentation — not just test syntax.","resourcePreview":{"name":"Test Structure & Naming Conventions Guide","purpose":"Keep tests and scenarios readable and well-organised as the suite grows.","whenToUse":"Apply it to your feature files and spec structure.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 2 and l.lesson_number = 5;


-- ▶ Module 3
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 3.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module3.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A new engineer put locators straight into step definitions; when the UI changed, fixes were scattered everywhere. Keeping feature (what), step definition (glue) and page object (how/locators) as distinct layers is what makes a BDD framework maintainable.","visualAid":{"type":"flow","title":"Three layers of a BDD framework","steps":[{"label":"Feature file","detail":"what (behaviour)"},{"label":"Step definition","detail":"glue"},{"label":"Page object","detail":"how (locators)"}]},"davidTip":"Keep the layers separate: features describe behaviour, step definitions translate it to actions, page objects hold the locators. When the UI changes, you fix one place — that separation is the whole point.","miniChallenge":"Take one scenario and list the step definitions it needs, with a one-line note on what each will do.","modelAnswer":"## Example — \"successful login\"\nGiven a registered user → seed/ensure a user exists. When they sign in with valid credentials → loginPage.login(user, pass). Then they see the dashboard → assert dashboard heading visible."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 3 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"A Then step quietly performed a click before asserting — so when it failed, nobody could tell if the action or the check broke. Keeping Given/When/Then honest (setup / one action / assertion only) makes failures instantly diagnosable.","badGood":{"label":"a Then step","bad":"Then('dashboard shows', async () => { await page.click('text=Refresh'); await expect(heading).toBeVisible(); })","good":"Then('dashboard shows', async () => { await expect(heading).toBeVisible(); }) // assertion only"},"davidTip":"Given sets up state, When performs the single action under test, Then only asserts. If a Then needs to click something first, the scenario is probably testing two behaviours — split it.","miniChallenge":"Write the Given/When/Then step implementations (pseudocode is fine) for a login scenario, each doing only its job.","modelAnswer":"## Example\nGiven → await loginPage.goto(); (and ensure user exists)\nWhen → await loginPage.login(user, pass);\nThen → await expect(dashboard.heading()).toBeVisible();"}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 3 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"A team wrote a separate step definition for every discount code — dozens of near-identical functions. Parameterising one step to capture the code collapsed them into a single, reusable definition that pairs perfectly with Scenario Outlines.","davidTip":"Parameterise steps to capture values from the Gherkin text, so one definition serves many scenarios. Combined with Scenario Outlines, your feature files stay tiny while coverage grows.","miniChallenge":"Turn a hard-coded step (\"When the user applies SAVE10\") into a parameterised step that accepts any code.","modelAnswer":"## Example\nWhen('the user applies {string}', async (code) => { await basket.applyCode(code); }); — one definition now handles SAVE10, EXPIRED, INVALID and any future code."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 3 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"Two engineers wrote \"Given a logged-in user\" with slightly different wording, creating two near-duplicate steps. A shared step vocabulary and a common login step removed the duplication across checkout, account and dashboard features.","davidTip":"Write steps at the behaviour level so they're reusable, and agree a shared step vocabulary with your team. Most duplication comes from two people phrasing the same action differently — a glossary prevents it.","miniChallenge":"Find (or imagine) two near-duplicate steps and merge them into one reusable, well-worded step.","modelAnswer":"## Example\n\"Given the user is signed in\" and \"Given a logged-in user\" → standardise on one: \"Given a logged-in user\", reused everywhere, implemented once.","resourcePreview":{"name":"Code Review Checklist for Test Automation","purpose":"Catch duplication and brittleness in step definitions and tests.","whenToUse":"Use it when reviewing step definitions for reuse.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 3 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"A \"fat\" step definition packed with locators and waits was impossible to read or reuse. Slimmed to a single line delegating to a page object, it became clear glue — and the framework's real strength moved into well-tested page objects.","badGood":{"label":"a step definition","bad":"When('place order', async () => { await page.waitForTimeout(2000); await page.click('.checkout > button.pay'); /* + more logic */ })","good":"When('place order', async () => { await checkoutPage.placeOrder(); }) // thin glue"},"davidTip":"Keep step definitions thin — one responsibility, delegating to page objects, no hard waits. The thinner the glue, the more your framework's strength lives in tested page objects and utilities.","miniChallenge":"Refactor a \"fat\" step definition to be thin — move locators and logic into a page object.","modelAnswer":"## Example\nMoved the selector and waiting logic into checkoutPage.placeOrder(); the step becomes one readable line, and the page object can be reused and tested independently.","portfolioBuilder":"Thin, well-organised step definitions in your capstone repo demonstrate the maintainable layering that senior reviewers look for."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 3 and l.lesson_number = 5;


-- ▶ Module 4
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 4.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module4.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A new starter spent a morning fighting a broken setup before writing a single test. The ones who scaffold cleanly with npm init playwright and run the example tests first confirm a healthy base in minutes — then build on solid ground.","davidTip":"Run the bundled example tests immediately after setup. If they pass, your environment is healthy and any later failure is your code, not your config. And push to GitHub from the first commit — a public repo is portfolio gold.","miniChallenge":"Set up a fresh Playwright project (TypeScript), run the example tests, and open the HTML report.","modelAnswer":"## Example\nnpm init playwright@latest → choose TypeScript + tests folder + GitHub Actions → npx playwright test (examples pass) → npx playwright show-report. Setup confirmed healthy.","resourcePreview":{"name":"Playwright Setup Guide","purpose":"Get a clean, working Playwright + TypeScript project running from scratch.","whenToUse":"Follow it for your first project and your capstone.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 4 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"An engineer re-ran the whole suite for every tweak to one flaky test — minutes wasted each cycle. Learning to run just that test in UI mode turned a slow loop into seconds. Knowing the runner makes you dramatically faster day to day.","davidTip":"Learn -g and --ui early. Running and watching exactly the test you care about — instantly — is what makes you fast at writing and fixing automation, instead of waiting on the full suite each time.","miniChallenge":"Run a single test by title with -g, then open it in UI mode, then view the HTML report.","modelAnswer":"## Example\nnpx playwright test -g \"valid login\" --ui — runs just that test in UI mode so I can step through it; then npx playwright show-report to review."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 4 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"An automation suite broke every time designers tweaked CSS, because tests targeted div > div:nth-child(3). Switching to user-facing locators made it survive redesigns. Locators are where automation stability is won or lost.","badGood":{"label":"a locator","bad":"page.locator('div.container > div:nth-child(3) > button.btn-primary')","good":"page.getByRole('button', { name: 'Sign in' })"},"davidTip":"Locate elements the way a user describes them — \"the Sign in button\" → getByRole('button', { name: 'Sign in' }). User-facing locators survive markup changes and double as accessibility checks. Brittle CSS chains are the #1 cause of flaky UI tests.","miniChallenge":"On any page, locate five elements using only getByRole/getByLabel/getByText; fall back to getByTestId only if you truly must.","modelAnswer":"## Example\ngetByRole('button', { name: 'Sign in' }), getByLabel('Email'), getByRole('heading', { name: 'Dashboard' }), getByText('Welcome'), getByTestId('cart-total') (only because nothing user-facing was stable).","resourcePreview":{"name":"Playwright Locator Strategy Cheat Sheet","purpose":"Choose robust, user-facing locators in priority order.","whenToUse":"Keep it open while writing tests.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 4 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A test slept 5 seconds \"to be safe\" before every check — slow and still flaky under load. Replacing sleeps with web-first assertions made it both faster and reliable. Auto-waiting removes the single biggest source of flakiness.","badGood":{"label":"waiting for a result","bad":"await page.waitForTimeout(3000); expect(await toast.isVisible()).toBe(true);","good":"await expect(page.getByText('Saved')).toBeVisible(); // retries until it appears or times out"},"davidTip":"Every fixed waitForTimeout is too long (slow) or too short (flaky). Replace them all with web-first assertions that auto-retry, and wait on real events (waitForURL, waitForResponse) rather than arbitrary time.","miniChallenge":"Find a waitForTimeout in a test and replace it with a web-first assertion; confirm it still passes and runs faster.","modelAnswer":"## Example\nReplaced \"sleep 2s then check toast\" with await expect(page.getByText('Saved')).toBeVisible(); — the assertion auto-waits, so the test is faster and no longer flaky.","resourcePreview":{"name":"Playwright Assertions Cheat Sheet","purpose":"The web-first assertions you will use every day.","whenToUse":"Reference it when asserting outcomes.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 4 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"Every test repeated the same login steps in beforeEach, cluttering the specs. A custom loggedInPage fixture handed each test an authenticated page — shorter tests, setup in one place, torn down automatically.","davidTip":"Use fixtures for reusable state (a logged-in page, seeded data) and set baseURL in config so tests use relative paths. Enable retries in CI only — locally you want to see flakiness, not mask it.","miniChallenge":"Add a baseURL to your config and switch a test to a relative path; then sketch a simple custom fixture.","modelAnswer":"## Example\nuse: { baseURL: 'https://app.example.com' } → page.goto('/login'). Fixture: loggedInPage logs in once and hands tests an authenticated page, so each test skips repeated setup.","resourcePreview":{"name":"Fixtures & Hooks Guide","purpose":"Set up and tear down cleanly with fixtures and hooks.","whenToUse":"Use it when extracting shared setup.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 4 and l.lesson_number = 5;

update public.lessons l set enhancements = $ench${"industryStory":"A CI test failed and the engineer guessed for an hour. Once they enabled traces and opened the trace viewer, the cause — a click before the element was ready — was obvious in seconds. The trace viewer is Playwright's superpower.","davidTip":"Before changing any code to fix a failure, open the trace. The trace viewer shows every action with before/after snapshots, network and console — it usually reveals the cause immediately. Enable trace on-first-retry in CI.","miniChallenge":"Deliberately break a locator, run with traces on, open the trace and identify exactly where and why it failed.","modelAnswer":"## Example\nThe trace showed the click fired before the button was attached/visible; I added the correct web-first assertion (or fixed the locator) and the trace confirmed the action then succeeded.","portfolioBuilder":"Mentioning trace-driven debugging in your capstone README (and CI artifacts) shows you can diagnose failures like a professional, not just write happy-path tests.","resourcePreview":{"name":"Debugging & Trace Viewer Guide","purpose":"Diagnose failures fast with Playwright’s debugging tools.","whenToUse":"Use it whenever a test fails and the cause is unclear.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 4 and l.lesson_number = 6;


-- ▶ Module 5
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 5.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module5.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A login field id changed and twenty tests broke — each had hard-coded the locator. With a page object, that change is one edit in one place. POM is what keeps a growing suite cheap to maintain.","davidTip":"Introduce a page object the moment two tests share locators — not before. Premature POM on a tiny project is as harmful as none. Let real duplication tell you when to abstract.","miniChallenge":"Pick a page in any app and list the locators and actions a page object for it would hold.","modelAnswer":"## Example — LoginPage\nLocators: email field, password field, sign-in button, error message. Actions: goto(), login(email, password). The test calls login() and asserts the outcome.","resourcePreview":{"name":"Page Object Model (POM) Template","purpose":"A clean, reusable structure for page objects.","whenToUse":"Use it as the template for each page object you build.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 5 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"A page object exposed raw locators, so tests read like CSS soup. Rewritten to expose intent — login(), addToBasket() — the tests became readable English and survived UI tweaks. Good page classes hide the \"how\" behind the \"what\".","badGood":{"label":"a page object method","bad":"await page.locator('#u').fill(email); await page.locator('#p').fill(pw); await page.locator('.btn').click();","good":"await loginPage.login(email, password); // intent-revealing method on the page object"},"davidTip":"Name methods after what the user does, not what the code does: addToBasket() beats clickAddButton(). Keep one page object per page/component, with locators encapsulated inside.","miniChallenge":"Write a page class (pseudocode or real) for a login page with goto() and login() methods.","modelAnswer":"## Example\nclass LoginPage { constructor(page){this.page=page} email=()=>this.page.getByLabel('Email'); signIn=()=>this.page.getByRole('button',{name:'Sign in'}); async login(e,p){ await this.email().fill(e); /* … */ await this.signIn().click(); } }"}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 5 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"A team buried all assertions inside page objects, so test reports said nothing useful when they failed. Moving assertions back into the tests made failures read clearly — and kept page objects focused on actions.","davidTip":"By convention, actions live in the page object and assertions live in the test — so failures read clearly in the report. Use small verify methods only when the same assertion repeats across many tests.","miniChallenge":"Take a test and ensure actions live in the page object while assertions stay in the test.","modelAnswer":"## Example\nTest: await checkout.placeOrder(); await expect(page.getByText('Order confirmed')).toBeVisible(); — the action is in the page object, the assertion stays in the test where the report can show it."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 5 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A nav bar's locators were re-declared on every page object — change the menu, edit ten files. Modelling it once as a NavBar component meant one update flowed everywhere. Shared UI deserves its own component object.","davidTip":"Model recurring widgets (nav bar, search box, data table) as component objects and have pages compose them. Extract a component when the same UI appears on three or more pages — keep components generic, not page-specific.","miniChallenge":"Identify one shared UI element in an app and sketch a component object for it.","modelAnswer":"## Example\nclass NavBar { constructor(page){this.page=page} async goTo(section){ await this.page.getByRole('link',{name:section}).click(); } } — reused by LoginPage, Dashboard and Account instead of each re-declaring the nav."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 5 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"Over a year, page objects grew into 500-line monsters full of dead methods and duplicated locators. A regular refactor — consolidate, delete unused, keep components generic — kept the suite cheap to change. Page objects only pay off if you maintain them.","davidTip":"Refactor page objects as readily as you add to them. Warning signs: huge classes, duplicated locators, methods nobody calls. A lean, well-named set is what keeps a large suite maintainable.","miniChallenge":"Review a page object and improve it: remove a dead method or consolidate a duplicated locator.","modelAnswer":"## Example\nFound two methods doing the same fill-and-submit with different names; merged into one. Removed a getOldBanner() locator no test used. The class is now shorter and clearer.","portfolioBuilder":"Clean, maintained page objects in your capstone repo are exactly what reviewers inspect to judge whether you write professional automation.","resourcePreview":{"name":"Automation Best Practices Checklist","purpose":"A quality bar covering page objects, locators and maintainability.","whenToUse":"Run your page objects through it before committing.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 5 and l.lesson_number = 5;


-- ▶ Module 6
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 6.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module6.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A registration test reused the same email every run, so the second run failed on \"email already exists\". Switching to a unique email per run made it repeatable. Test data choices quietly decide whether a suite is reliable.","visualAid":{"type":"comparison","title":"Static vs dynamic vs unique data","headers":["Kind","When to use"],"rows":[["Static","Fixed values you assert exactly"],["Dynamic","Created at run time (e.g. via API)"],["Unique/random","Avoid collisions (e.g. unique emails)"]]},"davidTip":"Unique-by-default data is the simplest cure for order-dependent, flaky suites. Generate it (user+timestamp@example.com) rather than relying on records that already exist.","miniChallenge":"For a sign-up test, decide what data should be static, dynamic or unique, and why.","modelAnswer":"## Example\nUnique: email (user+timestamp) to avoid collisions. Dynamic: an account created via API for a \"logged-in\" test. Static: a known invalid email to assert the exact validation message."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 6 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"Every test hand-built a full user object, repeating fields and occasionally producing invalid data. A factory function returning a valid user with overridable fields made tests short and their intent obvious.","badGood":{"label":"building test data","bad":"const user = { name:'Test', email:'a@b.com', password:'pw', role:'user', country:'UK', ... } // repeated everywhere","good":"const user = makeUser({ role: 'admin' }); // factory fills valid defaults + unique email"},"davidTip":"A good factory lets a test state only what's special about its data and fills the rest with valid defaults. Combine it with unique values for ids/emails to keep tests both short and collision-free.","miniChallenge":"Write a factory function that returns a valid user and lets you override the role.","modelAnswer":"## Example\nfunction makeUser(overrides={}){ return { name:'Test User', email:`user+${unique()}@example.com`, password:'Passw0rd!', role:'user', ...overrides }; }"}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 6 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"A data-driven test had 30 cases hard-coded inline, making the spec unreadable. Moving them to a JSON file meant adding a case was a one-line data change, and non-developers could review the data. External files shine when data changes often.","davidTip":"Use JSON/CSV files for reusable fixtures, larger sets, or data owned by non-developers. Read the file and iterate rows to drive parameterised tests — keep the files small and validated.","miniChallenge":"Move an inline data set into a JSON file and load it in the test.","modelAnswer":"## Example\ndiscounts.json: [{\"code\":\"SAVE10\",\"result\":\"10% off\"},{\"code\":\"EXPIRED\",\"result\":\"code expired\"}] — the test loads it and runs the same assertion per row; adding a case is a one-line edit."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 6 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A tester hard-coded a password in a test and committed it. It ended up in the public repo history — a real security incident. Secrets must come from the environment, never the code.","badGood":{"label":"handling a password in a test","bad":"const password = 'Sup3rSecret!'; // committed to the repo","good":"const password = process.env.TEST_PASSWORD; // from .env locally, CI secret in the pipeline"},"davidTip":"Treat any committed secret as compromised. Read credentials from environment variables, gitignore your .env, and store CI secrets in the pipeline's secret store. Drive baseURL/credentials from env so one suite runs against dev, staging and prod.","miniChallenge":"Refactor a test that hard-codes a password to read it from an environment variable instead.","modelAnswer":"## Example\nReplaced the literal with process.env.TEST_PASSWORD; added .env (gitignored) for local runs and a GitHub Actions secret for CI. The password never touches the repo."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 6 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"Tests passed when run alone but failed together — they shared one record and stepped on each other. Making each test create and clean up its own data fixed it and unlocked parallel execution. Independence is the foundation of a reliable suite.","davidTip":"A reliable test passes alone or with others, in any order, any number of times. If yours pass solo but fail together, data coupling is almost always the cause. Each test owns its data and cleans up.","miniChallenge":"Take an order-dependent test and refactor it to create its own data and clean up; run it twice to confirm independence.","modelAnswer":"## Example\nThe test now creates its account via the API in setup, runs the UI behaviour, and deletes the account in teardown — so it passes repeatedly and in parallel without interfering with other tests.","portfolioBuilder":"Independent, self-cleaning tests in your capstone are what make parallel CI runs reliable — a clear signal of professional-grade automation.","resourcePreview":{"name":"Test Data Management Template","purpose":"Keep test data clean, isolated and maintainable.","whenToUse":"Use it to plan data setup/teardown for your tests.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 6 and l.lesson_number = 5;


-- ▶ Module 7
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 7.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module7.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A new hire needed to change the login page object and spent twenty minutes hunting for it in a flat folder of mixed files. A predictable structure — pages, tests, components, fixtures, utils, data — would have made it a five-second find. Structure is onboarding documentation.","visualAid":{"type":"comparison","title":"A sensible framework layout","headers":["Folder","Holds"],"rows":[["tests/","Specs, grouped by feature"],["pages/","Page objects"],["components/","Reusable component objects"],["fixtures/","Custom fixtures"],["utils/ · data/","Helpers · JSON/CSV data"]]},"davidTip":"Group files by concern so anyone can guess where something lives. If a newcomer can find the login page object without asking, your structure is working.","miniChallenge":"Sketch a folder structure for an automation framework with tests, pages, fixtures, utils and data.","modelAnswer":"## Example\n/tests (auth, checkout, account) · /pages (LoginPage, CheckoutPage) · /components (NavBar) · /fixtures (auth) · /utils (uniqueEmail) · /data (discounts.json).","resourcePreview":{"name":"Test Structure & Naming Conventions Guide","purpose":"Organise a framework so it stays navigable as it grows.","whenToUse":"Use it to lay out your capstone framework.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 7 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"The same timestamp-email logic was copy-pasted across a dozen tests. Extracting one uniqueEmail() helper removed the duplication and made the tests read clearly. Helpers, used well, keep tests focused.","davidTip":"Extract a helper when you see real repetition — not speculatively. And helpers should make tests clearer, not hide important logic: if a reader must open the helper to understand the test, reconsider it.","miniChallenge":"Identify one repeated snippet across tests and extract it into a well-named helper.","modelAnswer":"## Example\nRepeated \"user+Date.now()@example.com\" became uniqueEmail(); tests now call uniqueEmail() — shorter, clearer, and the logic lives in one place."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 7 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"A team built a five-level class hierarchy for page objects \"for flexibility\" — and nobody could follow it. Replacing most of it with fixtures and a single thin BasePage made the framework far easier to understand. Composition beats deep inheritance.","davidTip":"Prefer fixtures and components over deep inheritance. One shallow BasePage (shared goto/wait helpers) is usually enough; deep class hierarchies obscure behaviour and trap maintainers.","miniChallenge":"Design a BasePage with one shared method your page objects could extend.","modelAnswer":"## Example\nclass BasePage { constructor(page){this.page=page} async goto(path){ await this.page.goto(path); } } — LoginPage and Dashboard extend it and add only their own specifics; shared state otherwise comes from fixtures."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 7 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A CI failure had no artefacts, so an engineer debugged blind for an hour. Once the suite captured trace, screenshot and the HTML report on failure, the next failure was diagnosed from the report in minutes. Reporting turns failures into evidence.","davidTip":"Capture trace/screenshot on failure and publish the HTML report — it doubles as evidence for stakeholders. Log meaningful context (which data, which environment), not noise; let the trace carry the step detail.","miniChallenge":"Enable the HTML reporter and on-failure artefacts, force a failure, and review the report.","modelAnswer":"## Example\nConfig: reporter 'html', use: { trace:'on-first-retry', screenshot:'only-on-failure' }. A forced failure produced a report linking the trace and screenshot — cause clear without re-running."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 7 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"A framework that worked for 20 tests fell apart at 500 — shared mutable state broke parallel runs and copy-paste growth made changes slow. Designing for scale from the start meant adding the 500th test felt like adding the 10th.","davidTip":"Design for growth: independent, parallel-safe tests (no shared mutable state), reusable pages/components/fixtures, consistent structure, and the right layer. If tests can't run in parallel, the suite gets slower with every addition.","miniChallenge":"List three properties your framework needs so the 100th test is as easy to add as the 10th.","modelAnswer":"## Example\n1) Tests are independent and parallel-safe. 2) Pages/components/fixtures are reusable (no copy-paste). 3) Consistent structure and naming, with checks at the right layer.","portfolioBuilder":"A scalable, well-architected framework is the heart of your capstone — document the structure and your key decisions in the README.","resourcePreview":{"name":"Automation Best Practices Checklist","purpose":"A quality bar covering structure, independence and scalability.","whenToUse":"Run your framework through it before submission.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 7 and l.lesson_number = 5;


-- ▶ Module 8
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 8.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module8.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"The UI looked fine but orders silently failed — the API behind \"Place order\" returned an error the UI swallowed. A tester who could check the API directly found it in minutes. A lot of real behaviour (and real bugs) lives at the API layer.","visualAid":{"type":"comparison","title":"HTTP methods & common status codes","headers":["Code / Method","Meaning"],"rows":[["GET / POST","Read / create"],["PUT-PATCH / DELETE","Update / remove"],["200 / 201","OK / Created"],["400 / 401 / 404","Bad request / Unauthorised / Not found"],["500","Server error"]]},"davidTip":"Know your status codes cold — they come up constantly in interviews and daily work. But never stop at the status: a 200 with the wrong body is still a bug.","miniChallenge":"For create/fetch/update/delete a user, name the method and the success status code you'd expect.","modelAnswer":"## Example\nCreate → POST → 201; Fetch → GET → 200; Update → PUT/PATCH → 200; Delete → DELETE → 200 or 204."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 8 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"A team did all their setup through slow UI clicks until they discovered Playwright's request fixture — fast, stable API tests with no browser. Their suite got quicker and less flaky overnight.","davidTip":"API tests are the fastest, most stable tests you can write in Playwright. Reach for the request fixture whenever a check doesn't truly need the browser — and always await both the request and the json() parse.","miniChallenge":"Write a Playwright API test that GETs a public endpoint and asserts the status and one field of the body.","modelAnswer":"## Example\ntest('gets a post', async ({ request }) => { const res = await request.get('/posts/1'); expect(res.status()).toBe(200); const body = await res.json(); expect(body.id).toBe(1); });","resourcePreview":{"name":"API Testing with Playwright Template","purpose":"Test APIs directly and combine them with UI tests.","whenToUse":"Use it as the pattern for your API tests.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 8 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"Every API test logged in again, making the suite slow and noisy. Acquiring a token once in setup and reusing it via a fixture sped everything up — and kept credentials out of the test code.","davidTip":"Acquire auth once and reuse it (token in a fixture/setup), rather than logging in per test. Store credentials in environment variables, never in code — repeated logins are slow and hard-coded secrets are a liability.","miniChallenge":"Outline how you'd authenticate once and reuse the token across several API tests.","modelAnswer":"## Example\nA setup step POSTs to /login with env credentials, captures the token, and a fixture attaches it as an Authorization header to every request — so tests run authenticated without repeating the login."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 8 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"An API test only checked \"status is 200\" and missed that the endpoint returned an empty list when it should have returned results. Strong assertions check the things that actually matter, including the error cases.","badGood":{"label":"an API assertion","bad":"expect(res.status()).toBe(200); // and nothing else","good":"expect(res.status()).toBe(201); expect(body.id).toBeDefined(); expect(body.total).toBe(120); // + a 400 case for bad input"},"davidTip":"A response can be \"200 OK\" and still wrong. Assert the fields and shape that matter, and test the error/negative cases (400, 401, 404) too — status alone is the weakest possible check.","miniChallenge":"For a \"create order\" endpoint, write assertions: status, one key field, and a negative case for invalid input.","modelAnswer":"## Example\nValid: status 201, body.id exists, body.total equals expected. Negative: an invalid payload returns 400; an unauthenticated request returns 401."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 8 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"A UI test wasted minutes clicking through a multi-step sign-up just to reach the account page. Creating the account via the API first, then driving only the behaviour under test through the UI, made it fast and stable.","davidTip":"The fastest UI tests do their setup via the API. Create the data you need with request.post, drive only the behaviour under test through the UI, and tear down via the API afterwards.","miniChallenge":"Take a UI test with slow setup and redesign it to create its starting state via the API.","modelAnswer":"## Example\nTo test the account page, the test creates the account via POST /users, then the UI test just logs in and checks the page — instead of clicking through the whole sign-up flow first.","portfolioBuilder":"Including API tests plus API-driven setup in your capstone shows you test beyond the UI and build fast, stable suites — a strong differentiator.","resourcePreview":{"name":"API Testing with Playwright Template","purpose":"Standalone API tests and using the API to seed UI tests.","whenToUse":"Use it for the API portion of your capstone.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 8 and l.lesson_number = 5;


-- ▶ Module 9
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 9.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module9.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A new starter's first task was \"commit that to the repo\" and they froze — unsure how to stage, commit or write a message. Basic Git fluency removes that day-one friction; your framework lives in Git and employers expect you to use it competently.","davidTip":"Commit small, logical changes with clear messages (what and why). A tidy GitHub history is itself a portfolio asset — treat commit messages as communication, not an afterthought.","miniChallenge":"Make a small change in a repo and commit it with a clear message; note what makes the message good.","modelAnswer":"## Example\ngit add tests/login.spec.ts && git commit -m \"Add login boundary tests for password length\" — small, scoped, and the message says exactly what and why."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 9 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"An engineer committed straight to main and broke the build for everyone. Moving to feature branches and pull requests meant CI ran and a teammate reviewed before anything merged. Branches and PRs are how teams ship safely.","visualAid":{"type":"flow","title":"Branch → PR → merge","steps":[{"label":"Feature branch","detail":"off main"},{"label":"Commit & push"},{"label":"Open PR","detail":"review + CI"},{"label":"Merge","detail":"once green & approved"}]},"davidTip":"Small, focused pull requests get reviewed faster and merge sooner. Never commit straight to main, and never merge before CI passes — a PR that does one thing is a gift to your reviewer.","miniChallenge":"Create a feature branch, push a change, and open a pull request on your own repo.","modelAnswer":"## Example\ngit checkout -b feature/checkout-tests → push → open a PR titled \"Add checkout regression tests\". CI runs on the PR and a reviewer checks it before it merges to main."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 9 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"Tests only ran when someone remembered to run them locally — so regressions slipped in. A GitHub Actions workflow running the suite on every push and PR turned testing from optional into automatic.","davidTip":"A green CI badge on a public repo is a powerful portfolio signal — it shows you can wire tests into a real pipeline, not just write them. Always install browsers with --with-deps and upload the report on failure.","miniChallenge":"Add a GitHub Actions workflow to your project that installs browsers, runs Playwright, and uploads the report.","modelAnswer":"## Example steps\ncheckout → setup-node → npm ci → npx playwright install --with-deps → npx playwright test → upload playwright-report/ (if: always()). Triggers: push and pull_request.","resourcePreview":{"name":"CI/CD Integration Guide (GitHub Actions)","purpose":"Run your Playwright tests automatically on every push and PR.","whenToUse":"Use it to wire CI into your capstone.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 9 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A team \"had CI\" but merges were allowed over red builds, so broken tests piled up. Making the test check required before merge turned CI from decoration into a real quality gate that protected main.","davidTip":"CI that can be ignored is just decoration. Make the test check required before merge, treat a red build as \"stop and fix\", and use retries in CI only for rare infra blips — never to mask genuine flakiness.","miniChallenge":"Describe how you'd configure your repo so tests run on every PR and must pass before merge.","modelAnswer":"## Example\nWorkflow runs on pull_request; branch protection requires the Playwright check to pass before merging. A failing run blocks the merge until it's fixed — main stays green."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 9 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"A growing suite took 40 minutes serially and slowed every release. With independent tests, Playwright ran them across workers in parallel, cutting it to under 10 — fast feedback restored. Parallelism is free speed, if your tests allow it.","davidTip":"Parallel execution is free speed — but only with independent, data-safe tests (the work you did on data-independence is exactly what enables it). Tune workers to the runner and surface clear pass/fail on the PR.","miniChallenge":"Run your suite with multiple workers and confirm it still passes; note the time saved.","modelAnswer":"## Example\nWith independent tests, npx playwright test ran across 4 workers and finished in roughly a quarter of the serial time; the PR showed a clear pass/fail and linked the report.","portfolioBuilder":"Green CI, parallel runs and uploaded reports in your capstone repo are concrete proof you can build a real, automated pipeline — exactly what employers want to see.","resourcePreview":{"name":"CI/CD Integration Guide (GitHub Actions)","purpose":"Parallelism, reporting and reliable CI runs.","whenToUse":"Reference it when tuning your pipeline.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 9 and l.lesson_number = 5;


-- ▶ Module 10
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 10.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module10.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"Asked to add tests for a new form, an engineer had AI draft the spec in seconds, then reviewed the locators, added boundary cases it missed, and ran it before committing. AI did the typing; the engineering stayed human.","davidTip":"Treat AI as a pair programmer you review, not an oracle. It drafts tests, explains errors and suggests refactors — but you run, verify and own everything it produces. Never paste secrets or proprietary code into public tools.","miniChallenge":"List three automation tasks you'd use AI for, and one you would not trust it to decide.","modelAnswer":"## Example\nUse AI for: drafting a test, explaining an error, suggesting a refactor. Don't delegate: whether the suite is reliable enough to trust — that judgement is mine.","resourcePreview":{"name":"AI Prompt Library for Automation Engineers","purpose":"Ready-to-use prompts for writing, debugging and improving Playwright tests.","whenToUse":"Use it as your starting point for AI-assisted automation.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 10 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"\"Write tests for login\" produced shallow, brittle output. Adding role, context and constraints — \"use getByRole, web-first assertions, no waitForTimeout\" — returned code that already matched the team's standards. The prompt made the difference.","badGood":{"label":"an automation prompt","bad":"\"Write Playwright tests for login.\"","good":"\"Act as a senior automation engineer. Write a Playwright test in TypeScript for the login flow using getByRole/getByLabel and web-first assertions. Do not use waitForTimeout.\""},"davidTip":"Bake your standards into the prompt: role, context, task, format, constraints. It's far faster to constrain up front (locators, assertions, no sleeps) than to fix brittle generated code afterwards.","miniChallenge":"Write a prompt that would generate a Playwright test matching this course's standards, then refine it once.","modelAnswer":"## Example\nFirst prompt as above; refinement: \"Add negative cases (wrong password, empty fields) and an account-lockout boundary, and keep each test to one behaviour.\""}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 10 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"AI scaffolded a page object fast — but used div:nth-child selectors. The engineer kept the structure and swapped the brittle locators for role-based ones. Generated code is a draft to conform to your patterns, not commit as-is.","badGood":{"label":"an AI-suggested locator","bad":"page.locator('div.container > div:nth-child(3) > button')","good":"page.getByRole('button', { name: 'Sign in' })"},"davidTip":"Let AI scaffold tests and page objects, then review: are the locators robust, assertions web-first, one behaviour per test? Conform generated code to your conventions before it lands, or it creates inconsistency debt.","miniChallenge":"Generate a page object for a simple page with AI, then review and fix at least one issue (usually a brittle locator).","modelAnswer":"## Example\nAI scaffolded a LoginPage using nth-child selectors; I kept the class shape but replaced them with getByLabel('Email') and getByRole('button', { name: 'Sign in' })."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 10 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A flaky test failed randomly. The engineer pasted it (sanitised) into AI, which spotted a fixed wait and suggested a web-first assertion. They applied it, re-ran with --repeat-each, and confirmed the flakiness was gone — verified, not assumed.","davidTip":"Pair AI with the trace viewer: the trace shows what happened, AI helps explain why. Always re-run after applying an AI fix to confirm the behaviour is unchanged — never trust the explanation alone.","miniChallenge":"Take a failing or flaky test, ask AI to explain and fix it, then describe how you'd verify the fix.","modelAnswer":"## Example\nAI identified a waitForTimeout before an assertion and suggested expect(locator).toBeVisible(). I applied it and ran --repeat-each=10 to confirm the test is now stable."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 10 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"Before opening a PR, an engineer asked AI to review a page object; it flagged a duplicated locator and a fragile selector, both fixed before review. AI as a first-pass reviewer raised the quality before a human even looked.","davidTip":"Use AI for a first-pass review of your tests — reliability, readability, brittleness — and apply what genuinely improves the code. It supplements human review and judgement; it doesn't replace them.","miniChallenge":"Ask AI to review one of your tests; apply one suggestion and note one you rejected and why.","modelAnswer":"## Example\nApplied: AI's suggestion to extract a repeated login into a fixture. Rejected: its suggestion to add retries to \"fix\" a flaky test — the right fix was removing a sleep, not masking it.","resourcePreview":{"name":"Code Review Checklist for Test Automation","purpose":"Review automation PRs (yours or AI-assisted) like a professional.","whenToUse":"Use it alongside an AI first-pass review.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 10 and l.lesson_number = 5;

update public.lessons l set enhancements = $ench${"industryStory":"An engineer nearly pasted proprietary code into a public AI tool for help. Catching that habit is essential — responsible AI use (data, verification, accountability) is now expected, and a leak can be career-defining.","visualAid":{"type":"comparison","title":"Responsible AI in automation","headers":["Do","Do not"],"rows":[["Sanitise before pasting","Share secrets or proprietary code"],["Verify specifics against reality","Trust output as fact"],["Run, review and own the code","Commit code you cannot explain"]]},"davidTip":"Before pasting anything, ask \"would I be comfortable if this were public?\" Verify hallucination-prone specifics, and never let AI dependence dull your fundamentals — you must be able to debug what you ship.","miniChallenge":"Write your three personal rules for responsible AI use in automation.","modelAnswer":"## Example\n1) Never paste secrets or proprietary code into public tools. 2) Verify generated specifics (locators, APIs) against the real app. 3) Run and understand every line before committing.","portfolioBuilder":"An \"AI-assisted automation\" note in your capstone — prompts used, what you accepted/changed, your safety rules — shows modern, responsible engineering practice."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 10 and l.lesson_number = 6;


-- ▶ Module 11
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 11.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module11.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A test failed about 1 in 5 runs and the team just hit \"re-run\" until it passed — until a real bug hid behind that noise. Running it with --repeat-each made the flakiness reproducible, the trace showed a click before the element was ready, and a web-first assertion fixed it for good.","davidTip":"Run a suspect test with --repeat-each=10 to make flakiness reproducible — a test you can't make fail reliably is one you can't prove you've fixed. Then open the trace and fix the root cause; never paper over it with retries.","miniChallenge":"Take a suspect test, run it with --repeat-each, and use the checklist (sleeps? awaits? shared state? brittle locators?) plus the trace to find the cause.","modelAnswer":"## Example\n--repeat-each=10 reproduced the failure ~twice; the trace showed a click before the button was enabled. Replacing a waitForTimeout with expect(button).toBeEnabled() then click() made it pass 10/10.","resourcePreview":{"name":"Flaky Test Troubleshooting Checklist","purpose":"Systematically diagnose and fix tests that pass and fail randomly.","whenToUse":"Work through it whenever a test is flaky.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 11 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"The same login code appeared in ten specs; brittle selectors and dead tests piled up until changes took forever. Tackling the highest-impact debt first — flaky and duplicated code — restored momentum. Test code is real code and accrues debt.","davidTip":"Fix the debt that costs you trust or time first — flaky and duplicated code — before cosmetic tidy-ups. Refactor little and often rather than waiting for a big-bang rewrite.","miniChallenge":"Identify two pieces of technical debt in a suite and say which you'd fix first and why.","modelAnswer":"## Example\nDebt: (1) login duplicated across 10 specs, (2) inconsistent test naming. Fix (1) first — extract a fixture — because it costs time on every change and risks inconsistency; naming is cosmetic and can follow."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 11 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"A reviewer approved a PR without reading it, and a waitForTimeout-laden flaky test slipped into the suite. A structured review — reliability, locators, independence — would have caught it. Reviewing automation well keeps the suite healthy.","davidTip":"Even as a junior, leaving clear, constructive review comments gets you noticed. Focus reviews on reliability and readability over style — and be specific: \"switch this waitForTimeout to expect(locator).toBeVisible()\".","miniChallenge":"Review a test against the checklist and write two specific, constructive comments.","modelAnswer":"## Example\nComment 1: \"This uses waitForTimeout(2000) before the assertion — can we use expect(locator).toBeVisible()? Faster and removes a likely flake.\" Comment 2: \"These two tests share data — can each create its own so they can run in parallel?\"","resourcePreview":{"name":"Code Review Checklist for Test Automation","purpose":"A structured way to review (or self-review) test pull requests.","whenToUse":"Use it on every automation PR.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 11 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A big refactor changed behaviour by accident and broke two flows, because nobody ran the tests between steps. Refactoring in small, verified steps — using the suite as a safety net — keeps behaviour intact while the code improves.","davidTip":"Refactor in small, behaviour-preserving steps and run the affected tests after each one. The suite you built is your safety net — commit each working step so a mistake is easy to undo.","miniChallenge":"Perform a small refactor (e.g. extract a fixture), running tests before and after to confirm behaviour is unchanged.","modelAnswer":"## Example\nExtracted a shared login fixture in one commit, ran the suite (all green), then committed. Behaviour unchanged, duplication gone — and if it had failed, one small revert undoes it."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 11 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"industryStory":"A suite quietly crept from 5 to 30 minutes over months as everything went into slow UI tests, eroding the fast feedback that made it valuable. Pushing checks to the right layer and running in parallel brought it back under control.","davidTip":"Track your suite's run time and flake rate over months, not just today. Keep it fast by using the right layer (API over UI), API-driven setup, parallelism, and pruning redundant tests before it becomes a bottleneck.","miniChallenge":"Identify one slow test and describe how you'd speed it up — layer, setup, or parallelism.","modelAnswer":"## Example\nA slow UI test that set up data via clicks: move the setup to an API call and keep only the behaviour under test in the UI. Combined with parallel workers, the suite's overall time drops sharply.","portfolioBuilder":"Demonstrating maintenance thinking — flaky-test fixes, refactors, performance — in your capstone README signals you can keep a real suite healthy, not just write one."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 11 and l.lesson_number = 5;


-- ▶ Module 12
-- ============================================================
-- Lesson enhancements for "practical-test-automation-playwright" Module 12.
-- Generated by scripts/enhancements/build-enhancements.mjs — do not hand-edit;
-- edit scripts/enhancements/pw-module12.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"One learner scoped their capstone around a flaky, sprawling app and never finished; another picked a stable demo shop and four clear journeys and shipped a polished framework. Scope decides whether you end with something you can show.","davidTip":"Pick an app with clear, stable journeys and aim for 8–12 meaningful tests — quality over quantity. A focused framework on a sensible app demonstrates more skill than a sprawling one on a flaky target.","miniChallenge":"Choose your demo app and list the 8–12 journeys/tests your framework will cover.","modelAnswer":"## Example — a demo shop\nBrowse products, search, add to basket, apply a discount code, checkout (happy path), invalid payment, login, and an account update — plus one or two API tests for setup.","resourcePreview":{"name":"Automation Portfolio Project Workbook","purpose":"Build a public Playwright project that proves you can automate.","whenToUse":"Use it as the blueprint and checklist for your capstone.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 12 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"industryStory":"An employer opened a candidate's capstone, saw robust locators, page objects, an API test and green CI, and invited them to interview on the strength of the repo alone. The capstone is what an employer actually opens — make it your best work.","davidTip":"Apply the standards you've learned, not shortcuts: robust locators, web-first assertions, independent data, page objects, at least one API test, and green CI. This repo is the thing an employer inspects — let it show your best.","miniChallenge":"Build your framework to the quality bar: robust locators, web-first assertions, independent data, green CI. Note any standard you had to go back and fix.","modelAnswer":"## Example\nBuilt BDD features + step definitions for the key journeys, page objects per page, a fixture for login, one API test plus API-driven setup, and a GitHub Actions workflow — all green on push.","resourcePreview":{"name":"Playwright Command Cheat Sheet","purpose":"The CLI commands you will use daily while building and running the suite.","whenToUse":"Keep it handy throughout the build.","formats":["PDF","DOCX"]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 12 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"industryStory":"A reviewer cloned a strong-looking repo, couldn't work out how to run it, and moved on. A clear README — what it tests, how to run it in two commands, the strategy — is what lets your work actually get seen.","davidTip":"The README is the first thing an employer reads. A clear, well-structured one (overview, how to run, what's covered and why, tech used, what it demonstrates) signals professionalism before they see a line of test code.","miniChallenge":"Write a README for your project covering overview, how to run, coverage/strategy and tech used.","modelAnswer":"## Example README sections\n1) Overview + app under test. 2) Install & run (npm ci; npx playwright test). 3) What's covered and why (test strategy). 4) Tech: Playwright, TypeScript, GitHub Actions. 5) What it demonstrates about me."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 12 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A graduate published their framework, confirmed CI was green, and recorded a 60-second walkthrough of their design choices. In interviews they could talk through any part with confidence — and it landed them the role.","davidTip":"Publish it public with green CI and working links, then be ready to walk through any part in 60 seconds. Employers value engineers who can explain their design decisions, not just produce code. Submit your repository URL for self-review against the model solution.","miniChallenge":"Publish your framework, self-review it against the model solution, and submit your public GitHub repository URL.","modelAnswer":"## Example\nRepo public, CI green, README clear, links working, tests reliable on repeat runs. Recorded a 60-second walkthrough explaining the framework structure and two key decisions, then submitted the URL.","managersReview":{"intro":"If I received your capstone repo as a hiring manager, I would look for:","strengths":["A focused, complete framework (BDD, page objects, API, CI)","Robust locators and reliable tests","A clear README and green CI","Ability to explain your design choices"],"gaps":["Private repo or red CI","Brittle locators / flaky tests","No README or broken links"],"improvements":["Make it public with green CI","Fix brittle locators and flakiness","Write a clear README and rehearse a walkthrough"]},"portfolioBuilder":"This capstone is the centrepiece of your automation portfolio — a public, documented, CI-backed framework. It does more for your job hunt than any certificate, because it shows exactly how you think and code."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'practical-test-automation-playwright'
  and m.module_number = 12 and l.lesson_number = 4;


