-- ============================================================
-- API Testing Masterclass — Module 8 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/istqb-module8.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$Risk Identification$L$, $L$13 minute read$L$, $L$Risk-based testing starts by finding the risks. Before you can prioritise or mitigate anything, you need a clear list of what could go wrong and why it matters to testing.$L$, array[$L$Define risk and distinguish product risk from project risk$L$, $L$Explain why testing is inherently risk-based$L$, $L$Run a simple risk identification activity with stakeholders$L$], $L$## What "risk" means in testing
In ISTQB terms a **risk** is a potential event, hazard, threat or situation whose occurrence causes an undesirable outcome. It is characterised by two factors: the **likelihood** of the event and its **impact** (harm) if it happens.

## Two categories of risk
- A **product risk** (quality risk) relates to the test object — the software could fail to meet a need. Examples: incorrect calculations, poor performance, security holes, data loss.
- A **project risk** relates to the management and control of the project — late delivery, unclear requirements, staff shortages, unstable environments.

Testers care most about **product risks**, because these directly shape what and how we test. Project risks are managed alongside them.

## Why testing is risk-based
Exhaustive testing is impossible, so we cannot test everything equally. Risk gives us a rational basis for **focusing effort where failure would hurt most**. Identifying risks early — during planning and analysis — means test effort is aligned to risk from the start.

## How to identify risks
Use techniques such as risk workshops, brainstorming, checklists, expert interviews and reviewing past defect data. Involve a **range of stakeholders** (developers, business analysts, product owners, support) — no single person sees every risk. Record each risk clearly so it can later be assessed and tracked.$L$, $L$A team building an online payments feature runs a 45-minute risk workshop. They list product risks: "card charged twice", "refund calculated wrongly", "payment page slow at peak". They also note a project risk: "test environment not ready until week 4". Each risk is written on a card so it can be scored later — identification first, assessment next.$L$, $L$- Confusing product risk (the software fails) with project risk (the project slips)
- Jumping straight to test design without listing risks first
- Letting one person identify all the risks and missing whole areas
- Treating risk identification as a one-off instead of revisiting it$L$, $L$The best risk lists come from a room, not a spreadsheet. Get a developer, a business analyst and a support person together for even thirty minutes — each sees failures the others never would.$L$, $L$For a hotel-booking app, write three product risks and one project risk. Label each clearly.$L$, $L$What are the two factors that characterise a risk?$L$, $L$A risk is characterised by two factors. What are they? (Answer: likelihood and impact)$L$, array[$L$I can define risk in ISTQB terms$L$, $L$I can distinguish product risk from project risk$L$, $L$I can run a basic risk identification activity$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$Risk Probability$L$, $L$12 minute read$L$, $L$The first half of a risk score is likelihood — how probable is it that this thing actually goes wrong? This lesson shows how to reason about probability without pretending to be exact.$L$, array[$L$Define likelihood (probability) as a factor of risk$L$, $L$List factors that raise or lower the probability of failure$L$, $L$Assign a relative likelihood rating on a simple scale$L$], $L$## Likelihood is one of the two risk factors
Risk level is derived from the **likelihood** of an event and its **impact**. Likelihood — also called **probability** — answers: *how likely is this failure to occur?* It reflects technical risk: the chance a fault exists and is triggered.

## What drives likelihood up
- **Complexity** of the code or feature
- **New or unfamiliar technology** and inexperienced staff
- Areas with a **history of defects**
- **Frequent or last-minute changes** to a component
- **Time pressure** and rushed implementation
- **Interfaces and integrations** with other systems

## What drives it down
- Simple, stable, well-understood code
- Mature components that have run reliably for a long time
- Strong prior test coverage and few past defects

## Rating likelihood
You do not need a precise percentage. Use a **relative scale** — for example Low / Medium / High, or 1–3 or 1–5. Consistency matters more than false precision: the goal is to compare risks against each other so testing can be prioritised. Base your rating on evidence — defect history, complexity, change frequency — not gut feel alone.$L$, $L$A team scores likelihood 1–3 for three areas. The legacy login (stable, ten years old, no recent changes) scores 1. A reworked pricing engine (complex, changed last sprint) scores 3. A settings page (moderate, occasionally touched) scores 2. Notice: change and complexity pushed pricing to the top of the likelihood scale.$L$, $L$- Treating likelihood as the whole risk and ignoring impact
- Chasing a precise percentage instead of a consistent relative rating
- Ignoring defect history — past failures predict future ones
- Rating from gut feel with no supporting evidence$L$, $L$Defect history is the single best predictor of likelihood. If a component has broken three times before, bet it breaks again — and test it as if it will.$L$, $L$List two technical factors that increase the likelihood of failure, and two that decrease it.$L$, $L$Which risk factor does "likelihood" represent, and what kinds of things raise it?$L$, $L$In risk analysis, likelihood is also commonly known by what other term? (Answer: probability)$L$, array[$L$I can define likelihood as a risk factor$L$, $L$I can list factors that raise or lower it$L$, $L$I can assign a relative likelihood rating$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Risk Impact$L$, $L$12 minute read$L$, $L$The second half of a risk score is impact — if this failure happens, how bad is it? A rare failure with catastrophic impact can outrank a frequent but trivial one.$L$, array[$L$Define impact (harm) as a factor of risk$L$, $L$Identify what makes a failure high-impact$L$, $L$Assign a relative impact rating on a simple scale$L$], $L$## Impact is the second risk factor
Alongside likelihood, **impact** (the harm or consequence if the risk occurs) determines the risk level. Impact reflects **business risk**: how much damage results if this feature actually fails in use.

## What makes impact high
- **Financial loss** — wrong charges, lost sales, fraud
- **Safety** — harm to people (critical in medical, automotive, aviation)
- **Legal or regulatory** breaches and fines
- **Reputation and trust** — a public, embarrassing failure
- **Frequency and visibility of use** — a failure on the checkout page hits everyone; a failure on a rarely used admin screen hits few
- **Number of users affected** and whether there is a workaround

## Rating impact
As with likelihood, use a **relative scale** (Low / Medium / High or 1–3 / 1–5). Ask the **business**, not just the technical team — impact is fundamentally a business judgement. A tester can estimate likelihood from the code; only the business can say how much a given failure would truly cost.

## Why impact alone is not enough
A high-impact failure that is extremely unlikely may still rank below a moderate failure that is almost certain. Impact must be combined with likelihood — which is exactly what the risk matrix does next.$L$, $L$A retail team rates impact 1–3. A failure in the checkout total scores 3 — every customer, real money, legal exposure. A broken "share to social" button scores 1 — cosmetic, rarely used, easy workaround. A wrong sort order on search results scores 2 — annoying and visible, but no money lost. The business, not the testers, set these scores.$L$, $L$- Letting testers alone decide impact — it is a business judgement
- Rating impact by how hard the code is, not by the consequences of failure
- Forgetting that a rare failure can still be catastrophic
- Ignoring how many users and how often a feature is used$L$, $L$Impact is the business's call, not yours. When a product owner says "if that number is wrong we get fined", that risk goes to the top regardless of how unlikely engineering thinks it is.$L$, $L$Rate the impact (Low/Medium/High) of these failures and justify each: a broken help-page link; an incorrect tax total on an invoice; a slow-loading logo image.$L$, $L$Who is best placed to judge the impact of a failure, and why?$L$, $L$Impact reflects which type of risk — technical or business? (Answer: business risk)$L$, array[$L$I can define impact as a risk factor$L$, $L$I can identify what makes a failure high-impact$L$, $L$I can assign a relative impact rating with the business$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$The Risk Matrix$L$, $L$15 minute read$L$, $L$Combine likelihood and impact and you get a risk level. The risk matrix is the simple, visual tool that does this — turning two ratings into one number that guides testing.$L$, array[$L$Explain how risk level combines likelihood and impact$L$, $L$Plot risks on a likelihood × impact matrix$L$, $L$Read a risk level and describe what it implies for testing$L$], $L$## Risk level = likelihood × impact
The **level of risk** is derived by combining its two factors: **likelihood** and **impact**. A common way to express this is:

**Risk level = likelihood × impact**

Multiply (or otherwise combine) the two ratings and you get a single value you can compare across all risks.

## The risk matrix
A **risk matrix** is a grid with likelihood on one axis and impact on the other. Each risk is plotted in a cell; its position shows its risk level.
- **High likelihood + High impact** → top-priority risk (red)
- **Low likelihood + Low impact** → low-priority risk (green)
- The remaining cells fall in between (amber)

Colour-coding (red/amber/green) makes priorities visible at a glance and easy to communicate to stakeholders.

## What the level tells you
The risk level is not the end — it is an input. A **high** risk level signals: test this more, test it earlier, and test it with more rigorous techniques. A **low** level signals: lighter testing may be acceptable. The matrix converts two subjective judgements into one comparable, defensible number.

## Keep it consistent
Use the same scale for every risk. The matrix only works if a "3" for impact means the same thing everywhere — that is what makes risks genuinely comparable.$L$, $L$On a 1–3 scale, a team scores the payment engine likelihood 3, impact 3 → risk level 9 (red, top priority). The help page scores likelihood 1, impact 1 → 1 (green). The search feature scores likelihood 2, impact 2 → 4 (amber). Plotted on the matrix, payment sits top-right, help bottom-left, search in the middle — and the test plan follows that order.$L$, $L$- Treating the risk level as a final verdict instead of an input to planning
- Using different scales for different risks so numbers can't be compared
- Ignoring the axes — plotting by feel rather than by likelihood and impact
- Forgetting that a mid-cell risk can still deserve serious testing$L$, $L$A colour-coded risk matrix is the most persuasive one-pager you can bring to a planning meeting. Managers who glaze over at a test plan instantly understand a red cell in the top-right corner.$L$, $L$Using a 1–3 scale, calculate the risk level for: (a) likelihood 3, impact 2; (b) likelihood 1, impact 3; (c) likelihood 2, impact 2. Which is highest?$L$, $L$How is a risk's overall level derived from its two factors?$L$, $L$Risk level is derived by combining which two factors? (Answer: likelihood and impact)$L$, array[$L$I can explain risk level as likelihood combined with impact$L$, $L$I can plot risks on a likelihood × impact matrix$L$, $L$I can read a risk level and say what it implies for testing$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Risk-Based Prioritisation$L$, $L$14 minute read$L$, $L$Once risks are scored, the payoff arrives: risk level drives how much you test, how early, in what order, and with which techniques. This is risk-based testing in action.$L$, array[$L$Explain how risk level guides test effort, priority and order$L$, $L$Allocate testing depth in proportion to risk$L$, $L$Sequence testing so the highest risks are addressed first$L$], $L$## Risk level guides four decisions
Risk-based testing uses the assessed risk levels to steer testing. Specifically, risk guides:
1. **How much to test** — depth and breadth of coverage (test effort)
2. **The priority** — which risks get attention first
3. **The order** — sequence tests so the most important risks are tackled earliest
4. **Which techniques** — apply more rigorous techniques to higher risks

## Effort in proportion to risk
Allocate the most effort, the most thorough techniques and the most experienced testers to the **highest-risk areas**. Low-risk areas may get lighter, faster checks. This is how a team gets the best possible coverage from limited time.

## Order matters
Sequencing tests by risk means that if time runs out — and it usually does — the important things are already tested. Testing the highest risks **early** also surfaces the scariest defects when there is still time to fix them.

## Risk-based testing runs throughout the lifecycle
This is not a one-off planning step. Risks are identified and assessed during planning, used to design and prioritise tests during analysis and design, tracked during execution, and **re-evaluated continuously** as new information appears. Test results feed back: if high-risk areas pass, residual risk falls; new risks may emerge and reshape the plan.$L$, $L$A team has one week and three areas: payment (risk 9), search (risk 4), help page (risk 1). They test payment first, deep and with rigorous techniques, using their most experienced tester. Search gets solid but lighter coverage. The help page gets a quick smoke check. When time runs out on Friday, the riskiest area was tested most and earliest — exactly as intended.$L$, $L$- Spreading effort evenly instead of concentrating it on high risks
- Testing in feature order rather than risk order
- Applying the same shallow technique to high- and low-risk areas alike
- Treating risk assessment as done at planning and never revisiting it$L$, $L$Time always runs out before testing is "finished". Sequencing by risk is your insurance: when the plug is pulled, the things that mattered most are already the things you tested first.$L$, $L$You have three features scored 9, 5 and 2 and only enough time to test two thoroughly. Which do you prioritise, in what order, and what do you do about the third?$L$, $L$Name the decisions that risk level helps a tester make.$L$, $L$Risk level guides test effort, priority and what other aspect of testing? (Answer: the order / sequence in which tests are run)$L$, array[$L$I can explain how risk guides effort, priority and order$L$, $L$I can allocate testing depth in proportion to risk$L$, $L$I can sequence testing so the highest risks come first$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 6, $L$Risk Mitigation$L$, $L$15 minute read$L$, $L$Testing does not remove risk on its own — it measures and helps reduce it. This final lesson covers how testing mitigates risk, what residual risk means, and how to report it honestly.$L$, array[$L$Explain how testing mitigates product risk$L$, $L$Define residual risk and how test results affect it$L$, $L$Report risk status to stakeholders and support release decisions$L$], $L$## How testing mitigates risk
Testing is a **risk-mitigation activity**. It does not eliminate risk directly, but it reduces it in two ways: by **finding defects** so they can be fixed before release, and by **providing information** about the actual state of quality so informed decisions can be made. Running tests against high-risk areas either confirms they work (risk reduced) or exposes defects (risk to be addressed).

## Responses to a risk
Testing is one response among several. A team may also **mitigate** a risk (add reviews, redesign, extra testing), **transfer** it (insurance, third party), draw up a **contingency** plan, or **accept** it. Testers mainly contribute to mitigation and to informing acceptance decisions.

## Residual risk
**Residual risk** is the risk that **remains after** mitigation actions have been taken. No amount of testing reduces risk to zero — some always remains. When high-risk tests pass, residual risk falls; when they fail and defects are fixed and re-tested, it falls further. The key is to make residual risk **visible** so the business can decide whether it is acceptable to release.

## Reporting and re-evaluation
Report risk status clearly: which risks are covered, which remain, and how much residual risk is left. This feeds the **release decision** — an informed go/no-go. Throughout, risks are **continuously re-evaluated**: new risks appear, some are closed, priorities shift. Risk-based testing is a loop, not a line.$L$, $L$Before a release, a tester summarises: payment (risk 9) fully tested, all defects fixed and re-tested — residual risk now low. Search (risk 4) tested, one minor open defect — residual risk medium. Help page (risk 1) smoke-tested only — residual risk low but accepted. The business reads this one page and gives an informed go/no-go, aware of exactly what remains.$L$, $L$- Claiming testing "removes" risk rather than reducing and measuring it
- Reporting only what passed and hiding the residual risk that remains
- Forgetting that residual risk is never zero
- Making the go/no-go call yourself instead of informing the business decision$L$, $L$Your job at release time is not to promise zero bugs — it is to make the remaining risk visible so the business chooses go or no-go with its eyes open. Honest residual-risk reporting is what earns a tester lasting trust.$L$, $L$Write a two-line residual-risk summary for a feature that was fully tested with two low-severity defects still open.$L$, $L$What is residual risk, and why can testing never reduce it to zero?$L$, $L$What name is given to the risk that remains after mitigation actions have been taken? (Answer: residual risk)$L$, array[$L$I can explain how testing mitigates product risk$L$, $L$I can define residual risk and how results change it$L$, $L$I can report risk status to support a release decision$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

