-- ============================================================
-- API Testing Masterclass — Module 5 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/modern-automation-module5.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$What a Test Should Assert$L$, $L$17 minute read$L$, $L$An assertion is the whole point of a test — everything before it just sets the stage. This lesson is about aiming that assertion at behaviour and user-visible outcomes rather than at the incidental details of how the app is built.$L$, array[$L$Distinguish an outcome-focused assertion from an implementation-focused one$L$, $L$Explain what makes an assertion valuable enough to defend a behaviour$L$, $L$Rewrite a test so its assertion would go red if the feature genuinely broke$L$], $L$## The assertion is the test
Every line before the assertion is arrangement and action. The assertion is where the test earns its keep: it is the sentence that says "this is what must be true, or the product is wrong". If that sentence is weak, nothing else in the test matters — you can drive the app perfectly and still learn nothing.

## Assert behaviour, not implementation
Aim assertions at what a user would notice and care about:

- **Outcomes** — the confirmation message appeared, the basket total updated, the URL changed, the record now shows in the list.
- **Behaviour** — the disabled button became enabled once the form was valid; the error text explained what went wrong.

Avoid assertions coupled to how the app happens to be built today:

- A specific CSS class name, DOM depth, or internal component structure.
- A network call firing (the call is a means; the outcome is the end).
- An exact pixel position or a framework-generated id.

Implementation details change constantly during healthy refactoring. An assertion tied to them breaks when nothing is actually wrong — and, worse, stays green when the *behaviour* breaks but the class name survives.

## What makes an assertion valuable
A valuable assertion has one property above all: **it fails when, and only when, the behaviour it protects is broken.** Ask of every assertion, "if this feature silently stopped working, would this line go red?" If the answer is no, the assertion is decoration. If the answer is "it goes red even when the feature is fine, just restyled", the assertion is brittle. You want the narrow band in between: sensitive to real breakage, indifferent to cosmetic change.

## A green test is not automatically a good test
This is the message the whole course keeps returning to. Automation exists to give timely, useful evidence about product quality and risk. A test that passes while asserting nothing meaningful gives false evidence — it is worse than no test, because it buys unearned confidence. The green tick is only as trustworthy as the assertion behind it.

## Key takeaway
Point every assertion at a user-visible outcome or behaviour and ask "would this go red if the feature broke?"; an assertion that survives real breakage is not protecting anyone, however green it looks.$L$, $L$Two tests for the same login flow — one asserts an implementation detail, the other an outcome:

~~~ts
import { test, expect } from '@playwright/test';

// Weak: asserts a network call fired and an element exists, not that login worked.
test('user logs in (implementation-focused)', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Email').fill('priya@example.com');
  await page.getByLabel('Password').fill('correct-horse');
  await page.getByRole('button', { name: 'Sign in' }).click();
  // The dashboard container renders for logged-out users too — this proves little.
  await expect(page.locator('.dashboard-shell')).toBeVisible();
});

// Strong: asserts the user-visible outcome of a successful login.
test('a valid user reaches their dashboard', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Email').fill('priya@example.com');
  await page.getByLabel('Password').fill('correct-horse');
  await page.getByRole('button', { name: 'Sign in' }).click();

  await expect(page).toHaveURL('/dashboard');
  await expect(page.getByRole('heading', { name: 'Welcome back, Priya' })).toBeVisible();
});
~~~

The first test can pass even when authentication is broken, because the shell element is not unique to a logged-in user. The second asserts what a real user would experience — they land on the dashboard and are greeted by name. Break login and only the second test goes red.$L$, $L$- Asserting that an element is present when presence is not evidence the feature worked (containers often render regardless)
- Coupling assertions to CSS classes or DOM structure that a restyle will change without any behaviour changing
- Asserting a network request fired instead of asserting the outcome that request was supposed to produce
- Ending a test on the action ("the button was clicked") rather than on the result of the action$L$, $L$On a delivery team, make "what does this assert, and would it fail if the feature broke?" a standard review question. The cheapest way to expose a weak assertion is to imagine the feature quietly regressing and trace whether any line turns red. If none would, the test is a green light wired to nothing — and everyone downstream is trusting it. Reviewers who ask that one question catch more useless tests than any linter.$L$, $L$Take one of your existing UI tests and write down, in a sentence, exactly what its final assertion protects. Then answer honestly: if that feature silently broke, would the test go red? If not, rewrite the assertion to target the user-visible outcome. Deliverable: the before/after assertion plus your one-sentence statement of what the new assertion defends.$L$, $L$Think of a test you trust. If a developer refactored the component's internals without changing its behaviour, would your test survive? If a developer broke the behaviour but kept the markup, would it fail? What do your answers tell you about where your assertions are aimed?$L$, $L$What single question best exposes a weak assertion? (Answer: "If this feature silently broke, would this assertion go red?")$L$, array[$L$I can tell an outcome-focused assertion from an implementation-focused one$L$, $L$I can state, for any assertion, what behaviour it protects$L$, $L$I write assertions that fail on real breakage and survive cosmetic change$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$Meaningful vs Weak Assertions$L$, $L$18 minute read$L$, $L$The most dangerous test on a team is the one that is always green and proves nothing. This lesson dissects the classic "the page loaded" test and shows how to strengthen weak assertions into ones that actually defend a behaviour.$L$, array[$L$Recognise the common shapes of a weak, always-green assertion$L$, $L$Strengthen a weak assertion by targeting the specific outcome that matters$L$, $L$Explain why "it loaded" is rarely evidence that the feature works$L$], $L$## The classic green-but-useless test
The archetype is the test that navigates somewhere, waits for the page, and asserts that the page loaded:

~~~ts
await page.goto('/checkout');
await expect(page.locator('body')).toBeVisible();
~~~

This can never meaningfully fail. The body is always visible. The test will stay green through a broken checkout, an empty basket, a 500 error rendered as a friendly page — anything, as long as *some* HTML comes back. It reports "checkout works" while checkout is on fire.

## The shapes weak assertions take
Weak assertions tend to fall into a few recognisable patterns:

- **Presence without meaning** — asserting an element exists when its existence is not tied to the feature working (`toBeVisible` on a wrapper that always renders).
- **Loose matching** — `toContainText('')` or a regex so broad it matches almost anything.
- **Asserting the action, not the result** — checking the button is still there after clicking it.
- **Count-of-something with no identity** — `toHaveCount(1)` when you never checked *what* the one thing is.
- **Snapshot-once values** — reading a value into a variable and asserting on the stale copy.

Each of these produces a green tick without producing evidence.

## Strengthening an assertion
To strengthen a weak assertion, name the specific thing that must be true for the feature to be working, and assert exactly that:

- From "the page loaded" to "the page shows the order summary with the correct total".
- From "a row exists" to "a row for the item I just added exists, with its price".
- From "the alert is visible" to "the alert says 'Payment successful'".

The pattern is always: replace a generic, always-true condition with a specific, feature-defining one.

## Why "it loaded" fools people
"It loaded" feels like progress because navigation is the visible part of the flow. But loading is a precondition, not an outcome. A test that stops at loading has walked to the door and declared the house clean without going inside. The green is real; the evidence is not.

## Key takeaway
A weak assertion is one that stays green when the feature breaks — "it loaded" is the archetype; strengthen it by asserting the specific outcome that would be false if the feature were broken, not the generic fact that some page rendered.$L$, $L$Turning a green-but-useless checkout test into one that defends the behaviour:

~~~ts
import { test, expect } from '@playwright/test';

// Weak — passes as long as any page renders, even a broken one.
test('checkout page loads', async ({ page }) => {
  await page.goto('/checkout');
  await expect(page.locator('body')).toBeVisible();
});

// Strong — asserts the specific state that proves checkout is working.
test('checkout shows the order summary and correct total', async ({ page }) => {
  await page.goto('/products');
  await page.getByRole('listitem').filter({ hasText: 'Mechanical keyboard' })
    .getByRole('button', { name: 'Add to basket' }).click();
  await page.getByRole('link', { name: 'Checkout' }).click();

  await expect(page.getByRole('heading', { name: 'Order summary' })).toBeVisible();
  await expect(page.getByRole('row', { name: /Mechanical keyboard/ })).toBeVisible();
  await expect(page.getByTestId('order-total')).toHaveText('£89.00');
});
~~~

The weak test never fails, so it never protects anyone. The strong test names three concrete facts — the summary heading, the specific line item, the exact total — each of which would be false if checkout regressed. Now green means something.$L$, $L$- Asserting on `body`, the page title alone, or a layout wrapper as a stand-in for "the feature works"
- Using `toContainText` with a substring so short it matches unrelated content
- Leaving a test that only navigates and never asserts an outcome, then calling the route "covered"
- Strengthening the wrong thing — adding more assertions about layout while still not checking the actual result$L$, $L$On a delivery team, be suspicious of any test that has never failed. A test that has been green since the day it was written, through months of change to the feature it supposedly covers, is far more likely to be asserting nothing than to be guarding a flawless feature. A quick mutation check — break the feature on a branch and see whether the test notices — separates the guardians from the decorations faster than reading the code.$L$, $L$Find a test in your suite whose strongest assertion is "the page loaded" or "an element is visible". Break the underlying feature deliberately (return an error, remove the data) and confirm the test still passes — proving it is weak. Then strengthen it until your broken version turns it red. Deliverable: the original assertion, the strengthened assertion, and a note of what breakage the new version now catches.$L$, $L$If you deleted the feature under test entirely, how many of your assertions for it would actually fail? What does that number tell you about how much evidence your "coverage" really provides?$L$, $L$Why is "assert the body is visible after navigating" a weak assertion? (Answer: the body is always visible, so the assertion stays green even when the feature is completely broken — it provides no evidence)$L$, array[$L$I can spot the common shapes of an always-green assertion$L$, $L$I can strengthen a weak assertion by targeting the specific outcome$L$, $L$I can explain why "it loaded" is not evidence a feature works$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Test Design Techniques for Automation$L$, $L$19 minute read$L$, $L$Classic test design techniques — equivalence partitioning, boundary values and negative cases — are not just for manual scripts. They are exactly how you decide which few Playwright tests are worth automating out of the infinite ones you could write.$L$, array[$L$Apply equivalence partitioning and boundary value analysis to choose automated cases$L$, $L$Design deliberate negative and error-path tests, not only happy paths$L$, $L$Select a small, high-value set of cases instead of exhaustively automating inputs$L$], $L$## You cannot automate everything — so choose well
There are effectively infinite inputs to any field. Automating them all is impossible and pointless; the skill is choosing the handful that carry the most information about risk. The classic techniques are tools for exactly that choice.

## Equivalence partitioning
Group inputs that the system should treat the same way into a **partition**, and test one representative from each. For a quantity field accepting 1–10:

- Below range (0 and less) — one partition.
- In range (1–10) — one partition.
- Above range (11 and more) — one partition.

One test per partition covers the behaviour; a hundred in-range values tell you nothing the first did not.

## Boundary value analysis
Bugs cluster at the edges of partitions — off-by-one errors, `<` versus `<=`. So test the boundaries and their neighbours: for a 1–10 field, the interesting values are 0, 1, 10 and 11. These four catch far more than four random values would, because they sit exactly where the logic switches.

## Negative and error cases
A suite of only happy paths is a suite that has never asked "what happens when it goes wrong?" — which is where users get hurt. Deliberately design for:

- Invalid input (a malformed email, a past date, letters in a number field).
- Missing input (a required field left blank).
- Rejected operations (wrong password, insufficient stock, expired card).

For each, assert the *right* failure: the specific error message, the field staying editable, no partial commit. "It errored somehow" is as weak as "it loaded".

## Choosing high-value cases
Not every partition deserves a UI test. Weigh each candidate by risk (what breaks if it fails) and by how uniquely the UI exercises it. A pure calculation across many inputs is better exhausted with cheap unit tests; reserve UI tests for the boundaries and paths where the *integrated* behaviour — form, validation, rendering — is the risk. (Lesson 6 goes deeper on where each check belongs.)

## Key takeaway
Use equivalence partitioning and boundary analysis to turn infinite inputs into a handful of representative cases, always include the negative and error paths, and spend your UI tests on the few high-risk boundaries rather than exhaustively re-checking the same partition.$L$, $L$Applying partitioning, boundaries and a negative case to a quantity field (valid range 1–10), using a data-driven Playwright test:

~~~ts
import { test, expect } from '@playwright/test';

// One representative per partition, focused on the boundaries where logic switches.
const cases = [
  { qty: '0',  valid: false, reason: 'below the minimum' },
  { qty: '1',  valid: true,  reason: 'lower boundary' },
  { qty: '10', valid: true,  reason: 'upper boundary' },
  { qty: '11', valid: false, reason: 'above the maximum' },
];

for (const { qty, valid, reason } of cases) {
  test(`quantity ${qty} is ${valid ? 'accepted' : 'rejected'} (${reason})`, async ({ page }) => {
    await page.goto('/products/keyboard');
    await page.getByLabel('Quantity').fill(qty);
    await page.getByRole('button', { name: 'Add to basket' }).click();

    if (valid) {
      await expect(page.getByRole('status')).toHaveText(`${qty} added to basket`);
    } else {
      // Assert the RIGHT failure, not just that something went wrong.
      await expect(page.getByRole('alert'))
        .toHaveText('Quantity must be between 1 and 10');
      await expect(page.getByRole('status')).toBeHidden();
    }
  });
}
~~~

Four cases replace dozens of arbitrary ones because they sit on the partition boundaries. The negative cases assert the specific error and confirm nothing was added — a precise failure, not a vague one.$L$, $L$- Automating many values from the same equivalence partition, adding runtime but no new information
- Testing only happy paths and never the invalid, missing or rejected cases where users actually get stuck
- Asserting "an error appeared" instead of asserting the correct, specific error for that input
- Exhaustively driving a pure calculation through the UI when unit tests could cover the partitions far more cheaply$L$, $L$On a delivery team, sketch the partitions and boundaries with a developer before writing the tests — often on a whiteboard during refinement. It surfaces disagreements about the rules ("is 10 inclusive?") while they are cheap to resolve, and it stops two people writing five redundant happy-path tests and zero negative ones. The design conversation is usually worth more than the tests it produces, because it exposes ambiguous requirements before code is written.$L$, $L$Choose a form field with a defined valid range or format. List its equivalence partitions and boundary values, then write a data-driven Playwright test covering one representative per partition plus the boundaries, including at least two negative cases that each assert the specific error. Deliverable: your partition/boundary table and the parameterised spec.$L$, $L$Look at a feature you have automated. How many of your tests are happy paths, and how many are negative or boundary cases? If a user hit an edge you did not test, would they get a helpful error or a broken experience — and would your suite know?$L$, $L$For a field accepting values 1 to 10, which four values does boundary value analysis suggest testing? (Answer: 0, 1, 10 and 11 — the boundaries and their immediate neighbours)$L$, array[$L$I can partition inputs and pick one representative per partition$L$, $L$I can identify the boundary values worth testing at the UI$L$, $L$I design deliberate negative cases that assert the correct, specific failure$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$One Test, One Reason to Fail$L$, $L$17 minute read$L$, $L$A test that checks five unrelated things is five tests wearing a trench coat — and when it fails, you cannot tell which one broke. This lesson is about focused tests, the Arrange-Act-Assert shape, and why over-stuffed tests are hard to trust and slow to debug.$L$, array[$L$Structure a test with a clear Arrange-Act-Assert shape$L$, $L$Explain why a test should have a single reason to fail$L$, $L$Split an over-stuffed test into focused tests that each defend one behaviour$L$], $L$## Arrange, Act, Assert
The clearest tests follow a three-part shape:

- **Arrange** — set up the state the behaviour needs (navigate, log in, seed data).
- **Act** — perform the one action under test (submit the form, click Save).
- **Assert** — check the outcome of that action.

Keeping the three visually separated — even with blank lines — makes a test readable at a glance and signals when a test is trying to do too much. Two "Act" sections is usually a sign you have two tests.

## One reason to fail
A focused test verifies **one behaviour** and therefore has **one reason to fail**. When it goes red, the name and the single assertion block tell you immediately what broke. Compare that with a test that logs in, updates a profile, changes a password and checks notifications: when it fails on line 40, you do not know which of four features regressed, and you must read the whole test to find out.

"One reason to fail" does not mean one `expect` call. Several assertions that together describe a single outcome — the order summary shows the item, the total and the address — are one reason to fail. The test is unfocused when the assertions describe *different, independent behaviours*.

## Why over-stuffed tests erode trust
Long, multi-purpose tests hurt in specific ways:

- **Ambiguous failures** — a red result does not localise the fault, so triage is slow.
- **Fragility** — the more the test touches, the more unrelated changes break it.
- **Hidden gaps** — an early failure hides everything after it; the later checks never even run, so you do not know if they would have passed.
- **Slow feedback** — one giant test cannot be parallelised or run in isolation as easily as several small ones.

A suite of focused tests fails informatively; a suite of sprawling ones fails mysteriously, and mysterious failures are the ones teams learn to ignore.

## When shared setup is expensive
The answer to "but logging in for every test is slow" is not to chain behaviours into one test — it is to share *setup* through fixtures or stored authentication state while keeping each *behaviour* in its own test. Share the arrangement; never share the act and assert.

## Key takeaway
Give each test a single behaviour to defend and a single reason to fail, laid out as Arrange-Act-Assert; when a focused test goes red its name tells you what broke, while an over-stuffed one leaves you reading forty lines to find out.$L$, $L$An over-stuffed test split into focused ones, sharing setup through a hook rather than through execution order:

~~~ts
import { test, expect } from '@playwright/test';

// Before: one test, four behaviours, one confusing failure when anything breaks.
test('account management works', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Email').fill('priya@example.com');
  await page.getByLabel('Password').fill('correct-horse');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByLabel('Display name').fill('Priya P');
  await page.getByRole('button', { name: 'Save profile' }).click();
  await expect(page.getByRole('alert')).toContainText('Profile updated');
  await page.getByRole('link', { name: 'Security' }).click();
  await page.getByLabel('New password').fill('new-battery-staple');
  await page.getByRole('button', { name: 'Change password' }).click();
  await expect(page.getByRole('alert')).toContainText('Password changed');
});
~~~

~~~ts
// After: shared login in a hook; each behaviour is its own focused test.
test.describe('Account management', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/login');
    await page.getByLabel('Email').fill('priya@example.com');
    await page.getByLabel('Password').fill('correct-horse');
    await page.getByRole('button', { name: 'Sign in' }).click();
  });

  test('updating the display name shows a confirmation', async ({ page }) => {
    // Act
    await page.getByLabel('Display name').fill('Priya P');
    await page.getByRole('button', { name: 'Save profile' }).click();
    // Assert
    await expect(page.getByRole('alert')).toContainText('Profile updated');
  });

  test('changing the password shows a confirmation', async ({ page }) => {
    await page.getByRole('link', { name: 'Security' }).click();
    await page.getByLabel('New password').fill('new-battery-staple');
    await page.getByRole('button', { name: 'Change password' }).click();
    await expect(page.getByRole('alert')).toContainText('Password changed');
  });
});
~~~

Now a failure in the password test cannot be masked by the profile test, each test name pinpoints the behaviour, and the shared login lives in one place without chaining the two behaviours together.$L$, $L$- Bundling several unrelated behaviours into one test so a failure cannot be localised
- Letting an early assertion failure hide later checks that then never run
- Confusing "one reason to fail" with "one expect" and splitting a single outcome into artificial tests
- Sharing setup by chaining tests in order instead of using a beforeEach or a fixture$L$, $L$On a delivery team, judge a test by its failure, not its success. When a test goes red in CI, can a teammate tell what broke from the test name alone, without opening the file? If yes, the test is focused and named well. If they have to read forty lines to find which of several behaviours failed, the test is doing too much — and in practice such tests get muted rather than fixed, because nobody has time to decode them under release pressure.$L$, $L$Find a test in your suite that verifies more than one behaviour. Split it into focused tests, each with a clear Arrange-Act-Assert shape and a name that states the single behaviour it defends, moving any shared setup into a `beforeEach`. Deliverable: the original test and the set of focused tests it became, plus a note on which behaviour each new test would flag if it failed.$L$, $L$Recall the last test failure you triaged. How long did it take to work out what had actually broken? How much of that time was the test's structure rather than the bug itself?$L$, $L$What does "one test, one reason to fail" mean in practice? (Answer: each test verifies a single behaviour, so a red result identifies exactly what broke — not that a test may contain only one expect call)$L$, array[$L$I can lay out a test as Arrange-Act-Assert$L$, $L$I can explain why a single reason to fail makes failures easy to triage$L$, $L$I can split an over-stuffed test into focused tests sharing setup properly$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Tests as Documentation$L$, $L$16 minute read$L$, $L$The next engineer to touch this feature will read your tests before they read the code. Written well, a test suite is the most honest specification a team has — it describes what the system does and stays true because it runs. This lesson is about writing tests that communicate intent.$L$, array[$L$Name and structure tests so they describe behaviour to a future reader$L$, $L$Write test bodies that read as intent rather than as mechanics$L$, $L$Explain why executable tests are more trustworthy documentation than prose$L$], $L$## Tests are read more than they are written
A test is written once and read many times — during reviews, when a related feature changes, when it fails at 4pm before a release. Its first job is to *communicate*: what behaviour does this protect, and what does the feature promise? Code comments drift out of date silently; a test that lies gets caught, because it runs. That makes a well-written suite the most trustworthy documentation a team owns.

## Names that describe behaviour
The test name is the headline. Write it as a statement about behaviour a stakeholder could read:

- Not `test('login')` but `test('a valid user is taken to their dashboard')`.
- Not `test('quantity')` but `test('rejects a quantity above the maximum with a clear message')`.

A good name completes the sentence "it verifies that…". Read down a list of such names and you have a plain-English specification of the feature. Read a list of `test1`, `login`, `checkTable` and you have nothing.

## Structure that reads as intent
Inside the test, favour readability over cleverness:

- Group with `test.describe('Checkout', ...)` so the report reads as a feature outline.
- Keep the Arrange-Act-Assert sections visually distinct.
- Prefer user-facing locators — `getByRole('button', { name: 'Sign in' })` reads like an instruction; `page.locator('.btn-x7')` reads like noise.
- Extract fiddly setup into a well-named helper or fixture so the test body shows *what* happens, not *how* it is wired.

## Let the assertions state the promise
Because assertions are the specification (Lesson 1), they should read like promises the feature makes: `toHaveText('Payment successful')`, `toHaveURL('/dashboard')`. A reader should be able to skim only the assertions and know what the feature guarantees.

## Documentation that cannot go stale
Prose docs and code comments describe intent but are not checked against reality, so they rot. A test describes intent *and* is executed every run — if the behaviour changes and the test is not updated, it fails. That coupling is why "the tests are the spec" is more than a slogan: it is the one form of documentation the build refuses to let you falsify.

## Key takeaway
Write test names as behaviour statements and bodies as intent, so a reader learns what the feature does from the suite alone; because tests run, they are the one specification that cannot quietly drift out of date — but only if you name and structure them for the human who reads them next.$L$, $L$The same test written as mechanics, then as documentation:

~~~ts
import { test, expect } from '@playwright/test';

// Reads as mechanics — the name and body tell a future reader almost nothing.
test('test2', async ({ page }) => {
  await page.goto('/login');
  await page.locator('#e').fill('priya@example.com');
  await page.locator('#p').fill('correct-horse');
  await page.locator('.sbtn').click();
  await expect(page.locator('.dash h1')).toBeVisible();
});
~~~

~~~ts
// Reads as documentation — a stakeholder could understand what it guarantees.
test.describe('Login', () => {
  test('a valid user is greeted on their dashboard', async ({ page }) => {
    // Arrange
    await page.goto('/login');

    // Act
    await page.getByLabel('Email').fill('priya@example.com');
    await page.getByLabel('Password').fill('correct-horse');
    await page.getByRole('button', { name: 'Sign in' }).click();

    // Assert
    await expect(page).toHaveURL('/dashboard');
    await expect(page.getByRole('heading', { name: 'Welcome back, Priya' })).toBeVisible();
  });
});
~~~

The behaviour is identical; the second version teaches the reader what login promises. The describe block, the behavioural name, the labelled sections and the user-facing locators all carry meaning the first version threw away.$L$, $L$- Naming tests after implementation or sequence (`test1`, `clickFlow`) instead of the behaviour they verify
- Filling test bodies with cryptic CSS locators that read as noise to the next engineer
- Relying on out-of-line comments to explain a test that clearer names and locators would make self-evident
- Writing the name for yourself today rather than for the teammate debugging it under pressure next quarter$L$, $L$On a delivery team, run `npx playwright test --list` and read the test titles as if they were the feature's specification. If a product owner could not follow what the system does from that list, the names are too technical. Some teams deliberately review the list of test names in refinement as a lightweight acceptance-criteria check — the suite doubles as living documentation only if the names are written for humans, so it is worth treating naming as part of the work, not an afterthought.$L$, $L$Take a spec file with vague test names and rewrite every name as a behaviour statement that completes "it verifies that…". Group related tests under a `test.describe`, and replace at least three cryptic locators with user-facing ones. Deliverable: the before/after list of test names and a note on whether the file now reads as a specification of the feature.$L$, $L$If a new engineer joined tomorrow and read only your test names for a feature, could they describe what it does and what rules it enforces? If not, what is the documentation gap — the code's, or the tests'?$L$, $L$Why are executable tests more trustworthy documentation than code comments? (Answer: tests run every build, so if the behaviour changes without the test being updated the test fails — comments can silently go stale because nothing checks them)$L$, array[$L$I can name a test as a behaviour statement a stakeholder could read$L$, $L$I can structure a test body so it reads as intent, not mechanics$L$, $L$I can explain why running tests are documentation that cannot quietly rot$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 6, $L$What NOT to Automate at the UI$L$, $L$18 minute read$L$, $L$The most valuable automation decision is often not writing a UI test at all. This lesson is about pushing checks down the testing pyramid — choosing the cheapest reliable level for each risk so your UI suite stays small, fast and focused on what only the UI can prove.$L$, array[$L$Explain the testing pyramid and why UI tests are the scarce, expensive tier$L$, $L$Decide the cheapest reliable level at which to check a given risk$L$, $L$Move logic-heavy checks down to unit or API tests and keep the UI suite lean$L$], $L$## The pyramid, and why UI tests are precious
The testing pyramid is a heuristic about *proportion*: many fast unit tests at the base, a moderate layer of integration and API tests in the middle, and a thin cap of end-to-end UI tests at the top. UI tests are the most valuable per test — they exercise the real integrated system a user touches — but also the slowest, the most brittle, and the most expensive to maintain. That combination means you want *few* of them, each earning its place.

## Push each check to the cheapest reliable level
For any given risk, ask: what is the lowest level of the pyramid that can reliably catch it? Test it there, once.

- **Business logic and calculations** (tax rules, discount tiers, date maths) — unit tests. Exhaust the partitions and boundaries where they are milliseconds each, not through the browser.
- **Contracts between services, validation, error codes** — API or integration tests. Faster and more stable than driving the UI, and they pinpoint the failing layer.
- **The integrated user journey** — a UI test, but only for the path that genuinely needs a real browser: rendering, navigation, the wiring between front end and back end.

The same rule of thumb: do not use a slow, flaky UI test to check something a fast, stable unit or API test could check just as well.

## What only the UI can prove
Reserve UI tests for what genuinely requires a rendered page in a real browser:

- Critical end-to-end journeys (log in, search, buy, receive confirmation).
- That the pieces are wired together — the form posts, the response renders, navigation works.
- Rendering and interaction that only exist in the browser.

If a test could pass or fail without ever painting a pixel, it probably does not belong at the UI.

## Avoid re-testing the same logic at every level
A common waste is verifying the same discount calculation in a unit test, again in an API test, and again through the UI. Test the logic once at the bottom; let the UI test assert only that the correct, already-trusted result is *displayed*. Duplicated checks cost triple to maintain and give no extra evidence.

## Green at the wrong level is expensive
A logic rule checked only through the UI gives you a slow, flaky guardian for something a unit test could protect in a millisecond. It is not wrong that it is green — it is wrong that it is *there*: it slows every pipeline run and flakes on unrelated UI churn. Choosing the level well is itself a quality decision, because automation's job is timely, useful evidence — and the wrong level makes the evidence slow and noisy.

## Key takeaway
Push every check to the cheapest level that can reliably catch its risk — logic and contracts down at unit and API tests, and the UI reserved for the few integrated journeys only a real browser can prove; a lean UI suite gives faster, more trustworthy evidence than a bloated one re-testing what belongs lower down.$L$, $L$Deciding the right level for a discount rule, then keeping the UI test lean:

~~~text
Risk: a 10% loyalty discount must apply to orders over £50, but never below.

Boundary cases (49.99, 50.00, 50.01, ...) — dozens of them.
  -> Unit-test the pricing function directly. Milliseconds each, exhaust the boundaries.

The API returns the discounted total for a basket.
  -> One API/integration test that the endpoint applies the rule end to end.

The user sees the right total at checkout.
  -> ONE UI test: the displayed total reflects the discount. Not the maths — just the display.
~~~

The UI test then asserts only that the trusted result is shown, not the calculation itself:

~~~ts
import { test, expect } from '@playwright/test';

// The discount MATHS is proven by unit tests. This UI test proves only that
// the qualifying basket displays the discounted total to the user.
test('a qualifying basket shows the loyalty discount at checkout', async ({ page }) => {
  await page.goto('/products/keyboard');       // priced to push the basket over £50
  await page.getByRole('button', { name: 'Add to basket' }).click();
  await page.getByRole('link', { name: 'Checkout' }).click();

  await expect(page.getByRole('row', { name: /Loyalty discount/ })).toBeVisible();
  await expect(page.getByTestId('order-total')).toHaveText('£80.10');
});
~~~

Every boundary of the rule is checked cheaply at the unit level; the UI carries a single test proving the number reaches the user. If the discount logic changes, one fast unit test fails precisely — not a dozen slow browser tests vaguely.$L$, $L$- Automating business-logic permutations through the browser when unit tests would cover them in milliseconds
- Re-testing the same calculation at unit, API and UI levels, tripling maintenance for no extra evidence
- Treating "we have UI tests for it" as thorough while the fast, stable layers below sit empty
- Building a top-heavy suite — an inverted pyramid — that is slow, flaky, and distrusted$L$, $L$On a delivery team, when a new risk appears the first question is not "how do we automate this in Playwright?" but "what is the cheapest level that catches it reliably?". Teams that ask the second question keep a small, fast, trusted UI suite; teams that default to UI for everything end up with a slow, flaky pipeline people learn to re-run until it is green — which quietly destroys the evidence automation was supposed to provide. Deciding the level is a shared engineering conversation, not something QA settles alone.$L$, $L$Take three checks currently done at the UI in your suite and, for each, decide the cheapest reliable level (unit, API, or genuinely UI). Move at least one down a level — or write the unit/API test that would let you delete the UI version — and reduce the UI test to asserting only the integrated outcome. Deliverable: a short table of the three checks, the level you chose for each with a one-line justification, and the leaner UI test.$L$, $L$Look at your UI suite. How many of its tests would still be needed if the logic they exercise were fully covered by fast unit and API tests? What is that count telling you about the shape of your pyramid?$L$, $L$Why should business-logic boundary cases usually be unit-tested rather than UI-tested? (Answer: unit tests run in milliseconds and are stable, so they can exhaust the boundaries cheaply; UI tests are slow and brittle, so reserve them for integrated journeys only a real browser can prove)$L$, array[$L$I can explain the pyramid and why UI tests are the scarce, expensive tier$L$, $L$I can choose the cheapest reliable level for a given risk$L$, $L$I keep the UI suite lean by pushing logic checks down and asserting only integrated outcomes$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

