-- ============================================================
-- API Testing Masterclass — Module 9 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/api-module9.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$Where AI Helps in API Testing$L$, $L$13 minute read$L$, $L$AI tools can genuinely speed up API testing — but only in the right places. This lesson maps where AI adds real value and where it quietly creates risk, so you stay the accountable tester.$L$, array[$L$Identify tasks where AI reliably accelerates API testing$L$, $L$Recognise where AI output must be verified before you trust it$L$, $L$Explain why the tester, not the tool, remains accountable$L$], $L$## What AI is genuinely good at
AI is fast at the *drafting* and *summarising* parts of API testing:
- Generating first-draft **test ideas** from an endpoint or spec
- Suggesting **edge cases** and boundary values you might miss
- Drafting **assertions** and test data
- Explaining an unfamiliar response or error in plain English

## Where AI needs a tight leash
- **Facts about your specific system** — it will confidently invent endpoints and fields
- **Anything security-sensitive** — never paste real tokens, secrets or live data
- **Final judgement** — whether a test is *correct and worth running* is yours

## The mental model
Treat AI as a **fast, tireless junior tester**: brilliant at first drafts, terrible at knowing what it doesn't know. You review everything it produces before it goes anywhere near your suite.

## Example
A prompt that plays to AI's strengths:

```
You are helping a QA engineer. Given this endpoint description,
list 10 test ideas grouped by: happy path, validation, auth,
and edge cases. Do not invent fields I did not provide.
Endpoint: POST /orders — body {item: string, qty: integer}.
```

You keep the accountability; AI just gets you to a first draft faster.$L$, $L$You ask an AI to "list test ideas for POST /orders with body {item, qty}". It returns happy-path, missing-field, negative-qty, huge-qty and wrong-type cases — a solid start. To verify: check each idea against the *real* endpoint (does qty actually reject 0?), delete any that reference fields you never mentioned, and add domain cases the AI couldn't know (e.g. your business caps qty at 50). The AI saved ten minutes; your review made it correct.$L$, $L$- Treating AI output as fact instead of a first draft to verify
- Asking AI about your specific system, which it cannot know, then trusting invented endpoints
- Handing over judgement — letting AI decide what "passing" means instead of you$L$, $L$Use AI for breadth, use your brain for depth. AI is superb at generating twenty test ideas in seconds; deciding which five actually matter for *this* release is still your job.$L$, $L$Pick one endpoint you know well. List three testing tasks where AI would genuinely help you, and two where you would not trust it without verification. Write one sentence explaining each.$L$, $L$If an AI drafts your assertions and one is wrong, who is accountable for the escaped bug?$L$, $L$When AI generates test ideas for your API, whose responsibility is it to verify they are correct? (Answer: the tester's — AI drafts, you verify and stay accountable)$L$, array[$L$I can name tasks where AI accelerates API testing$L$, $L$I can name tasks where AI output must be verified first$L$, $L$I can explain why I stay accountable for AI-assisted work$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 9
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$AI for Endpoint Analysis & Test Ideas$L$, $L$15 minute read$L$, $L$Given an endpoint or a spec, AI can generate a broad, structured set of test ideas in seconds. This lesson shows how to prompt for that breadth — and how to turn a raw list into a real test plan.$L$, array[$L$Write a context-rich prompt that produces structured test ideas$L$, $L$Group AI-generated ideas by category (happy path, validation, auth, edge)$L$, $L$Filter and prioritise the raw list into a usable plan$L$], $L$## Give the AI what it needs
A good test-idea prompt includes the **method**, **path**, **request shape**, **response shape** and any **rules** you know. The more context, the fewer hallucinations.

## Ask for structure, not a wall of text
Request the ideas **grouped** so you can scan and prioritise:
- Happy path
- Validation / negative
- Authentication & authorisation
- Boundaries & edge cases

## Example prompt

```
You are a senior API tester. Generate test ideas for this endpoint,
grouped by: happy path, validation, auth, boundaries. Number each
idea and keep them one line. Only use the fields I provide.

POST /transfers
Body: { fromAccount: string, toAccount: string, amount: number }
Rules: amount must be > 0; both accounts must exist; caller must
own fromAccount.
```

## Turn the list into a plan
AI gives you breadth; you add depth. Delete duplicates, remove anything referencing invented fields, add domain cases the AI can't know (currency limits, fraud thresholds), then **prioritise by risk**. The list is a starting point, never the finished plan.$L$, $L$You paste the `POST /transfers` prompt above. The AI returns ~15 ideas including "transfer to a non-existent account", "negative amount", "amount = 0", "transfer from an account you don't own", and "very large amount". You verify: 0 and negative are real per your rules (keep), the "duplicate transfer idempotency" idea is genuinely valuable (keep, flag as high risk), and one idea references a `currency` field you never mentioned — you delete it as a hallucination. Result: a prioritised 10-case plan in five minutes instead of thirty.$L$, $L$- Prompting with just an endpoint name and no request/response shape, so the AI guesses
- Accepting the whole list without pruning duplicates or invented fields
- Skipping the prioritisation step — twenty unranked ideas is not a test plan$L$, $L$The quality of AI test ideas is almost entirely down to the context you provide. Paste the actual request and response shapes and the AI stops guessing and starts reasoning.$L$, $L$Take a real endpoint (or one from jsonplaceholder / reqres). Write a context-rich prompt asking for test ideas grouped by category. Generate them, then mark each idea keep / delete / needs-verification and explain why for three of them.$L$, $L$Why does giving the AI the response shape, not just the endpoint name, reduce hallucinated test ideas?$L$, $L$What is the single most effective way to reduce hallucinated test ideas from an AI? (Answer: give it rich context — the real request and response shapes and known rules)$L$, array[$L$I can write a context-rich prompt for test ideas$L$, $L$I can get ideas returned grouped by category$L$, $L$I can filter and prioritise the raw list into a plan$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 9
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Generating Assertions & Test Data with AI$L$, $L$15 minute read$L$, $L$AI can draft the fiddly parts of a test — assertions and test data — quickly. This lesson shows how to get usable Postman/JS assertions and realistic data, then verify every line before it enters your suite.$L$, array[$L$Prompt AI for assertions in a specific framework and style$L$, $L$Generate realistic, boundary-aware test data$L$, $L$Verify AI-generated assertions and data against the real API$L$], $L$## Assertions: be specific about the tool
Tell the AI *which framework* and *which response* you're asserting on. Vague requests produce pseudo-code; specific ones produce runnable snippets.

```
Write Postman test assertions (pm.test / pm.expect) for this response.
Assert: status 200, body has id (number), email is a valid string,
status is one of ["active","suspended"], and orders is an array.
Response: { "id": 7, "email": "a@b.com", "status": "active", "orders": [] }
```

## Test data: ask for the awkward values
AI is excellent at generating boundary and nasty-input data:
- Valid, minimal, maximal values
- Empty strings, nulls, wrong types
- Injection-style and unicode strings for robustness

## Always verify against reality
- Run the assertions against the **real** endpoint — do the field names and types match?
- Delete any assertion on a field the API doesn't actually return
- Check generated data is **safe** and **synthetic** — never real customer records

## The rule
AI writes the draft; you run it, read it, and confirm it matches the true response before it's trusted.$L$, $L$You give the AI a sample response and ask for Postman assertions. It returns `pm.expect(pm.response.json().status).to.be.oneOf(["active","suspended"])` and a check for `orders` being an array. You verify by running it against the real endpoint: the status assertion passes, but the AI also added a check for `lastLogin` — a field your API never returns, so the test fails. You delete that line (it was hallucinated) and keep the rest. Five assertions drafted, one caught and removed, all confirmed against the live response.$L$, $L$- Not naming the framework, so you get pseudo-code you can't run
- Trusting assertions against fields the API doesn't actually return
- Generating "test data" that is really copied production data — a privacy breach$L$, $L$Ask the AI for the boundary and malformed data specifically — empty, null, maximum length, wrong type. Those are exactly the values humans forget and where the interesting bugs hide.$L$, $L$Take a real JSON response from an endpoint. Ask an AI to write assertions for it in Postman (or your framework). Run them against the live endpoint, then list which passed, which failed, and which asserted on a field that doesn't exist.$L$, $L$Why must you run AI-generated assertions against the real endpoint before trusting them?$L$, $L$Before adding AI-generated assertions to your suite, what must you do first? (Answer: run them against the real endpoint and confirm the fields and types actually match)$L$, array[$L$I can prompt AI for assertions in my chosen framework$L$, $L$I can generate boundary and malformed test data$L$, $L$I can verify AI assertions and data against the real API$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 9
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$AI for API Documentation$L$, $L$13 minute read$L$, $L$AI can turn a raw request/response into readable documentation, summarise a sprawling spec, and explain a confusing error. Used well it saves hours; used carelessly it publishes confident nonsense. This lesson keeps you on the useful side.$L$, array[$L$Use AI to draft and summarise API documentation from real examples$L$, $L$Explain an unfamiliar endpoint or error using AI$L$, $L$Verify AI-written documentation against the actual API behaviour$L$], $L$## Great documentation uses cases
- Draft a **plain-English summary** of what an endpoint does from a real example
- Summarise a **long OpenAPI/Swagger spec** into the parts you care about
- Explain a **cryptic error response** and suggest likely causes
- Draft a **table of fields** with types and meanings

## Feed it real examples
Give the AI an actual request and response — it documents what it *sees*, not what it *guesses*. That single habit removes most documentation hallucinations.

```
Turn this request/response into concise API docs: a one-line summary,
a parameter table (name, type, required, description), and one example.
Only document what is shown; flag anything you are unsure about.

GET /invoices?status=unpaid&page=2
Response: { "data": [ { "id": 11, "amount": 40.0, "status": "unpaid" } ],
            "page": 2, "total": 57 }
```

## Always verify before publishing
- Cross-check every field and type against the **real** response
- Confirm required-vs-optional is correct — AI often guesses this wrong
- Never document security details (tokens, internal URLs) that shouldn't be public

Documentation you didn't verify is worse than none — people trust it.$L$, $L$You paste a real `GET /invoices` request and response and ask for concise docs. The AI produces a clean one-line summary, a parameter table, and an example. You verify: the `status` and `page` params are correct, but the AI marked `page` as *required* when it's actually optional (defaults to 1). You correct that one cell. It also invented a `currency` field description — you delete it because the sample never showed one. Ten minutes of drafting saved; two errors caught before anyone relied on the doc.$L$, $L$- Publishing AI docs without checking field types and required/optional flags
- Letting the AI describe endpoints from their names alone, so it invents behaviour
- Documenting sensitive details (auth tokens, internal hosts) that should never be public$L$, $L$Always give the AI a real request/response pair to document, and explicitly tell it to flag anything it's unsure about. Documentation grounded in a real example is far more trustworthy than documentation grounded in a guess.$L$, $L$Take a real endpoint's request and response. Ask an AI to produce a one-line summary plus a field table (name, type, required, description). Verify every field and required flag against the actual response, and note any the AI got wrong.$L$, $L$Why is unverified AI-written documentation potentially more dangerous than having no documentation at all?$L$, $L$What is the safest input to give an AI when asking it to document an endpoint? (Answer: a real request/response example, so it documents what it sees rather than guessing)$L$, array[$L$I can use AI to draft documentation from a real example$L$, $L$I can use AI to explain an unfamiliar endpoint or error$L$, $L$I can verify AI documentation against the real API before trusting it$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 9
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Responsible & Safe AI Use in API Testing$L$, $L$16 minute read$L$, $L$AI accelerates API testing, but it can also leak secrets, hallucinate confidently, and lull you into skipping review. This closing lesson sets the professional standard: use AI hard, but safely — and never surrender your accountability.$L$, array[$L$Apply data-safety rules when using AI (no secrets, tokens or real data)$L$, $L$Detect and handle AI hallucinations in a testing context$L$, $L$Define a responsible personal policy for AI-assisted API testing$L$], $L$## The non-negotiables
- **Never paste secrets** — no real tokens, API keys, passwords or connection strings
- **Never paste confidential or personal data** — redact real customer records; use synthetic values
- **Assume public AI tools may retain input** — treat the prompt box like a public forum unless your org's enterprise tool guarantees otherwise
- **Follow your organisation's AI policy** — if there isn't one, ask

## Spot the hallucinations
AI states invented facts with total confidence. In testing, watch for:
- **Invented endpoints** and query params that don't exist
- **Hallucinated fields** in requests or assertions
- **Wrong status codes** or made-up error meanings
Verify every specific claim against the real API or the spec.

## Redact before you prompt

```
Explain what this API error means and likely causes. I have redacted
the token and customer id — do not ask me to paste the real values.
Response: 401 { "error": "invalid_token" } on GET /accounts/{REDACTED}
Authorization: Bearer {REDACTED}
```

## Your responsible-use policy
Draft breadth with AI, verify everything, keep secrets out, follow policy, and own the outcome. The tester stays accountable — that never changes.$L$, $L$You hit a confusing `401 invalid_token` on a real staging endpoint. Rather than pasting the live bearer token, you redact it to `{REDACTED}` and ask the AI to explain likely causes. It suggests an expired token, a wrong scope, or a clock-skew issue — all plausible. You verify against your auth provider's docs, find the token had indeed expired, and refresh it. You got the answer fast *and* no secret ever left your machine. That is responsible AI use in one small loop.$L$, $L$- Pasting real tokens, keys or customer data into a public AI tool
- Accepting a confident answer without checking the endpoint or field actually exists
- Assuming "AI wrote it" removes your responsibility for an escaped bug$L$, $L$Before you paste anything into an AI tool, ask one question: "Would I be comfortable if this appeared on a public forum?" If not, redact it or don't paste it. That single reflex prevents almost every AI data-safety incident.$L$, $L$Choose an endpoint and use an AI tool end-to-end: generate test ideas and assertions for it, then validate them against the real API. As you go, redact anything sensitive, and write down (a) two things you verified and corrected, and (b) one thing you deliberately did not paste and why.$L$, $L$What is your personal red line for what you will never paste into a public AI tool, and how will you enforce it under deadline pressure?$L$, $L$Is it acceptable to paste a real production API token into a public AI chat tool to debug an error? (Answer: no — never paste real secrets, tokens or confidential data; redact and use synthetic values)$L$, array[$L$I can apply data-safety rules when using AI for testing$L$, $L$I can spot and verify AI hallucinations against the real API$L$, $L$I can state my own responsible-use policy for AI-assisted testing$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 9
on conflict (module_id, lesson_number) do nothing;

