-- ============================================================
-- API Testing Masterclass — Module 12 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/istqb-module12.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$Study Techniques$L$, $L$14 minute read$L$, $L$How you study matters more than how long you study. This lesson shows you the two techniques that reliably beat re-reading for the ISTQB Foundation (CTFL) exam: active recall and spaced repetition.$L$, array[$L$Explain why active recall beats passive re-reading$L$, $L$Apply spaced repetition to the CTFL syllabus$L$, $L$Build a simple study routine that fits around a job$L$], $L$## Passive reading is the trap
Highlighting the syllabus and re-reading it *feels* productive, but recognition is not recall. In the exam you must **retrieve** definitions and apply them under time pressure — so practise retrieval, not recognition.

## Active recall
Close the book and ask yourself the question first. "What are the seven testing principles?" "What is the difference between verification and validation?" Struggling to remember is the moment the memory actually forms. Flashcards, self-quizzing and blank-page brain-dumps all force recall.

## Spaced repetition
Review material at increasing intervals — day 1, day 3, day 7, day 16 — rather than cramming it once. Each successful recall pushes the next review further out. Tools like Anki automate the schedule; a paper Leitner box of index cards works just as well.

## A realistic weekly routine
- **Learn** a new chapter (K1/K2 definitions).
- **Recall** yesterday's chapter from a blank page.
- **Practise** exam questions on older chapters.
Rotate these three so every topic gets revisited before you forget it.$L$, $L$Take the seven testing principles. Day 1: read them, then close the syllabus and write them from memory — you get four. Day 3: try again — six. Day 7: all seven, in order. That climb from 4→6→7 is spaced active recall doing its job; re-reading the list ten times in one sitting would not have produced it.$L$, $L$- Re-reading and highlighting instead of self-testing
- Cramming a topic once and never revisiting it
- Studying for hours with the syllabus open, never closing it to recall$L$, $L$The single highest-value study habit is the blank-page brain-dump: after each chapter, write everything you remember with the book shut, then check. It exposes exactly what you don't know.$L$, $L$Pick one chapter you've already read. Close the syllabus and write everything you remember on a blank page. Then open it and mark what you missed.$L$, $L$Why does trying to recall something before checking the answer build stronger memory than re-reading it?$L$, $L$Which study technique builds stronger memory — passively re-reading notes, or actively recalling answers before checking? (Answer: active recall)$L$, array[$L$I understand why active recall beats re-reading$L$, $L$I can apply spaced repetition to my study plan$L$, $L$I have a weekly routine that rotates learn / recall / practise$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 12
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$Revision Planning$L$, $L$15 minute read$L$, $L$A vague intention to "revise" is how people run out of time. This lesson turns the CTFL syllabus into a realistic, dated revision plan you can actually follow around a full-time job.$L$, array[$L$Break the CTFL syllabus into a weekly plan$L$, $L$Weight revision time towards higher-value chapters$L$, $L$Build in mock exams and a taper before exam day$L$], $L$## Start from the exam, work backwards
The CTFL exam is **40 multiple-choice questions in 60 minutes** (75 minutes if English is not your first language), pass mark **65% — that's 26 out of 40**. Every chapter is worth a known number of marks in the syllabus; spend your time in proportion to those marks, not to how interesting a topic is.

## Weight your time
Chapters 1 (Fundamentals) and 4 (Test Techniques) carry the most marks and the most K3 "apply" questions — give them the most revision. Chapters 3 (Static Testing) and 5 (Test Management) are mid-weight. Don't over-invest in the smallest chapters.

## A realistic 12-week shape
- **Weeks 1–8:** learn one chapter a week using active recall.
- **Weeks 9–10:** full mock exams under timed conditions.
- **Week 11:** re-drill your weakest topics from mock results.
- **Week 12:** light revision and taper — no cramming the night before.

## Plan for slippage
Life happens. Leave one empty "catch-up" slot each week so a missed evening doesn't derail the whole schedule.$L$, $L$A tester with eight weeks and evenings only maps it out: Mon = learn new chapter, Wed = recall last chapter, Fri = 10 practice questions on older chapters, Sun = catch-up. Weeks 7–8 become back-to-back timed mocks. Because Sundays are deliberately empty, a missed Wednesday never snowballs.$L$, $L$- No dated plan — just "I'll revise this week"
- Spending equal time on every chapter regardless of its mark weighting
- Leaving all the mock exams to the final two days$L$, $L$Book your exam date first, then build the plan backwards from it. A booked, paid-for date is the deadline that makes a revision plan real.$L$, $L$Count the weeks between today and your target exam date. Sketch a plan that ends with at least two full timed mock exams.$L$, $L$Why should revision time be weighted towards Chapters 1 and 4 rather than spread evenly?$L$, $L$What is the pass mark for the ISTQB Foundation (CTFL) exam, as a fraction of the 40 questions? (Answer: 65% — 26 out of 40)$L$, array[$L$I have a dated revision plan ending on my exam date$L$, $L$My plan weights time towards high-mark chapters$L$, $L$My plan includes at least two timed mock exams and a taper$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 12
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Time Management in the Exam$L$, $L$13 minute read$L$, $L$40 questions in 60 minutes leaves roughly 90 seconds each — and some questions eat far more. This lesson gives you a pacing plan so you never run out of time with questions unanswered.$L$, array[$L$Calculate your per-question time budget$L$, $L$Pace yourself with checkpoints during the exam$L$, $L$Handle time-hungry calculation questions without stalling$L$], $L$## The maths of the clock
**40 questions, 60 minutes** = **90 seconds per question** on average (75 minutes, or ~112 seconds each, if English is not your first language). Most K1/K2 recall questions take far less than 90 seconds; that banked time is what you spend on the K3 "apply" questions.

## Pace with checkpoints
Don't watch every question — watch milestones. By the **20-minute mark** you should be around question 13–14; by **40 minutes**, around question 27. If you're behind at a checkpoint, speed up on the easy ones.

## The two-pass strategy
1. **First pass:** answer every question you find easy, flag anything slow or uncertain, and move on. Never let one hard question burn five minutes.
2. **Second pass:** return to flagged questions with your remaining time and a calmer head.

## Answer everything
There is no negative marking. A blank answer scores zero; a guess has a one-in-four chance. In your final minute, make sure no question is left blank.$L$, $L$A candidate hits a decision-table question at question 9 and spends four minutes on it. Instead of finishing it there, they take their best answer, flag it, and move on. By the 40-minute checkpoint they're on question 28 — on pace — with ten minutes spare to revisit the two flagged questions properly.$L$, $L$- Spending five minutes on one hard question and running out of time
- Leaving questions blank when there's no negative marking
- Not knowing whether you're ahead or behind until it's too late$L$, $L$Practise your mocks with a visible timer from day one. Pacing is a skill you build, not something that switches on automatically on exam day.$L$, $L$In your next mock, note your question number at 20 and 40 minutes. Are you ahead of or behind the 13-then-27 checkpoints?$L$, $L$Roughly how many seconds do you have per question, and why is the average misleading for the hardest ones?$L$, $L$With 40 questions in 60 minutes, roughly how long is the average time per question? (Answer: about 90 seconds)$L$, array[$L$I know my per-question time budget$L$, $L$I use checkpoints to stay on pace$L$, $L$I flag-and-move rather than stalling on hard questions$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 12
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$Exam Strategy$L$, $L$14 minute read$L$, $L$Knowing the material is half the battle; extracting marks from tricky questions is the other half. This lesson covers elimination, keyword spotting and the discipline that turns knowledge into a score above 26/40.$L$, array[$L$Eliminate wrong options to improve your odds$L$, $L$Spot the keywords that change what a question is asking$L$, $L$Apply a repeatable per-question process$L$], $L$## Eliminate before you choose
Every question has one correct answer and three distractors. If you can rule out even two options as clearly wrong, a guess jumps from 25% to 50%. Cross out options that are false, out of scope, or contradict the syllabus definition — then choose between what's left.

## Read the whole question
Distractors are written to catch people who read only the first line. Read the full stem and all four options before deciding. The "obviously right" first option is often the trap.

## Keyword spotting
Certain words change everything:
- **NOT / EXCEPT** — you're looking for the odd one out; the three "correct-sounding" options are wrong here.
- **BEST / MOST** — several options may be true; you want the strongest, not merely a true one.
- **ALWAYS / NEVER** — usually a warning sign that an absolute statement is false.

## A per-question process
Read the stem → underline the keyword → read all four options → eliminate the clearly wrong → choose the best of the rest → answer (never leave blank).$L$, $L$"Which of the following is NOT a test design technique?" Three options are real techniques (equivalence partitioning, boundary value analysis, decision tables); the fourth is "regression testing" — a test *type*, not a design technique. Miss the word "NOT" and you'd pick a real technique and score zero. Spot it, and the answer is obvious.$L$, $L$- Missing the word NOT or EXCEPT and answering the opposite question
- Picking the first true-sounding option on a BEST/MOST question
- Choosing an option with ALWAYS or NEVER without questioning the absolute$L$, $L$On every question, underline the keyword before you look at the options. That one habit prevents the most common — and most avoidable — exam mistakes.$L$, $L$Look back at any mock question you got wrong. Was there a keyword (NOT, BEST, MOST) you missed? Note how the keyword changed the answer.$L$, $L$On a "which is BEST" question where two options are both technically true, how do you decide?$L$, $L$When a question contains the word "NOT" (e.g. "which is NOT a test technique"), which option are you looking for? (Answer: the one that is false / does not belong)$L$, array[$L$I eliminate wrong options before choosing$L$, $L$I underline keywords like NOT, BEST and MOST$L$, $L$I read all four options before committing$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 12
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Memory Techniques & Mnemonics$L$, $L$13 minute read$L$, $L$Some CTFL content is pure recall — the seven principles, the seven review types, the fundamental test process. Mnemonics turn hard-to-remember lists into things you can retrieve instantly under pressure.$L$, array[$L$Use mnemonics to memorise CTFL lists$L$, $L$Distinguish what to memorise from what to understand$L$, $L$Build your own memory aids for stubborn topics$L$], $L$## Memorise the lists, understand the rest
K1 "remember" questions test lists and definitions — memorise those. K2 "understand" and K3 "apply" questions test reasoning — you can't mnemonic your way through those, so understand them instead. Know which is which.

## Mnemonics for the classic lists
- **Fundamental test process (the activities):** Planning, Monitoring & control, Analysis, Design, Implementation, Execution, Completion. A first-letter phrase makes the order stick.
- **Seven testing principles:** turn each into a vivid one-word hook — "Absence", "Exhaustive", "Early", "Clustering", "Pesticide", "Context", "Absence-of-errors" — and rehearse the hooks.

## Make them personal and vivid
Memory loves the strange and the personal. A silly image or a phrase built from your own name sticks far better than a dry acronym someone handed you. Build your own — the act of building it *is* the memorising.

## Rehearse under recall
A mnemonic only helps if you can produce it from nothing. Drill it with the book shut, not by re-reading it — same active-recall rule as Lesson 1.$L$, $L$To recall the seven principles in order, a candidate builds the sentence "Testing Elephants Can't Prove Perfect Absence" — Testing shows presence, Exhaustive is impossible, Early testing, Clustering, Pesticide paradox, testing is context-dependent, Absence-of-errors fallacy. Ridiculous, personal, and impossible to forget after two rehearsals.$L$, $L$- Trying to memorise concepts that need understanding (K3 apply questions)
- Using someone else's mnemonic you don't find memorable
- Building a mnemonic but never rehearsing it from a blank page$L$, $L$The best mnemonic is one you invented, because building it forced you to process the material. Don't collect other people's — make your own.$L$, $L$Pick one CTFL list you keep forgetting and invent a mnemonic for it. Say it out loud, then write it from memory an hour later.$L$, $L$Why are mnemonics right for the seven principles but wrong for applying boundary value analysis?$L$, $L$Are mnemonics best suited to K1 "remember" questions or K3 "apply" questions? (Answer: K1 remember questions — lists and definitions)$L$, array[$L$I can use mnemonics for the classic CTFL lists$L$, $L$I know which topics to memorise vs understand$L$, $L$I have built at least one mnemonic of my own$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 12
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 6, $L$Question Analysis$L$, $L$18 minute read$L$, $L$The apply (K3) questions are where exams are won or lost — especially the calculation questions on equivalence partitioning, boundary value analysis and decision tables. This lesson gives you a repeatable method to dissect any exam question and get the calculations right under pressure.$L$, array[$L$Dissect a question stem into what is actually being asked$L$, $L$Work calculation questions (EP, BVA, decision tables) methodically$L$, $L$Avoid the classic traps in apply-level questions$L$], $L$## Read the stem like a spec
An exam question is a tiny specification. Identify: what is given (the inputs, ranges, rules), what is asked (a count? an identification? a best choice?), and the K-level. K3 questions ask you to *do* something — calculate partitions, find boundaries, complete a decision table.

## Calculation questions, step by step
- **Equivalence Partitioning (EP):** split the input range into valid and invalid partitions; one value from each partition is one test. Count the partitions the question defines — no more, no fewer.
- **Boundary Value Analysis (BVA):** for a range like 1–100, test the boundaries and their neighbours (0, 1, 100, 101 in two-value BVA). Know which convention the question uses.
- **Decision tables:** count conditions to get the number of rules (n conditions → 2ⁿ columns), then read the required action for the given combination.

## Show your working mentally
Don't do it all in your head. Jot the range, mark the boundaries, count. A ten-second sketch prevents the off-by-one error that turns a known answer into a wrong one.

## Then apply your strategy
Once you've worked it out, still use Lesson 4's process: check the keyword, eliminate wrong options, pick the best — and never leave it blank.$L$, $L$Question: "A field accepts 18–65. Using two-value boundary value analysis, how many boundary values should be tested?" Sketch the range: boundaries are 18 and 65. Two-value BVA tests each boundary and its outer neighbour: 17, 18, 65, 66 — plus commonly the inner neighbours depending on convention. Read the stem to see which convention it wants, count carefully, and you avoid the classic off-by-one trap.$L$, $L$- Doing calculations entirely in your head and making an off-by-one error
- Confusing equivalence partitioning (one value per partition) with BVA (values at edges)
- Miscounting decision-table rules (forgetting it's 2ⁿ for n conditions)$L$, $L$For any calculation question, spend the first ten seconds writing down the range and marking the boundaries. That tiny sketch is the difference between a known answer and a careless miss.$L$, $L$Take one EP, one BVA and one decision-table question from a mock. For each, write down the given inputs, what's asked, and your working before choosing an option.$L$, $L$For a decision table with three conditions, how many rules (columns) are there, and why?$L$, $L$In a decision table with 3 conditions, how many rules (columns) are there? (Answer: 2³ = 8)$L$, array[$L$I can dissect a stem into given / asked / K-level$L$, $L$I can work EP, BVA and decision-table questions methodically$L$, $L$I sketch my working before choosing an option$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 12
on conflict (module_id, lesson_number) do nothing;

