-- ============================================================
-- API Testing Masterclass — Module 5 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/api-module5.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$Why APIs Need Authentication$L$, $L$12 minute read$L$, $L$Most APIs handle data that shouldn't be public. Before you test any protected endpoint, you need to understand two words people constantly muddle: authentication and authorisation.$L$, array[$L$Distinguish authentication from authorisation$L$, $L$Explain why APIs restrict access$L$, $L$Match 401 and 403 to the right concept$L$], $L$## Two words, two questions
- **Authentication** asks *"who are you?"* — proving identity.
- **Authorisation** asks *"what are you allowed to do?"* — checking permissions.
You authenticate **once**, then every request is authorised against your permissions.

## Why APIs lock the door
An API often exposes personal data, payments and admin actions. Without a check, anyone who knows the URL could read or change other people's records. Authentication puts a lock on the door; authorisation decides which rooms your key opens.

## The two status codes that matter
- `401 Unauthorized` — an **authentication** failure. The API doesn't know who you are (missing or invalid credentials). Confusingly named: 401 really means *unauthenticated*.
- `403 Forbidden` — an **authorisation** failure. The API knows who you are, but you're not allowed to do this.

## Why testers care
These two failures are tested completely differently. Send a request with **no** credentials and you should get `401`. Send it as a **valid but low-privilege** user hitting an admin endpoint and you should get `403`. Confusing them hides real security bugs.$L$, $L$A banking API exposes `GET /accounts/123/balance`. With no token you get `401 Unauthorized` — the API doesn't know you. Log in as a normal customer and call `DELETE /admin/users/9` and you get `403 Forbidden` — it knows exactly who you are, you're just not an admin. Same door, two different locks.$L$, $L$- Using "authentication" and "authorisation" as if they mean the same thing
- Expecting `403` when no credentials were sent (it should be `401`)
- Assuming a hidden or unlinked endpoint is safe because "nobody knows the URL"$L$, $L$Whenever you meet a protected endpoint, write two negative tests before any happy path: one with no credentials (expect `401`) and one as the wrong user (expect `403`). Those two catch the majority of access bugs.$L$, $L$In Postman, send `GET https://reqres.in/api/users/2` with no auth, then think of one endpoint at your workplace that should reject you with a `401`. Note both.$L$, $L$Which question does authorisation answer — "who are you?" or "what can you do?"$L$, $L$A request arrives with no credentials at all. Which status code should the API return? (Answer: 401 Unauthorized — it's an authentication failure)$L$, array[$L$I can define authentication and authorisation in one line each$L$, $L$I can explain why APIs restrict access$L$, $L$I can map 401 and 403 to the correct concept$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$API Keys & Basic Auth$L$, $L$14 minute read$L$, $L$The two simplest ways an API identifies a caller are API keys and Basic auth. Both are easy to use and easy to get wrong — especially the myth that Basic auth "encrypts" anything.$L$, array[$L$Describe how an API key identifies a caller$L$, $L$Explain what Basic auth actually sends$L$, $L$Recognise why base64 is encoding, not encryption$L$], $L$## API keys
An **API key** is a long secret string the caller sends to identify itself, usually in a header like `x-api-key: abc123` or a query parameter. It says *"this is a known caller"* but often carries no user identity and no fine-grained permissions. Keys are simple, which is also their weakness: leak one and anyone can impersonate you.

## Basic auth
**Basic authentication** sends a username and password on every request in a header:
`Authorization: Basic <credentials>`
The credentials are `username:password` **base64-encoded** — for example `am9objpwYXNz`.

## Base64 is NOT encryption
This is the trap. Base64 is **reversible encoding**, not encryption — anyone who sees the header can decode it back to the plain password in one step. Basic auth is only safe over **HTTPS**, which encrypts the whole connection. Over plain HTTP the password travels in effectively clear text.

## Testing angle
Check that keys and Basic credentials are only ever sent over HTTPS, never logged, and never committed to code. A leaked key or a decoded Basic header is a real, common breach.$L$, $L$Encode `jane:pass` as base64 and you get `amFuZTpwYXNz`. Send `Authorization: Basic amFuZTpwYXNz` and the API decodes it straight back to `jane:pass`. Paste that base64 into any online decoder and the password appears instantly — proof it's encoding, not protection. That's why HTTPS is mandatory.$L$, $L$- Believing base64 hides the password — it's trivially reversible
- Sending API keys or Basic credentials over plain HTTP
- Pasting real keys into shared docs, screenshots, or git commits$L$, $L$Treat every API key like a password in plain text. Rotate it if it ever appears in a screenshot, a log, a Slack message, or a committed `.env` file. Testers are often the first to spot a key that's leaked into a response body.$L$, $L$In Postman, add a header `x-api-key: demo-key-123` to any request. Then use the Authorization tab to set Basic auth with username `jane` and password `pass`, send it, and inspect the generated `Authorization` header.$L$, $L$If Basic auth only base64-encodes the password, what single thing makes it safe to use in practice?$L$, $L$Basic auth base64-encodes `username:password`. Is base64 encryption? (Answer: no — it's reversible encoding, so Basic auth is only safe over HTTPS)$L$, array[$L$I can explain what an API key is and its main weakness$L$, $L$I can describe what the Basic auth header contains$L$, $L$I can explain why base64 is not encryption$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Bearer Tokens & JWT$L$, $L$15 minute read$L$, $L$Most modern APIs authenticate with bearer tokens, and the token is very often a JWT. Understanding its three parts and its expiry unlocks a whole category of tests.$L$, array[$L$Explain how a bearer token is sent$L$, $L$Describe the three parts of a JWT$L$, $L$Test token expiry and tampering$L$], $L$## The bearer token
After you log in, the API hands you a **token**. You send it on every subsequent request:
`Authorization: Bearer <token>`
"Bearer" means *whoever holds this token is granted access* — so the token itself is a credential and must be protected like a password.

## What a JWT looks like
A **JWT** (JSON Web Token) is the most common bearer token. It's three base64url parts joined by dots:
`header.payload.signature`
- **Header** — the algorithm, e.g. `HS256`.
- **Payload** — the **claims**: user id, roles, and `exp` (expiry timestamp). Readable by anyone — never put secrets here.
- **Signature** — proves the token wasn't altered. The server checks it and rejects a tampered token.

## Expiry matters
JWTs carry an `exp` claim. After it passes, the token is dead and the API returns `401`. Clients then use a **refresh token** to get a fresh one.

## Testing angle
Decode a JWT at jwt.io to read its claims and expiry. Then test: an **expired** token → `401`; a **tampered** payload (change one character) → `401` because the signature no longer matches; a **missing** token → `401`.$L$, $L$You log in and receive `eyJhbGciOi...`. You paste it into jwt.io and see the payload `{ "sub": "42", "role": "user", "exp": 1720200000 }`. You send `Authorization: Bearer eyJhbGciOi...` and get `200`. Change one character in the middle (payload) section and resend — the signature check fails and you get `401`. That single test proves the API validates the signature.$L$, $L$- Thinking a JWT is encrypted — the payload is only encoded and fully readable
- Putting sensitive data (passwords, card numbers) in the payload
- Never testing an expired token, so silent "tokens never expire" bugs slip through$L$, $L$Always decode the JWT your app receives and read the `exp` and `role` claims. I've caught APIs that issued tokens with no expiry at all, and others that put a user's full email and internal permissions in the payload for anyone to read.$L$, $L$Log in against a practice API (or use a sample token), copy the `access_token`, paste it into jwt.io, and note the algorithm, the claims, and the expiry time. Then send a request with a deliberately altered token and record the status.$L$, $L$Why can anyone read a JWT's payload, yet not forge a valid token?$L$, $L$A JWT has three dot-separated parts. What are they, in order? (Answer: header, payload, signature)$L$, array[$L$I can send a bearer token correctly$L$, $L$I can name and describe the three parts of a JWT$L$, $L$I can test expired and tampered tokens$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$OAuth 2.0 Explained$L$, $L$16 minute read$L$, $L$OAuth 2.0 is the standard behind "Log in with Google" and most large APIs. You don't need to implement it, but as a tester you must understand its flow, its players, and scopes.$L$, array[$L$Name the four players in an OAuth 2.0 flow$L$, $L$Describe how an access token is obtained$L$, $L$Explain what scopes control$L$], $L$## The problem OAuth solves
You want an app to access your data in another service **without handing it your password**. OAuth lets you grant limited access via a token instead.

## The four players
- **Resource owner** — you, the user who owns the data.
- **Client** — the app requesting access.
- **Authorisation server** — issues tokens after you log in and consent.
- **Resource server** — the API holding your data, which accepts the token.

## The flow at a tester's level
1. The client sends you to the **authorisation server** to log in.
2. You consent to the requested **scopes**.
3. The auth server returns an **authorisation code** to the client.
4. The client swaps that code (plus its secret) for an **access token**.
5. The client calls the **resource server** with `Authorization: Bearer <access token>`.

## Scopes
**Scopes** are the specific permissions the token grants, e.g. `read:profile` or `write:orders`. A token should only carry the scopes it needs — this is least privilege in action.

## Testing angle
Confirm a token limited to `read` scope is rejected (`403`) when it attempts a write, and that consent lists only the scopes actually required.$L$, $L$You click "Connect your calendar" in a scheduling app. It redirects you to Google (the authorisation server), where you log in and consent to the scope `calendar.read`. Google returns a code; the app exchanges it for an access token and calls Google's Calendar API (the resource server) with `Authorization: Bearer <token>`. The app reads your calendar but never saw your Google password — and with a read-only scope it cannot delete an event.$L$, $L$- Confusing the authorisation server (issues tokens) with the resource server (holds data)
- Assuming a token can do anything — it's limited by its scopes
- Sharing your actual password instead of granting a scoped token$L$, $L$The single most valuable OAuth test is the scope test: take a read-only token and try to write. If the API lets it through, the whole point of scopes has failed — and that's a report-worthy authorisation bug.$L$, $L$Pick a service you've used "Log in with Google/GitHub" on. Write out the four OAuth players for that case, then list the scopes it asked you to consent to (check your account's connected-apps page).$L$, $L$Why is OAuth safer than giving the third-party app your actual password?$L$, $L$In OAuth 2.0, which player issues the access token — the authorisation server or the resource server? (Answer: the authorisation server; the resource server accepts it)$L$, array[$L$I can name the four OAuth 2.0 players$L$, $L$I can describe how a client obtains an access token$L$, $L$I can explain what scopes limit$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Testing Authorisation & Access Control$L$, $L$18 minutes$L$, $L$This is where authentication knowledge becomes hands-on security testing. You'll test that the right users can do the right things — and, crucially, that the wrong users cannot.$L$, array[$L$Design negative tests for 401 and 403$L$, $L$Test broken object-level authorisation (BOLA)$L$, $L$Verify that roles are enforced server-side$L$], $L$## The three questions to test
1. **No credentials** → does it return `401`?
2. **Valid but wrong role** → does it return `403`?
3. **Valid user, someone else's data** → does it return `403` or `404`, never `200`?

## Broken object-level authorisation (BOLA)
The most common API vulnerability. The API authenticates you but forgets to check that the **resource belongs to you**. If you're user 42 and `GET /users/42/orders` works, try `GET /users/43/orders`. If you can read user 43's orders, that's **BOLA** — a critical bug. Always test by swapping the id to a resource you don't own.

## Enforce it server-side
UIs often just hide the admin button — that is not security. The check must happen on the **server**. Prove it by calling the protected endpoint **directly**, with a low-privilege token, bypassing the UI entirely.

## Building the tests
For each protected endpoint, keep two saved requests: one as a legitimate owner (expect success) and one as an attacker — wrong user or wrong role (expect `401`/`403`). This pair is your access-control regression suite.$L$, $L$You're logged in as customer 42. `GET /users/42/profile` returns `200` — correct. You change the id: `GET /users/43/profile`. If it returns `200` with user 43's details, you've found a BOLA vulnerability — the API checked *who you are* but not *whose data this is*. A correct API returns `403` (or `404` to avoid confirming the record exists).$L$, $L$- Only testing the happy path as the correct, privileged user
- Trusting a hidden UI button as if it were an access control
- Never swapping the resource id to test for broken object-level authorisation$L$, $L$The fastest way to find real security bugs as a tester: log in as a low-privilege user and call the endpoints you "shouldn't" be able to reach — directly, in Postman. BOLA and missing role checks fall out almost immediately, and they're exactly what attackers try first.$L$, $L$In Postman, create two saved requests to a protected endpoint: one with a valid token for the owning user (expect `200`), one with the id changed to a resource you don't own (expect `403`/`404`). Add a test script asserting the negative case is not `200`.$L$, $L$If `GET /users/43/orders` returns `200` while you're logged in as user 42, what have you found and why is it serious?$L$, $L$A logged-in user changes an id in the URL to access another user's record and succeeds. What vulnerability is this? (Answer: Broken Object-Level Authorisation — BOLA)$L$, array[$L$I can write negative tests for 401 and 403$L$, $L$I can test for broken object-level authorisation$L$, $L$I can prove a role check is enforced on the server, not just the UI$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 6, $L$Common API Security Risks$L$, $L$16 minute read$L$, $L$You'll pull everything together with the industry's shared checklist — the OWASP API Security Top 10 — and turn it into practical tests you can run in Postman today.$L$, array[$L$Describe what the OWASP API Security Top 10 is$L$, $L$Identify the most common API risks a tester can check$L$, $L$Turn a risk into a concrete test$L$], $L$## What OWASP gives you
The **OWASP API Security Top 10** is a free, industry-agreed list of the most common and dangerous API weaknesses. It's your ready-made checklist — you don't have to invent risks, you can test against a shared standard.

## Risks a tester can check directly
- **Broken object-level authorisation (BOLA)** — swap the id, can you read others' data? (Module 5, Lesson 5.)
- **Broken authentication** — do expired, tampered or missing tokens still work?
- **Excessive data exposure** — does the response return more fields than the UI needs (passwords, internal ids, PII)?
- **Lack of rate limiting** — can you hammer `POST /login` endlessly with no lockout?
- **Security misconfiguration** — verbose stack traces, secrets in responses, missing HTTPS.

## From risk to test
Each risk becomes a request. "Excessive data exposure" → send a normal `GET` and read *every* field in the body, asking "should the client see this?" A user object returning a `passwordHash` is a finding.

## Your role
You aren't a penetration tester, but a tester who runs this checklist catches the majority of everyday API security bugs long before they reach production.$L$, $L$Testing "excessive data exposure": you call `GET /users/42` and the body includes `"passwordHash"`, `"internalNotes"` and `"ssn"` — none of which the UI shows. The frontend simply ignores those fields, so it looked fine, but the data crossed the wire to the browser where anyone with dev tools can read it. You raise it against OWASP "Excessive Data Exposure" with the exact response body as evidence.$L$, $L$- Treating security as "someone else's job" and never running the checklist
- Only reading the fields the UI uses and ignoring the rest of the response body
- Assuming no rate limiting is fine because "who would try thousands of logins?"$L$, $L$Keep the OWASP API Security Top 10 pinned next to your test cases. Turning each item into one saved Postman request gives you a reusable security regression suite — the single highest-leverage thing a functional tester can add to their skill set this year.$L$, $L$In Postman, send a `GET` to a user or profile endpoint and list every field in the response body. Mark any field the UI doesn't display and ask whether the client should receive it. Save the request in an "OWASP checks" folder.$L$, $L$Why is a response returning extra hidden fields a security risk even if the UI never shows them?$L$, $L$What is the name of the free industry checklist of the most common API security risks? (Answer: the OWASP API Security Top 10)$L$, array[$L$I can explain what the OWASP API Security Top 10 is$L$, $L$I can name several API risks a tester can check$L$, $L$I can turn a listed risk into a concrete Postman test$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 5
on conflict (module_id, lesson_number) do nothing;

