-- ============================================================
-- API Testing Masterclass — Module 4 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/api-module4.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$Collections & Organising Requests$L$, $L$14 minute read$L$, $L$A collection is how you turn a pile of one-off requests into a reusable, shareable test asset. Getting the structure right early pays off for the rest of the course.$L$, array[$L$Create a collection and add requests to it$L$, $L$Organise requests into folders that mirror the API$L$, $L$Explain why saved collections beat one-off requests$L$], $L$## What a collection is
A **collection** is a saved, ordered group of requests. It lives in the sidebar, can be exported as JSON, shared with your team, run end to end, and put into CI. It is the unit of work in Postman — everything else hangs off it.

## Folders give structure
Inside a collection you create **folders** to group related requests. Mirror the API: a folder per resource (`Users`, `Orders`, `Auth`). A newcomer should read the sidebar and understand the API without asking.

## Collection-level settings
A collection carries shared **auth**, **variables**, and **pre-request/test scripts** that every request inherits. Set auth once at the collection level rather than pasting a token into twenty requests.

## Why it matters
- Requests you can find are requests you'll re-run.
- A tidy collection becomes documentation, a regression suite, and your Module 10 portfolio piece.
- Naming matters: `Create user — happy path` beats `New Request (3)`.$L$, $L$Create a collection `Reqres API`. Add folders `Users` and `Auth`. In `Users`, save three requests: `GET List users` (`GET https://reqres.in/api/users`), `GET Single user` (`GET https://reqres.in/api/users/2`), and `POST Create user`. In `Auth`, save `POST Login`. The sidebar now reads like a map of the API, and you can run the whole collection with one click.$L$, $L$- Leaving requests unsaved so they vanish when the tab closes
- Naming everything `New Request` instead of describing the intent
- One flat list of 40 requests with no folders to navigate$L$, $L$Treat your collection like source code: name things clearly, group logically, and export the JSON into version control so the team shares one source of truth.$L$, $L$In Postman, create a collection called `API Masterclass — <your name>`, add a `Users` folder, and save two GET requests into it with descriptive names.$L$, $L$Why is a saved, well-named collection worth more than a scratch request you send once?$L$, $L$What is the top-level container that groups related Postman requests? (Answer: a collection)$L$, array[$L$I can create a collection and add requests$L$, $L$I can organise requests into meaningful folders$L$, $L$I save and name requests clearly$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 4
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$Environments & Variables$L$, $L$16 minute read$L$, $L$Variables let one collection run against dev, staging and production without editing a single request. This is the difference between a demo and a real, reusable test suite.$L$, array[$L$Create environments and switch between them$L$, $L$Use variables to remove hardcoded values$L$, $L$Explain variable scopes and their precedence$L$], $L$## Why variables
Hardcoding `https://staging.api.com` into 30 requests means 30 edits when the URL changes. Instead, define `{{baseUrl}}` once and reuse it. Reference any variable in a URL, header or body with double curly braces: `{{baseUrl}}/users/{{userId}}`.

## Environments
An **environment** is a named set of variables — `Dev`, `Staging`, `Prod`. Each defines its own `baseUrl`, `apiKey`, and so on. Switch the environment dropdown and the same collection now hits a different server. No request edits.

## Scopes and precedence
Postman resolves a variable from the narrowest scope outwards:
- **Local** (data/temporary) → **Environment** → **Collection** → **Global**

Set shared defaults at the **collection** scope; put per-environment values (URLs, keys) in the **environment**.

## Reading and writing in scripts
In scripts you read with `pm.environment.get('baseUrl')` and write with `pm.environment.set('token', value)`. Use `pm.collectionVariables` for collection scope. **Secrets** should be set as *secret* variable types so they aren't stored in plain text.$L$, $L$Create a `Dev` environment with `baseUrl = https://reqres.in/api`. Change a request URL from `https://reqres.in/api/users/2` to `{{baseUrl}}/users/{{userId}}`, and set `userId = 2` in the environment. Now duplicate the environment as `Staging` with a different `baseUrl`. Switching the dropdown re-points every request instantly — you edited nothing in the request itself.$L$, $L$- Hardcoding URLs and tokens directly into requests
- Forgetting to select an environment, so `{{baseUrl}}` resolves to nothing
- Confusing scopes — setting a value at collection scope but expecting it per environment$L$, $L$Never paste a real API key or token as a plain variable you might export. Use Postman's *secret* variable type, and keep production credentials out of shared collections entirely.$L$, $L$Create a `Dev` environment with a `baseUrl` variable, then rewrite one of your saved requests to use `{{baseUrl}}` instead of the full URL. Confirm it still returns 200.$L$, $L$If a variable exists at both environment and collection scope, which value wins, and why is that useful?$L$, $L$What syntax references a variable inside a request URL or body? (Answer: double curly braces, e.g. {{baseUrl}})$L$, array[$L$I can create and switch environments$L$, $L$I can replace hardcoded values with variables$L$, $L$I understand variable scope and precedence$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 4
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Writing Tests with pm.test$L$, $L$18 minute read$L$, $L$A request that isn't asserted is just a click. This lesson turns your requests into automated checks using Postman's built-in test API.$L$, array[$L$Write assertions with pm.test and pm.expect$L$, $L$Assert status codes, response bodies and headers$L$, $L$Read the Test Results tab to interpret pass/fail$L$], $L$## Where tests live
Every request has a **Scripts → Post-response** (formerly "Tests") tab. Code there runs in JavaScript *after* the response arrives. Results show in the **Test Results** tab.

## The core pattern
Wrap each assertion in `pm.test('name', () => { ... })`. The name is what shows in results, so make it descriptive:

- `pm.test('status is 200', () => { pm.response.to.have.status(200); });`
- Parse the body once: `const body = pm.response.json();`
- Assert with `pm.expect(body.id).to.eql(2);`

## Common assertions
- Status: `pm.response.to.have.status(201)`
- Body value: `pm.expect(body.email).to.eql('eve@reqres.in')`
- Existence: `pm.expect(body).to.have.property('token')`
- Type: `pm.expect(body.data).to.be.an('array')`
- Header: `pm.expect(pm.response.headers.get('Content-Type')).to.include('json')`
- Response time: `pm.expect(pm.response.responseTime).to.be.below(800)`

## Why it matters
Assertions are what make the Collection Runner and Newman (Module 8) meaningful — green means the contract held, red means a real problem.$L$, $L$On `GET {{baseUrl}}/users/2`, add to the Post-response script:
```
const body = pm.response.json();
pm.test('status is 200', () => {
  pm.response.to.have.status(200);
});
pm.test('returns the requested user', () => {
  pm.expect(body.data.id).to.eql(2);
  pm.expect(body.data).to.have.property('email');
});
```
Send it and open Test Results: two green ticks. Break the expected id to `99` and watch one turn red — that's the safety net working.$L$, $L$- Only asserting the status code and never the body contents
- Calling `pm.response.json()` on a non-JSON response, which throws
- Writing one giant test instead of small, individually named checks$L$, $L$Give each `pm.test` a name that reads like a sentence about the requirement. When a run goes red in CI, the test name alone should tell you what broke without opening the request.$L$, $L$Add three tests to one request: status is 200, the body has a specific property, and the response time is below 1000ms. Confirm all three pass.$L$, $L$Why is asserting only the status code rarely enough to trust an API response?$L$, $L$Which Postman function wraps a single named assertion? (Answer: pm.test)$L$, array[$L$I can write assertions with pm.test and pm.expect$L$, $L$I can assert status, body and headers$L$, $L$I can read the Test Results tab$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 4
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$Pre-request Scripts & Chaining Requests$L$, $L$18 minute read$L$, $L$Real workflows need one request to feed the next — log in, capture the token, then use it. Pre-request scripts and variable-passing make Postman behave like a real client.$L$, array[$L$Use a pre-request script to prepare data before sending$L$, $L$Capture a value from one response and reuse it in the next$L$, $L$Explain the request execution order in Postman$L$], $L$## Two script slots
Each request has a **Pre-request** script (runs *before* the request) and a **Post-response** script (runs *after*). Pre-request is for setup — building a timestamp, generating a random email, computing a signature. Post-response is for assertions and for capturing values.

## Chaining: the login → use-token pattern
1. `POST /login` returns a token.
2. In its **Post-response** script, save it:
   ```
   const body = pm.response.json();
   pm.environment.set('token', body.token);
   ```
3. The next request sends header `Authorization: Bearer {{token}}`.

Postman substitutes `{{token}}` at send time, so the second request uses the freshly captured value.

## Generating data in pre-request
```
pm.environment.set('email', `user_${Date.now()}@test.com`);
```
Now the request body can use `{{email}}` for a guaranteed-unique value.

## Execution order
Pre-request script → request sent → response received → Post-response script. Inside the Collection Runner this repeats per request, top to bottom.$L$, $L$Chain a login into a protected call. On `POST {{baseUrl}}/login` (body `{"email":"eve.holt@reqres.in","password":"pistol"}`), add a Post-response script:
```
const body = pm.response.json();
pm.test('token returned', () => pm.expect(body).to.have.property('token'));
pm.environment.set('token', body.token);
```
Then create `GET {{baseUrl}}/users/2` with header `Authorization: Bearer {{token}}`. Run them in order — the second request automatically uses the captured token.$L$, $L$- Capturing a value but referencing the wrong variable name later
- Putting capture logic in the pre-request script instead of post-response
- Running the second request alone and wondering why `{{token}}` is empty$L$, $L$Generate unique data in a pre-request script (e.g. a timestamped email) so re-running a "create" request never fails on a duplicate. Repeatable tests are reliable tests.$L$, $L$Set up a two-request chain: a login that captures a token into an environment variable, and a follow-up request that sends that token in an Authorization header. Run them in order and confirm the second gets 200.$L$, $L$Why must the value be captured in the post-response script rather than the pre-request script?$L$, $L$In which script slot do you capture a value from the response for the next request? (Answer: the post-response script)$L$, array[$L$I can write a pre-request script to prepare data$L$, $L$I can capture a response value and reuse it$L$, $L$I understand the Postman request execution order$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 4
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Data-Driven Testing with the Collection Runner$L$, $L$17 minute read$L$, $L$Run one request against many rows of data — dozens of inputs, one click. The Collection Runner plus a data file is how you test breadth without writing dozens of requests.$L$, array[$L$Run a collection or folder with the Collection Runner$L$, $L$Drive a request with a CSV or JSON data file$L$, $L$Read iteration results and spot failing rows$L$], $L$## The Collection Runner
Open a collection and click **Run**. The Runner executes every request top to bottom, running each request's tests and showing a pass/fail summary. You choose the environment, iteration count, and delay.

## Data-driven testing
Attach a **data file** (CSV or JSON) and the Runner iterates once per row. Each row's columns become variables you reference with `{{columnName}}`. Access the same value in scripts with `pm.iterationData.get('email')`.

A CSV like:
```
email,password,expectedStatus
eve.holt@reqres.in,pistol,200
missing@reqres.in,,400
```
runs the login twice — once expecting 200, once expecting 400.

## Dynamic assertions per row
Read the expected value from the data and assert against it:
```
pm.test('status matches data', () => {
  pm.response.to.have.status(Number(pm.iterationData.get('expectedStatus')));
});
```

## Why it matters
This is boundary and equivalence-class testing at speed: valid, invalid, empty and edge inputs in one run, with a clear per-iteration report.$L$, $L$Create `data.csv`:
```
email,password,expectedStatus
eve.holt@reqres.in,pistol,200
peter@klaven,,400
```
Point `POST {{baseUrl}}/login` body at `{"email":"{{email}}","password":"{{password}}"}` and add:
```
pm.test('status matches expected', () => {
  pm.response.to.have.status(Number(pm.iterationData.get('expectedStatus')));
});
```
Run the collection with the CSV attached. The Runner shows 2 iterations; each row's expected status is asserted independently.$L$, $L$- CSV column names not matching the `{{variable}}` names in the request
- Forgetting that data-file values arrive as strings (cast with `Number()`)
- Selecting the wrong environment so `{{baseUrl}}` is empty during the run$L$, $L$Keep your data file in the repo next to the collection. When a row fails, the Runner tells you exactly which iteration — so your test data doubles as living documentation of the cases you cover.$L$, $L$Build a small CSV of three login rows (valid, wrong password, missing password) with an `expectedStatus` column, then run the collection with the Runner and confirm each row asserts its own expected status.$L$, $L$How does a data file let you test many input cases without duplicating the request?$L$, $L$What Postman feature runs a request once per row of a data file? (Answer: the Collection Runner)$L$, array[$L$I can run a collection with the Collection Runner$L$, $L$I can drive a request from a CSV or JSON data file$L$, $L$I can read iteration results and find failing rows$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 4
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 6, $L$Mock Servers & Documentation$L$, $L$20 minutes$L$, $L$Postman can fake an API before it exists and generate live docs from your collection. Both let testers add value early and keep the whole team in sync.$L$, array[$L$Create a mock server that returns example responses$L$, $L$Test against a mock before the real API is built$L$, $L$Generate and publish documentation from a collection$L$], $L$## Mock servers
A **mock server** is a Postman-hosted endpoint that returns **saved example responses** instead of calling a real backend. You attach examples to a request (status, headers, body), create a mock from the collection, and Postman gives you a mock URL. Point `{{baseUrl}}` at that URL and your requests get realistic responses — before any backend exists.

## Why testers love mocks
- **Shift left**: write and validate tests against the agreed contract while devs are still building.
- **Stability**: mocks return the same response every time — perfect for developing assertions.
- **Isolation**: test your client logic without a flaky or rate-limited real service.

Postman can match examples by request path, method and query params, so one mock can serve several scenarios.

## Documentation
Every collection can auto-generate **documentation** from its requests, descriptions and saved examples. Add a description to each request and folder, then **Publish** the docs to get a shareable web page that stays in step with the collection.

## Why it matters
Mocks let you test early; auto-docs mean your collection is the single source of truth — the tests, the contract and the reference are one artefact.$L$, $L$Take `GET {{baseUrl}}/users/2`. Send it once, then **Save Response → Save as example** so you have a `200` example with a JSON user body. Right-click the collection → **Mock collection**; Postman returns a mock URL like `https://<id>.mock.pstmn.io`. Set your `Dev` environment's `baseUrl` to that URL and re-send — you get the example back with no real backend involved. Then click **View documentation** to see the auto-generated page, add a request description, and **Publish**.$L$, $L$- Creating a mock but saving no examples, so it returns 404 or empty
- Expecting a mock to contain real logic — it only replays saved examples
- Publishing docs once and letting them drift because requests lack descriptions$L$, $L$When a backend team is a sprint behind, agree the contract, build a mock from example responses, and write your tests against it. When the real API lands, just repoint `{{baseUrl}}` — your test suite is already done.$L$, $L$Save an example response on one of your requests, create a mock server from the collection, repoint `{{baseUrl}}` at the mock URL, and confirm the request returns your example. Then add a description to the request and open the auto-generated documentation.$L$, $L$How does a mock server let you write and validate tests before the real API exists?$L$, $L$What does a Postman mock server return instead of calling a real backend? (Answer: saved example responses)$L$, array[$L$I can create a mock server from saved examples$L$, $L$I can point my collection at a mock and test against it$L$, $L$I can generate and publish documentation from a collection$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 4
on conflict (module_id, lesson_number) do nothing;

