-- ============================================================
-- API Testing Masterclass — Module 8 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/api-module8.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$Introducing Newman$L$, $L$13 minute read$L$, $L$Everything you've built in Postman can run without Postman. Newman is Postman's command-line runner — the bridge between clicking "Run" and full automation.$L$, array[$L$Explain what Newman is and why it exists$L$, $L$Describe how Newman relates to your Postman collections$L$, $L$Install Newman and confirm it works$L$], $L$## What Newman is
**Newman** is Postman's official **command-line collection runner**. It takes the exact same collection you built and tested in the Postman app and runs it in a terminal — no GUI, no clicking. The requests, tests, scripts and assertions all behave identically.

## Why testers need it
The Postman app is brilliant for building and exploring. But automation lives on the command line: CI servers, scheduled jobs and monitoring tools can't click buttons. Newman lets the *same* collection run anywhere a terminal exists.

## How it fits
- You **build and debug** in the Postman app.
- You **export** the collection (and environment) to JSON.
- Newman **runs** that JSON from the command line — locally, in CI, or on a schedule.

## Installing it
Newman runs on Node.js, so install Node first, then:
```
npm i -g newman
```
Confirm it worked with `newman --version`. That's it — you now have Postman's engine on the command line.$L$, $L$After installing Node, run `npm i -g newman` in a terminal. Then `newman --version` prints something like `6.2.1`. You haven't run a collection yet, but the tool that will drive all your automation is now installed and ready.$L$, $L$- Trying to install Newman without Node.js — it depends on npm
- Forgetting the `-g` flag, so `newman` isn't on your PATH
- Assuming Newman is a different tool — it runs your *existing* Postman collections unchanged$L$, $L$Newman is not "Postman lite". It's the same test engine with no UI — which is exactly why it belongs in every pipeline. If a collection passes in the app, it passes in Newman.$L$, $L$Install Node.js if you don't have it, then run `npm i -g newman` and `newman --version`. Note the version number you see.$L$, $L$Why can't the Postman desktop app run inside a CI pipeline, but Newman can?$L$, $L$What is Newman? (Answer: Postman's command-line collection runner)$L$, array[$L$I can explain what Newman is$L$, $L$I have Newman installed$L$, $L$I can run `newman --version`$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$Running Collections from the Command Line$L$, $L$16 minute read$L$, $L$Time to actually run something. You'll export a collection and its environment, then drive them through Newman — including feeding in data files for data-driven runs.$L$, array[$L$Run a collection with Newman$L$, $L$Pass an environment and variables on the command line$L$, $L$Feed a data file for data-driven runs$L$], $L$## The core command
Export your collection to JSON from the Postman app (Collection → ⋯ → **Export**). Then:
```
newman run collection.json
```
Newman executes every request and every test, printing a pass/fail summary.

## Adding an environment
Environments (base URLs, tokens) export the same way. Attach one with `-e`:
```
newman run collection.json -e env.json
```
Now `{{baseUrl}}` and `{{token}}` resolve exactly as they did in the app.

## Data-driven runs
Point Newman at a CSV or JSON data file with `-d`. It runs the collection **once per row**, substituting the columns as variables:
```
newman run collection.json -e env.json -d users.csv
```
A three-row CSV means three iterations — perfect for testing the same endpoint across many inputs.

## Reading the output
The CLI summary shows iterations, requests, assertions, and how many failed. Zero failures is a green run.$L$, $L$You export "User API" to `collection.json` and your staging environment to `env.json`. A `users.csv` has columns `name,job` with three rows. Running `newman run collection.json -e env.json -d users.csv` runs the whole collection three times — once per row — so a single command tests three users end to end.$L$, $L$- Running the collection but forgetting `-e`, so `{{baseUrl}}` is empty and every request 404s
- A CSV whose header names don't match the `{{variables}}` used in requests
- Exporting the collection but editing it further in the app and forgetting to re-export$L$, $L$Keep your exported `collection.json` and `env.json` in the repo next to your code. That way the tests version alongside the app, and anyone can run `newman run` to reproduce a result.$L$, $L$Export one of your Postman collections and its environment, then run `newman run collection.json -e env.json`. Confirm the requests run and note the pass/fail summary.$L$, $L$What does the `-d` flag change about how a collection runs, and when is that useful?$L$, $L$Which Newman flag attaches an environment file to a run? (Answer: -e, e.g. `newman run collection.json -e env.json`)$L$, array[$L$I exported a collection and environment$L$, $L$I ran a collection with `newman run`$L$, $L$I understand how `-d` drives iterations$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Newman Reporters & HTML Reports$L$, $L$15 minute read$L$, $L$A wall of terminal text is fine for you, but not for your team. Reporters turn a Newman run into readable output — from JSON for machines to polished HTML for humans.$L$, array[$L$List Newman's built-in reporters$L$, $L$Generate a machine-readable JSON report$L$, $L$Produce a shareable HTML report with htmlextra$L$], $L$## What a reporter is
A **reporter** decides how Newman presents results. You choose reporters with `-r`. The default is `cli` — the summary printed to the terminal.

## Built-in reporters
- `cli` — human-readable terminal output (the default)
- `json` — a machine-readable file, great for feeding other tools
- `junit` — XML that CI systems understand for test dashboards

Combine them: `newman run collection.json -r cli,json`.

## The star: htmlextra
`htmlextra` produces a rich, shareable HTML report with pass/fail breakdowns, request/response detail and timings. It's a separate package:
```
npm i -g newman-reporter-htmlextra
newman run collection.json -e env.json -r htmlextra
```
By default it writes to `newman/`. This is the report you send to a manager who wasn't watching the run.

## Choosing reporters
- **You, live** → `cli`
- **Another tool / CI dashboard** → `json` or `junit`
- **A human who needs a nice summary** → `htmlextra`$L$, $L$You install htmlextra with `npm i -g newman-reporter-htmlextra`, then run `newman run collection.json -e env.json -r cli,htmlextra`. The terminal shows a live summary (cli) and Newman writes an HTML file under `newman/` that you open in a browser — colour-coded passes and failures your lead can read at a glance.$L$, $L$- Trying `-r htmlextra` without installing `newman-reporter-htmlextra` first
- Overwriting the same HTML file every run, so you lose the history
- Emailing raw terminal logs when a clean HTML report would land far better$L$, $L$The `htmlextra` report is your reputation on a page. When a stakeholder asks "did the API tests pass?", a tidy HTML report answers instantly — and quietly shows how thorough you are.$L$, $L$Install `newman-reporter-htmlextra`, run your collection with `newman run collection.json -e env.json -r htmlextra`, and open the generated HTML report in a browser.$L$, $L$Which reporter would you pick to feed results into a CI dashboard, and which to email a non-technical manager?$L$, $L$Which reporter produces a rich, shareable HTML report? (Answer: htmlextra, via `-r htmlextra`)$L$, array[$L$I can name the built-in reporters$L$, $L$I generated a JSON report$L$, $L$I produced an htmlextra HTML report and opened it$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$Integrating API Tests into CI/CD$L$, $L$17 minute read$L$, $L$This is where automation earns its keep. You'll wire your Newman run into a CI/CD pipeline so the API tests run automatically on every commit — and fail the build when they should.$L$, array[$L$Explain why Newman fits naturally into CI/CD$L$, $L$Describe how exit codes make a build pass or fail$L$, $L$Add a Newman step to a pipeline (e.g. GitHub Actions)$L$], $L$## Why CI/CD loves Newman
CI systems run commands and check whether they succeeded. Newman is just a command, so it drops straight in. Commit code → pipeline installs Newman → runs the collection → reports pass or fail. No human required.

## Exit codes are the magic
When a run passes, Newman exits with code **0**. If **any** assertion fails, it exits with a **non-zero** code. CI treats non-zero as failure — so a failing API test automatically **fails the build**. That's the whole contract:
- `0` → tests passed → pipeline continues
- non-zero → tests failed → pipeline stops (or is marked red)

## A minimal GitHub Actions example
```yaml
name: API Tests
on: [push]
jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm i -g newman newman-reporter-htmlextra
      - run: newman run collection.json -e env.json -r cli,htmlextra
```
On every push, the pipeline installs Newman and runs your collection. If a test fails, the non-zero exit code turns the whole run red.$L$, $L$You commit `collection.json` and `env.json` to the repo, add the workflow above, and push. GitHub Actions checks out the code, installs Newman, and runs `newman run collection.json -e env.json -r cli,htmlextra`. A broken endpoint makes an assertion fail, Newman exits non-zero, and the commit gets a red ✗ — the team knows *before* it ships.$L$, $L$- Assuming CI knows a test failed — it only knows the exit code, so your Postman *tests* must actually assert
- Hard-coding secrets in `env.json` and committing them, instead of using CI secret variables
- Forgetting to install Newman as a pipeline step, so `newman run` isn't found$L$, $L$The value of CI isn't the fancy report — it's that a failing API test *stops the line*. If your collection has no real assertions, Newman exits 0 and the pipeline goes green on broken code. Assertions are what make automation meaningful.$L$, $L$Take the collection you exported earlier and write the CI step that would run it: a single `newman run collection.json -e env.json` line inside a pipeline job. Note where the exit code decides pass/fail.$L$, $L$If a collection has no assertions, what exit code will Newman return even when the API is broken — and why is that dangerous?$L$, $L$What exit code does Newman return when a run passes, and what does CI do with a non-zero code? (Answer: 0 on pass; a non-zero code fails the build)$L$, array[$L$I can explain why Newman suits CI/CD$L$, $L$I understand how exit codes pass/fail a build$L$, $L$I can add a Newman step to a pipeline$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Scheduling & Monitoring$L$, $L$16 minute read$L$, $L$CI catches problems when code changes — but APIs can break when nothing changed at all. This final lesson covers running your tests on a schedule and using them as lightweight monitoring.$L$, array[$L$Explain the difference between CI runs and scheduled runs$L$, $L$Schedule a Newman run with cron or a CI scheduler$L$, $L$Use scheduled runs as lightweight API monitoring$L$], $L$## CI vs scheduled runs
CI runs on **change** — a commit or a pull request. But a third-party dependency can go down, a certificate can expire, or data can drift **without anyone touching the code**. **Scheduled runs** trigger on **time** instead, so you catch these silent failures.

## Scheduling options
- **cron** on a server: `0 * * * * newman run collection.json -e env.json` runs hourly.
- **CI scheduler**: GitHub Actions supports `on: schedule` with a cron expression — no server needed.
- **Postman Monitors**: Postman's own cloud scheduler runs the same collection on an interval.

A GitHub Actions schedule looks like:
```yaml
on:
  schedule:
    - cron: '0 * * * *'   # every hour
```

## Lightweight monitoring
Point a scheduled Newman run at your **production or staging** environment and it becomes a health check: is the API up, fast enough, and returning the right shape? Add htmlextra plus a notification (email/Slack) on failure and you have monitoring for the cost of a cron line.

## Keep it sensible
- Run a small, fast **smoke** collection frequently; the full suite less often.
- Alert only on failure — nobody reads "all green" emails.
- Watch response times, not just status codes.$L$, $L$You add `on: schedule: - cron: '0 * * * *'` to your workflow and point it at staging with `newman run smoke.json -e staging.json -r cli,htmlextra`. Every hour it checks the core endpoints. At 3am a dependency's certificate expires; the next run fails, exits non-zero, and you get an alert — hours before any user notices.$L$, $L$- Scheduling the entire regression suite every 5 minutes — expensive and noisy
- Alerting on success too, so real failures drown in "all good" emails
- Only checking status codes and missing slow-but-200 responses$L$, $L$A scheduled smoke test against production is the cheapest early-warning system you'll ever build. It won't replace a proper monitoring platform, but it often catches outages before the dashboards do.$L$, $L$Export a small "smoke" collection (2–3 critical requests), then write the cron expression and Newman command you'd use to run it hourly against staging.$L$, $L$Why might a scheduled run catch a failure that a commit-triggered CI run never would?$L$, $L$What triggers a scheduled run rather than a CI run? (Answer: time — e.g. a cron schedule — not a code change)$L$, array[$L$I can explain CI runs vs scheduled runs$L$, $L$I can schedule a Newman run with cron or a CI scheduler$L$, $L$I can use a scheduled run as lightweight monitoring$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 8
on conflict (module_id, lesson_number) do nothing;

