-- ============================================================
-- API Testing Masterclass — Module 6 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/modern-automation-module6.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$How Auto-Waiting Actually Works$L$, $L$16 minute read$L$, $L$Most flakiness in older tools came from guessing when the page was ready. Playwright removes that guesswork with actionability checks and a built-in retry loop, so you rarely wait manually. This lesson shows you exactly what happens before every action and assertion.$L$, array[$L$Describe the actionability checks Playwright runs before an action$L$, $L$Explain the built-in retry loop behind actions and web-first assertions$L$, $L$Recognise when you genuinely need an explicit wait and when you do not$L$], $L$## The problem auto-waiting solves
In older tools a test would find an element, then act on it, and the two steps were separate. If the element was not ready yet — still animating, still disabled, still behind a spinner — the action failed. Teams patched this with sleeps, and sleeps are the root of most flakiness. Playwright's answer is to make waiting part of every action rather than something you bolt on.

## Actionability checks
Before Playwright clicks, fills or checks anything, it waits for the target element to satisfy a set of **actionability checks**. Depending on the action these include:

- **Attached** — the element is present in the DOM.
- **Visible** — it has a non-empty bounding box and is not `visibility: hidden`.
- **Stable** — it has stopped moving; the same bounding box across two animation frames.
- **Enabled** — it is not disabled.
- **Receives events** — it is the actual hit target at its centre point, not covered by an overlay.
- **Editable** — for `fill`, the field is not read-only.

If any required check is not yet met, Playwright does not fail. It waits and re-checks, up to the action's timeout.

## The retry loop
The same idea powers web-first assertions. `await expect(locator).toBeVisible()` does not sample the page once — it re-queries the locator and re-evaluates the condition on a loop until it passes or the timeout expires. Actions and assertions share this "poll until ready" model, which is why a well-written Playwright test almost never contains an explicit wait.

## When you genuinely need to wait
Auto-waiting covers the element you are acting on. It cannot know about conditions it has no locator for — a background job finishing, a specific network response you care about, an animation with no DOM signal. For those, you use targeted waits (`waitForResponse`, `expect(...).toPass()`), covered later in this module — never a blind sleep.

## Key takeaway
Every Playwright action and web-first assertion runs a retry loop that waits for the element to be genuinely usable first; understanding those actionability checks is what lets you delete manual waits with confidence instead of superstition.$L$, $L$A test with no explicit waits, where auto-waiting quietly does the work:

~~~ts
import { test, expect } from '@playwright/test';

test('a disabled button becomes clickable after valid input', async ({ page }) => {
  await page.goto('/transfer');

  // The "Send" button starts disabled until the form validates.
  const send = page.getByRole('button', { name: 'Send' });

  await page.getByLabel('Amount').fill('50');
  await page.getByLabel('Recipient').fill('alex@example.com');

  // No sleep needed: click waits for the button to pass the "enabled" check.
  await send.click();

  // The assertion retries until the confirmation appears.
  await expect(page.getByRole('alert')).toHaveText('Transfer sent');
});
~~~

The button is disabled when the page loads and only enables once both fields are valid. There is no `waitForTimeout` guessing how long validation takes — `click()` keeps re-checking the actionability of `send` until it is enabled and stable, then clicks. The final assertion waits for the async confirmation. The test reads like a description of user intent, and the waiting is invisible because Playwright owns it.$L$, $L$- Adding `waitForTimeout` before an action "to be safe" when the action already waits
- Assuming auto-waiting covers a background process it has no locator for
- Reading an element's state once into a variable, then acting on the stale snapshot
- Blaming Playwright for a timeout instead of reading which actionability check never passed$L$, $L$On a delivery team, treat any explicit sleep in a pull request as a question to answer in review: "what condition are you actually waiting for?" Nine times in ten the honest answer names something with a DOM signal — a button enabling, a spinner disappearing — that a locator and auto-waiting handle for free. The rare tenth case is a real asynchronous condition that deserves a targeted wait, not a fixed delay.$L$, $L$Find or build a flow where a control is disabled until a form is valid (a payment or transfer form is ideal). Write a test that fills the form and clicks the control with no explicit wait, then assert the outcome. Deliverable: the spec file plus one sentence naming which actionability check made the click safe.$L$, $L$If Playwright already waits for elements to be actionable, why does flakiness still exist at all? What kinds of conditions fall outside what auto-waiting can see?$L$, $L$Name two of the actionability checks Playwright runs before clicking an element. (Answer: any two of attached, visible, stable, enabled, receives events)$L$, array[$L$I can describe the actionability checks that gate an action$L$, $L$I can explain the retry loop shared by actions and assertions$L$, $L$I can tell when auto-waiting is enough and when a targeted wait is needed$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 6
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$The Real Causes of Flakiness$L$, $L$18 minute read$L$, $L$Flaky tests feel like bad luck, but they almost never are. They are a design problem with a small set of recurring causes. This lesson names those causes so you can diagnose flakiness structurally instead of retrying and hoping.$L$, array[$L$Name the main structural causes of flaky tests$L$, $L$Explain why flakiness is a design problem rather than random misfortune$L$, $L$Diagnose which category a given flaky failure belongs to$L$], $L$## Flakiness is not luck
A flaky test passes and fails on the same code without any change. It is tempting to call this random and move on, but "random" here just means "caused by something you have not identified yet". Almost every flake traces back to one of a handful of design faults. Name the category and the fix usually becomes obvious.

## Timing and race conditions
The classic cause: the test acts before the application is ready, or asserts before the result has arrived. Fixed sleeps make this worse, not better — too short and it fails, too long and it wastes time and still fails under load. The fix is auto-waiting and web-first assertions that wait for the actual condition.

## Shared or leaked state
Tests that share a database record, a user account, a logged-in session or a global counter will interfere with each other, especially in parallel. Test A mutates something test B assumed. This is the most damaging category because the failing test is often not the one that caused the problem.

## Poor test data
Tests that depend on data someone might change, on "the third row of the table", or on a record that another test also edits, are fragile by construction. Good tests create the data they need and clean up after themselves, or use isolated, deterministic fixtures.

## Environment
Differences between where a test passes and where it fails: a slower CI machine, a different viewport that shows a cookie banner, a different time zone or locale, a service that is up locally but rate-limited in CI. "Works on my machine" is an environment flake.

## Test ordering
If a suite only passes when tests run in a particular order, the tests are coupled. Playwright isolates browser contexts to help, but shared back-end state can still leak. A suite you can run in any order, or shuffled, is a suite that is honestly independent.

## Key takeaway
Flakiness is a design signal, not noise: timing, shared state, poor data, environment and ordering account for nearly all of it — diagnose the category and you fix the cause, rather than retrying a symptom forever.$L$, $L$A flaky test caused by shared state, and the isolated version that fixes it:

~~~ts
import { test, expect } from '@playwright/test';

// Flaky: every test edits the SAME shared account. In parallel they collide.
test('updates the display name', async ({ page }) => {
  await page.goto('/profile');
  await page.getByLabel('Display name').fill('Jordan');
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByRole('alert')).toHaveText('Profile updated');
});
~~~

If another test signs in as the same user and changes the name concurrently, this one may see the wrong value or a stale session. The fix is to give each test its own data:

~~~ts
import { test, expect } from '@playwright/test';
import { createUser } from './helpers/users';

test('updates the display name', async ({ page }) => {
  // Each test creates its own user, so nothing is shared.
  const user = await createUser();
  await page.goto('/login');
  await page.getByLabel('Email').fill(user.email);
  await page.getByLabel('Password').fill(user.password);
  await page.getByRole('button', { name: 'Sign in' }).click();

  await page.goto('/profile');
  await page.getByLabel('Display name').fill('Jordan');
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByRole('alert')).toHaveText('Profile updated');
});
~~~

The behaviour under test is identical. The difference is that the second version owns its data end to end, so no other test can invalidate its assumptions — the flake disappears because the shared state that caused it is gone.$L$, $L$- Labelling a test "just flaky" and adding a retry instead of finding the cause
- Sharing one seeded user or record across many tests that all mutate it
- Depending on data ("row 3", "the newest order") that other tests or people can change
- Assuming a test that passes locally is order-independent without ever shuffling the suite$L$, $L$On a delivery team, keep a flaky-test log: when a test fails then passes on rerun, record it rather than shrugging. Within a sprint the log almost always shows clusters — a set of tests sharing one account, a handful that only fail on the slower CI runner. Flakiness treated as data reveals its structural cause; flakiness treated as luck stays forever.$L$, $L$Take a suite (yours or a sample) and run it with tests shuffled and in parallel. For any test that fails, classify the failure into one of the five categories — timing, shared state, data, environment, ordering. Deliverable: a short table of the failures you found and the category each belongs to.$L$, $L$A test fails roughly one run in twenty and always passes on rerun. Which of the five categories would you investigate first, and what evidence would tell you you were right?$L$, $L$Why is shared state considered the most damaging cause of flakiness? (Answer: because the test that fails is often not the one that caused the problem, making it hard to trace)$L$, array[$L$I can name the main structural causes of flakiness$L$, $L$I can classify a flaky failure into the right category$L$, $L$I treat flakiness as a design problem to diagnose, not luck to absorb$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 6
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Never Use Hard Waits$L$, $L$17 minute read$L$, $L$The single most common flakiness anti-pattern is the hard wait — `waitForTimeout`. This lesson shows you how to replace every one with a web-first assertion, a targeted `locator.waitFor`, or `expect(...).toPass()` for conditions that need polling.$L$, array[$L$Explain why fixed-duration waits both slow the suite and increase flakiness$L$, $L$Replace waitForTimeout with web-first assertions and locator.waitFor$L$, $L$Use expect(...).toPass() to poll a custom condition correctly$L$], $L$## Why hard waits are a trap
`await page.waitForTimeout(3000)` waits exactly three seconds, no matter what. This fails you in both directions. If the app is slow today — a loaded CI machine, a cold cache — three seconds is not enough and the test flakes. If the app is fast, you have thrown away nearly three seconds on every run, and a suite of hundreds of tests bleeds minutes. A fixed wait is a guess about a duration you cannot actually predict.

## The default replacement: web-first assertions
Most of the time you are sleeping because you are waiting for something to appear or change. Assert that thing directly and let the assertion do the waiting:

~~~ts
await expect(page.getByRole('alert')).toHaveText('Saved');
~~~

This waits precisely until the alert says "Saved" — no longer, no shorter. It is faster than any sleep on a good day and more reliable on a bad one.

## Waiting for a locator to reach a state
When you need to wait for an element to appear or disappear but are not yet asserting on it, use `locator.waitFor`:

~~~ts
await page.getByText('Loading…').waitFor({ state: 'hidden' });
~~~

States are `attached`, `detached`, `visible` and `hidden`. This is the honest way to wait out a spinner.

## Polling a custom condition: toPass
Sometimes the condition is not a single assertion — it is a small block that should eventually all hold, perhaps re-fetching data. `expect(...).toPass()` retries the whole block:

~~~ts
await expect(async () => {
  const orders = await api.get('/orders');
  expect(orders.status).toBe(200);
  expect(orders.data).toHaveLength(1);
}).toPass();
~~~

Playwright re-runs the callback until it stops throwing or the timeout hits. This is the correct tool for eventual consistency — a job that finishes shortly after you trigger it — and it replaces the ugliest sleeps of all.

## Key takeaway
There is no condition a fixed sleep handles better than a web-first assertion, `locator.waitFor`, or `expect(...).toPass()`; each waits for the actual state instead of a guessed duration, so replacing hard waits makes a suite both faster and more reliable at once.$L$, $L$Replacing a sleep-driven flow with targeted waits:

~~~ts
import { test, expect } from '@playwright/test';

test('exported report becomes available for download', async ({ page }) => {
  await page.goto('/reports');
  await page.getByRole('button', { name: 'Export' }).click();

  // The export runs in the background. Wait for the spinner to clear...
  await page.getByText('Preparing export…').waitFor({ state: 'hidden' });

  // ...then assert the real outcome, which retries until it holds.
  await expect(page.getByRole('link', { name: 'Download report' })).toBeVisible();
});
~~~

No step guesses a duration. `waitFor({ state: 'hidden' })` waits exactly as long as the export takes, and the web-first assertion confirms the download link actually appeared. On a fast run this finishes in a fraction of a second; on a slow CI run it waits patiently — and either way it asserts a genuine outcome rather than hoping three seconds was enough.$L$, $L$- Reaching for `waitForTimeout` as the default fix for any intermittent failure
- Converting a sleep into a longer sleep when it flakes, doubling the wasted time
- Using `waitForTimeout` to wait out an animation that has a perfectly good DOM signal
- Wrapping a single assertion in `toPass()` when a plain web-first assertion already retries$L$, $L$On a delivery team, add a lint rule or a simple CI grep that fails the build if `waitForTimeout` appears in the test suite. It sounds heavy-handed, but it forces the real conversation every time: "what are you actually waiting for?" The handful of legitimate cases (a deliberate debounce you are testing, say) can be allow-listed explicitly, and everyone can see exactly where and why a fixed wait was justified.$L$, $L$Find every `waitForTimeout` in a suite (or write three tests that misuse it). Replace each with the right tool: a web-first assertion, `locator.waitFor`, or `expect(...).toPass()`. Deliverable: the before/after for each, with a one-line note on which replacement you chose and why.$L$, $L$A hard wait of three seconds "fixes" a flaky test. In what two different ways is that fix an illusion, and what is the test really waiting for?$L$, $L$Which Playwright API retries an entire block of assertions until it stops throwing? (Answer: expect(...).toPass())$L$, array[$L$I can explain why fixed sleeps both slow tests and increase flakiness$L$, $L$I can replace a waitForTimeout with the correct targeted wait$L$, $L$I can use expect(...).toPass() to poll a custom condition$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 6
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$Locators That Survive Change$L$, $L$18 minute read$L$, $L$A resilient locator is coupled to what a user perceives, not to how the page is built. This lesson contrasts role, label and test-id strategies with the brittle CSS and XPath selectors that shatter on the next refactor, and shows how locator choice is itself a reliability decision.$L$, array[$L$Prefer role, label and test-id locators over structural CSS and XPath$L$, $L$Explain why structural selectors break on refactors that change nothing a user sees$L$, $L$Choose a resilient locator and add a test-id only as a deliberate escape hatch$L$], $L$## Locator choice is a reliability decision
Flakiness is not only about timing. A locator that breaks whenever a developer restructures the markup is a reliability problem too — it produces red runs with no real defect behind them, which erodes trust in the suite exactly as much as a timing flake does. The most durable locators describe the element the way a person or an assistive technology would.

## The resilient strategies
Prefer, in roughly this order:

1. `getByRole('button', { name: 'Add to basket' })` — role plus accessible name. Buttons, links, headings, checkboxes, inputs. This is coupled to behaviour and content, which change rarely.
2. `getByLabel('Email')` — form fields by their visible label.
3. `getByText('Order confirmed')` — non-interactive content.
4. `getByTestId('cart-total')` — an explicit, agreed `data-testid` hook for cases where nothing user-facing is stable enough.

## Why structural selectors break
`page.locator('div.sidebar > ul > li:nth-child(3) > a')` encodes the current DOM shape. It says nothing about what the element *is* — only where it happens to sit today. The moment a developer wraps that list in a new container, reorders items, or swaps a CSS-in-JS class hash, the selector points at nothing or, worse, at the wrong element. None of those changes altered what the user sees, yet the test breaks. That mismatch — the test failing when nothing meaningful changed — is the definition of brittle.

## Test-ids are a tool, not a default
A `data-testid` is stable because your team agrees not to change it, and it is invisible to users so it never accidentally couples a test to copy or styling. That makes it a good escape hatch — for a canvas, a chart, an icon-only control with no accessible name. But reach for it last: if `getByRole` cannot find a control because it has no accessible name, that is often a genuine accessibility bug, and adding a test-id routes around a defect instead of raising it.

## Key takeaway
Locate by what the user perceives — role, label, text — and keep `data-testid` as a deliberate escape hatch; a locator tied to behaviour survives the refactors that shatter CSS and XPath, which makes locator choice a first-class reliability decision, not a stylistic one.$L$, $L$The same element located brittly and resiliently, and a justified test-id:

~~~ts
import { test, expect } from '@playwright/test';

test('resilient locators for a product card', async ({ page }) => {
  await page.goto('/products');

  // Brittle — breaks if the card markup is restructured:
  // await page.locator('.card:nth-child(2) button.btn-primary').click();

  // Resilient — scoped to the item, found by role and name:
  const card = page.getByRole('listitem').filter({ hasText: 'Mechanical keyboard' });
  await card.getByRole('button', { name: 'Add to basket' }).click();

  await expect(page.getByRole('status')).toHaveText('Mechanical keyboard added to basket');

  // Justified test-id: an icon-only rating widget with no accessible text.
  await expect(page.getByTestId('rating-stars')).toHaveAttribute('data-value', '4');
});
~~~

The click is located by scoping to the right list item and then finding the button by its accessible name, so reordering the products or restyling the card cannot break it. The one `getByTestId` is a conscious choice for a widget that genuinely has no user-facing text to target — the exception that proves the rule, not the default.$L$, $L$- Defaulting to CSS or XPath because the editor's "copy selector" produces it
- Locating by a CSS-in-JS class hash that changes on every build
- Adding `data-testid` everywhere as a first choice instead of a last resort
- Routing around a missing accessible name with a test-id instead of raising the accessibility bug$L$, $L$On a delivery team, make "no new structural selectors without justification" a review standard, and pair it with the developers rather than fighting them. When a test needs a hook the product does not offer, the best outcome is usually a shared `data-testid` the developers agree to keep stable, added at the same time as the feature — not a fragile CSS path bolted on afterwards by whoever wrote the test. Locator resilience is a contract between test and product, negotiated up front.$L$, $L$Take five locators from an existing suite that use CSS or XPath. Rewrite each as the most resilient user-facing locator you can. For any you cannot, decide between raising a missing-accessible-name bug and agreeing a `data-testid`, and say which. Deliverable: a before/after table plus your decision on each stubborn case.$L$, $L$A refactor that changed no user-visible behaviour turned dozens of tests red. What does that tell you about how those tests were located, and what would have prevented it?$L$, $L$Why does a role-based locator survive a restyle that breaks a CSS selector? (Answer: it is coupled to behaviour and accessible name, which the restyle did not change, rather than to DOM structure and classes)$L$, array[$L$I default to role, label and text locators over structural selectors$L$, $L$I can explain why structural selectors break on cosmetic refactors$L$, $L$I use data-testid deliberately, as an agreed escape hatch, not a default$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 6
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Handling Async UI$L$, $L$18 minute read$L$, $L$Dialogs, toasts, animations, navigations and in-flight network requests are where sleeps sneak back in. This lesson shows how to handle each asynchronous UI pattern by waiting for the real signal — an event, a state, a response — instead of a fixed delay.$L$, array[$L$Handle dialogs, toasts and animations without sleeps$L$, $L$Wait for navigations and specific network responses deterministically$L$, $L$Choose the narrowest reliable signal for each async pattern$L$], $L$## The general rule
Every asynchronous UI pattern has a real signal you can wait for: an element appearing, a class settling, a URL changing, a response arriving. The reliable approach is always to wait for that specific signal, never for a duration. Below are the patterns you meet most.

## Dialogs
Native `alert`, `confirm` and `prompt` dialogs block the page. Register a handler **before** the action that triggers them:

~~~ts
page.on('dialog', dialog => dialog.accept());
await page.getByRole('button', { name: 'Delete account' }).click();
~~~

Custom in-page modals are just elements — locate the modal and act on it with normal web-first assertions; no special handling needed.

## Toasts and transient messages
A toast that auto-dismisses is a race: assert it while it is there, and do not sleep waiting for it to go. `await expect(page.getByRole('alert')).toHaveText('Saved')` catches it during its lifetime because the assertion retries from the moment you call it.

## Animations
Auto-waiting already includes a **stability** check — Playwright waits for an element to stop moving before acting on it. So a button sliding into place is handled for you. If you must wait for an animation with no actionable target, wait on a state change (a class, an `aria` attribute) rather than a fixed duration.

## Navigations
You rarely need an explicit wait: asserting on the destination is enough, because the assertion retries across the navigation.

~~~ts
await page.getByRole('link', { name: 'Checkout' }).click();
await expect(page).toHaveURL(/\/checkout/);
~~~

For a click that triggers a navigation you want to bracket explicitly, use `waitForURL`.

## Network settling
Do not wait for "the network to be idle" as a blunt instrument — it is fragile on pages with polling or analytics. Wait for the **specific** response you care about:

~~~ts
const response = page.waitForResponse(r => r.url().includes('/api/orders') && r.ok());
await page.getByRole('button', { name: 'Place order' }).click();
await response;
await expect(page.getByRole('heading', { name: 'Order confirmed' })).toBeVisible();
~~~

## Key takeaway
Every async pattern — dialog, toast, animation, navigation, network — has a precise signal; wait for that signal, not a duration, and prefer the narrowest one (a specific response over "network idle", a state change over a sleep) so the test is both deterministic and fast.$L$, $L$Bracketing a network call and confirming the resulting UI, with no sleeps:

~~~ts
import { test, expect } from '@playwright/test';

test('placing an order waits for the API, not a timer', async ({ page }) => {
  await page.goto('/cart');

  // Arm the wait BEFORE the click so we cannot miss the response.
  const orderPosted = page.waitForResponse(
    r => r.url().includes('/api/orders') && r.request().method() === 'POST' && r.ok(),
  );

  await page.getByRole('button', { name: 'Place order' }).click();

  const response = await orderPosted;
  const body = await response.json();
  expect(body.status).toBe('confirmed');

  // The UI outcome is asserted with a retrying web-first assertion.
  await expect(page.getByRole('heading', { name: 'Order confirmed' })).toBeVisible();
  await expect(page).toHaveURL(/\/orders\/[a-z0-9-]+/);
});
~~~

The `waitForResponse` is armed before the click, so there is no window in which the response could arrive unobserved. The test then checks both the API result and the user-facing outcome — the heading and the new URL — each waited for by its own retrying assertion. Nothing here guesses a duration, so it runs fast when the API is fast and stays reliable when it is slow.$L$, $L$- Registering a `dialog` handler after the click that triggers the dialog
- Sleeping to wait out a toast instead of asserting on it while it is visible
- Using `waitForLoadState('networkidle')` on a page that polls, so it never settles
- Arming `waitForResponse` after the action, creating a race where the response is missed$L$, $L$On a delivery team, prefer `waitForResponse` on a specific endpoint over any "wait for the network to be quiet" approach. Real applications fire analytics beacons, heartbeat polls and lazy-loaded chunks that mean the network is never truly idle — a blanket network wait either hangs or resolves at an arbitrary moment. Naming the one request that matters makes the test say what it actually depends on, which is also documentation for the next person.$L$, $L$Write a test for a flow that makes a specific API call (a submit, a search, a save). Arm `waitForResponse` on that endpoint before the action, assert on the response body, then assert the resulting UI with web-first assertions. Deliverable: the spec file with a comment explaining why the wait is armed before the action.$L$, $L$Playwright's stability check already handles most animations. Given that, when is waiting on an animation still your responsibility, and what signal would you wait for instead of a sleep?$L$, $L$Why should you arm waitForResponse before the action that triggers it? (Answer: so the response cannot arrive and be missed in the gap between acting and starting to wait)$L$, array[$L$I can handle dialogs, toasts and animations without sleeps$L$, $L$I can wait for a navigation and a specific network response deterministically$L$, $L$I choose the narrowest reliable signal for each async pattern$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 6
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 6, $L$Diagnosing & Fixing a Flaky Test$L$, $L$20 minute read$L$, $L$This lesson is a worked rescue. You will take a test that fails roughly one run in ten, reproduce it deliberately with `--repeat-each`, find the true cause in the trace viewer, and fix it so it goes green for the right reason — not because you padded it with a wait.$L$, array[$L$Reproduce an intermittent failure deliberately with --repeat-each$L$, $L$Use the trace viewer to locate the exact step where a flaky test diverges$L$, $L$Fix the underlying cause so the test passes for the right reason$L$], $L$## Reproduce before you fix
You cannot fix what you cannot see fail. A test that fails one run in ten will almost never fail while you watch it once. Force it:

~~~bash
npx playwright test flaky.spec.ts --repeat-each=20
~~~

`--repeat-each` runs each selected test that many times in one go. If it fails a few times out of twenty, you now have a reproducible flake to investigate. Combine with `--workers` to reproduce parallelism-related flakes, or `--retries=0` so a flake is not silently absorbed while you are hunting it.

## Capture a trace of the failure
Set traces to record on failure so the flaky run leaves evidence:

~~~ts
// playwright.config.ts (excerpt)
use: { trace: 'on-first-retry' },
~~~

Or force it for the hunt with `--trace on`. When a repeated run fails, open the trace it captured:

~~~bash
npx playwright show-trace test-results/.../trace.zip
~~~

## Read the trace, do not guess
In the trace viewer, scrub to the failing step. You get a DOM snapshot at that exact moment, the action log, network activity and console output. The questions to answer:

- What was on the page when the step failed? An overlay? A spinner still visible?
- Did the locator resolve to the element you expected, or to nothing?
- Was a network response still in flight that the test assumed had arrived?

Most flaky tests reveal their cause here in under a minute — a cookie banner over a button on the CI viewport, a save that had not completed, a shared record another test had changed.

## Fix the cause, not the symptom
The wrong fix is a longer timeout or a sleep — that makes the test pass sometimes-more-often while leaving the real fault in place. The right fix addresses the category from Lesson 2: dismiss the overlay in setup, wait for the specific response, give the test its own data. Then prove it:

~~~bash
npx playwright test flaky.spec.ts --repeat-each=50
~~~

Fifty green runs is evidence the flake is gone. One green run never was.

## Green for the right reason
A test that now passes because you fixed the race is trustworthy. A test that passes because you raised its timeout to thirty seconds is a slower version of the same lie. The goal of this whole module is a suite whose green means what the team thinks it means — timely, honest evidence about the product, not a light that stays green by luck.

## Key takeaway
Rescue a flaky test in four moves: reproduce it with `--repeat-each`, capture and read a trace to find the true cause, fix that cause structurally, and re-run many times to prove it — so the test ends up green for the right reason rather than padded into silence.$L$, $L$A full rescue of a flake caused by an unobserved network call.

The failing test asserts a total immediately after a click, but the total is populated by an async request:

~~~ts
// Flaky: reads the total before the pricing API has responded.
test('shows the order total', async ({ page }) => {
  await page.goto('/cart');
  await page.getByRole('button', { name: 'Recalculate' }).click();
  await expect(page.getByTestId('order-total')).toHaveText('£42.00');
});
~~~

Reproduce it:

~~~bash
npx playwright test cart.spec.ts --repeat-each=20 --trace on
~~~

It fails perhaps three times in twenty. Open one failing trace with `npx playwright show-trace`. The DOM snapshot at the failing step shows `order-total` still reading `£0.00`, and the network panel shows the `/api/price` request only completing a beat later. The assertion was retrying, but on a slow run it timed out before the response landed because the element existed with stale text the whole time.

The correct fix waits for the specific response, not a longer timeout:

~~~ts
test('shows the order total', async ({ page }) => {
  await page.goto('/cart');

  const priced = page.waitForResponse(r => r.url().includes('/api/price') && r.ok());
  await page.getByRole('button', { name: 'Recalculate' }).click();
  await priced;

  await expect(page.getByTestId('order-total')).toHaveText('£42.00');
});
~~~

Prove it with `npx playwright test cart.spec.ts --repeat-each=50` — fifty green runs. The test now passes because the race is gone, not because it was given more time to get lucky.$L$, $L$- Trying to fix a flake you have not reproduced, so you cannot tell if the fix worked
- Adding `console.log` and re-running blindly instead of opening the trace
- "Fixing" the flake by raising the timeout, leaving the real race in place
- Declaring victory after one green run rather than many repeated runs$L$, $L$On a delivery team, make trace-first the norm for any flaky-test ticket: the ticket is not "investigate flaky test", it is "attach the trace of a reproduced failure and name the cause". That framing stops the endless rerun-and-hope loop and turns a vague annoyance into a concrete, fixable bug. Publish traces as CI artefacts so anyone — including the developer who wrote the feature — can open the failing step without reproducing it themselves.$L$, $L$Take a flaky test (or introduce a realistic race — assert an async value without waiting for its response). Reproduce it with `--repeat-each`, capture a trace, identify the cause from the trace, fix the underlying issue, and prove stability with fifty repeated runs. Deliverable: the before/after test plus a short note of what the trace showed and how you proved the fix.$L$, $L$You have two ways to make a flaky test stop failing: fix the race it exposes, or raise its timeout until it stops. Both make CI green. Why is only one of them a real fix, and what does the other cost the team later?$L$, $L$Which Playwright flag runs each selected test many times in one command to reproduce an intermittent failure? (Answer: --repeat-each)$L$, array[$L$I can reproduce an intermittent failure deliberately with --repeat-each$L$, $L$I can use the trace viewer to find the exact step a flaky test diverges$L$, $L$I fix the underlying cause and prove stability with repeated runs$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'modern-test-automation-bootcamp' and m.module_number = 6
on conflict (module_id, lesson_number) do nothing;

