-- ============================================================
-- API Testing Masterclass — Module 1 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/api-module1.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$What Is an API?$L$, $L$12 minute read$L$, $L$An API is how two pieces of software talk to each other. Before you can test one, you need a clear mental model of what an API actually is and why it exists.$L$, array[$L$Explain what an API is in plain language$L$, $L$Describe the client–server relationship$L$, $L$Identify where APIs sit in a real application$L$], $L$## The plain-English definition
An **API** (Application Programming Interface) is a contract that lets one program request something from another and get a predictable response back. You don't need to know *how* the other program works — only what to send and what you'll get.

## An everyday analogy
Ordering at a restaurant: you (the **client**) give your order to the waiter (the **API**), who takes it to the kitchen (the **server**) and brings back your food (the **response**). You never enter the kitchen — the waiter is the defined interface.

## Where APIs live
- The **frontend** calls APIs to fetch and save data.
- The **backend** exposes those APIs and talks to databases.
- Apps also call **third-party** APIs (payments, maps, email).

## Why testers care
Most business logic and integration risk lives at the API layer — below the UI. Testing there is faster, more stable, and catches bugs the UI can hide.$L$, $L$Open a weather app. When you type a city, it sends `GET /weather?city=Sheffield` to a weather service, which replies with JSON (temperature, conditions, forecast). The app draws the screen from that data — the UI is just a view of an API response.$L$, $L$- Thinking an API is "a website" — it returns data, not pages
- Believing you must be a developer to test APIs
- Assuming the UI and the API always show the same thing (they often don't)$L$, $L$APIs are where the real contract between systems lives. If you can read and test an API, you can find bugs long before they ever reach a screen.$L$, $L$In one or two sentences, describe an app you use daily and name one thing it almost certainly requests from an API.$L$, $L$In the client–server model, which side sends the request?$L$, $L$In the client–server model, which side sends the request? (Answer: the client)$L$, array[$L$I can explain what an API is without jargon$L$, $L$I can describe the client–server relationship$L$, $L$I can point to where APIs sit in an app$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 1
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$Requests & Responses: How the Web Talks$L$, $L$14 minute read$L$, $L$Every API interaction is a request and a response. Understanding their anatomy is the foundation of everything else in this course.$L$, array[$L$Break a request into its parts (method, URL, headers, body)$L$, $L$Break a response into its parts (status, headers, body)$L$, $L$Read a real request/response exchange$L$], $L$## The request has four parts
1. **Method** — the action: GET, POST, PUT, PATCH, DELETE
2. **URL / endpoint** — what you're acting on
3. **Headers** — metadata: `Content-Type`, `Authorization`, `Accept`
4. **Body** — the data you send (mostly POST/PUT/PATCH), usually JSON

## The response has three parts
1. **Status code** — did it work?
2. **Headers** — metadata about the response
3. **Body** — the returned data (usually JSON)

## Reading an exchange
`GET /orders/42` → `200 OK` + a JSON order. `POST /orders` with a body → `201 Created`. Each request is **stateless** — it carries everything the server needs.$L$, $L$Request: `POST /orders` with `Content-Type: application/json` and body `{"item":"mug","qty":2}`. Response: `201 Created`, header `Location: /orders/99`, body `{"id":99,"item":"mug","qty":2,"status":"pending"}`. Check: status is 201, body echoes input, an id was assigned.$L$, $L$- Ignoring headers — auth and content-type problems hide there
- Only checking the status code and never the body
- Forgetting the body must match the Content-Type you declared$L$, $L$Always inspect the full response — status, headers and body. Many "passing" API tests only checked the status code and missed a wrong payload.$L$, $L$Write out the four parts of a request to fetch user 7 from `https://api.example.com`.$L$, $L$Which part of the response tells you whether the request succeeded?$L$, $L$Which part of the response tells you whether the request succeeded? (Answer: the status code)$L$, array[$L$I can name the parts of a request$L$, $L$I can name the parts of a response$L$, $L$I can read a request/response exchange$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 1
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$REST Principles & Resources$L$, $L$13 minute read$L$, $L$REST is the style most modern APIs follow. Knowing its principles tells you what to expect from an endpoint before you even test it.$L$, array[$L$Explain what REST means$L$, $L$Describe resources and how URLs represent them$L$, $L$Recognise statelessness and its testing impact$L$], $L$## REST in one line
**RE**presentational **S**tate **T**ransfer: you act on **resources** using standard HTTP methods.

## Resources and URLs
- Collection: `/users`
- Single item: `/users/42`
- Sub-resource: `/users/42/orders`
Nouns, not verbs — the *method* is the verb.

## Key principles
- **Statelessness** — each request is independent
- **Uniform interface** — consistent methods and status codes
- **Client–server separation**

## Why it matters
Once you know an API is RESTful you can predict behaviour: `GET /users/42` reads, `DELETE /users/42` removes, a missing user returns `404`. Predictability = testability.$L$, $L$A bookshop API: `GET /books` (list), `GET /books/12` (one), `POST /books` (add), `PUT /books/12` (replace), `DELETE /books/12` (remove). If `GET /getBook?id=12` appears instead, the API isn't cleanly RESTful — worth noting in your approach.$L$, $L$- Expecting verbs in URLs (`/createUser`) — REST uses nouns + methods
- Assuming a session is remembered between requests
- Treating every API as REST when some are RPC or GraphQL$L$, $L$RESTful design is a gift to testers: it makes behaviour predictable. When an API breaks its own conventions, that unpredictability is a risk worth flagging.$L$, $L$Design the five REST endpoints (method + path) for managing "projects".$L$, $L$Should REST URLs contain nouns or verbs, and why?$L$, $L$In REST, should URLs contain nouns or verbs? (Answer: nouns — the HTTP method is the verb)$L$, array[$L$I can explain REST simply$L$, $L$I can design resource URLs$L$, $L$I understand statelessness$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 1
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$Where API Testing Fits in the SDLC$L$, $L$12 minute read$L$, $L$API testing is one of the highest-value activities a tester can do. This lesson shows why, and where it fits in the test pyramid and delivery lifecycle.$L$, array[$L$Place API testing on the test pyramid$L$, $L$Explain the value of shifting testing left$L$, $L$Describe when API tests run in delivery$L$], $L$## The test pyramid
- **Unit** (many, fast) — individual functions
- **API / integration** (fewer, still fast) — services talking
- **UI / end-to-end** (few, slow, brittle) — the whole app

API tests sit in the middle: far more stable and faster than UI, far broader than unit.

## Shift left
APIs are often built **before** the UI. Testing them early finds integration and data bugs when they're cheapest to fix.

## Where they run
- During development
- In CI/CD on every commit (via Newman — Module 8)
- In regression suites and monitoring$L$, $L$A team's checkout kept failing flaky UI tests. Moving the core checks to the API layer (`POST /cart`, `POST /orders`) made them fast and stable — and caught a real tax-calculation bug days before release.$L$, $L$- Only testing through the UI and ignoring the API layer
- Waiting for the UI to exist before testing anything
- Duplicating every UI test at the API level instead of choosing the right layer$L$, $L$If a test can be done at the API layer instead of the UI, it usually should — faster, more stable, and it runs on every build.$L$, $L$List two checks that are better done at the API layer than through the UI, and say why.$L$, $L$Why are API tests generally more stable than end-to-end UI tests?$L$, $L$On the test pyramid, are API tests faster or slower than UI/end-to-end tests? (Answer: faster and more stable)$L$, array[$L$I can place API testing on the pyramid$L$, $L$I can explain shifting left$L$, $L$I know when API tests run$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 1
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$API Testing vs UI Testing$L$, $L$11 minute read$L$, $L$API and UI testing answer different questions. Knowing which to use — and when — is what separates a strategic tester from a button-clicker.$L$, array[$L$Contrast API and UI testing$L$, $L$Choose the right layer for a given check$L$, $L$Explain why the UI can mask API problems$L$], $L$## Different questions
- **API testing** asks: *is the logic and data correct?*
- **UI testing** asks: *can a user actually do this on screen?*

## Trade-offs
| | API | UI |
|---|---|---|
| Speed | Fast | Slow |
| Stability | High | Lower |
| Setup | Low | Higher |
| User realism | Lower | High |

## The UI can hide API bugs
A screen might show "Success" while the API returned the wrong data. Only testing the API reveals it.

## Rule of thumb
Push logic, data and edge-case checks **down** to the API. Keep the UI for a few true end-to-end journeys.$L$, $L$A discount API returned `£0.00` off for a valid code, but the UI defaulted to full price with no error — so UI testing "passed". An API test asserting the discounted total caught it immediately.$L$, $L$- Doing everything through the UI because it "feels real"
- Assuming a green UI means the data underneath is correct
- Never testing the API independently of the screen$L$, $L$When the UI and the API disagree, trust the API response — then find out why the UI hid the truth.$L$, $L$Give one example of a bug the UI could show as "passing" while the API is actually wrong.$L$, $L$Which layer better answers "is the returned data correct?" and why?$L$, $L$Which layer better answers "is the returned data correct?" (Answer: the API layer)$L$, array[$L$I can contrast API and UI testing$L$, $L$I can choose the right layer$L$, $L$I understand how UIs can mask API bugs$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 1
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 6, $L$Setting Up Your API Testing Toolkit$L$, $L$25 minutes$L$, $L$Time to get hands-on. You install Postman, point it at a free public API, and send your very first request.$L$, array[$L$Install and open Postman$L$, $L$Send a first GET request to a public API$L$, $L$Read the status code and JSON response$L$], $L$## Your toolkit
- **Postman** (free) — the client we use throughout the course
- A **free public API**: `https://jsonplaceholder.typicode.com` and `https://reqres.in`
- No coding required to start

## Step by step
1. Download Postman from postman.com and open it.
2. Click **New → HTTP Request**.
3. Set method **GET**, URL `https://jsonplaceholder.typicode.com/users/1`.
4. Click **Send**.
5. You should see **200 OK** and a JSON user object.

## What you're looking at
The bottom pane shows the **status** (200), **time**, **size**, and **body** (JSON). You just made an API request and read the response.$L$, $L$`GET https://reqres.in/api/users?page=2` returns `200 OK` and a body with a `data` array plus pagination (`page`, `total`, `total_pages`). Change `page=2` to `page=3` and watch the data change — you're already exploring an API.$L$, $L$- Putting the URL in the wrong field or forgetting `https://`
- Choosing the wrong method (POST when you meant GET)
- Panicking at a 404 — it usually just means a wrong path$L$, $L$Keep one "scratch" request tab open while you learn. Being able to poke any endpoint in seconds is how experienced API testers explore quickly.$L$, $L$Send a GET to `https://jsonplaceholder.typicode.com/posts/1` and note the status code and two fields from the body.$L$, $L$What does a 200 status code tell you, and what does it not tell you?$L$, $L$What status code indicates a successful GET request? (Answer: 200 OK)$L$, array[$L$Postman is installed and open$L$, $L$I sent a GET request successfully$L$, $L$I can read the status code and JSON body$L$, $L$I saved my first request$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 1
on conflict (module_id, lesson_number) do nothing;

