-- ============================================================
-- API Testing Masterclass — Module 2 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/istqb-module2.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$The Waterfall Model$L$, $L$13 minute read$L$, $L$Waterfall is the classic sequential lifecycle. Understanding it — and where testing sits within it — is the foundation for everything the ISTQB syllabus says about how testing fits the way software is built.$L$, array[$L$Describe the sequential phases of the Waterfall model$L$, $L$Explain where and when testing happens in Waterfall$L$, $L$Recognise the risks Waterfall creates for testers$L$], $L$## What Waterfall is
The **Waterfall model** is a *sequential* software development lifecycle (SDLC). Each phase must be completed before the next begins, and work "flows down" like a waterfall: **requirements → design → implementation → testing → deployment → maintenance**.

## Where testing sits
In classic Waterfall, testing is a **single phase near the end**, after the code is built. Testers often receive the software late, with little time before release. This is the opposite of *early testing*, one of the seven testing principles.

## Why the ISTQB cares
The syllabus stresses that in *any* lifecycle, good testing has certain characteristics: for every development activity there is a corresponding test activity, each test level has objectives specific to that level, and test analysis and design begin during the matching development phase. Waterfall makes these hard because verification is deferred.

## Strengths and weaknesses
- **Strengths:** simple, well-documented, easy to manage when requirements are stable.
- **Weaknesses:** defects are found late (expensive to fix per the *cost of defects* idea), no working software until late, and it copes poorly with change.

## The tester's role
Testers should still start work early — reviewing requirements and designs as they are produced — even though execution comes late. Static testing of documents is a tester's best lever in a Waterfall project.$L$, $L$A bank builds a payments system in strict Waterfall. Requirements are signed off in month 1, design in month 3, coding runs months 4–8, and the test team finally gets a build in month 9 with two weeks before go-live. They find a currency-rounding defect rooted in a requirement that was ambiguous back in month 1 — cheap to fix then, very expensive now. The lesson: had a tester reviewed that requirement in month 1, the defect never reaches code.$L$, $L$- Believing testing only happens in the "testing phase" — test analysis and design should start much earlier, even in Waterfall
- Thinking Waterfall means testers do nothing until coding ends (they should be reviewing requirements and designs)
- Exam trap: assuming Waterfall has no early testing possible — early *static* testing is both possible and recommended$L$, $L$In a Waterfall project your most valuable contribution is often a requirements review, not a test run. Catching an ambiguous requirement on paper is dramatically cheaper than catching the resulting defect in month nine.$L$, $L$List the six phases of the Waterfall model in order, and mark the phase where test *execution* traditionally happens.$L$, $L$In classic Waterfall, why are defects typically more expensive to fix than in a lifecycle that tests earlier?$L$, $L$In the Waterfall model, at what point does dynamic test execution traditionally take place? (Answer: in a single dedicated test phase near the end, after implementation is complete)$L$, array[$L$I can list the Waterfall phases in order$L$, $L$I can explain where testing sits in Waterfall$L$, $L$I can describe the risks late testing creates$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 2
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$The V-Model$L$, $L$15 minute read$L$, $L$The V-model fixes Waterfall's biggest flaw by pairing every development phase with a test level. It is the model the ISTQB uses to explain how test levels map to development, so it is worth knowing cold.$L$, array[$L$Describe the V-model and its two sides$L$, $L$Map each test level to its corresponding development phase$L$, $L$Explain how the V-model embeds early testing and verification$L$], $L$## What the V-model is
The **V-model** is a sequential lifecycle (a refinement of Waterfall) where the development phases going *down* the left side are each matched by a testing level going *up* the right side. It is shaped like a **V**.

## The mapping (left → right)
- **Requirements / business analysis** ↔ **Acceptance testing**
- **System / functional specification** ↔ **System testing**
- **Architectural design** ↔ **Integration testing**
- **Component / detailed design** ↔ **Component (unit) testing**
- At the bottom point of the V sits **coding**.

## Verification and validation
Each development phase produces a work product that can be **verified** (reviewed) immediately, and the matching right-side level later **validates** the built software against it. This is why the V-model embeds *early testing*: test planning, analysis and design for each level begin as its matching left-side document is written — not at the end.

## Where testing happens
Testing is not one late phase; it is distributed across **four levels**, each with objectives specific to that level. Component testing checks individual units; integration testing checks interfaces between them; system testing checks the whole system's behaviour; acceptance testing checks fitness for use against user needs.

## Strengths and limits
- **Strengths:** clear traceability, early test design, defined levels.
- **Limits:** still sequential, so it copes poorly with changing requirements — the same rigidity as Waterfall.$L$, $L$A team building an insurance quote engine writes the system specification. On the V-model, that document immediately drives two things: developers move down toward design and code, and testers begin **designing the system tests** that will later validate the software against that same specification. When the build is ready, component tests run first (each calculation unit), then integration tests (units talking), then system tests (an end-to-end quote), then user acceptance tests (a broker confirms it meets their needs). Each level traces straight back to the document that spawned it.$L$, $L$- Mixing up the levels: acceptance pairs with requirements, not with detailed design
- Thinking the right-side test levels only start after coding — their *design* starts as the matching left-side document is written
- Exam trap: assuming the V-model removes Waterfall's rigidity — it still struggles with changing requirements$L$, $L$Learn the four level-to-phase pairings by heart. In real projects and in the exam, being able to say "this defect should have been caught at integration testing, which maps to architectural design" instantly shows you understand where risk lives.$L$, $L$Draw the V-model and label each of the four test levels against its corresponding development phase.$L$, $L$Which development phase does acceptance testing correspond to in the V-model, and why does that pairing make sense?$L$, $L$In the V-model, which test level corresponds to the architectural (high-level) design phase? (Answer: integration testing)$L$, array[$L$I can describe the two sides of the V-model$L$, $L$I can map each test level to its development phase$L$, $L$I can explain how the V-model embeds early testing$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 2
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Agile Development$L$, $L$15 minute read$L$, $L$Agile turns the sequential models on their head: build in short iterations, get working software early, and test continuously. The ISTQB expects you to know how the tester's role changes when the lifecycle becomes iterative and incremental.$L$, array[$L$Distinguish iterative and incremental development from sequential models$L$, $L$Describe how testing works within an Agile iteration$L$, $L$Explain how the tester's role changes in an Agile team$L$], $L$## Iterative and incremental
**Agile** is an umbrella for lifecycles that are **iterative** (repeating cycles that refine the product) and **incremental** (delivering the product in small, working slices). Instead of one long pass, the team builds in short **iterations** (often called sprints), each producing a potentially shippable increment.

## Testing is continuous, not a phase
Testing happens **inside every iteration**, not at the end. As soon as a small piece of functionality exists, it is tested. Testers, developers and business roles collaborate throughout. Frequent change is expected, so **regression testing** grows in importance and **test automation** becomes essential to keep pace.

## How the tester's role changes
The tester is embedded in a **cross-functional team** and involved from the start of each iteration. They help clarify user stories, define **acceptance criteria**, and often contribute to **acceptance test-driven development (ATDD)**, where tests are agreed *before* code is written. Testing is a whole-team responsibility, not a separate gate.

## Test levels in Agile
The levels (component, integration, system, acceptance) still exist, but they run **concurrently and repeatedly** within iterations rather than in a fixed sequence. Continuous integration runs component and integration tests on every commit.

## Trade-offs
- **Strengths:** early and frequent feedback, adapts to change, working software fast.
- **Challenges:** heavy regression load, requires strong automation, less up-front documentation to test against.$L$, $L$A team runs two-week sprints on a booking app. On day one of the sprint, the tester joins the developer and product owner to turn the user story "a guest can cancel a booking" into concrete **acceptance criteria** and example tests — *before* any code is written (ATDD). During the sprint, each commit triggers automated component and integration tests. By day eight the feature is done, exploratory tested, and its automated checks join the regression suite that runs on every future commit. Testing was continuous, not a phase bolted on at the end.$L$, $L$- Thinking Agile means "no testing" or "no documentation" — it means continuous testing and just-enough documentation
- Assuming the test levels disappear in Agile — they still exist, but run concurrently and repeatedly
- Exam trap: confusing *iterative* (refining through repeated cycles) with *incremental* (delivering in slices) — Agile is both$L$, $L$In Agile, your influence is greatest at the *start* of the iteration, not the end. Get into the story-refinement conversation and turn vague stories into testable acceptance criteria — that prevents defects rather than just finding them.$L$, $L$Take the user story "a registered user can reset their password" and write three acceptance criteria a tester could turn into checks.$L$, $L$Why does test automation become essential in Agile, whereas a slow Waterfall project might survive with mostly manual testing?$L$, $L$In Agile development, when does testing take place relative to development? (Answer: continuously, within every iteration — not as a separate phase at the end)$L$, array[$L$I can distinguish iterative and incremental development$L$, $L$I can describe how testing runs within an iteration$L$, $L$I can explain how the tester's role shifts in Agile$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 2
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$DevOps & Continuous Delivery$L$, $L$15 minute read$L$, $L$DevOps and continuous delivery extend Agile's fast feedback all the way to production. For a tester this means automated pipelines, continuous testing, and quality gates that decide whether code ships — the modern context the ISTQB expects you to understand.$L$, array[$L$Explain DevOps, continuous integration and continuous delivery$L$, $L$Describe where automated testing sits in a CI/CD pipeline$L$, $L$Identify the benefits and risks DevOps creates for testing$L$], $L$## What DevOps is
**DevOps** is a way of working that unites development and operations to deliver software faster and more reliably, with shared responsibility for quality. It relies on **automation**: **continuous integration (CI)** merges and tests every code change, and **continuous delivery/deployment (CD)** automatically prepares (and often releases) each change to production.

## The pipeline
A **CI/CD pipeline** is an automated sequence triggered by each commit: build → automated tests → package → deploy. Tests are staged — fast **component** and **integration** tests run first, then broader **system** and acceptance checks. A failing test stops the pipeline, so broken code never reaches production.

## Continuous testing and quality gates
DevOps depends on **continuous testing**: automated tests run at every stage as a **quality gate**. Only changes that pass the gates progress. This gives very fast feedback and lets defects be caught within minutes of being written.

## Benefits for testing
- Faster, more frequent feedback on every change.
- A stable, repeatable environment reduces "works on my machine" defects.
- Rapid, low-risk releases — small changes are easier to test and roll back.

## Risks and the tester's role
- Heavy reliance on **automation** — gaps in automated coverage let defects through.
- Speed can outrun exploratory and non-functional testing if the team isn't careful.
- The tester designs the automated checks that form the gates, guards against false confidence, and still performs exploratory testing that automation can't replace.$L$, $L$A developer commits a change to a pricing service. The CI/CD pipeline immediately kicks off: it builds the code, runs fast unit tests, then integration tests against the checkout service, then a set of automated system tests. All green, so the change is automatically deployed to a staging environment where smoke and acceptance checks run as a **quality gate**. Only then can it be promoted to production. The whole cycle takes fifteen minutes — and because a broken pricing calculation would have failed the integration stage, it could never have reached customers.$L$, $L$- Believing DevOps automation removes the need for testers — it changes the role, it doesn't remove it
- Assuming a green pipeline means the change is fully tested — it only means the *automated* checks passed; exploratory and non-functional gaps can remain
- Exam trap: thinking continuous delivery always auto-releases to production — continuous *delivery* keeps a release-ready build; continuous *deployment* is the step that auto-releases$L$, $L$Treat the pipeline as a product you own. A tester who can add a meaningful automated check to a quality gate — and knows which risks the gate does *not* cover — is worth their weight in gold on a DevOps team.$L$, $L$List, in order, the stages you would expect a basic CI/CD pipeline to run after a commit, and mark where automated tests act as a quality gate.$L$, $L$Why is a fully green CI/CD pipeline not the same as "this change has been fully tested"?$L$, $L$In a CI/CD pipeline, what is the purpose of a quality gate? (Answer: to automatically stop a change from progressing unless it passes the required tests/checks)$L$, array[$L$I can explain DevOps, CI and CD$L$, $L$I can describe where automated tests sit in a pipeline$L$, $L$I can identify the benefits and risks DevOps creates for testing$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 2
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Shift-Left Testing$L$, $L$13 minute read$L$, $L$"Shift left" is the practical expression of the early-testing principle: move testing activities earlier in the lifecycle to catch defects when they are cheapest to fix. The ISTQB names shift-left explicitly, so know what it means and how to do it.$L$, array[$L$Define shift-left testing and link it to the early-testing principle$L$, $L$Describe concrete practices that shift testing left$L$, $L$Explain the benefits and the pre-conditions for shift-left to work$L$], $L$## What shift-left means
**Shift-left testing** means performing testing activities **earlier** in the software development lifecycle — moving them "left" on a timeline that runs left (early) to right (late). It is the direct application of the testing principle *early testing saves time and money*.

## Why earlier is cheaper
The **cost of fixing defects** rises the later they are found. A defect caught in a requirements review costs a fraction of the same defect found in system testing or, worse, in production. Shift-left targets exactly this: find defects close to where they were introduced.

## Concrete shift-left practices
- **Static testing early:** reviews of requirements, designs and user stories, plus static analysis of code — catching defects before code even runs.
- **Test-first approaches:** test-driven development (TDD), acceptance test-driven development (ATDD) and behaviour-driven development (BDD), where tests are written *before* the code.
- **Involving testers early:** testers help define acceptance criteria and review work products from the very start.
- **Running unit and integration tests continuously** in the pipeline.

## Benefits and pre-conditions
- **Benefits:** cheaper defects, faster feedback, better-quality requirements, fewer late surprises.
- **Pre-conditions:** it requires effort and buy-in — teams may need coaching, and management must accept some extra up-front cost for large downstream savings. Shift-left does not remove later testing; it *adds* earlier activity.$L$, $L$A team adopts shift-left on a new feature. Before any code is written, testers review the user stories and spot that two acceptance criteria contradict each other — a defect removed on paper for the cost of a fifteen-minute conversation. During development, TDD means each unit has a failing test written first, and static analysis flags a null-handling bug on commit. By the time the feature reaches system testing, the classes of defect that usually swamp that phase have already been prevented — so system testing is calmer and focuses on genuine end-to-end risk.$L$, $L$- Thinking shift-left just means "test earlier" and skipping the specific practices (reviews, static analysis, test-first)
- Believing shift-left removes the need for later test levels — it complements them, it doesn't replace them
- Exam trap: not linking shift-left to the *early testing* principle and the *cost of defects* — that link is the whole point$L$, $L$The cheapest defect you will ever fix is the one you find in a requirements review. If you want to demonstrate shift-left value quickly, start reviewing requirements and user stories — it needs no tooling and pays back immediately.$L$, $L$List three specific practices that "shift testing left", and for each say which defects it helps catch earlier.$L$, $L$Which of the seven testing principles does shift-left most directly put into practice, and how?$L$, $L$What is the primary goal of shift-left testing? (Answer: to move testing activities earlier in the lifecycle so defects are found — and fixed — sooner and more cheaply)$L$, array[$L$I can define shift-left and link it to early testing$L$, $L$I can name concrete shift-left practices$L$, $L$I can explain the benefits and pre-conditions of shift-left$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 2
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 6, $L$Shift-Right Testing & How Testing Changes$L$, $L$16 minute read$L$, $L$Shift-right complements shift-left by testing in production, and this final lesson pulls the module together: how the tester's role and the test levels adapt across every model you have studied. This is the synthesis the ISTQB expects you to carry into practice.$L$, array[$L$Define shift-right testing and its main techniques$L$, $L$Explain how testing and the tester's role change across Waterfall, V-model, Agile and DevOps$L$, $L$Summarise how test levels map to each lifecycle model$L$], $L$## What shift-right means
**Shift-right testing** means continuing testing activities **after** release, in the live production environment. Where shift-left moves testing earlier, shift-right extends it *rightward* into operation. It relies on real users and real data to reveal what pre-release testing cannot.

## Shift-right techniques
- **Monitoring and observability:** watching logs, metrics and alerts to detect issues in production.
- **A/B testing and canary releases:** exposing a change to a small slice of users first.
- **Feature toggles:** switching functionality on or off in production to control and test exposure.
- **Chaos and resilience testing:** deliberately injecting failures to test robustness.

## Shift-left and shift-right together
They are complementary, not rival: shift-left prevents defects early; shift-right catches what only appears under real load and real usage. Together they give feedback across the *whole* lifecycle — the ideal for DevOps and continuous delivery.

## How testing changes across the models
- **Waterfall:** testing is a late phase; the tester's early value is reviewing documents.
- **V-model:** testing is distributed across four levels, each mapped to a development phase, with early test design and traceability.
- **Agile:** testing is continuous within iterations; the tester is embedded and helps define acceptance criteria.
- **DevOps:** testing is automated and continuous through the pipeline, extended into production by shift-right.

## The constant
Across every model the **test levels** — component, integration, system, acceptance — still exist. What changes is *when* and *how often* they run, and how early the tester is involved. Earlier and more continuous involvement is the direction of travel.$L$, $L$A streaming service releases a new recommendations algorithm. Shift-left has already done its work: reviews, unit tests and automated pipeline checks all passed. Now shift-right takes over — the change goes out as a **canary release** to 5% of users behind a **feature toggle**, while **monitoring** watches error rates and engagement. Real traffic surfaces a slowdown for users with very large watch histories, a case no pre-release test had data for. The team toggles the feature off instantly, fixes it, and re-releases. Shift-left prevented the predictable defects; shift-right caught the one only production could reveal.$L$, $L$- Treating shift-right as "testing in production instead of before release" — it complements pre-release testing, it doesn't replace it
- Assuming shift-right means letting users find bugs unmonitored — it depends on deliberate monitoring, canaries and toggles
- Exam trap: thinking the test levels disappear in modern models — component, integration, system and acceptance persist across all lifecycles$L$, $L$Shift-left and shift-right are two ends of the same idea: feedback everywhere. In a DevOps interview, being able to say "I'd prevent defects early with reviews and automation, and catch the rest in production with canary releases and monitoring" shows a complete, modern mental model.$L$, $L$Create a one-line summary for each of the four models (Waterfall, V-model, Agile, DevOps) stating where testing happens and how involved the tester is.$L$, $L$Why are shift-left and shift-right described as complementary rather than alternatives?$L$, $L$What does shift-right testing add that shift-left cannot provide? (Answer: feedback from real users and real production conditions after release — behaviour under genuine load and usage that pre-release testing cannot reproduce)$L$, array[$L$I can define shift-right and its main techniques$L$, $L$I can explain how testing changes across the four models$L$, $L$I can summarise how test levels map to each lifecycle$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'istqb-foundation-masterclass' and m.module_number = 2
on conflict (module_id, lesson_number) do nothing;

