-- ============================================================
-- API Testing Masterclass — Module 10 lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/api-module10.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 1, $L$Project Brief & Choosing Your API$L$, $L$45 minutes$L$, $L$This is your capstone. Over five sessions you'll build a complete, employer-ready API testing portfolio piece. It starts here: understanding the brief, choosing an API, and writing down the scope you'll be judged on.$L$, array[$L$Understand what the portfolio project must deliver$L$, $L$Choose a suitable API to test$L$, $L$Write a one-page project scope and set of test objectives$L$], $L$## What you are building
By the end of Module 10 you will have a single, coherent portfolio artefact: a documented Postman collection with environments, an automated test suite run through Newman, and an HTML report you can show a hiring manager. Everything you learned in Modules 1–9 comes together here.

## Choosing your API
Pick something you can actually hit and re-run:
- A free public API — `https://reqres.in`, `https://jsonplaceholder.typicode.com`, or the **restful-booker** hotel API (`https://restful-booker.herokuapp.com`), which has real auth and CRUD.
- Avoid APIs needing paid keys, card details, or a VPN.
- Prefer one with a **create-read-update-delete** flow — it gives you far richer tests.

## Write the scope first
Senior testers scope before they test. In a short document, capture:
- The API and its base URL
- Which endpoints are **in scope** (and which are out)
- Your **test objectives** (functional, negative, auth, schema)
- Any assumptions and risks

## Why this matters
A hiring manager doesn't just want to see requests fire. They want to see that you decided *what mattered* and *why* before touching a keyboard.$L$, $L$Choosing **restful-booker**: base URL `https://restful-booker.herokuapp.com`. In scope: `POST /auth` (token), `POST /booking` (create), `GET /booking/{id}` (read), `PUT /booking/{id}` (update), `DELETE /booking/{id}` (remove). Objectives: happy-path CRUD, an auth-required negative case (delete without token → 403), and schema validation on the booking response. Out of scope: performance and load. One page, written before any request is sent.$L$, $L$- Choosing an API that needs paid access or card details, then getting stuck
- Skipping the scope and diving straight into requests
- Picking a read-only API so there's no create/update/delete story to tell$L$, $L$The best portfolio APIs have a full CRUD lifecycle and real authentication. They let you demonstrate the whole toolbox — happy paths, negatives, auth, and data cleanup — in one coherent story.$L$, $L$Choose your API and write a one-page scope: base URL, in-scope endpoints, out-of-scope items, and three to five test objectives. Save it as `README.md` in a new project folder.$L$, $L$Why is deciding what NOT to test just as important as deciding what to test?$L$, $L$What single document should you produce before sending any request in this project? (Answer: a one-page scope / test objectives document)$L$, array[$L$I can explain what the portfolio project must deliver$L$, $L$I have chosen a suitable API with a CRUD flow$L$, $L$I have written a one-page scope and objectives$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 2, $L$Building the Collection & Environments$L$, $L$60 minutes$L$, $L$With scope agreed, you build the Postman collection that mirrors it — organised folders, parameterised requests, and environments so the same suite runs against different targets. This is the backbone of your portfolio.$L$, array[$L$Structure a Postman collection into logical folders$L$, $L$Use variables and environments instead of hard-coded values$L$, $L$Chain requests so created data flows into later calls$L$], $L$## Structure the collection
Mirror your scope. A clean layout tells a reviewer you think in systems:
- A folder per resource or flow (e.g. **Auth**, **Bookings**)
- Requests named as actions: `Create booking`, `Get booking by id`
- A short description on the collection explaining what it covers

## Never hard-code
Replace literals with variables (Module 6):
- `{{baseUrl}}` for the host
- `{{token}}` for auth
- `{{bookingId}}` for the id you created

## Environments do the heavy lifting
Create at least two environments — for example **Local/Dev** and **Public** — each defining `baseUrl`. The same collection now runs anywhere by switching the environment. That portability is exactly what CI needs in the next session.

## Chain your requests
Use a test script on **Create** to save the returned id:
`pm.environment.set('bookingId', pm.response.json().bookingid)`
Later requests use `{{bookingId}}` — so the suite creates, reads, updates and deletes the *same* record end to end.$L$, $L$In the **Auth** folder, `POST {{baseUrl}}/auth` returns a token; a script saves it: `pm.environment.set('token', pm.response.json().token)`. In **Bookings**, `POST {{baseUrl}}/booking` creates a record and saves `bookingid`. `GET {{baseUrl}}/booking/{{bookingId}}` then reads that exact record. Switching the environment from Public to Local changes only `baseUrl` — every request follows.$L$, $L$- Hard-coding the base URL and token into every request
- One giant flat list of requests with no folders or descriptions
- Not saving the created id, so read/update/delete point at the wrong record$L$, $L$A collection that runs against three environments by flipping one dropdown is worth ten collections that only work on the author's laptop. Portability is what makes a suite reusable — and reusable is what employers pay for.$L$, $L$Build your collection: folders per resource, every value parameterised with `{{variables}}`, and two environments defining `baseUrl`. Add a script that captures the created id into an environment variable and use it in a later request.$L$, $L$What breaks if you hard-code the base URL instead of using an environment variable?$L$, $L$What Postman feature lets one collection run against dev and production without editing requests? (Answer: environments / environment variables)$L$, array[$L$I have organised the collection into logical folders$L$, $L$I have replaced hard-coded values with variables$L$, $L$I have at least two environments$L$, $L$A created id flows into later requests$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 3, $L$Designing & Automating the Test Suite$L$, $L$75 minutes$L$, $L$Requests that only return data aren't tests. Now you add assertions — status, body, schema and negative cases — turning your collection into an automated suite that passes or fails on its own.$L$, array[$L$Write meaningful assertions for status, body and schema$L$, $L$Add negative and authorisation test cases$L$, $L$Cover the full CRUD lifecycle with independent, repeatable tests$L$], $L$## Assert more than the status
A test that only checks `200` misses wrong data (Module 2). For each request assert:
- The **status code** you expect
- Key **body fields** and their values
- The **response schema** where it matters

```js
pm.test('status is 200', () => pm.response.to.have.status(200));
pm.test('has bookingid', () => {
  pm.expect(pm.response.json()).to.have.property('bookingid');
});
```

## Schema validation
Use `pm.response.to.have.jsonSchema(schema)` (Module 5) so the *shape* of the response is guaranteed, not just one field.

## Don't forget the negatives
Portfolios that only show happy paths look junior. Add:
- Auth required: `DELETE` without a token → **403**
- Not found: `GET /booking/999999` → **404**
- Bad input: `POST` with a missing field → **400** (or documented behaviour)

## Make it repeatable
Each run should create its own data and delete it at the end, so the suite is **independent** and leaves nothing behind. That's what lets it run unattended in CI.$L$, $L$On `POST /booking`: assert `200`, assert the body has `bookingid` (number) and `booking.firstname` equals what you sent, then validate against a JSON schema for the booking object. Add a negative test: `DELETE /booking/{{bookingId}}` with no `Authorization` header asserts `403`. The final happy-path delete (with token) asserts `201`/`200` and confirms a follow-up `GET` returns `404` — proving the record is gone.$L$, $L$- Asserting only the status code and never the body or schema
- A suite with zero negative or auth-failure tests
- Tests that depend on data left over from a previous run, so they fail on a clean machine$L$, $L$Negative and authorisation tests are what separate a portfolio that says "I can send requests" from one that says "I think like a tester". Reviewers look for them first.$L$, $L$Add assertions to every request: status, at least one body field, and a schema check on your main resource. Add at least two negative tests (an auth failure and a not-found). Confirm the whole collection passes when run top to bottom.$L$, $L$Why must each test set up and clean up its own data rather than relying on the previous test?$L$, $L$Beyond the status code, name two things a good API test should assert. (Answer: body field values and the response schema)$L$, array[$L$I assert status, body and schema$L$, $L$I have at least two negative / auth tests$L$, $L$The suite covers full CRUD$L$, $L$It runs cleanly top to bottom and leaves no data behind$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 4, $L$Reporting & Documentation$L$, $L$60 minutes$L$, $L$A test suite nobody can read is a test suite nobody trusts. You'll run your collection through Newman on the command line, generate a shareable HTML report, and write the documentation that turns a folder of files into a portfolio piece.$L$, array[$L$Run a collection headlessly with Newman$L$, $L$Generate a clean HTML report a non-tester can read$L$, $L$Document the suite so anyone can run it$L$], $L$## Run it with Newman
Newman (Module 8) runs your collection from the command line — no clicking. Point it at the exported collection and environment:
```bash
newman run collection.json -e public.postman_environment.json
```
Green output means every assertion passed, headlessly.

## Generate a shareable report
Install the HTML reporter and produce a file a manager can open in a browser:
```bash
npm i -g newman-reporter-htmlextra
newman run collection.json -e public.postman_environment.json \
  -r htmlextra --reporter-htmlextra-export report.html
```
The report shows pass/fail counts, timings and each assertion — no Postman needed to read it.

## Document so anyone can run it
Update your `README.md` with:
- **Prerequisites** (Node, Newman, the htmlextra reporter)
- **How to run** (the exact commands, copy-pasteable)
- **What it tests** (the objectives from Session 1)
- **A screenshot** of the passing report

## Why documentation is the multiplier
Good docs turn "my project" into "our project". A reviewer who can clone and run your suite in two minutes rates it far higher than one who can't get past step one.$L$, $L$From the project folder: `newman run collection.json -e public.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export report.html`. The terminal prints a summary table (iterations, requests, assertions, failures = 0); `report.html` opens in any browser showing every request, its assertions, and response times. You add a screenshot of the green report to the README under "Results".$L$, $L$- Only ever running in the Postman GUI, so there's no headless proof it works
- Committing a report but no instructions on how to reproduce it
- A README that assumes the reader already has Newman and the reporter installed$L$, $L$Write the README as if the reader has never seen your project and has two minutes. If they can clone it, run one command, and see a green report, you've demonstrated more professionalism than most senior testers manage.$L$, $L$Install Newman and the htmlextra reporter, run your collection headlessly, and generate `report.html`. Then write a README section with copy-pasteable run instructions and a screenshot of the passing report.$L$, $L$Why does running through Newman prove something that running only in the Postman GUI does not?$L$, $L$Which command-line tool runs a Postman collection headlessly for CI and reporting? (Answer: Newman)$L$, array[$L$I can run my collection with Newman$L$, $L$I generate a readable HTML report$L$, $L$My README lets anyone reproduce the run$L$, $L$The report shows all assertions passing$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, 5, $L$Publishing Your API Testing Portfolio$L$, $L$45 minutes$L$, $L$Everything comes together. You publish the project to a public repository, write it up so a hiring manager instantly understands its value, and learn how they'll actually assess it. This is the artefact you'll link to on your CV and in interviews.$L$, array[$L$Publish the project to a public Git repository$L$, $L$Write a portfolio-ready README that sells the work$L$, $L$Understand how a hiring manager assesses the finished piece$L$], $L$## Publish it
Put the whole project on GitHub (public):
- `README.md`, `collection.json`, environment files, `schemas/`, `report.html`, screenshot
- A sensible `.gitignore` (no `node_modules`, no secrets)
- **Never commit real tokens or keys** — use placeholder environment values

## Write the README to sell it
Lead with value, not mechanics. Cover, in order:
1. **What this is** — one line: "An automated API test suite for the restful-booker API."
2. **What it demonstrates** — CRUD, auth, negatives, schema validation, Newman/CI.
3. **How to run it** — the copy-pasteable commands from Session 4.
4. **Results** — the screenshot of the green report.

## See it as they will
A hiring manager skims for signal: is it real, does it run, and does the author *think*? Structure, negative tests, and clear docs are the signals. A wall of `status === 200` is noise.

## The finish line
When this is live and linked on your CV, you have something 90% of applicants don't: proof, not claims. That is the entire point of a portfolio.$L$, $L$You push the folder to `github.com/yourname/api-testing-portfolio`. The README opens with "Automated API test suite for restful-booker — CRUD, auth, negative and schema tests, run via Newman with an HTML report." A reviewer reads it in 90 seconds, runs `newman run …`, sees the green report, and has concrete evidence you can scope, build, automate and document API tests. You link that repo from your CV under "Projects".$L$, $L$- Committing real API tokens or a `.env` with secrets to a public repo
- A README that explains *how* it's built but never *why it's worth looking at*
- Leaving `node_modules` and clutter in the repo so the signal is buried$L$, $L$Recruiters and managers spend under two minutes on a portfolio link. The first paragraph of your README does 80% of the work — make it say what the project is and what it proves, before any setup detail.$L$, $L$Publish your project to a public GitHub repo with a portfolio-ready README (what it is, what it demonstrates, how to run, results screenshot). Add the repo link to your CV or LinkedIn. Confirm the repo contains no secrets.$L$, $L$If a manager only reads the first paragraph of your README, what must it convey?$L$, $L$What must you never commit to a public portfolio repository? (Answer: real tokens, keys or secrets)$L$, array[$L$I have published the project to a public repo$L$, $L$My README sells the work in its first paragraph$L$, $L$The repo contains no secrets$L$, $L$The link is on my CV / LinkedIn$L$]
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'api-testing-masterclass' and m.module_number = 10
on conflict (module_id, lesson_number) do nothing;

