-- ============================================================
-- Lesson enhancements for "modern-test-automation-bootcamp" Module 2.
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/modern-automation-module2.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================

update public.lessons l set enhancements = $ench${"industryStory":"A team ran their end-to-end suite in plain JavaScript for two years. A fixture field was quietly renamed in one PR, and because nothing checked property names, a dozen tests kept passing while asserting against undefined values. The gap was only noticed when a real regression slipped to production. After migrating the suite to TypeScript, the same class of rename produced an immediate compile error listing every affected test.","badGood":{"label":"Silencing the compiler versus using it","bad":"// Reaches for 'any' the moment a type is inconvenient\nfunction submit(form: any) {\n  return form.feilds.map((f: any) => f.value); // typo survives\n}","good":"interface Field { value: string; }\ninterface Form { fields: Field[]; }\n\nfunction submit(form: Form) {\n  return form.fields.map((f) => f.value); // typo would be caught\n}"},"davidTip":"Adopt TypeScript at the boundary first: type your fixtures and page objects, where a wrong shape does the most damage. You do not need to type every line on day one to get most of the benefit."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'modern-test-automation-bootcamp'
  and m.module_number = 2 and l.lesson_number = 1;

update public.lessons l set enhancements = $ench${"visualAid":{"type":"comparison","title":"Annotate or infer?","headers":["Situation","What to do","Why"],"rows":[["const with a literal value","Let TypeScript infer","The value already makes the type obvious"],["Function parameter","Annotate","There is no value to infer the type from"],["One of a fixed set of strings","Annotate with a union","Constrains to the valid menu; catches typos"],["Empty array to be filled later","Annotate the element type","An empty [] infers as never[] and blocks pushes"]]},"davidTip":"A good heuristic: if deleting the type annotation would leave the compiler equally sure of the type, delete it. Keep annotations that genuinely add information, especially unions."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'modern-test-automation-bootcamp'
  and m.module_number = 2 and l.lesson_number = 2;

update public.lessons l set enhancements = $ench${"badGood":{"label":"Positional flags versus an options object","bad":"async function open(page: Page, name: string, wait?: number, force?: boolean, exact?: boolean) {\n  // callers must pass open(page, 'Menu', undefined, true) — what is 'true'?\n}","good":"interface OpenOptions { wait?: number; force?: boolean; exact?: boolean; }\n\nasync function open(page: Page, name: string, options: OpenOptions = {}) {\n  // callers write open(page, 'Menu', { force: true }) — self-documenting\n}"},"miniChallenge":"Refactor a helper of your own that has more than three positional parameters into one that takes a page plus a single typed options object with sensible defaults."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'modern-test-automation-bootcamp'
  and m.module_number = 2 and l.lesson_number = 3;

update public.lessons l set enhancements = $ench${"industryStory":"A suite shared a single user fixture object across many tests to save setup time. One test mutated a field on that object mid-run, and every test that happened to run afterwards inherited the change. The failures moved around depending on run order, which made them nearly impossible to reproduce. Declaring the fixture type with readonly fields turned the offending mutation into a compile error and the flakiness disappeared.","davidTip":"Treat your fixture type definitions as a product artefact, not throwaway test plumbing. When they mirror the real domain model, updating them when the product changes becomes a guided task rather than a hunt.","visualAid":{"type":"comparison","title":"interface versus type alias","headers":["Aspect","interface","type"],"rows":[["Object shapes","Yes, idiomatic","Yes, also fine"],["Unions (a | b | c)","No","Yes"],["Naming a primitive","No","Yes (type Id = number)"],["Common convention","Fixtures and object contracts","Unions and aliases"]]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'modern-test-automation-bootcamp'
  and m.module_number = 2 and l.lesson_number = 4;

update public.lessons l set enhancements = $ench${"badGood":{"label":"Manual loop versus a collection method","bad":"let allPriced = true;\nfor (const r of rows) {\n  if (r.priceInPence <= 0) { allPriced = false; break; }\n}\nexpect(allPriced).toBe(true);","good":"expect(rows.every((r) => r.priceInPence > 0)).toBe(true);"},"miniChallenge":"Take a list assertion in your suite that uses a manual loop and a boolean flag, and rewrite it as a single some or every expression. Check it still reads clearly to someone who did not write it."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'modern-test-automation-bootcamp'
  and m.module_number = 2 and l.lesson_number = 5;

update public.lessons l set enhancements = $ench${"industryStory":"A suite had one assertion missing its await. The test was green for months and everyone trusted it, until a regression broke exactly the behaviour that assertion was meant to guard — and the test stayed green through the whole incident. The fix was one keyword, but the lesson stuck: the team turned on lint rules for floating promises so the compiler would never let it recur.","badGood":{"label":"Awaiting in a loop","bad":"// forEach ignores the returned promises — nothing is actually awaited\nitems.forEach(async (item) => {\n  await page.getByText(item).click();\n});","good":"// for...of awaits each iteration before the next\nfor (const item of items) {\n  await page.getByText(item).click();\n}"},"visualAid":{"type":"flow","title":"What happens to a forgotten await","steps":[{"label":"You call an action without await","detail":"page.click() returns a promise that is never awaited"},{"label":"Code races ahead","detail":"The next line runs before the click has completed"},{"label":"Order is not guaranteed","detail":"Sometimes it works, sometimes it does not — flakiness"},{"label":"On an assertion, worse","detail":"The check never resolves, so the test can pass regardless of state"}]}}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'modern-test-automation-bootcamp'
  and m.module_number = 2 and l.lesson_number = 6;

update public.lessons l set enhancements = $ench${"badGood":{"label":"Logic in the spec versus a shared helper","bad":"// tests/checkout.spec.ts — login steps copy-pasted into every spec\ntest('checkout', async ({ page }) => {\n  await page.goto('/login');\n  await page.getByLabel('Username').fill('ada');\n  await page.getByLabel('Password').fill('correct-horse');\n  await page.getByRole('button', { name: 'Sign in' }).click();\n  // ... the actual checkout test\n});","good":"// tests/checkout.spec.ts — one shared, typed helper\nimport { login } from '../helpers/login';\n\ntest('checkout', async ({ page }) => {\n  await login(page, admin);\n  // ... the actual checkout test\n});"},"davidTip":"Decide the folder structure and export style on day one and write it into the repo README. It is far cheaper to agree the shape of the repo before there are two hundred specs than to reorganise after.","miniChallenge":"Add path aliases to your tsconfig (for example @helpers/* and @fixtures/*) and update one import to use them. Confirm both the editor and tsc --noEmit still resolve the import."}$ench$::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = 'modern-test-automation-bootcamp'
  and m.module_number = 2 and l.lesson_number = 7;

