// 90-Day Roadmap — Resource Pack, batch 1 (templates + a checklist).
const COURSE = '90-Day Software Testing Career Roadmap';

export default [
  {
    slug: 'test-case-template',
    title: 'Test Case Template',
    subtitle: 'A professional, reusable format for writing clear, runnable test cases.',
    courseTitle: COURSE,
    category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A test case describes exactly how to verify one behaviour, so anyone can run it and get the same result. Well-written test cases are repeatable, specific, and independent. This template gives you a consistent structure you can reuse for every feature.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Give each test case a unique ID and a clear, descriptive title.',
        'State the preconditions and the exact test data needed.',
        'Write numbered, unambiguous steps — no assumed knowledge.',
        'Define a specific, verifiable expected result.',
        'Keep each test case independent of others and focused on one behaviour.',
      ] },
      { t: 'h1', text: 'Real QA Example' },
      { t: 'table', headers: ['Field', 'Example'], rows: [
        ['Test Case ID', 'TC-LOGIN-002'],
        ['Title', 'Login fails with an incorrect password'],
        ['Preconditions', 'A registered, active user account exists'],
        ['Test Data', 'Email: valid@example.com · Password: WrongPass1'],
        ['Steps', '1. Go to /login  2. Enter the valid email  3. Enter the wrong password  4. Click Log in'],
        ['Expected Result', 'Error "Incorrect email or password" is shown; the user remains logged out'],
        ['Priority', 'High'],
        ['Status', 'Pass / Fail'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'table', headers: ['Field', 'Detail'], rows: [
        ['Test Case ID', ''], ['Title', ''], ['Module / Feature', ''], ['Preconditions', ''],
        ['Test Data', ''], ['Steps', '1.\n2.\n3.'], ['Expected Result', ''], ['Priority', 'High / Medium / Low'],
        ['Actual Result', ''], ['Status', 'Pass / Fail'], ['Notes', ''],
      ] },
      { t: 'h1', text: 'Best Practice Tips' },
      { t: 'ul', items: [
        'Use test-design techniques (equivalence partitioning, boundary value analysis) to choose strong inputs.',
        'Write the expected result as something observable and specific.',
        'One test case = one behaviour. Split anything that checks several things.',
        'Include negative and boundary cases, not just the happy path.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Vague expected results such as "it works".',
        'Steps that assume knowledge ("log in as usual").',
        'One giant test case verifying ten unrelated things.',
        'Test cases that depend on a previous test having run first.',
      ] },
      { t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text: 'Your test cases are portfolio gold. A small set of clear, professional test cases shared in an interview proves your skill better than any certificate.' },
    ],
  },

  {
    slug: 'test-scenario-template',
    title: 'Test Scenario Template',
    subtitle: 'Capture high-level test scenarios before drilling into detailed cases.',
    courseTitle: COURSE,
    category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A test scenario is a high-level description of what to test ("verify the checkout flow"), while a test case is the detailed steps for one check. Scenarios help you map coverage quickly before writing detailed cases.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'List scenarios per feature or user journey.',
        'Tie each scenario to a requirement or acceptance criterion.',
        'Rate each by risk so you know where to focus detailed test cases.',
        'Expand high-risk scenarios into detailed test cases.',
      ] },
      { t: 'h1', text: 'Real QA Example' },
      { t: 'table', headers: ['Scenario ID', 'Scenario', 'Linked Requirement', 'Risk'], rows: [
        ['SC-CO-01', 'Verify a successful checkout with a valid card', 'REQ-CO-1', 'High'],
        ['SC-CO-02', 'Verify checkout is blocked with an expired card', 'REQ-CO-3', 'High'],
        ['SC-CO-03', 'Verify discount code is applied correctly', 'REQ-CO-5', 'Medium'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'table', headers: ['Scenario ID', 'Scenario', 'Linked Requirement', 'Risk', 'Detailed cases?'], rows: [
        ['', '', '', 'High / Med / Low', 'Y / N'],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
      ] },
      { t: 'h1', text: 'Best Practice Tips' },
      { t: 'ul', items: [
        'Keep scenarios outcome-focused and concise.',
        'Use risk to decide which scenarios get the most detailed cases.',
        'Map scenarios back to requirements to expose coverage gaps.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Writing detailed steps at the scenario level (that belongs in the test case).',
        'Only listing happy-path scenarios.',
        'No link to requirements, so coverage is guesswork.',
      ] },
      { t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text: 'Scenarios first, cases second. A risk-rated scenario list lets you justify exactly where you invested your testing time — a powerful thing to show a hiring manager.' },
    ],
  },

  {
    slug: 'bug-report-template',
    title: 'Bug Report Template',
    subtitle: 'Report defects so clearly they can be reproduced and fixed without a single follow-up question.',
    courseTitle: COURSE,
    category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A great bug report gets fixed fast because the developer can reproduce it from your report alone. This template captures everything needed: environment, steps, expected vs actual, severity, priority and attachments.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Write a concise title: what is wrong and where.',
        'Record the environment (browser/device/build/URL).',
        'List numbered, exact reproduction steps.',
        'State the expected result and the actual result separately.',
        'Set severity (technical impact) and priority (business urgency).',
        'Attach evidence (screenshot, video, logs).',
      ] },
      { t: 'h1', text: 'Real QA Example' },
      { t: 'table', headers: ['Field', 'Example'], rows: [
        ['Title', 'Checkout — Apply Coupon button does nothing on mobile (build 1.4.2)'],
        ['Environment', 'iPhone 13, Safari, build 1.4.2, /checkout'],
        ['Preconditions', 'Item in cart; coupon SAVE10 is valid'],
        ['Steps to Reproduce', '1. Add item to cart  2. Open cart on mobile Safari  3. Enter SAVE10  4. Tap Apply'],
        ['Expected Result', '10% discount is applied and shown in the total'],
        ['Actual Result', 'Nothing happens; no discount, no error message'],
        ['Severity', 'Major'],
        ['Priority', 'High'],
        ['Attachments', 'screen-recording.mp4'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'table', headers: ['Field', 'Detail'], rows: [
        ['Title', ''], ['Environment', ''], ['Preconditions', ''], ['Steps to Reproduce', '1.\n2.\n3.'],
        ['Expected Result', ''], ['Actual Result', ''], ['Severity', 'Critical / Major / Minor / Trivial'],
        ['Priority', 'High / Medium / Low'], ['Attachments', ''], ['Notes', ''],
      ] },
      { t: 'h1', text: 'Best Practice Tips' },
      { t: 'ul', items: [
        'If a developer cannot reproduce it from your report alone, it is not finished.',
        'Keep severity and priority separate — they are different things.',
        'Reduce to the minimum steps that reliably trigger the bug.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Titles like "it is broken" or "checkout bug".',
        'Missing environment or build number.',
        'No expected vs actual, leaving the developer to guess your intent.',
      ] },
      { t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text: 'Consistent, complete bug reports build your reputation faster than the number of bugs you find. Keep this template to hand and use it every time.' },
    ],
  },

  {
    slug: 'test-plan-template',
    title: 'Test Plan Template',
    subtitle: 'A concise, professional plan covering scope, approach, risks and exit criteria.',
    courseTitle: COURSE,
    category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A test plan sets out what you will test, how, by when, and what "done" means. It keeps the team aligned and protects you from scope and timeline disputes later.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Define scope: what is in and explicitly out.',
        'Describe the test approach and the levels/types of testing.',
        'Capture entry and exit criteria so "done" is unambiguous.',
        'List risks and how you will mitigate them.',
      ] },
      { t: 'h1', text: 'Real QA Example (extract)' },
      { t: 'table', headers: ['Section', 'Example content'], rows: [
        ['Scope (in)', 'Checkout, payment, order confirmation'],
        ['Scope (out)', 'Admin reporting (unchanged this release)'],
        ['Approach', 'Risk-based manual testing + API checks + regression of impacted areas'],
        ['Entry criteria', 'Build deployed to test; smoke test passes'],
        ['Exit criteria', 'All high-priority cases run; no open critical defects; regression passed'],
        ['Key risk', 'Payment integration changes — mitigation: deep test of payment paths'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: [
        '1. Overview & objectives',
        '2. Scope (in / out)',
        '3. Test approach (levels, types, tools)',
        '4. Environment & test data',
        '5. Entry criteria',
        '6. Exit criteria',
        '7. Risks & mitigations',
        '8. Schedule & responsibilities',
        '9. Deliverables',
      ] },
      { t: 'h1', text: 'Best Practice Tips' },
      { t: 'ul', items: [
        'Keep it as short as it can be while still useful — a plan nobody reads helps no one.',
        'Agree entry/exit criteria in writing, early.',
        'Tie the approach to risk, not to "test everything".',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'No clear exit criteria, so testing "finishes" when time runs out.',
        'Scope with no explicit out-of-scope list.',
        'Risks listed but never mitigated or revisited.',
      ] },
      { t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text: 'Clear entry/exit criteria are your best defence against being blamed for a rushed release. Put them in the plan and get sign-off.' },
    ],
  },

  {
    slug: 'regression-testing-checklist',
    title: 'Regression Testing Checklist',
    subtitle: 'Protect existing features after every change with a risk-based regression pass.',
    courseTitle: COURSE,
    category: 'Checklists',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Regression testing confirms that recent changes have not broken existing functionality. As a product grows you cannot re-test everything every time, so regression must be risk-based and focused on what the change could affect.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Identify what changed and which areas it could impact.',
        'Prioritise regression by risk and business impact.',
        'Always include the core critical paths (login, checkout, key journeys).',
        'Record results and raise any new defects.',
      ] },
      { t: 'h1', text: 'Real QA Example' },
      { t: 'p', text: 'A change to the discount engine could affect the cart, checkout totals, and tax. The regression pass therefore focuses there first, plus the always-run critical paths, rather than re-testing the whole application.' },
      { t: 'h1', text: 'Regression Checklist' },
      { t: 'ul', items: [
        'Core critical paths verified (login, checkout, primary journeys)',
        'Areas directly impacted by the change tested',
        'Adjacent/integrated areas checked',
        'Previously failed/fixed defects re-verified',
        'Cross-browser / device checks where relevant',
        'Key API endpoints validated',
        'Results recorded; new defects raised',
        'Sign-off against exit criteria',
      ] },
      { t: 'h1', text: 'Best Practice Tips' },
      { t: 'ul', items: [
        'Automate stable, high-value regression checks so they run every release.',
        'Use change-impact analysis to scope the pass.',
        'Keep a living core-regression suite for the critical journeys.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Re-testing everything (slow) or testing only the change (risky).',
        'Skipping regression under deadline pressure.',
        'Not re-verifying previously fixed defects.',
      ] },
      { t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text: 'Risk-based regression beats "run it all". Being able to explain what you focused on and why is exactly the judgement employers hire for.' },
    ],
  },
];
