// 90-Day Roadmap — Resource Pack, batch 3 (glossary + guides/cheat sheets).
const COURSE = '90-Day Software Testing Career Roadmap';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

const GLOSSARY = [
  ['Acceptance Criteria', 'Conditions a feature must meet to be accepted; the basis for tests.'],
  ['Ad-hoc Testing', 'Informal testing with no formal plan, relying on tester intuition.'],
  ['Agile', 'Iterative delivery approach with continuous testing and feedback.'],
  ['Alpha Testing', 'Early testing by internal staff before external release.'],
  ['API', 'Interface allowing systems to communicate; tested below the UI.'],
  ['API Testing', 'Validating requests, responses, status codes and data at the API layer.'],
  ['Assertion', 'A check in a test that confirms an expected outcome.'],
  ['Automation Testing', 'Using scripts/tools to execute tests automatically.'],
  ['Backlog', 'Prioritised list of work (stories, tasks, bugs) to be done.'],
  ['Baseline', 'An agreed reference version used for comparison.'],
  ['Beta Testing', 'Testing by real users before full release.'],
  ['Black Box Testing', 'Testing functionality without knowledge of internal code.'],
  ['Boundary Value Analysis', 'Testing at the edges of input ranges where bugs cluster.'],
  ['Bug', 'A defect; behaviour that differs from what is expected.'],
  ['Bug Report', 'A structured record of a defect enabling reproduction and fix.'],
  ['Build', 'A compiled, deployable version of the software.'],
  ['CI/CD', 'Continuous Integration/Delivery; automated build, test and deploy.'],
  ['Compatibility Testing', 'Checking behaviour across browsers, devices and OSes.'],
  ['Coverage', 'How much of the requirements/code/risk the tests address.'],
  ['Defect', 'A flaw in the software causing incorrect behaviour.'],
  ['Defect Density', 'Number of defects relative to size (e.g. per module).'],
  ['Defect Lifecycle', 'The states a defect moves through from new to closed.'],
  ['Defect Leakage', 'Defects that escape a phase and are found later.'],
  ['Deployment', 'Releasing a build into an environment.'],
  ['Dynamic Testing', 'Testing by executing the software.'],
  ['End-to-End Testing', 'Testing a complete workflow across the whole system.'],
  ['Entry Criteria', 'Conditions required before a test phase can start.'],
  ['Environment', 'A configured system (dev/test/staging/prod) to run software.'],
  ['Equivalence Partitioning', 'Grouping inputs that should behave the same and testing one per group.'],
  ['Exit Criteria', 'Conditions that must be met to consider testing done.'],
  ['Exploratory Testing', 'Simultaneous learning, test design and execution.'],
  ['Functional Testing', 'Verifying the software does what it should.'],
  ['Gherkin', 'A readable Given/When/Then syntax for BDD scenarios.'],
  ['Happy Path', 'The default, successful flow through a feature.'],
  ['Hotfix', 'An urgent fix applied directly to production.'],
  ['Integration Testing', 'Testing that components work together correctly.'],
  ['Issue', 'A general term for a problem, often tracked in a tool.'],
  ['Jira', 'A popular tool for tracking work and defects.'],
  ['Load Testing', 'Checking behaviour under expected load.'],
  ['Manual Testing', 'Testing performed by a person without automation.'],
  ['Mock', 'A simulated component used in place of a real dependency.'],
  ['Negative Testing', 'Testing with invalid input to confirm correct handling.'],
  ['Non-Functional Testing', 'Testing qualities like performance, security, usability.'],
  ['Performance Testing', 'Assessing speed, responsiveness and stability under load.'],
  ['Postman', 'A widely used tool for manual and automated API testing.'],
  ['Priority', 'How soon a defect should be fixed (business urgency).'],
  ['Production', 'The live environment used by real users.'],
  ['Regression Testing', 'Confirming existing features still work after a change.'],
  ['Release', 'A version of software made available to users.'],
  ['Requirement', 'A statement of what the software should do.'],
  ['Retesting', 'Verifying that a specific fixed defect is now resolved.'],
  ['Risk-Based Testing', 'Focusing testing effort on the highest-risk areas.'],
  ['RTM', 'Requirements Traceability Matrix mapping requirements to tests.'],
  ['Sanity Testing', 'A focused check on a specific area after a change.'],
  ['Scrum', 'An agile framework with sprints, roles and ceremonies.'],
  ['Severity', 'The technical impact of a defect.'],
  ['Smoke Testing', 'A quick check that a build is stable enough to test.'],
  ['SDLC', 'Software Development Life Cycle; how software is built.'],
  ['STLC', 'Software Testing Life Cycle; the testing process.'],
  ['Sprint', 'A fixed, short iteration in Scrum (often 1–2 weeks).'],
  ['Stakeholder', 'Anyone with an interest in the product or project.'],
  ['Static Testing', 'Reviewing artefacts without executing the software.'],
  ['Stress Testing', 'Testing beyond normal load to find breaking points.'],
  ['System Testing', 'Testing the complete, integrated application.'],
  ['Test Case', 'Detailed steps and expected result for one check.'],
  ['Test Data', 'The inputs used to execute tests.'],
  ['Test Environment', 'The setup in which testing is carried out.'],
  ['Test Execution', 'Running tests and recording results.'],
  ['Test Plan', 'A document defining scope, approach, schedule and criteria.'],
  ['Test Scenario', 'A high-level description of what to test.'],
  ['Test Strategy', 'The high-level, long-lived approach to quality.'],
  ['Test Suite', 'A collection of related test cases.'],
  ['Traceability', 'The ability to link requirements, tests and defects.'],
  ['UAT', 'User Acceptance Testing; users confirm fitness for purpose.'],
  ['Usability Testing', 'Assessing how easy the product is to use.'],
  ['Use Case', 'A description of how a user achieves a goal with the system.'],
  ['User Story', 'A short requirement from the user perspective.'],
  ['Validation', 'Confirming the product meets the user’s real need.'],
  ['Verification', 'Confirming the product meets its specification.'],
  ['Version Control', 'Tracking changes to code (e.g. Git).'],
  ['Waterfall', 'A sequential development approach with distinct phases.'],
  ['White Box Testing', 'Testing with knowledge of internal code/structure.'],
  ['Workaround', 'A temporary way around a defect until it is fixed.'],
  ['Acceptance Testing', 'Confirming the system meets acceptance criteria.'],
  ['Bug Triage', 'Reviewing defects to decide priority and ownership.'],
  ['Checklist', 'A list used to ensure consistent coverage of steps.'],
  ['Defect Report', 'See Bug Report; a documented defect.'],
  ['Edge Case', 'An unusual input or condition at the limits of behaviour.'],
  ['Flaky Test', 'A test that passes and fails inconsistently.'],
  ['Mind Map', 'A visual way to brainstorm test ideas.'],
  ['Page Object Model', 'An automation pattern that encapsulates page interactions.'],
  ['Pair Testing', 'Two people testing together to share insight.'],
  ['Quality Assurance', 'Processes that prevent defects and improve quality.'],
  ['Quality Control', 'Activities that detect defects in the product.'],
  ['Root Cause Analysis', 'Investigating the underlying cause of a defect.'],
  ['Selector / Locator', 'How an automated test finds a UI element.'],
  ['Test Charter', 'A focused mission for an exploratory session.'],
  ['Test Coverage', 'A measure of how much is exercised by tests.'],
  ['Test Harness', 'The setup enabling automated test execution.'],
  ['Defect Age', 'How long a defect has been open.'],
  ['Shift Left', 'Involving testing earlier in the lifecycle.'],
];

export default [
  {
    slug: 'software-testing-glossary',
    title: 'Software Testing Glossary',
    subtitle: '100+ essential QA terms explained simply — your quick-reference companion.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'This glossary defines the QA terms you will hear daily on the job and in interviews. Each definition is deliberately plain-English so you can learn fast and explain concepts clearly to others.' },
      { t: 'h1', text: 'How to Use It' },
      { t: 'ul', items: [
        'Skim it early to build vocabulary; revisit before interviews.',
        'When you meet a new term at work, find it here and use it correctly.',
        'Being able to define these clearly is a fast way to sound experienced.',
      ] },
      { t: 'h1', text: 'Glossary' },
      { t: 'table', headers: ['Term', 'Meaning'], rows: GLOSSARY },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Confusing verification with validation, or severity with priority.',
        'Mixing up regression and retesting.',
        'Using terms loosely — precise language signals professionalism.',
      ] },
      proTip('Pick five terms a day and practise explaining each in one sentence. Clear definitions are interview gold and build everyday credibility.'),
    ],
  },

  {
    slug: 'risk-assessment-matrix',
    title: 'Risk Assessment Matrix',
    subtitle: 'Prioritise testing by rating likelihood against impact.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A risk assessment matrix helps you focus testing where it matters by rating each risk on likelihood (how probable) and impact (how damaging). High-likelihood, high-impact risks get the deepest testing.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'List the risks for the feature or release.',
        'Rate each: Likelihood (Low/Medium/High) and Impact (Low/Medium/High).',
        'Combine to a rating and focus effort on the highest.',
      ] },
      { t: 'h1', text: 'The Matrix' },
      { t: 'table', headers: ['Likelihood \\ Impact', 'Low', 'Medium', 'High'], rows: [
        ['High', 'Medium', 'High', 'Critical'],
        ['Medium', 'Low', 'Medium', 'High'],
        ['Low', 'Low', 'Low', 'Medium'],
      ] },
      { t: 'h1', text: 'Real QA Example' },
      { t: 'table', headers: ['Risk', 'Likelihood', 'Impact', 'Rating'], rows: [
        ['Payment double-charge', 'Medium', 'High', 'High'],
        ['Minor label misalignment', 'High', 'Low', 'Medium'],
        ['Data loss on save', 'Low', 'High', 'Medium'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'table', headers: ['Risk', 'Likelihood', 'Impact', 'Rating', 'Test focus'], rows: [
        ['', 'L/M/H', 'L/M/H', '', ''], ['', '', '', '', ''], ['', '', '', '', ''],
      ] },
      { t: 'h1', text: 'Best Practice Tips' },
      { t: 'ul', items: [
        'Rate with the team and stakeholders — risk is a shared judgement.',
        'Re-assess as the product and context change.',
        'Use the ratings to justify where you spend testing time.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Rating everything "high".',
        'Assessing once and never revisiting.',
        'Not linking the rating to actual test effort.',
      ] },
      proTip('A risk matrix turns "I tested a lot" into "I focused on the biggest risks, and here is why" — exactly the judgement employers pay for.'),
    ],
  },

  {
    slug: 'defect-severity-vs-priority-guide',
    title: 'Defect Severity vs Priority Guide',
    subtitle: 'Tell these two apart with confidence — and explain them in interviews.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Severity is the technical impact of a defect; priority is how soon the business wants it fixed. They are independent, and confusing them leads to the wrong bugs being fixed first.' },
      { t: 'h1', text: 'Definitions' },
      { t: 'ul', items: [
        'Severity: how badly it breaks things (crash, data loss vs cosmetic).',
        'Priority: how urgently the business needs it fixed.',
      ] },
      { t: 'h1', text: 'The Four Combinations' },
      { t: 'table', headers: ['Combination', 'Example'], rows: [
        ['High severity, High priority', 'Checkout crashes for all users — fix now.'],
        ['High severity, Low priority', 'Rare crash on an unused admin screen.'],
        ['Low severity, High priority', 'Company name misspelled on the homepage.'],
        ['Low severity, Low priority', 'Minor padding issue on a rarely seen page.'],
      ] },
      { t: 'h1', text: 'Best Practice Tips' },
      { t: 'ul', items: [
        'Set severity from technical impact; agree priority with the business.',
        'Always be ready with a mismatch example (low severity, high priority).',
        'Keep the two as separate fields in your tracker.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Treating severity and priority as the same thing.',
        'Marking everything critical.',
        'Setting priority without business input.',
      ] },
      proTip('"A homepage typo is low severity but high priority" is the single best line to nail this interview question — memorise it.'),
    ],
  },

  {
    slug: 'sdlc-cheat-sheet',
    title: 'SDLC Cheat Sheet',
    subtitle: 'The Software Development Life Cycle at a glance — and where testing fits.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'The SDLC is the process of building software from idea to live product. Testing belongs in every phase, not just at the end.' },
      { t: 'h1', text: 'The Phases' },
      { t: 'table', headers: ['Phase', 'What happens', 'Tester contribution'], rows: [
        ['Requirements', 'Define what to build and why', 'Review for clarity, gaps, testability'],
        ['Design', 'Decide how it will work', 'Ask "how will we test this?"'],
        ['Development', 'Build the software', 'Unit/component checks; early collaboration'],
        ['Testing', 'Verify the software', 'System, integration, regression testing'],
        ['Deployment', 'Release to environments', 'Smoke test; release readiness'],
        ['Maintenance', 'Support and improve', 'Re-test fixes; guard against regressions'],
      ] },
      { t: 'h1', text: 'Waterfall vs Agile' },
      { t: 'ul', items: [
        'Waterfall: phases run once, in sequence.',
        'Agile: phases repeat in short iterations with continuous testing.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Believing testing is a single phase at the end.',
        'Ignoring requirements quality, then testing against a vague spec.',
        'Thinking agile means no process or documentation.',
      ] },
      proTip('"Shift left" simply means start testing thinking at the requirements stage — the earlier you are involved, the cheaper quality becomes.'),
    ],
  },

  {
    slug: 'stlc-cheat-sheet',
    title: 'STLC Cheat Sheet',
    subtitle: 'The Software Testing Life Cycle at a glance.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'The STLC is the testing-specific process that runs alongside the SDLC, from analysing requirements to closing out testing.' },
      { t: 'h1', text: 'The Phases' },
      { t: 'table', headers: ['Phase', 'Purpose', 'Key deliverable'], rows: [
        ['Requirement analysis', 'Understand what to test', 'Testability notes, questions'],
        ['Test planning', 'Scope, approach, schedule', 'Test plan'],
        ['Test design', 'Write cases and prepare data', 'Test cases, test data'],
        ['Environment setup', 'Prepare a system to test', 'Ready test environment'],
        ['Test execution', 'Run tests, log defects', 'Results, defect reports'],
        ['Test closure', 'Report and learn', 'Test summary report'],
      ] },
      { t: 'h1', text: 'Entry & Exit Criteria' },
      { t: 'ul', items: [
        'Entry criteria: what must be ready before a phase starts.',
        'Exit criteria: what must be true before a phase is considered done.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Jumping to execution with no planning or design.',
        'No clear exit criteria, so testing stops when time runs out.',
        'Designing test cases with no test data prepared.',
      ] },
      proTip('Agree entry/exit criteria in writing, early — they are your best protection against being blamed for a rushed release.'),
    ],
  },
];
