// AI for QA Testers — Resource Vault, batch 2 (policy + checklists).
const COURSE = 'AI for QA Testers';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'ai-usage-policy-template',
    title: 'AI Usage Policy Template',
    subtitle: 'A simple, adaptable policy for using AI responsibly in QA work.',
    courseTitle: COURSE, category: 'AI Prompt Packs',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Using AI professionally means protecting data and following clear rules. This template gives you a starting policy you can adapt for yourself or propose to your team.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Adapt the clauses below to your organisation and approved tools.',
        'Share it with your team and keep it visible.',
        'Review it as tools and policies evolve.',
      ] },
      { t: 'h1', text: 'Worked Example (policy clauses)' },
      { t: 'table', headers: ['Area', 'Policy'], rows: [
        ['Approved tools', 'Only use [approved tools] for work involving company data.'],
        ['Data', 'Never paste secrets, credentials, customer or production data. Use synthetic/dummy data.'],
        ['Verification', 'All AI output is reviewed and verified by a person before use.'],
        ['Accountability', 'The author owns AI-assisted work as if they wrote it themselves.'],
        ['Confidentiality', 'Respect IP and confidentiality; do not share proprietary code with public tools.'],
        ['Transparency', 'Note where AI was relied upon when it materially affects deliverables.'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: [
        '1. Purpose & scope', '2. Approved tools', '3. Data handling rules', '4. Verification requirements',
        '5. Accountability', '6. Confidentiality & IP', '7. Transparency', '8. Review cadence',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Draft a one-page version of this policy for your own QA practice, including two example prompts you would NOT send and how you would rework them safely.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Keep it short and practical.', 'Anchor it on data safety and human accountability.', 'Align it with any existing company policy.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Treating policy as optional.', 'No data-handling rules.', 'Never reviewing or updating it.'] },
      proTip('Demonstrating responsible AI use is now a professional expectation. A clear personal policy sets you apart as trustworthy.'),
    ],
  },

  {
    slug: 'ai-risk-assessment-checklist',
    title: 'AI Risk Assessment Checklist',
    subtitle: 'Run this before using AI on any real QA task.',
    courseTitle: COURSE, category: 'Checklists',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'AI brings real risks — data exposure, hallucination, bias and over-reliance. This quick checklist helps you use it safely on each task.' },
      { t: 'h1', text: 'Pre-Use Checklist' },
      { t: 'ul', items: [
        'Is the tool approved for this type of data?',
        'Have I removed/anonymised any sensitive or customer data?',
        'Do I have a way to verify the output?',
        'Am I using AI to draft/assist, not to make a quality decision?',
        'Will I review and own the result?',
        'Does this comply with company policy?',
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'Before asking AI to analyse a defect, you confirm the tool is approved, swap the real customer email for a dummy one, and plan to verify the steps against the app — all six checks pass, so you proceed safely.' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Apply the checklist to a real task you would use AI for. If any item fails, rework the task until it passes.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Make the checklist a habit before every AI task.', 'When unsure about data, leave it out.', 'Prefer approved/enterprise tools for sensitive work.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Skipping the data check "just this once".', 'No plan to verify the output.', 'Letting AI make the call instead of you.'] },
      proTip('A simple test: "Would I be comfortable if this prompt were public?" If not, do not send it.'),
    ],
  },

  {
    slug: 'ai-hallucination-checklist',
    title: 'AI Hallucination Checklist',
    subtitle: 'Spot confident-but-false AI output before it reaches your testing.',
    courseTitle: COURSE, category: 'Checklists',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A hallucination is plausible, confident output that is actually false — invented requirements, fields, functions or results. This checklist helps you catch them.' },
      { t: 'h1', text: 'Detection Checklist' },
      { t: 'ul', items: [
        'Does the output cite a rule, field or function I can confirm exists?',
        'Have I checked specifics against the real spec / app / docs?',
        'Are there overly confident claims with no source?',
        'Does any "requirement" appear that no one actually stated?',
        'Is the test data actually valid for the real system?',
        'If I cannot verify a specific, have I flagged or removed it?',
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'AI states an API returns a "discountCode" field. You check the real API — no such field exists. You remove the hallucinated detail rather than build a useless test around it.' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Ask AI about a system you know well and deliberately look for one inaccuracy. Note how confidently it presented the wrong detail.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Verify against the source, not against how good the text sounds.', 'Be most sceptical of precise specifics.', 'Never let hallucinated rules into your test basis.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Trusting fluent output as accurate.', 'Skipping verification under time pressure.', 'Treating AI as a source of truth.'] },
      proTip('Hallucinations are most dangerous when they are plausible. The more important the detail, the harder you verify it.'),
    ],
  },

  {
    slug: 'ai-validation-checklist',
    title: 'AI Validation Checklist',
    subtitle: 'A consistent way to validate any AI-generated QA output before you use it.',
    courseTitle: COURSE, category: 'Checklists',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'AI drafts; you validate. This checklist gives you a repeatable validation step so AI output reaches the same quality bar as work you produced yourself.' },
      { t: 'h1', text: 'Validation Checklist' },
      { t: 'ul', items: [
        'Accuracy: are the facts, rules and expected results correct?',
        'Relevance: does it fit this product and context?',
        'Completeness: are edge/negative cases and key scenarios covered?',
        'No hallucinations: nothing invented or unverifiable?',
        'Safety: no sensitive data was used?',
        'Ownership: I have reviewed it and can stand behind it.',
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'For AI-generated test cases you confirm the expected results are correct, add a missing "expired link" case from your own knowledge, and remove one irrelevant case — then they are ready to use.' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Take one AI-generated artefact and run it through all six checks. Record what you accepted, changed and rejected.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Treat AI output like work from a junior — helpful, but verify it.', 'Use your QA techniques to judge coverage.', 'Document your review where it matters.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Validating only the format, not the facts.', 'Assuming completeness because it looks thorough.', 'No record of what was AI-assisted.'] },
      proTip('"AI drafts, I validate and own it" is the professional standard. Make validation a non-negotiable step.'),
    ],
  },

  {
    slug: 'ai-test-case-review-checklist',
    title: 'AI Test Case Review Checklist',
    subtitle: 'Review AI-generated test cases like a professional.',
    courseTitle: COURSE, category: 'Checklists',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'AI can draft test cases fast, but the value is in your review. This checklist helps you turn an AI draft into a strong, trustworthy test set.' },
      { t: 'h1', text: 'Review Checklist' },
      { t: 'ul', items: [
        'Are expected results specific and verifiable (not "it works")?',
        'Did it invent any rules or behaviour that do not exist?',
        'Are negative and boundary cases covered, not just the happy path?',
        'Any duplicates or overlapping cases to merge?',
        'Is the test data realistic and valid for the field rules?',
        'Are cases independent and focused on one behaviour each?',
        'Is each case prioritised by risk?',
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'A generated case asserts a "loyalty points" message that no feature provides — a hallucination you remove. You also add boundary cases for the 8–20 character password the draft missed.' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Generate test cases for a feature, review them against this checklist, and note at least two issues you found and fixed.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Apply equivalence partitioning and boundary analysis to judge coverage.', 'Tighten vague expected results.', 'Prioritise by risk before use.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Shipping AI cases without checking expected results.', 'Keeping every generated case regardless of value.', 'Missing hallucinated requirements.'] },
      proTip('Anyone can generate test cases; a professional catches the wrong and missing ones. Your review is the value-add.'),
    ],
  },
];
