// AI for QA Testers — Resource Vault, batch 3 (guides + workbooks).
const COURSE = 'AI for QA Testers';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'ai-bug-report-review-guide',
    title: 'AI Bug Report Review Guide',
    subtitle: 'Use AI to sharpen bug reports without losing your own judgement.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'AI is excellent at tightening the wording, structure and clarity of a bug report — but the technical accuracy stays your responsibility. This guide shows you how to use AI to review and polish a report while keeping the facts correct.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Write the bug report yourself first, with the real facts.',
        'Ask AI to review it for clarity, structure and completeness.',
        'Apply the wording improvements; verify every technical detail yourself.',
        'Never paste production data, credentials or customer PII into the prompt.',
      ] },
      { t: 'h1', text: 'Worked Example (review prompt)' },
      { t: 'p', text: '"Review this bug report for clarity, structure and missing information. Suggest improvements to the title, steps to reproduce, and expected vs actual results. Do not invent any technical details — only flag what is missing: [paste sanitised report]."' },
      { t: 'h1', text: 'What AI Should Check' },
      { t: 'table', headers: ['Element', 'Question'], rows: [
        ['Title', 'Is it specific and scannable (what/where)?'],
        ['Steps', 'Are they numbered, minimal and reproducible?'],
        ['Expected vs actual', 'Are both stated clearly and separately?'],
        ['Environment', 'Build, browser/device, account type captured?'],
        ['Evidence', 'Screenshot/log/video referenced?'],
        ['Severity/priority', 'Justified by impact, not emotion?'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: [
        'Title:', 'Environment:', 'Steps to reproduce:', 'Expected result:', 'Actual result:',
        'Evidence:', 'Severity / Priority:', 'Notes:',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Take a real (sanitised) bug report, run it through the review prompt, and list three improvements you accepted and one suggestion you rejected because it was wrong.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Let AI improve the words; you own the facts.', 'Always sanitise data before pasting.', 'Re-read steps to reproduce after editing — clarity edits can break accuracy.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Accepting reworded steps without re-checking them.', 'Letting AI invent an environment or severity.', 'Pasting real customer data into a public tool.'] },
      proTip('A clear bug report gets fixed faster. Use AI to remove ambiguity, but the developer is acting on your facts — so verify them.'),
    ],
  },

  {
    slug: 'ai-regression-planning-template',
    title: 'AI Regression Planning Template',
    subtitle: 'Plan a risk-based regression set with AI as your brainstorming partner.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Regression planning is about choosing what to re-test when something changes. AI can help you brainstorm impacted areas quickly — but you decide scope based on real risk and product knowledge.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Describe the change and the areas it touches.',
        'Ask AI to suggest potentially impacted areas and regression candidates.',
        'Filter the list by real risk, usage and history; cut the noise.',
        'Finalise a prioritised regression set you can justify.',
      ] },
      { t: 'h1', text: 'Worked Example (planning prompt)' },
      { t: 'p', text: '"We changed the checkout discount logic. List areas that could be impacted directly and indirectly, and suggest regression test scenarios grouped by risk (high/medium/low). Ask me for any context you need."' },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'table', headers: ['Area', 'Why impacted', 'Risk', 'Include?'], rows: [
        ['', '', 'H / M / L', 'Yes / No'],
        ['', '', 'H / M / L', 'Yes / No'],
        ['', '', 'H / M / L', 'Yes / No'],
      ] },
      { t: 'h1', text: 'Prioritisation Guide' },
      { t: 'ul', items: [
        'Always include: critical paths, areas touched by the change, high-usage features.',
        'Usually include: features that share data/logic with the change.',
        'Time-permitting: low-risk, rarely-used areas.',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'For a recent change in any app you know, use the prompt to generate impacted areas, then build a one-page prioritised regression set and write one line justifying the scope.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Anchor scope on risk, not on the size of the AI list.', 'Always cover critical user journeys.', 'Record why something was excluded — it protects you later.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Running everything AI suggests with no prioritisation.', 'Forgetting indirectly impacted areas.', 'No record of scope decisions.'] },
      proTip('AI widens your thinking on what could break; your job is to narrow it to what matters most. Smart regression is targeted, not exhaustive.'),
    ],
  },

  {
    slug: 'ai-exploratory-testing-workbook',
    title: 'AI Exploratory Testing Workbook',
    subtitle: 'Generate sharper test ideas and charters with AI, then explore like a pro.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Exploratory testing is creative, structured investigation. AI is a great idea-generator for charters, personas and "what if" scenarios — then you do the actual exploring and thinking.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Pick a feature and a time-box (e.g. 45 minutes).',
        'Use AI to brainstorm charters, risks and edge ideas.',
        'Explore against the real product; take session notes.',
        'Log findings and new questions; feed surprises back into more charters.',
      ] },
      { t: 'h1', text: 'Worked Example (idea prompt)' },
      { t: 'p', text: '"Suggest 10 exploratory testing charters for a password reset feature, covering security, usability, error handling and edge cases. For each, give a one-line mission."' },
      { t: 'h1', text: 'Blank Charter Template' },
      { t: 'ul', items: [
        'Charter / mission:', 'Time-box:', 'Areas / risks to explore:', 'Test data / personas:',
        'Observations:', 'Bugs found:', 'New questions / follow-up charters:',
      ] },
      { t: 'h1', text: 'Heuristics to Prompt With' },
      { t: 'table', headers: ['Lens', 'Prompt idea'], rows: [
        ['Boundaries', 'What happens at min/max/empty/huge inputs?'],
        ['Interruptions', 'What if I refresh, go back, or lose connection mid-flow?'],
        ['Personas', 'How would a careless / hostile / first-time user behave?'],
        ['Data', 'What unusual but valid data could break assumptions?'],
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Generate 10 charters for a feature you can access, run two 30-minute sessions, and record findings plus three follow-up charters the exploration revealed.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Use AI to widen ideas, not to replace your investigation.', 'Time-box and take notes as you go.', 'Let real findings drive the next charter.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Treating AI charters as a script to click through.', 'No note-taking, so findings are lost.', 'Stopping at the happy path.'] },
      proTip('AI gives you more doors to try; exploratory skill is knowing which to open and what you notice once inside. Stay curious and follow the surprises.'),
    ],
  },

  {
    slug: 'ai-requirement-review-workbook',
    title: 'AI Requirement Review Workbook',
    subtitle: 'Find gaps, ambiguity and missing acceptance criteria before a line of code is written.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'The cheapest defect to fix is one caught in the requirement. AI is a strong second pair of eyes for spotting ambiguity, gaps and untestable statements — so you can ask better questions early.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Paste the requirement / user story (sanitised).',
        'Ask AI to find ambiguity, missing cases and untestable wording.',
        'Turn the output into real questions for the team.',
        'Confirm acceptance criteria are clear and testable.',
      ] },
      { t: 'h1', text: 'Worked Example (review prompt)' },
      { t: 'p', text: '"Review this user story as a QA analyst. List ambiguous terms, missing scenarios (including negative and edge cases), and any acceptance criteria that are not testable. Phrase each as a question I can ask the team: [paste story]."' },
      { t: 'h1', text: 'What to Look For' },
      { t: 'table', headers: ['Issue', 'Example'], rows: [
        ['Ambiguity', '"fast", "user-friendly", "etc." — undefined terms'],
        ['Missing cases', 'No error, empty, or unauthorised path'],
        ['Untestable', '"should work well" — no measurable outcome'],
        ['Conflicts', 'Two rules that contradict each other'],
        ['Assumptions', 'Unstated dependencies or pre-conditions'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: [
        'Requirement reviewed:', 'Ambiguities:', 'Missing scenarios:', 'Untestable criteria:',
        'Questions for the team:', 'Agreed clarifications:',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Take a real user story, run the review prompt, and produce five sharp questions you would raise in refinement. Mark which two are most important.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Turn findings into questions, not accusations.', 'Prioritise the gaps that carry the most risk.', 'Confirm acceptance criteria are measurable.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Accepting vague requirements to "save time".', 'Not raising questions until testing.', 'Treating AI gaps as facts rather than prompts to verify.'] },
      proTip('Great testers prevent defects, not just find them. Reviewing requirements early — with AI helping you spot gaps — is the highest-leverage testing you can do.'),
    ],
  },
];
