// AI for QA Testers — Resource Vault, batch 4 (cheat sheet, governance, poster, planner). Completes the 15.
const COURSE = 'AI for QA Testers';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'ai-prompt-cheat-sheet',
    title: 'AI Prompt Cheat Sheet for Testers',
    subtitle: 'The one-page reference for writing effective QA prompts, fast.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Keep this beside you. It distils everything about prompting for QA into a single reference: the structure of a strong prompt, ready-to-use patterns, and the safety rules that keep you professional.' },
      { t: 'h1', text: 'The Prompt Formula' },
      { t: 'p', text: 'Role + Context + Task + Format + Constraints.' },
      { t: 'table', headers: ['Part', 'Example'], rows: [
        ['Role', '"Act as a senior QA engineer..."'],
        ['Context', '"...for a login feature with email + password..."'],
        ['Task', '"...generate positive, negative and boundary test cases..."'],
        ['Format', '"...as a table: ID, scenario, steps, expected result..."'],
        ['Constraints', '"...do not invent fields; ask if context is missing."'],
      ] },
      { t: 'h1', text: 'Go-To Patterns' },
      { t: 'ul', items: [
        'Test design: "Generate test cases for [feature] covering happy path, negative and boundary."',
        'Review: "Review these test cases/this bug report for gaps and clarity."',
        'Requirement check: "Find ambiguity and missing scenarios in this story."',
        'Explain: "Explain [concept] simply, then give a QA example."',
        'Data: "Suggest realistic but synthetic test data for [field rules]."',
      ] },
      { t: 'h1', text: 'Quality Boosters' },
      { t: 'ul', items: [
        'Give an example of the output you want.',
        'Ask it to ask you questions before answering.',
        'Iterate: "Add boundary cases", "Make expected results more specific".',
        'Request a format you can paste straight into your tool.',
      ] },
      { t: 'h1', text: 'Safety Rules (never skip)' },
      { t: 'ul', items: [
        'No secrets, credentials, customer or production data.',
        'Verify every specific against the real spec/app.',
        'You review and own the output — AI drafts, you decide.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['One-line vague prompts.', 'Trusting output without verifying.', 'Pasting sensitive data.'] },
      proTip('A great prompt is just clear thinking written down. If you can brief a junior tester to do the task, you can prompt AI to draft it.'),
    ],
  },

  {
    slug: 'ai-ethics-governance-guide',
    title: 'AI Ethics & Governance Guide for QA',
    subtitle: 'Use AI responsibly — data, bias, accountability and transparency.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Using AI well is not just about output quality — it is about doing it responsibly. This guide covers the ethics and governance every professional tester should understand and be able to talk about.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Read each principle and the practical rule that follows it.',
        'Apply the rules to your own AI use today.',
        'Be ready to explain your responsible-AI approach in interviews and at work.',
      ] },
      { t: 'h1', text: 'Core Principles' },
      { t: 'table', headers: ['Principle', 'What it means in practice'], rows: [
        ['Data protection', 'Never expose secrets, customer or production data to AI tools.'],
        ['Human accountability', 'A person reviews and owns every AI-assisted deliverable.'],
        ['Bias awareness', 'AI can reflect bias; check that suggestions are fair and complete.'],
        ['Transparency', 'Be open about where AI materially shaped your work.'],
        ['Verification', 'Treat output as a draft to be checked, never as truth.'],
        ['Confidentiality & IP', 'Respect ownership; do not share proprietary code with public tools.'],
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'Asked in an interview "how do you use AI responsibly?", you answer: "I only use approved tools, never paste real customer data, treat output as a draft I verify, and I stay accountable for the final result." That answer signals maturity instantly.' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Write your own three-sentence "responsible AI" statement you could say in an interview, covering data, verification and accountability.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Default to caution with any sensitive data.', 'Make verification a habit, not an afterthought.', 'Stay current as tools and policies evolve.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Assuming "the tool handles privacy".', 'Hiding AI use instead of being transparent.', 'Letting AI make quality or risk decisions.'] },
      proTip('Employers increasingly value testers who use AI responsibly. Being able to articulate your governance approach is a genuine differentiator.'),
    ],
  },

  {
    slug: 'ai-qa-workflow-poster',
    title: 'AI-Assisted QA Workflow Poster',
    subtitle: 'Where AI fits across the testing lifecycle — at a glance.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'The AI-Assisted QA Workflow' },
      { t: 'p', text: 'Print this and keep it visible. It shows where AI helps across the testing lifecycle — and where your judgement stays in control at every step.' },
      { t: 'h1', text: 'Across the Lifecycle' },
      { t: 'table', headers: ['Stage', 'AI assists with', 'You stay in control of'], rows: [
        ['Requirements', 'Spotting ambiguity and gaps', 'Deciding what to clarify'],
        ['Test design', 'Drafting cases and ideas', 'Coverage, risk and accuracy'],
        ['Test data', 'Generating synthetic data', 'Validity and privacy'],
        ['Execution', 'Summarising, triaging notes', 'Actual testing and observation'],
        ['Defects', 'Polishing report wording', 'Technical facts and severity'],
        ['Regression', 'Brainstorming impacted areas', 'Final scope by risk'],
        ['Reporting', 'Drafting summaries', 'The quality story and decisions'],
      ] },
      { t: 'h1', text: 'The Golden Rule' },
      { t: 'p', text: 'AI drafts and assists. You verify, decide and own. Quality decisions are never delegated to a model.' },
      { t: 'h1', text: 'Three Safety Checks (every time)' },
      { t: 'ul', items: [
        'Data: nothing sensitive went into the prompt.',
        'Verify: every specific checked against reality.',
        'Own: I reviewed it and stand behind it.',
      ] },
      proTip('The strongest modern testers are not the ones who use AI the most — they are the ones who know exactly where to trust it and where not to.'),
    ],
  },

  {
    slug: 'personal-ai-toolkit-planner',
    title: 'Personal AI Toolkit Planner',
    subtitle: 'Build your own repeatable AI-assisted testing toolkit.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'The testers who get the most from AI build a personal toolkit: their best prompts, their go-to tools, and their own rules. This planner helps you assemble yours so you work faster and more consistently.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Capture the prompts that work well for you as you go.',
        'Note which tool you use for which task.',
        'Write your own usage rules and keep refining them.',
        'Review and prune your toolkit monthly.',
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'A tester keeps a note with five saved prompts (test design, bug report review, requirement review, data generation, explain-a-concept), a one-line rule ("never paste real data"), and a tool-per-task list. Each new task starts from a proven prompt instead of a blank box.' },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'table', headers: ['Task', 'My go-to prompt', 'Tool', 'Notes'], rows: [
        ['Test design', '', '', ''],
        ['Bug report review', '', '', ''],
        ['Requirement review', '', '', ''],
        ['Test data', '', '', ''],
        ['Learning / explain', '', '', ''],
      ] },
      { t: 'h1', text: 'My Personal Rules' },
      { t: 'ul', items: [
        'Data I will never share:',
        'How I verify output:',
        'When I will NOT use AI:',
        'How I record AI-assisted work:',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Fill in the table with at least three saved prompts you have used successfully, and write your four personal rules. Revisit it after two weeks and improve one prompt.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Save prompts that work — do not rewrite from scratch each time.', 'Keep one place for your toolkit.', 'Refine continuously as tools change.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Reinventing prompts every time.', 'No personal data/safety rules.', 'Letting the toolkit go stale.'] },
      proTip('Your prompt library is a career asset. The tester who walks into a new job with a proven AI toolkit ramps up far faster than one starting from zero.'),
    ],
  },
];
