// API Testing Masterclass — resource vault, batch 2.
const COURSE = 'API Testing Masterclass';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'postman-collections-guide',
    title: 'Postman Collections Guide',
    subtitle: 'Organise, parameterise and run professional Postman collections.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'p', text: 'Postman is the tool most testers reach for first, but a folder full of one-off requests is not a test asset. This guide shows you how to build a collection that is organised, parameterised and repeatable — something you can hand to a colleague, run in CI, and be proud to put in your portfolio.' },
      { t: 'h1', text: 'What a Collection Is' },
      { t: 'p', text: 'A collection is a saved, shareable group of API requests. It bundles the requests themselves, the folder structure that organises them, environment and variable definitions, pre-request scripts, and the tests (assertions) that run after each response. Think of it as an executable test suite for an API rather than a scratchpad.' },
      { t: 'h1', text: 'Folder Structure' },
      { t: 'p', text: 'Mirror the API or the user journeys, not your trial-and-error history. A clear structure makes the collection self-documenting.' },
      { t: 'ul', items: [
        'Top level: one folder per resource or feature (e.g. Auth, Users, Orders).',
        'Within a folder: group by operation or scenario (Create, Retrieve, Update, Delete; happy path vs negative).',
        'Name requests by intent — "Create user (valid)" and "Create user (missing email → 400)", not "POST 2".',
        'Keep a Setup/Teardown folder for login and cleanup requests that other folders depend on.',
      ] },
      { t: 'h1', text: 'Variables & Environments' },
      { t: 'p', text: 'Never hard-code a base URL, token or ID into a request. Store them as variables and let scope decide where each value lives. Postman resolves a variable from the narrowest scope outwards.' },
      { t: 'table', headers: ['Scope', 'Lives in', 'Use for', 'Example'], rows: [
        ['Global', 'The whole workspace', 'Rarely-changing values shared everywhere', 'apiVersion'],
        ['Collection', 'One collection', 'Values true for every environment', 'defaultPageSize'],
        ['Environment', 'A selected environment (Dev/Staging/Prod)', 'Values that differ per environment', 'baseUrl, authToken'],
        ['Local / Data', 'A single run or data file row', 'Iteration-specific data', 'username, expectedStatus'],
      ] },
      { t: 'p', text: 'Reference a variable with double curly braces, e.g. a request URL of {{baseUrl}}/users/{{userId}}. Switch the active environment (top-right dropdown) to point the same collection at Dev, Staging or Prod without editing a single request. Store secrets as environment "secret" variables so they are masked.' },
      { t: 'h1', text: 'Writing Tests in the Tests Tab' },
      { t: 'p', text: 'The Tests tab runs JavaScript after the response arrives. Each pm.test block is one assertion that shows as pass or fail in the run summary.' },
      { t: 'ul', items: [
        'pm.test("Status is 200", () => pm.response.to.have.status(200));',
        'pm.test("Response is JSON", () => pm.response.to.be.json);',
        'const body = pm.response.json(); pm.test("Has id", () => pm.expect(body.id).to.exist);',
        'pm.test("Responds within 800ms", () => pm.expect(pm.response.responseTime).to.be.below(800));',
      ] },
      { t: 'h1', text: 'Chaining Requests with Variables' },
      { t: 'p', text: 'Real API tests are sequences: create a resource, then read, update and delete it. Capture a value from one response and reuse it in the next by saving it to a variable.' },
      { t: 'ol', items: [
        'In the first request (e.g. Login), open the Tests tab.',
        'Read the value from the response: const token = pm.response.json().access_token;',
        'Save it to an environment variable: pm.environment.set("authToken", token);',
        'In later requests, use it: set the Authorization header to Bearer {{authToken}}.',
        'Repeat the pattern for IDs — pm.collectionVariables.set("userId", pm.response.json().id) after a create, then GET {{baseUrl}}/users/{{userId}}.',
      ] },
      { t: 'h1', text: 'Running a Collection' },
      { t: 'p', text: 'Use the Collection Runner (Run button on the collection) to execute every request in order and see a pass/fail summary. To run the same requests against many inputs, attach a data file.' },
      { t: 'ul', items: [
        'Prepare a CSV or JSON file where each row/object is one iteration; column names become variables.',
        'In the Runner, select the collection, choose the environment, and upload the data file.',
        'Reference the columns as variables in requests and tests (e.g. {{username}}, {{expectedStatus}}).',
        'For unattended runs, the Newman CLI executes the exported collection in CI — newman run collection.json -e env.json -d data.csv.',
      ] },
      { t: 'h1', text: 'Exporting & Sharing' },
      { t: 'ul', items: [
        'Export the collection (and each environment) as v2.1 JSON for version control or Newman.',
        'Never commit real environment secrets — export environments with secret values cleared, or keep them in a separate untracked file.',
        'Prefer sharing via a workspace or Git-backed collection over emailing JSON, so everyone stays in sync.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Hard-coding base URLs, tokens or IDs into requests instead of using variables.',
        'Storing secrets at collection or global scope, then exporting and leaking them.',
        'One giant flat list of requests with no folders and names like "Copy of POST".',
        'No tests in the Tests tab — a green 200 in the UI is not an assertion.',
        'Requests that only pass when run manually in a specific order, with no variable chaining to enforce it.',
      ] },
      proTip('Build the collection so a stranger could run it: sensible folders, every value a variable, an environment per stage, and at least one assertion per request. A clean, runnable Postman collection exported to your GitHub is a genuine portfolio piece.'),
    ],
  },

  {
    slug: 'openapi-swagger-guide',
    title: 'OpenAPI / Swagger Guide for Testers',
    subtitle: 'Turn an API specification into a test plan.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'p', text: 'An OpenAPI specification is the single most useful document a tester can be handed. It tells you every endpoint, every parameter, every valid input and every response the API promises — before you send a single request. This guide shows you how to read a spec and turn it directly into test cases.' },
      { t: 'h1', text: 'What OpenAPI / Swagger Is' },
      { t: 'p', text: 'OpenAPI is a standard, machine-readable format (YAML or JSON) for describing a REST API — its endpoints, inputs and outputs. "Swagger" refers to the earlier version of the standard and to the popular tooling (Swagger UI, Swagger Editor) that renders a spec into an interactive, browsable page. In practice testers use the terms loosely, but the spec is the contract between the API and everyone who calls it.' },
      { t: 'h1', text: 'Anatomy of a Spec' },
      { t: 'p', text: 'You do not need to write specs, but you must be able to read them. These are the parts you will use every day.' },
      { t: 'table', headers: ['Part', 'What it describes', 'Why the tester cares'], rows: [
        ['paths', 'The endpoints, e.g. /users, /users/{id}', 'The list of things to test'],
        ['methods', 'GET, POST, PUT, PATCH, DELETE on each path', 'Which operations exist and their expected behaviour'],
        ['parameters', 'Path, query, header and cookie inputs; required vs optional', 'Boundary, missing and invalid-input cases'],
        ['requestBody / schemas', 'Structure and types of the JSON you send/receive', 'Field validation, required fields, data types'],
        ['responses', 'Documented status codes (200, 201, 400, 404…) and bodies', 'The expected results to assert against'],
        ['security', 'Auth schemes each endpoint requires', 'Access-control and 401/403 tests'],
      ] },
      { t: 'h1', text: 'Deriving Test Cases from a Spec' },
      { t: 'p', text: 'Read the spec systematically and each element hands you tests. Work endpoint by endpoint.' },
      { t: 'ol', items: [
        'For each documented response code, write a case that provokes it (200 valid GET, 201 valid POST, 404 unknown id, 400 bad body).',
        'For each required parameter or field, add a negative case that omits it and expect the documented error (usually 400).',
        'For each field schema, test type and constraint boundaries (min/max length, numeric ranges, enum values, wrong types).',
        'For each secured endpoint, test with no token, an invalid token and a valid token (expect 401/403 vs success).',
        'Assert the response body matches the schema — required fields present, correct types — not just the status code.',
      ] },
      { t: 'h1', text: 'Importing a Spec into Postman' },
      { t: 'p', text: 'Postman can generate a ready-made collection from a spec, saving hours of manual request-building.' },
      { t: 'ol', items: [
        'In Postman choose Import and select the OpenAPI file, URL or pasted YAML/JSON.',
        'Choose to generate a collection from the spec when prompted.',
        'Postman creates a folder structure and a request per endpoint, pre-filled with example parameters and bodies.',
        'Set a {{baseUrl}} variable and an environment, then add your assertions in each Tests tab.',
        'Re-import when the spec changes to spot new, removed or altered endpoints.',
      ] },
      { t: 'h1', text: 'Contract Awareness' },
      { t: 'p', text: 'The spec is a contract, so a large class of bugs is simply "the API does not match its own spec". Watch for these mismatches — they are real defects even if the endpoint "works".' },
      { t: 'ul', items: [
        'A field documented as required is accepted as missing (or vice versa).',
        'A response returns a status code or field the spec never mentions.',
        'A type differs — the spec says the id is an integer, the API returns a string.',
        'An endpoint or parameter exists in the API but not in the spec (undocumented surface area).',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Testing only the happy paths the spec shows and ignoring the documented error responses.',
        'Asserting the status code but never checking the response body against the schema.',
        'Treating the spec as gospel — sometimes the spec is wrong and the code is right, so query mismatches rather than auto-raising bugs.',
        'Ignoring optional parameters entirely instead of testing them present and absent.',
      ] },
      proTip('Before writing a single request, print the spec and annotate every response code and required field with a test case. A tester who arrives at test design with the spec already dissected looks far more senior than one who explores blindly.'),
    ],
  },

  {
    slug: 'api-authentication-guide',
    title: 'API Authentication Guide',
    subtitle: 'API keys, Basic, Bearer/JWT and OAuth 2.0 — for testers.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'p', text: 'Most real APIs are protected, so you cannot test them without understanding how authentication works. This guide covers the four schemes you will meet most often, how to set each one in Postman, and — crucially — how to test that access control actually holds.' },
      { t: 'h1', text: 'Authentication vs Authorisation' },
      { t: 'p', text: 'These two words are used interchangeably in conversation but mean different things, and the difference shows up directly in status codes.' },
      { t: 'ul', items: [
        'Authentication — "who are you?". Proving identity with a credential (key, password, token). Failure returns 401 Unauthorized.',
        'Authorisation — "are you allowed to do this?". Checking whether an authenticated identity has permission for the action. Failure returns 403 Forbidden.',
        'Quick test heuristic: 401 means your credential is missing, malformed or expired; 403 means your credential is valid but you lack the rights.',
      ] },
      { t: 'h1', text: 'The Four Common Schemes' },
      { t: 'table', headers: ['Scheme', 'How it works', 'Where the credential goes', 'Tester notes'], rows: [
        ['API key', 'A single secret string identifies the caller', 'Header (e.g. X-API-Key) or query parameter', 'Simple; often no per-user identity. Test missing/invalid key → 401'],
        ['Basic', 'Base64 of username:password sent each request', 'Authorization: Basic <base64>', 'Not encrypted, only encoded — must be over HTTPS. Test wrong password → 401'],
        ['Bearer / JWT', 'A signed token issued after login, sent on each call', 'Authorization: Bearer <token>', 'Token expires; test missing/expired/tampered token'],
        ['OAuth 2.0', 'Exchange credentials/grant for a short-lived access token via an auth server', 'Authorization: Bearer <access token>', 'Multi-step flow; test token refresh and scope limits'],
      ] },
      { t: 'h1', text: 'Setting Each in Postman' },
      { t: 'p', text: 'Use the Authorization tab on the request or folder rather than hand-typing headers where possible — Postman builds the correct header for you.' },
      { t: 'ol', items: [
        'API key: Authorization tab → type "API Key" → set the key name, value and whether it goes in Header or Query. Store the value as {{apiKey}}.',
        'Basic: Authorization tab → type "Basic Auth" → enter username and password (use {{user}} / {{password}} variables).',
        'Bearer/JWT: Authorization tab → type "Bearer Token" → paste or reference the token as {{authToken}} (typically captured from a login response).',
        'OAuth 2.0: Authorization tab → type "OAuth 2.0" → configure the token URL, client id/secret and scope, then "Get New Access Token"; Postman stores and injects it.',
        'Set auth at the collection or folder level so child requests inherit it, and override only where needed.',
      ] },
      { t: 'h1', text: 'JWT Structure' },
      { t: 'p', text: 'A JWT is three Base64URL-encoded parts joined by dots: header.payload.signature. It is signed, not encrypted, so anyone can decode and read the header and payload — never put secrets in it.' },
      { t: 'ul', items: [
        'Header — the algorithm and token type, e.g. {"alg":"HS256","typ":"JWT"}.',
        'Payload — the claims: who the token is for (sub), when it expires (exp), and roles/scopes.',
        'Signature — proves the token has not been altered; the server verifies it with its secret/key.',
        'Expiry — the exp claim is a Unix timestamp. Decode it (jwt.io or a script) to see when the token dies; an expired token must be rejected with 401.',
      ] },
      { t: 'h1', text: 'Testing Access Control' },
      { t: 'p', text: 'A protected endpoint that lets the wrong caller in is a serious security bug. Do not just confirm the happy path works — actively try to break in.' },
      { t: 'ul', items: [
        'No token — send the request with the credential removed; expect 401.',
        'Expired token — use a token past its exp; expect 401, not a silent success.',
        'Tampered token — change a character in the payload/signature; expect 401.',
        'Wrong-user token — authenticate as User A and try to read/modify User B\'s resource; expect 403 (or 404 by design), never User B\'s data.',
        'Insufficient scope/role — use a valid low-privilege token on an admin action; expect 403.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: [
        'Confusing 401 and 403, then raising bugs against the wrong behaviour.',
        'Only testing that a valid token works, never that missing/expired/wrong-user tokens are rejected.',
        'Pasting a token that has since expired and reporting a false "auth broken" bug.',
        'Committing real tokens or credentials into an exported collection.',
        'Assuming Basic auth is secure because it is "encrypted" — it is only Base64-encoded.',
      ] },
      proTip('The most valuable API auth bugs are broken access control: a valid token for User A reaching User B\'s data. Always test "authenticated as the wrong user", not just "not authenticated at all" — it is where real vulnerabilities hide.'),
    ],
  },

  {
    slug: 'api-test-strategy-template',
    title: 'API Test Strategy Template',
    subtitle: 'A reusable, fill-in strategy for testing any API.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'p', text: 'A test strategy is the one-page (or few-page) document that says what you will test, how, where and when you will stop. This is a genuine fill-in template: copy it, replace every prompt in [square brackets] with your project\'s detail, and delete the guidance you no longer need. Aim for clarity over length — a strategy nobody reads is worthless.' },
      { t: 'h1', text: 'How to Use This Template' },
      { t: 'ol', items: [
        'Copy the sections below into your project doc or wiki.',
        'Answer every prompt — if a section genuinely does not apply, write "N/A" and say why rather than deleting it.',
        'Keep it living: update it when scope, tools or environments change.',
        'Review it with a developer and a product owner before you start — a strategy is an agreement, not a solo essay.',
      ] },
      { t: 'h1', text: '1. Scope & Objectives' },
      { t: 'p', text: 'State what this effort covers and, just as importantly, what it does not. Objectives should be outcomes, not activities.' },
      { t: 'ul', items: [
        'API(s) / services under test: [name, version, base URLs]',
        'In scope: [endpoints, features, flows]',
        'Out of scope: [e.g. third-party APIs, UI, performance] and why',
        'Objectives: [e.g. verify all documented endpoints meet their contract; confirm access control holds]',
      ] },
      { t: 'h1', text: '2. Risks' },
      { t: 'p', text: 'List what could go wrong and how badly, so testing effort follows the risk. Rank so the team can focus.' },
      { t: 'table', headers: ['Risk', 'Likelihood (H/M/L)', 'Impact (H/M/L)', 'Mitigation / test focus'], rows: [
        ['[e.g. Broken access control exposes other users\' data]', '[ ]', '[ ]', '[ ]'],
        ['[e.g. Breaking change to response schema]', '[ ]', '[ ]', '[ ]'],
        ['[add rows as needed]', '[ ]', '[ ]', '[ ]'],
      ] },
      { t: 'h1', text: '3. Test Types & Coverage' },
      { t: 'p', text: 'Which kinds of testing will you do, and to what depth? Tick, delete or expand as appropriate.' },
      { t: 'ul', items: [
        'Functional (happy path + negative/error responses): [depth]',
        'Contract / schema validation against the spec: [yes/no, how]',
        'Authentication & authorisation / access control: [scenarios]',
        'Data validation & boundaries (types, required, limits): [depth]',
        'Non-functional — performance / load / security: [in scope? owned by whom?]',
        'Integration between services / end-to-end flows: [which flows]',
      ] },
      { t: 'h1', text: '4. Environments' },
      { t: 'p', text: 'Where will testing run, and what state can you rely on there?' },
      { t: 'table', headers: ['Environment', 'Base URL', 'Purpose', 'Notes / limitations'], rows: [
        ['Dev', '[url]', '[early integration]', '[unstable data]'],
        ['Staging / QA', '[url]', '[main test target]', '[prod-like]'],
        ['Production', '[url]', '[smoke only]', '[read-only? which checks are safe?]'],
      ] },
      { t: 'h1', text: '5. Test Data' },
      { t: 'p', text: 'Define how you obtain, create and clean up data, and how you protect anything sensitive.' },
      { t: 'ul', items: [
        'Source: [seeded fixtures / created via setup requests / anonymised copy]',
        'Accounts & roles needed: [admin, standard user, unauthorised user]',
        'Sensitive data handling: [no real PII; secrets stored where]',
        'Cleanup / teardown approach: [how created data is removed]',
      ] },
      { t: 'h1', text: '6. Tools' },
      { t: 'ul', items: [
        'Manual / exploratory: [Postman, curl]',
        'Automation & CI: [Newman, Playwright API, REST-assured, pytest]',
        'Reporting / tracking: [where results and defects go]',
        'Spec / contract source: [OpenAPI location]',
      ] },
      { t: 'h1', text: '7. Entry & Exit Criteria' },
      { t: 'h2', text: 'Entry criteria (before testing starts)' },
      { t: 'ul', items: [
        '[Spec / documentation available and stable]',
        '[Test environment deployed and reachable]',
        '[Credentials and test accounts provisioned]',
      ] },
      { t: 'h2', text: 'Exit criteria (when testing is "done")' },
      { t: 'ul', items: [
        '[All planned test cases executed]',
        '[No open Critical/High defects; agreed threshold for Medium/Low]',
        '[Contract checks pass against the current spec]',
        '[Results reported and signed off]',
      ] },
      { t: 'h1', text: '8. Reporting' },
      { t: 'p', text: 'Say what you will report, to whom, and how often, so results are visible and defects are actionable.' },
      { t: 'ul', items: [
        'Cadence & audience: [e.g. daily summary to the team, sign-off report to PO]',
        'Metrics: [pass/fail counts, coverage of endpoints, open defects by severity]',
        'Defect process: [where raised, required detail, severity definitions]',
      ] },
      { t: 'h1', text: '9. Sign-off' },
      { t: 'p', text: 'Record who agrees the strategy and who accepts the results — a strategy without owners is easy to ignore.' },
      { t: 'table', headers: ['Role', 'Name', 'Date', 'Signature / approval'], rows: [
        ['QA / Test lead', '[ ]', '[ ]', '[ ]'],
        ['Development lead', '[ ]', '[ ]', '[ ]'],
        ['Product owner', '[ ]', '[ ]', '[ ]'],
      ] },
      proTip('Keep this to a page or two and treat it as living. A concise, agreed strategy that the whole team has read beats a beautiful 20-page document nobody opens. Bring a completed version of this template to an interview — it shows you think strategically, not just click "Send".'),
    ],
  },
];
