// API Testing Masterclass — API Resource Vault, batch 1.
const COURSE = 'API Testing Masterclass';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'api-cheat-sheet',
    title: 'API Testing Cheat Sheet',
    subtitle: 'The essentials of HTTP, requests and assertions on one sheet.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'p', text: 'This is your one-page working reference for API testing over HTTP. Keep it beside you when writing requests in Postman or automating them in code: it covers the anatomy of a request, the methods and headers you use daily, how to read a response, and the assertions that turn a manual check into a repeatable test.' },
      { t: 'h1', text: 'Anatomy of a Request' },
      { t: 'p', text: 'Every HTTP request is made of four parts. Get these right and the rest follows.' },
      { t: 'ul', items: [
        'Method — the verb: what you want to do (GET, POST, PUT, PATCH, DELETE).',
        'URL — the endpoint plus any path and query parameters, e.g. https://api.example.com/users/1?expand=orders',
        'Headers — metadata such as Authorization, Content-Type and Accept.',
        'Body — the payload you send (usually JSON), used by POST, PUT and PATCH.',
      ] },
      { t: 'h1', text: 'HTTP Methods' },
      { t: 'table', headers: ['Method', 'Purpose', 'Idempotent', 'Body'], rows: [
        ['GET', 'Retrieve a resource; must not change state', 'Yes', 'No'],
        ['POST', 'Create a resource or trigger an action', 'No', 'Yes'],
        ['PUT', 'Replace a resource in full', 'Yes', 'Yes'],
        ['PATCH', 'Partially update a resource', 'No', 'Yes'],
        ['DELETE', 'Remove a resource', 'Yes', 'Optional'],
        ['HEAD', 'Like GET but headers only, no body', 'Yes', 'No'],
      ] },
      { t: 'p', text: 'Idempotent means repeating the same call has the same effect as making it once — a key property to test, especially for retries.' },
      { t: 'h1', text: 'Key Headers' },
      { t: 'table', headers: ['Header', 'Direction', 'What it does'], rows: [
        ['Authorization', 'Request', 'Credentials, e.g. "Bearer <token>" or Basic auth'],
        ['Content-Type', 'Both', 'Format of the body being sent, e.g. application/json'],
        ['Accept', 'Request', 'Format the client wants back, e.g. application/json'],
        ['Content-Length', 'Both', 'Size of the body in bytes'],
        ['Cache-Control', 'Both', 'Caching rules, e.g. no-cache'],
        ['Location', 'Response', 'URL of a newly created or moved resource'],
      ] },
      { t: 'h1', text: 'The Response' },
      { t: 'p', text: 'A response mirrors the request: a status line, headers and (usually) a body.' },
      { t: 'ul', items: [
        'Status code — the outcome as a number, e.g. 200 OK or 404 Not Found (see the Status Codes reference).',
        'Headers — metadata about the response, e.g. Content-Type, Location, caching.',
        'Body — the returned data, typically JSON. Always confirm the body, not just the status.',
      ] },
      { t: 'h1', text: 'Postman Assertions' },
      { t: 'p', text: 'Assertions live in Postman’s Scripts (Tests) tab and run after the response arrives. These are the ones you reach for most.' },
      { t: 'table', headers: ['Goal', 'Snippet'], rows: [
        ['Assert status code', 'pm.response.to.have.status(200);'],
        ['Response time under 500 ms', 'pm.expect(pm.response.responseTime).to.be.below(500);'],
        ['Parse the JSON body', 'const json = pm.response.json();'],
        ['Field equals a value', 'pm.expect(json.id).to.eql(1);'],
        ['Field exists', 'pm.expect(json).to.have.property(\'email\');'],
        ['Array has a length', 'pm.expect(json.items).to.have.lengthOf(3);'],
        ['Header present', 'pm.response.to.have.header(\'Content-Type\');'],
      ] },
      { t: 'p', text: 'Wrap related checks in pm.test(\'a clear name\', () => { … }); so the results read like a report.' },
      proTip('Never assert on status alone. A 200 with the wrong body, a missing field or a five-second response time is still a failing test. Check the status, then the shape and values of the body, then performance where it matters.'),
    ],
  },

  {
    slug: 'http-status-codes-reference',
    title: 'HTTP Status Codes Reference',
    subtitle: 'Every status class a tester needs — and what to check.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'p', text: 'Status codes are the first thing an API tells you about a request. This reference groups them by class, lists the codes you will actually meet, and — crucially — says what to verify as a tester when you see each one.' },
      { t: 'h1', text: 'What the Classes Mean' },
      { t: 'table', headers: ['Class', 'Meaning', 'Who to blame'], rows: [
        ['1xx', 'Informational — request received, continuing', 'Rarely seen in testing'],
        ['2xx', 'Success — the request worked', 'Nobody; verify the body'],
        ['3xx', 'Redirection — further action needed', 'Usually the client/config'],
        ['4xx', 'Client error — the request was wrong', 'The caller (your request)'],
        ['5xx', 'Server error — the server failed', 'The server/backend'],
      ] },
      { t: 'h1', text: '2xx Success' },
      { t: 'table', headers: ['Code', 'Name', 'Meaning', 'Tester note'], rows: [
        ['200', 'OK', 'Request succeeded', 'Confirm the body matches the request; do not stop at the code'],
        ['201', 'Created', 'A new resource was created', 'Check the Location header and the returned resource'],
        ['202', 'Accepted', 'Accepted for async processing', 'Verify the job/status endpoint later'],
        ['204', 'No Content', 'Success with no body', 'Expected for many DELETEs; assert there is no body'],
      ] },
      { t: 'h1', text: '3xx Redirection' },
      { t: 'table', headers: ['Code', 'Name', 'Meaning', 'Tester note'], rows: [
        ['301', 'Moved Permanently', 'Resource has a new permanent URL', 'Check the Location header; update the client'],
        ['302', 'Found', 'Temporary redirect', 'Confirm whether your client should follow it'],
        ['304', 'Not Modified', 'Cached copy is still valid', 'Test with conditional headers (If-None-Match)'],
        ['307', 'Temporary Redirect', 'Redirect, method preserved', 'Verify the method is not silently changed'],
      ] },
      { t: 'h1', text: '4xx Client Errors' },
      { t: 'table', headers: ['Code', 'Name', 'Meaning', 'Tester note'], rows: [
        ['400', 'Bad Request', 'Malformed request or invalid data', 'Send bad payloads deliberately and expect this'],
        ['401', 'Unauthorized', 'Not authenticated', 'Test with missing/expired/invalid credentials'],
        ['403', 'Forbidden', 'Authenticated but not allowed', 'Test with a valid user lacking permission'],
        ['404', 'Not Found', 'Resource does not exist', 'Request a bad ID; confirm no data leaks in the body'],
        ['405', 'Method Not Allowed', 'Wrong method for the endpoint', 'Try DELETE on a read-only endpoint'],
        ['409', 'Conflict', 'State conflict, e.g. duplicate', 'Create the same resource twice'],
        ['422', 'Unprocessable Entity', 'Valid syntax, failed validation', 'Test business-rule validation, not just format'],
        ['429', 'Too Many Requests', 'Rate limit exceeded', 'Check for a Retry-After header'],
      ] },
      { t: 'h1', text: '5xx Server Errors' },
      { t: 'table', headers: ['Code', 'Name', 'Meaning', 'Tester note'], rows: [
        ['500', 'Internal Server Error', 'Unhandled server fault', 'A bug — log it; the client did nothing wrong'],
        ['502', 'Bad Gateway', 'Bad response from an upstream server', 'Often infrastructure/proxy; note and escalate'],
        ['503', 'Service Unavailable', 'Server overloaded or down', 'Check for Retry-After; test graceful degradation'],
        ['504', 'Gateway Timeout', 'Upstream server timed out', 'Investigate slow dependencies/timeouts'],
      ] },
      { t: 'h1', text: '401 vs 403 — the Classic Distinction' },
      { t: 'p', text: 'These are the two everyone confuses. 401 Unauthorized means "I do not know who you are" — authentication failed or is missing, so logging in (or supplying a valid token) could fix it. 403 Forbidden means "I know who you are, and you still may not do this" — authentication succeeded but you lack the permission, so re-authenticating will not help.' },
      { t: 'ul', items: [
        '401 — no token, expired token, or wrong credentials.',
        '403 — valid login, but the resource or action is off-limits to this user.',
      ] },
      { t: 'callout', variant: 'mistake', title: 'Common Mistake', text: 'Only asserting that the status is 200. Real APIs return 201, 204, 400, 401, 403, 404, 422 and more — each is correct in its own scenario. Assert the exact status your test expects for that case, and cover the error paths too, not just the happy path.' },
    ],
  },

  {
    slug: 'json-assertions-reference',
    title: 'JSON & Assertions Reference',
    subtitle: 'Read JSON, navigate it, and assert on it with confidence.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'p', text: 'Most modern APIs speak JSON, so reading it and asserting on it is the core skill of API testing. This reference covers JSON’s data types, how to navigate a payload with dot and bracket paths, the assertions you will use most, and a note on validating an entire response against a schema.' },
      { t: 'h1', text: 'JSON Data Types' },
      { t: 'table', headers: ['Type', 'Example', 'Notes'], rows: [
        ['String', '"Ada Lovelace"', 'Always double quotes, never single'],
        ['Number', '42 or 3.14', 'No quotes; integers and floats, no distinction'],
        ['Boolean', 'true / false', 'Lowercase, unquoted'],
        ['Null', 'null', 'Explicit absence of a value'],
        ['Object', '{ "id": 1, "name": "Ada" }', 'Unordered set of key/value pairs'],
        ['Array', '[ 1, 2, 3 ]', 'Ordered list; can hold any types'],
      ] },
      { t: 'h1', text: 'Sample Payload' },
      { t: 'p', text: 'The examples below navigate this response body: { "id": 1, "name": "Ada", "active": true, "roles": ["admin", "tester"], "address": { "city": "London", "postcode": "EC1A" } }' },
      { t: 'ul', items: [
        'id — a number (1)',
        'name — a string ("Ada")',
        'active — a boolean (true)',
        'roles — an array of strings (["admin", "tester"])',
        'address — a nested object with city and postcode',
      ] },
      { t: 'h1', text: 'Path Navigation' },
      { t: 'p', text: 'Use dot notation for object keys and bracket notation for array indices (zero-based) or awkward keys.' },
      { t: 'table', headers: ['Path', 'Resolves to', 'Note'], rows: [
        ['json.id', '1', 'Dot notation for a top-level key'],
        ['json.address.city', '"London"', 'Chain dots to go deeper'],
        ['json.roles[0]', '"admin"', 'Bracket + index for arrays (starts at 0)'],
        ['json.roles.length', '2', 'Array length'],
        ['json.roles[json.roles.length - 1]', '"tester"', 'Last element'],
        ['json[\'address\'][\'postcode\']', '"EC1A"', 'Bracket notation for keys works too'],
      ] },
      { t: 'h1', text: 'Common Assertions' },
      { t: 'p', text: 'Shown in Postman/Chai style; the same ideas apply in any test framework.' },
      { t: 'table', headers: ['Check', 'Assertion'], rows: [
        ['Status is 200', 'pm.response.to.have.status(200);'],
        ['Field equals a value', 'pm.expect(json.name).to.eql(\'Ada\');'],
        ['Field exists', 'pm.expect(json).to.have.property(\'id\');'],
        ['Type is correct', 'pm.expect(json.id).to.be.a(\'number\');'],
        ['Boolean is true', 'pm.expect(json.active).to.be.true;'],
        ['Array length', 'pm.expect(json.roles).to.have.lengthOf(2);'],
        ['Array contains value', 'pm.expect(json.roles).to.include(\'admin\');'],
        ['Nested value', 'pm.expect(json.address.city).to.eql(\'London\');'],
      ] },
      { t: 'h1', text: 'JSON Schema Validation' },
      { t: 'p', text: 'Field-by-field assertions confirm specific values; schema validation confirms the whole shape at once — which keys exist, their types, and which are required. It is the fastest way to catch a contract change (a renamed or dropped field) that individual assertions might miss.' },
      { t: 'ul', items: [
        'Define a schema describing the expected types and required fields.',
        'In Postman: pm.test(\'schema is valid\', () => { pm.expect(pm.response.json()).to.be.jsonSchema(schema); });',
        'Great for regression: one check guards the entire response contract.',
      ] },
      proTip('Combine both approaches. Use schema validation as a broad contract guard on the whole payload, then add a handful of targeted value assertions for the fields that carry business meaning. Together they catch both structural breaks and wrong data.'),
    ],
  },
];
