// Practical Test Automation with Playwright — Automation Resource Vault, batch 1.
const COURSE = 'Practical Test Automation with Playwright';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'playwright-setup-guide',
    title: 'Playwright Setup Guide',
    subtitle: 'Get a clean, working Playwright project running from scratch.',
    courseTitle: COURSE, category: 'Automation Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Before you can automate anything, you need a reliable setup. This guide takes you from nothing to a running Playwright project with TypeScript, so the rest of the course (and your portfolio) has a solid base.' },
      { t: 'h1', text: 'Prerequisites' },
      { t: 'ul', items: ['Node.js (LTS) installed', 'A code editor (VS Code recommended)', 'Basic command line familiarity'] },
      { t: 'h1', text: 'Step-by-Step' },
      { t: 'ol', items: [
        'Create a project folder and open a terminal there.',
        'Run: npm init playwright@latest',
        'Choose TypeScript, a tests folder, and add a GitHub Actions workflow when prompted.',
        'Run the example tests: npx playwright test',
        'Open the HTML report: npx playwright show-report',
      ] },
      { t: 'h1', text: 'Worked Example (project layout)' },
      { t: 'table', headers: ['Path', 'Purpose'], rows: [
        ['playwright.config.ts', 'Global config (browsers, baseURL, reporters)'],
        ['tests/', 'Your test files (*.spec.ts)'],
        ['tests-examples/', 'Generated example tests'],
        ['playwright-report/', 'HTML test report output'],
      ] },
      { t: 'h1', text: 'Verify It Works' },
      { t: 'ul', items: [
        'npx playwright test runs and passes the example tests',
        'npx playwright test --ui opens the UI mode',
        'npx playwright codegen <url> records actions',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Set up a fresh project, run the example tests, then use codegen against a public site (e.g. a demo shop) and save the generated test.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Use TypeScript from day one.', 'Commit your project to GitHub early (great for your portfolio).', 'Keep dependencies updated.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Skipping the example tests, so setup issues hide until later.', 'Not installing browsers (npx playwright install).', 'Committing node_modules instead of using .gitignore.'] },
      proTip('Push your Playwright project to GitHub from the very first commit. A public automation repo with a clear README is one of the strongest portfolio pieces a tester can show.'),
    ],
  },

  {
    slug: 'first-test-walkthrough',
    title: 'Your First Playwright Test — Walkthrough',
    subtitle: 'Write, understand and run a complete test end to end.',
    courseTitle: COURSE, category: 'Automation Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'This walkthrough takes you through a complete, readable first test so you understand every line — not just copy it. Once this clicks, the rest of automation builds on the same pattern.' },
      { t: 'h1', text: 'The Anatomy of a Test' },
      { t: 'table', headers: ['Part', 'Role'], rows: [
        ['import { test, expect }', 'Brings in the test runner and assertions'],
        ['test(\'name\', async ({ page }) => {…})', 'Defines a test with a browser page'],
        ['await page.goto(url)', 'Navigates to the app'],
        ['await page.getByRole(...)', 'Finds an element the way a user would'],
        ['await expect(...).toBeVisible()', 'Asserts the expected outcome'],
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'A login test: go to the login page, fill email and password using getByLabel, click the "Sign in" button using getByRole, then assert the dashboard heading is visible. Each step uses await because Playwright actions are asynchronous.' },
      { t: 'h1', text: 'The AAA Pattern' },
      { t: 'ul', items: [
        'Arrange — navigate and set up state',
        'Act — perform the user action',
        'Assert — verify the expected result',
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: [
        'test(\'<clear behaviour>\', async ({ page }) => {',
        '  // Arrange: await page.goto(...)',
        '  // Act: await page.getByRole(...).click()',
        '  // Assert: await expect(...).toBeVisible()',
        '});',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Write a test for a public demo site: navigate, perform one action, and assert one clear outcome. Run it and view the report.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Name tests by behaviour, not by steps.', 'Always await Playwright actions.', 'One clear behaviour per test.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Forgetting await (causes flaky/false passes).', 'Testing several behaviours in one test.', 'Vague test names like "test1".'] },
      proTip('If you can describe what a test does in one sentence, it is well-scoped. If your sentence needs an "and", consider splitting it into two tests.'),
    ],
  },

  {
    slug: 'locator-strategy-cheat-sheet',
    title: 'Playwright Locator Strategy Cheat Sheet',
    subtitle: 'Choose robust, user-facing locators that do not break.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Locators are where automation succeeds or fails. This cheat sheet shows the recommended Playwright locators in priority order, so your tests are stable and readable.' },
      { t: 'h1', text: 'Locator Priority (best first)' },
      { t: 'table', headers: ['Locator', 'Use when'], rows: [
        ['getByRole', 'Almost always — buttons, links, headings, inputs by role + name'],
        ['getByLabel', 'Form fields with a label'],
        ['getByPlaceholder', 'Inputs identified by placeholder'],
        ['getByText', 'Non-interactive text content'],
        ['getByTestId', 'When nothing user-facing is stable (data-testid)'],
        ['CSS / XPath', 'Last resort only'],
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'ul', items: [
        'page.getByRole(\'button\', { name: \'Sign in\' })',
        'page.getByLabel(\'Email address\')',
        'page.getByRole(\'heading\', { name: \'Dashboard\' })',
        'page.getByTestId(\'cart-total\')',
      ] },
      { t: 'h1', text: 'Why User-Facing Locators Win' },
      { t: 'ul', items: [
        'They survive CSS/markup refactors.',
        'They double as accessibility checks.',
        'They read like the user’s intent.',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Take a page and locate five elements using only getByRole/getByLabel/getByText. Only fall back to getByTestId if you truly cannot.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Prefer role + accessible name.', 'Add data-testid for genuinely ambiguous elements.', 'Avoid brittle CSS chains and indexes.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Long CSS selectors tied to layout.', 'Using nth-child / indexes that shift.', 'XPath everywhere "because it works".'] },
      proTip('A good rule: locate elements the way a user would describe them. If you would say "the Sign in button", use getByRole(\'button\', { name: \'Sign in\' }).'),
    ],
  },

  {
    slug: 'playwright-assertions-cheat-sheet',
    title: 'Playwright Assertions Cheat Sheet',
    subtitle: 'The web-first assertions you will use every day.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Playwright’s web-first assertions auto-wait and retry, which removes most flakiness. This cheat sheet lists the assertions you will reach for most.' },
      { t: 'h1', text: 'Element State' },
      { t: 'table', headers: ['Assertion', 'Checks'], rows: [
        ['toBeVisible()', 'Element is visible'],
        ['toBeHidden()', 'Element is hidden/absent'],
        ['toBeEnabled() / toBeDisabled()', 'Interactable state'],
        ['toBeChecked()', 'Checkbox/radio checked'],
        ['toBeFocused()', 'Element has focus'],
      ] },
      { t: 'h1', text: 'Content' },
      { t: 'table', headers: ['Assertion', 'Checks'], rows: [
        ['toHaveText()', 'Exact text'],
        ['toContainText()', 'Partial text'],
        ['toHaveValue()', 'Input value'],
        ['toHaveAttribute()', 'Attribute value'],
        ['toHaveCount()', 'Number of matched elements'],
      ] },
      { t: 'h1', text: 'Page' },
      { t: 'ul', items: ['await expect(page).toHaveURL(...)', 'await expect(page).toHaveTitle(...)'] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'await expect(page.getByRole(\'heading\', { name: \'Dashboard\' })).toBeVisible(); — Playwright retries until it is visible or times out, so you do not need manual waits.' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Add three different web-first assertions to one of your tests (state, content and page). Confirm they auto-wait by testing an element that appears after a short delay.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Prefer web-first assertions (expect(locator)) over manual checks.', 'Assert the outcome a user cares about.', 'Avoid sleeping — let assertions wait.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Using expect on a value you fetched manually instead of the locator.', 'Adding page.waitForTimeout before assertions.', 'Asserting implementation detail instead of user-visible outcome.'] },
      proTip('Web-first assertions auto-retry until the condition is met or it times out. Lean on them and you eliminate the single biggest source of flaky tests: manual waits.'),
    ],
  },

  {
    slug: 'page-object-model-template',
    title: 'Page Object Model (POM) Template',
    subtitle: 'Structure tests for reuse and maintainability with page objects.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'The Page Object Model keeps locators and actions for a page in one place, so tests read clearly and changes happen in one spot. This template gives you a clean, reusable structure.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Create one class per page/component.',
        'Keep locators and actions inside the class.',
        'Keep assertions in the test (or expose verify methods).',
      ] },
      { t: 'h1', text: 'Worked Example (LoginPage)' },
      { t: 'ul', items: [
        'class LoginPage {',
        '  constructor(page) { this.page = page; }',
        '  emailInput = () => this.page.getByLabel(\'Email\');',
        '  signInButton = () => this.page.getByRole(\'button\', { name: \'Sign in\' });',
        '  async login(email, password) { /* fill + click */ }',
        '}',
      ] },
      { t: 'h1', text: 'How the Test Reads' },
      { t: 'p', text: 'const login = new LoginPage(page); await login.goto(); await login.login(user, pass); await expect(page.getByRole(\'heading\', { name: \'Dashboard\' })).toBeVisible();' },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: [
        'Page class name:', 'URL / goto():', 'Key locators:', 'Actions (methods):', 'What the test asserts:',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Refactor one of your existing tests to use a page object. Notice how much cleaner the test reads.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['One page object per page/component.', 'Expose intent-revealing methods (login, addToCart).', 'Keep assertions out of locators-only objects.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Over-engineering POM for a tiny project.', 'Putting test logic/assertions inside page objects.', 'Duplicating locators across files instead of reusing the object.'] },
      proTip('Start simple: introduce page objects when you find yourself repeating locators. Premature abstraction is as harmful as none — let the duplication tell you when.'),
    ],
  },

  {
    slug: 'test-structure-naming-guide',
    title: 'Test Structure & Naming Conventions Guide',
    subtitle: 'Organise tests so they stay readable as your suite grows.',
    courseTitle: COURSE, category: 'Automation Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A small suite is easy; a growing one becomes a mess without conventions. This guide gives you simple rules for structuring and naming tests so the suite stays clear and maintainable.' },
      { t: 'h1', text: 'Folder & File Structure' },
      { t: 'ul', items: [
        'Group tests by feature/area (e.g. tests/auth, tests/checkout).',
        'One spec file per feature or user journey.',
        'Keep page objects, fixtures and data in their own folders.',
      ] },
      { t: 'h1', text: 'Naming Conventions' },
      { t: 'table', headers: ['Item', 'Convention', 'Example'], rows: [
        ['Spec file', 'feature.spec.ts', 'login.spec.ts'],
        ['describe block', 'Feature / area', 'describe(\'Login\')'],
        ['Test name', 'behaviour + expectation', '\'rejects an invalid password\''],
        ['Page object', 'PascalCase + Page', 'LoginPage'],
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'test.describe(\'Checkout\', () => { test(\'applies a valid discount code\', …); test(\'rejects an expired discount code\', …); }); — anyone reading the report instantly understands what is covered.' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Reorganise a small set of tests into feature folders and rename them to describe behaviour and expectation. Re-read the report — is it clearer?' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Name tests so a failure report reads like a sentence.', 'Group with describe blocks.', 'Keep one behaviour per test.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Generic names (test1, works).', 'Giant spec files covering everything.', 'No grouping, so reports are hard to scan.'] },
      proTip('Write test names so that when one fails, the report alone tells you what broke — "Checkout › rejects an expired discount code" needs no investigation to understand.'),
    ],
  },
];
