// Practical Test Automation with Playwright — Automation Resource Vault, batch 2.
const COURSE = 'Practical Test Automation with Playwright';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'playwright-config-reference',
    title: 'Playwright Config Reference',
    subtitle: 'The settings in playwright.config.ts that matter most.',
    courseTitle: COURSE, category: 'Automation Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'The config file controls how your whole suite runs. Understanding the key options lets you make tests faster, more reliable and easier to debug. This reference covers the settings you will actually touch.' },
      { t: 'h1', text: 'Key Options' },
      { t: 'table', headers: ['Option', 'What it does'], rows: [
        ['testDir', 'Where your tests live'],
        ['use.baseURL', 'Base for page.goto(\'/path\')'],
        ['use.trace', 'Capture traces (e.g. \'on-first-retry\')'],
        ['use.screenshot / video', 'Capture on failure'],
        ['retries', 'Re-run failed tests (useful in CI)'],
        ['workers', 'Parallelism'],
        ['projects', 'Run across browsers/devices'],
        ['reporter', 'Output format (html, list, etc.)'],
      ] },
      { t: 'h1', text: 'Worked Example (sensible defaults)' },
      { t: 'ul', items: [
        'use: { baseURL: \'https://app.example.com\', trace: \'on-first-retry\', screenshot: \'only-on-failure\' }',
        'retries: process.env.CI ? 2 : 0',
        'reporter: \'html\'',
        'projects: [{ name: \'chromium\' }, { name: \'firefox\' }, { name: \'webkit\' }]',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Set a baseURL and switch your tests to relative paths. Enable trace on-first-retry and confirm a trace is produced when a test is retried.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Use baseURL so tests are environment-portable.', 'Enable traces/screenshots on failure for fast debugging.', 'Use retries in CI, not locally.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Hard-coding full URLs everywhere.', 'High retries hiding genuinely flaky tests.', 'No artefacts captured on failure, so CI failures are hard to diagnose.'] },
      proTip('Set retries in CI but keep them at 0 locally. Retries mask flakiness — you want to see and fix it on your machine, not paper over it in the pipeline.'),
    ],
  },

  {
    slug: 'auto-waiting-guide',
    title: 'Auto-Waiting & Handling Async Guide',
    subtitle: 'Stop fighting timing issues — work with Playwright’s auto-waiting.',
    courseTitle: COURSE, category: 'Automation Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Most flaky tests come from timing. Playwright auto-waits for elements to be actionable and for assertions to pass — if you let it. This guide shows you how to rely on that and avoid manual sleeps.' },
      { t: 'h1', text: 'How Auto-Waiting Works' },
      { t: 'ul', items: [
        'Actions (click, fill) wait for the element to be visible, stable and enabled.',
        'Web-first assertions (expect(locator)) retry until they pass or time out.',
        'You almost never need manual waits.',
      ] },
      { t: 'h1', text: 'Do This, Not That' },
      { t: 'table', headers: ['Avoid', 'Use instead'], rows: [
        ['page.waitForTimeout(3000)', 'await expect(locator).toBeVisible()'],
        ['Manual polling loops', 'Web-first assertions'],
        ['Sleep then click', 'Just click — it auto-waits'],
        ['waitForSelector then act', 'Act on the locator directly'],
      ] },
      { t: 'h1', text: 'When You Do Need to Wait' },
      { t: 'ul', items: [
        'await page.waitForURL(...) after a navigation',
        'await page.waitForResponse(...) for a specific network call',
        'await expect(...) for the visible result of async work',
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'Instead of waiting 3 seconds for a toast, assert it: await expect(page.getByText(\'Saved\')).toBeVisible(); — Playwright retries until it appears, so the test is both faster and more reliable.' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Find any waitForTimeout in your tests and replace it with a web-first assertion. Confirm the test still passes and runs faster.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Assert outcomes instead of sleeping.', 'Wait on events (URL, response), not arbitrary time.', 'Trust auto-waiting for actions.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Sprinkling waitForTimeout to "fix" flakiness.', 'Waiting on fixed times that fail under load.', 'Re-implementing waits Playwright already does.'] },
      proTip('Every fixed waitForTimeout is either too long (slow suite) or too short (flaky). Replace them all with assertions on the actual outcome you are waiting for.'),
    ],
  },

  {
    slug: 'api-testing-with-playwright-template',
    title: 'API Testing with Playwright Template',
    subtitle: 'Test APIs directly and combine them with UI tests.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Playwright can test APIs directly via request — faster and more stable than the UI, and great for setting up state. This template covers standalone API tests and using the API to speed up UI tests.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Use the request fixture for API calls.',
        'Assert status, body and key fields.',
        'Use API calls to set up data before UI tests.',
      ] },
      { t: 'h1', text: 'Worked Example (standalone API test)' },
      { t: 'ul', items: [
        'test(\'creates a user\', async ({ request }) => {',
        '  const res = await request.post(\'/api/users\', { data: { name: \'Test\' } });',
        '  expect(res.status()).toBe(201);',
        '  const body = await res.json();',
        '  expect(body.name).toBe(\'Test\');',
        '});',
      ] },
      { t: 'h1', text: 'Using API to Seed UI Tests' },
      { t: 'p', text: 'Create the data you need via request.post (fast, reliable), then drive only the behaviour under test through the UI. This avoids slow, brittle setup clicks.' },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: ['Endpoint:', 'Method:', 'Request data:', 'Expected status:', 'Expected body fields:', 'Cleanup needed?'] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Write one API test against a public API (assert status + a field), then write a UI test that uses an API call to set up its starting state.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Assert status and the fields that matter.', 'Use API setup to keep UI tests focused and fast.', 'Clean up data you create where possible.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Doing all setup through slow UI clicks.', 'Only checking status, never the body.', 'Leaving test data behind and polluting environments.'] },
      proTip('The fastest UI tests do their setup via the API. Reserve the UI for the behaviour you are actually testing — everything else is faster and more stable through request.'),
    ],
  },

  {
    slug: 'visual-screenshot-testing-guide',
    title: 'Visual & Screenshot Testing Guide',
    subtitle: 'Catch unintended visual changes with snapshot testing.',
    courseTitle: COURSE, category: 'Automation Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Visual regression testing catches changes functional tests miss — layout breaks, missing styles, shifted components. Playwright has built-in snapshot comparison. This guide shows you how to use it well.' },
      { t: 'h1', text: 'How It Works' },
      { t: 'ul', items: [
        'await expect(page).toHaveScreenshot() captures and compares an image.',
        'The first run creates a baseline; later runs compare against it.',
        'Update baselines deliberately with --update-snapshots.',
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'ul', items: [
        'await expect(page).toHaveScreenshot(\'dashboard.png\');',
        'await expect(page.getByRole(\'navigation\')).toHaveScreenshot(\'nav.png\');',
      ] },
      { t: 'h1', text: 'Keeping Visual Tests Stable' },
      { t: 'table', headers: ['Problem', 'Mitigation'], rows: [
        ['Animations', 'Disable or wait for them to finish'],
        ['Dynamic data/dates', 'Mask or stub them'],
        ['Font rendering differences', 'Run in CI/containers consistently'],
        ['Full-page noise', 'Snapshot a component, not the whole page'],
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Add a screenshot assertion for one stable component. Make a small CSS change and confirm the test fails, then update the baseline intentionally.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Snapshot stable components, not noisy full pages.', 'Control dynamic content before snapshotting.', 'Update baselines deliberately and review the diff.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Snapshotting pages full of changing data.', 'Blindly updating baselines to make tests pass.', 'Different rendering locally vs CI causing false diffs.'] },
      proTip('Run and store visual baselines in the same environment (usually CI/containers) every time. Local font and rendering differences are the number-one cause of false visual failures.'),
    ],
  },

  {
    slug: 'test-data-management-template',
    title: 'Test Data Management Template',
    subtitle: 'Keep test data clean, isolated and maintainable.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Poor test data causes flaky, order-dependent tests. This template helps you manage data so each test is independent and repeatable.' },
      { t: 'h1', text: 'Principles' },
      { t: 'ul', items: [
        'Each test owns its data; no test depends on another.',
        'Create what you need (preferably via API), then clean up.',
        'Avoid relying on pre-existing shared records.',
      ] },
      { t: 'h1', text: 'Approaches' },
      { t: 'table', headers: ['Approach', 'When to use'], rows: [
        ['Inline data', 'Simple, self-contained tests'],
        ['Data files (JSON)', 'Reusable fixtures and parameterised tests'],
        ['Factory functions', 'Generating varied valid records'],
        ['API setup/teardown', 'Fast, reliable state for UI tests'],
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: 'A test generates a unique email (e.g. user+timestamp), creates the account via API, runs the UI behaviour, then deletes the account in teardown — so it can run any number of times in any order.' },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: ['Data needed:', 'How it is created:', 'How uniqueness is ensured:', 'Cleanup/teardown:', 'Independent of other tests? (Y/N)'] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Take a test that reuses shared data and refactor it to create its own unique data and clean up afterwards. Run it twice in a row to confirm independence.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Generate unique data to avoid collisions.', 'Prefer API setup/teardown.', 'Never depend on test execution order.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Tests sharing one record and interfering.', 'Hard-coded data that breaks on re-run.', 'No cleanup, leaving environments messy.'] },
      proTip('A reliable suite has tests that pass in any order, run alone or together, any number of times. If yours do not, data coupling is almost always the cause.'),
    ],
  },

  {
    slug: 'fixtures-and-hooks-guide',
    title: 'Fixtures & Hooks Guide',
    subtitle: 'Set up and tear down cleanly with fixtures and hooks.',
    courseTitle: COURSE, category: 'Automation Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Fixtures and hooks remove repetitive setup and keep tests focused. This guide explains when to use each so your suite stays DRY without becoming confusing.' },
      { t: 'h1', text: 'Hooks' },
      { t: 'table', headers: ['Hook', 'Runs'], rows: [
        ['beforeEach', 'Before every test (common setup)'],
        ['afterEach', 'After every test (cleanup)'],
        ['beforeAll', 'Once before all tests in a file/describe'],
        ['afterAll', 'Once after all tests'],
      ] },
      { t: 'h1', text: 'Custom Fixtures' },
      { t: 'p', text: 'Fixtures provide ready-made objects to tests — e.g. a logged-in page, or a page object. They are created on demand and torn down automatically, which is cleaner than repeated beforeEach logic.' },
      { t: 'h1', text: 'Worked Example (logged-in fixture)' },
      { t: 'ul', items: [
        'export const test = base.extend({',
        '  loggedInPage: async ({ page }, use) => {',
        '    await login(page); await use(page);',
        '  },',
        '});',
        '// test(\'…\', async ({ loggedInPage }) => { /* already logged in */ })',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Move repeated login steps from beforeEach into a custom fixture, and use it in two tests. Notice how much shorter the tests become.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Use fixtures for reusable state (login, data, page objects).', 'Keep setup close to where it is needed.', 'Tear down what you create.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Heavy beforeAll state shared (and mutated) across tests.', 'Over-abstracting setup so tests are hard to follow.', 'Forgetting teardown, leaking state.'] },
      proTip('Fixtures beat beforeEach for reusable setup because they are composable and torn down automatically. Reach for a fixture as soon as two tests need the same starting state.'),
    ],
  },
];
