// AI for QA Testers — Assignment Briefs (one per module).
import { makeBrief } from './briefs-lib.mjs';

const COURSE = 'AI for QA Testers';
const b = (n, moduleTitle, spec) => makeBrief({ courseSlug: 'ai-for-qa-testers', courseTitle: COURSE, moduleNumber: n, moduleTitle, slug: `ai-m${n}-assignment-brief`, ...spec });

export default [
  b(1, 'The AI Shift in QA', {
    scenario: 'Your team is starting to use AI and your lead wants to see you have a balanced, realistic view — where AI genuinely helps testers and where human judgement must stay in control.',
    objectives: ['Explain where AI helps in QA', 'Identify decisions that must stay human', 'Set realistic expectations of AI'],
    deliverables: ['A one-page reflection on AI in QA', 'Five testing tasks AI can assist with and three decisions that must stay with a human, each with a reason'],
    steps: ['List routine testing tasks AI could speed up', 'List quality/risk decisions that must stay human', 'Give a short reason for each', 'Conclude with your one-line position on AI in QA'],
    format: 'Submit as a PDF or DOCX, around one page.',
    assessment: ['A balanced, realistic view of AI', 'Clear examples of where it helps', 'Awareness of limits and the tester’s accountability'],
    resources: ['AI Usage Policy Template', 'AI-Assisted QA Workflow Poster'],
    proTip: 'Frame AI as a productivity multiplier, not a replacement — that balanced view is exactly what employers want to hear.',
  }),
  b(2, 'AI Fundamentals for Testers', {
    scenario: 'Before relying on AI output, you need to understand how it behaves — why it can sound confident yet be wrong — and how to use it securely.',
    objectives: ['Explain how LLMs generate output (simply)', 'Recognise hallucinations and limitations', 'State secure, responsible-use rules'],
    deliverables: ['Three of your own prompts, each with the output and whether you spotted a hallucination or limitation', 'Two rules you will follow for responsible AI use'],
    steps: ['Run three prompts through an AI tool', 'For each, record the prompt, output, and any inaccuracy', 'Note how confidently it presented anything wrong', 'Write two responsible-use rules'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['Clear, simple grasp of how LLMs work', 'Awareness of hallucinations and limits', 'Concrete data-safety and verification rules'],
    resources: ['AI Hallucination Checklist', 'AI Usage Policy Template'],
    proTip: 'Be most sceptical of precise specifics — field names, numbers, rules. The more exact and confident the detail, the harder you verify it.',
  }),
  b(3, 'Prompt Engineering for QA', {
    scenario: 'Your prompts are producing shallow output. You need to write structured prompts that reliably generate useful, specific QA results.',
    objectives: ['Write structured prompts (role/context/task/format/constraints)', 'Improve a weak prompt', 'Build reusable prompt patterns'],
    deliverables: ['Five well-structured QA prompts for different testing tasks', 'A before/after for one weak prompt you improved'],
    steps: ['Pick five testing tasks', 'Write a structured prompt for each using the five-part anatomy', 'Take one weak prompt and improve it; show both versions', 'Note when you would use each prompt'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['Well-structured prompts (role/context/task/format/constraints)', 'A clear before/after improvement', 'Patterns you can reuse'],
    resources: ['Prompt Writing Framework', 'AI Prompt Cheat Sheet for Testers'],
    proTip: 'Bake your standards into the prompt up front (format + constraints like "do not invent fields") — far faster than fixing weak output afterwards.',
  }),
  b(4, 'Requirements Analysis with AI', {
    scenario: 'A new story is heading into the sprint. You will use AI to surface ambiguity, gaps and untestable criteria so you can raise sharp questions before code is written.',
    objectives: ['Use AI to find gaps and ambiguity', 'Turn findings into team questions', 'Confirm acceptance criteria are testable'],
    deliverables: ['A review of a real or sample user story', 'Five sharp questions for the team, with the two most important marked'],
    steps: ['Paste a (sanitised) user story and prompt AI to find ambiguity, gaps and untestable criteria', 'Turn the output into clear questions', 'Mark the two most important by risk', 'Propose testable acceptance criteria where weak'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['Real ambiguities and gaps identified', 'Findings turned into sharp questions', 'Testable acceptance criteria proposed', 'Gaps prioritised by risk'],
    resources: ['AI Requirement Review Workbook'],
    proTip: 'Turn AI’s findings into questions, not accusations — that is how value is added at refinement.',
  }),
  b(5, 'AI-Assisted Test Case Design', {
    scenario: 'You need test cases for a feature quickly. You will generate them with AI, then review and harden them so they reach the same bar as work you wrote yourself.',
    objectives: ['Generate test cases with AI', 'Review and improve AI output', 'Prioritise by risk'],
    deliverables: ['AI-generated test cases for a feature', 'A review note: what you kept, changed and rejected (including a hallucination removed and a boundary case added)'],
    steps: ['Prompt AI for positive/negative/boundary cases', 'Review against the checklist — remove invented cases, add missing boundaries', 'Tighten vague expected results', 'Prioritise by risk'],
    format: 'Submit as a PDF or DOCX — generated set plus your review notes.',
    assessment: ['Generated cases hardened by review', 'Boundary/negative coverage added', 'Hallucinations removed; risk-prioritised', 'Specific expected results'],
    resources: ['AI Test Case Review Checklist', 'AI Validation Checklist'],
    proTip: 'The review is what proves QA skill — anyone can generate; a professional catches what is wrong or missing.',
  }),
  b(6, 'Exploratory Testing with AI', {
    scenario: 'You have a feature and a time-box. You will use AI to generate charters and personas, then do the actual exploring and capture what you find.',
    objectives: ['Generate charters and personas with AI', 'Explore against the real product', 'Let findings drive new charters'],
    deliverables: ['10 AI-generated charters for a feature', 'Notes from two short sessions', 'Three follow-up charters your findings revealed'],
    steps: ['Prompt AI for charters and personas', 'Run two time-boxed sessions, taking notes', 'Log findings and surprises', 'Create follow-up charters from what you found'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['Charters used as a start, then real exploration', 'Clear session notes and findings', 'Follow-up charters from surprises', 'Security/usability/edge angles covered'],
    resources: ['AI Exploratory Testing Workbook'],
    proTip: 'AI gives you more doors to try; exploratory skill is knowing which to open and what you notice once inside.',
  }),
  b(7, 'Defect Reporting and Root Cause Support', {
    scenario: 'You found a defect and want AI to help you write it up clearly and reason about the cause — while you stay accountable for every technical fact.',
    objectives: ['Use AI to sharpen a bug report', 'Reason about root cause with AI', 'Verify all technical detail'],
    deliverables: ['A bug report you wrote, plus the AI-improved version', 'Three wording improvements you accepted and one suggestion you rejected because it was wrong'],
    steps: ['Write a bug report yourself with the real facts', 'Ask AI to review it for clarity, structure and completeness (sanitised)', 'Apply genuine improvements; verify every technical detail', 'Note one suggestion you rejected and why'],
    format: 'Submit as a PDF or DOCX, before and after.',
    assessment: ['Clearer reports with verified facts', 'AI used for wording, not invented facts', 'Data sanitised before pasting', 'Severity/priority owned by you'],
    resources: ['AI Bug Report Review Guide'],
    proTip: 'Let AI improve the words; you own the facts. The developer acts on your facts — so verify them.',
  }),
  b(8, 'API Testing with AI', {
    scenario: 'You are handed an unfamiliar API. You will use AI to understand it and generate test ideas, then verify everything against the real API before relying on it.',
    objectives: ['Use AI to understand endpoints', 'Generate API test ideas including error cases', 'Verify AI output against the real API'],
    deliverables: ['8 API test ideas (method, purpose, expected result) for a public API', 'A note of any AI suggestion you had to correct'],
    steps: ['Pick a public API and ask AI to explain key endpoints', 'Generate test ideas including negative/error cases', 'Verify fields and status codes against the real docs', 'Record any inaccuracies you corrected'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['Good test ideas including error cases', 'Details verified against the real API', 'Risk thinking (auth, validation, exposure)', 'Hallucinated fields caught'],
    resources: ['AI Prompt Library (100 Prompts)'],
    proTip: 'Confirm specifics (field names, status codes) against the real docs before building tests on them — AI can invent plausible-sounding fields.',
  }),
  b(9, 'Automation Support with AI', {
    scenario: 'You are using AI to support an automation task. You will show AI accelerating the work while you keep ownership — good locators, verified fixes, code you understand.',
    objectives: ['Use AI to support automation', 'Apply good-practice judgement to AI output', 'Verify before trusting'],
    deliverables: ['One AI-supported automation task (generate test data, draft a selector strategy, or explain an error)', 'A note of what AI produced and what you verified or changed'],
    steps: ['Pick an automation task and prompt AI for help', 'Review the output (locators robust? code understood?)', 'Fix anything brittle and verify the result', 'Document what you accepted and changed'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['AI used to accelerate, with output reviewed', 'Robust locators and verified fixes', 'Synthetic data only', 'Code you can explain'],
    resources: ['AI Prompt Library (100 Prompts)'],
    proTip: 'Copying code you cannot debug just moves the problem downstream — run and understand everything before trusting it.',
  }),
  b(10, 'AI in Agile QA Workflows', {
    scenario: 'You will show how to weave AI through one sprint — refinement, regression scoping, reporting — using it to prepare and summarise while you lead the decisions.',
    objectives: ['Use AI across sprint stages', 'Scope a risk-based regression set', 'Report quality led by risk'],
    deliverables: ['How you would use AI across one sprint', 'For a recent change: AI-brainstormed impacted areas and a prioritised regression set with a one-line scope justification'],
    steps: ['Describe AI’s role at refinement, planning, regression and reporting', 'For a change, use AI to list impacted areas', 'Filter by real risk into a prioritised set', 'Justify the scope in one line'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['AI used to prepare and summarise', 'Risk-led regression scope with justification', 'Human collaboration kept central', 'Reports led by risk, not counts'],
    resources: ['AI Regression Planning Template'],
    proTip: 'AI widens what could break; you narrow it to what matters. Always cover the critical journeys and record why you included/excluded areas.',
  }),
  b(11, 'AI Risks, Ethics and Governance', {
    scenario: 'Your team needs to use AI responsibly. You will demonstrate the data, bias, accountability and transparency thinking expected of a professional.',
    objectives: ['Apply data-handling rules', 'Recognise bias and reliability risks', 'State review controls and accountability'],
    deliverables: ['Your personal responsible-AI statement (data, verification, accountability)', 'The AI Risk Assessment Checklist applied to a real task, with any failing item reworked to pass', 'One unsafe prompt reworked into a safe one'],
    steps: ['Write your four-point governance statement', 'Apply the risk checklist to a real task', 'Rework anything that fails', 'Show an unsafe→safe prompt example'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['Clear data-handling rules', 'Awareness of bias and hallucination', 'Explicit review/accountability', 'Concrete safe/unsafe examples'],
    resources: ['AI Ethics & Governance Guide for QA', 'AI Risk Assessment Checklist'],
    proTip: 'A simple test before sending any prompt: "would I be comfortable if this were public?" If not, do not send it.',
  }),
  b(12, 'Building Your AI QA Workflow', {
    scenario: 'This is your capstone: assemble a complete, repeatable, responsible AI QA workflow and toolkit you could actually use on the job.',
    objectives: ['Design a repeatable AI-assisted workflow', 'Build a personal toolkit', 'Show responsible use and judgement'],
    deliverables: ['Your AI QA Pack: a workflow across the sprint, a toolkit (5 saved prompts + tool-per-task + rules), one worked example (prompt → output → your review), and your governance statement'],
    steps: ['Map where AI helps at each sprint stage and what you verify', 'Capture your saved prompts, tools and rules', 'Include one worked example with your review notes', 'Add your governance statement'],
    format: 'Submit as a PDF or DOCX — your complete AI QA Pack.',
    assessment: ['A repeatable, sensible workflow', 'A real toolkit with safe rules', 'A worked example showing review/judgement', 'Clear governance'],
    resources: ['Personal AI Toolkit Planner', 'AI-Assisted QA Workflow Poster'],
    proTip: 'Your prompt library is a career asset — a tester who arrives with a proven AI toolkit ramps up far faster than one starting from zero.',
  }),
];
