// Practical Test Automation with Playwright — Assignment Briefs (one per module).
import { makeBrief } from './briefs-lib.mjs';

const COURSE = 'Practical Test Automation with Playwright';
const b = (n, moduleTitle, spec) => makeBrief({ courseSlug: 'practical-test-automation-playwright', courseTitle: COURSE, moduleNumber: n, moduleTitle, slug: `pw-m${n}-assignment-brief`, ...spec });

export default [
  b(1, 'Automation Fundamentals', {
    scenario: 'Your team is considering automation and wants your judgement on what to automate — and what to keep manual — with clear, defensible reasoning.',
    objectives: ['Decide what to automate using sound criteria', 'Apply the test pyramid (right layer)', 'Justify each decision'],
    deliverables: ['A review of 20 sample test cases', 'For each: automate or keep manual, the layer, and a one-line reason'],
    steps: ['Take 20 sample test cases', 'For each, decide automate/manual and the layer', 'Justify against frequency, stability, value and maintenance', 'Summarise your automation strategy'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['Sensible automate/not-automate decisions with reasons', 'Awareness of the pyramid', 'No "automate everything" without reasoning', 'Decisions justified by risk and ROI'],
    resources: ['Automation Best Practices Checklist'],
    proTip: 'Knowing what NOT to automate (volatile, one-off, exploratory) is as important as what to automate — say so explicitly.',
  }),
  b(2, 'Behaviour Driven Development', {
    scenario: 'Your team uses BDD. You need to express behaviour in clear, readable Gherkin that a product owner could confirm without seeing any code.',
    objectives: ['Write clear feature files', 'Use scenarios and scenario outlines', 'Keep steps at the behaviour level'],
    deliverables: ['Feature files for Login, Checkout and Registration', 'Including happy-path, negative and at least one scenario outline with an examples table'],
    steps: ['Write a Feature with scenarios for each flow', 'Add negative scenarios and a scenario outline', 'Keep steps declarative (behaviour, not clicks)', 'Check a non-technical reader could follow them'],
    format: 'Submit as a PDF/DOCX or a link to the .feature files.',
    assessment: ['Readable, declarative scenarios', 'Negative and outline coverage', 'Consistent vocabulary', 'Business language, not technical detail'],
    resources: ['Test Structure & Naming Conventions Guide'],
    proTip: 'The readability test: could a non-technical colleague read your feature file and confirm the behaviour is right? If not, simplify the language.',
  }),
  b(3, 'Step Definitions', {
    scenario: 'Your feature files need to run. You will convert them into thin, reusable step definitions that delegate to page objects.',
    objectives: ['Map features to step definitions', 'Keep steps thin and reusable', 'Avoid duplication'],
    deliverables: ['Working step definitions for your Module 2 feature files', 'Evidence they are thin (delegating to page objects) and free of duplication'],
    steps: ['Implement Given/When/Then for each scenario', 'Keep each step to one responsibility, delegating to page objects', 'Parameterise steps for data-driven scenarios', 'Remove or merge any near-duplicate steps'],
    format: 'Submit your step definition code as a PDF/DOCX export or a repository link.',
    assessment: ['Thin glue delegating to page objects', 'Given/When/Then used correctly', 'Reusable, parameterised steps', 'No duplicate steps'],
    resources: ['Code Review Checklist for Test Automation'],
    proTip: 'Treat step definitions as glue, not logic — the thinner they are, the more your framework’s strength lives in well-tested page objects.',
  }),
  b(4, 'Playwright Essentials', {
    scenario: 'Time to write real Playwright tests. You will build your first suite using robust locators and web-first assertions — no fixed waits.',
    objectives: ['Use robust, user-facing locators', 'Use web-first assertions', 'Run and debug tests'],
    deliverables: ['A Playwright suite of at least five tests', 'A screenshot of a passing run and your config'],
    steps: ['Set up the project and pick a target app', 'Write five tests using getByRole/getByLabel and web-first assertions', 'Avoid waitForTimeout entirely', 'Run the suite and capture a passing report'],
    format: 'Submit as a PDF/DOCX or a repository link.',
    assessment: ['Robust, user-facing locators', 'Web-first assertions, no fixed waits', 'One behaviour per test', 'A clean passing run'],
    resources: ['Playwright Locator Strategy Cheat Sheet', 'Playwright Assertions Cheat Sheet'],
    proTip: 'Locate elements the way a user describes them — "the Sign in button" → getByRole(\'button\', { name: \'Sign in\' }). It is the single biggest factor in stable tests.',
  }),
  b(5, 'Page Object Model', {
    scenario: 'Your suite is growing and locators are repeating. You will introduce page objects so changes happen in one place and tests read clearly.',
    objectives: ['Design clean page objects', 'Separate actions from assertions', 'Refactor tests to use them'],
    deliverables: ['Page objects for Login, Dashboard, Shopping Basket and Checkout', 'A test refactored to use them, showing how it reads'],
    steps: ['Create a page object per page with intent-revealing methods', 'Keep locators encapsulated; assertions in the test', 'Refactor your tests to use the page objects', 'Note how much cleaner the tests read'],
    format: 'Submit as a PDF/DOCX or a repository link.',
    assessment: ['Intent-revealing methods, encapsulated locators', 'Assertions in the test, not the page object', 'One page object per page', 'Tests read clearly'],
    resources: ['Page Object Model (POM) Template'],
    proTip: 'Name methods after what the user does, not what the code does — addToBasket() reads better than clickAddButton() and survives UI changes.',
  }),
  b(6, 'Test Data Management', {
    scenario: 'Your tests must be reliable and repeatable. You will manage test data so each test owns its data and runs in any order.',
    objectives: ['Generate unique, valid data', 'Use a data file and a factory', 'Keep tests data-independent'],
    deliverables: ['A factory that generates unique valid records', 'One JSON or CSV data set driving a parameterised test', 'A test shown creating and cleaning up its own data'],
    steps: ['Write a factory returning a valid record with a unique email', 'Move a data set into JSON/CSV and drive a parameterised test', 'Make a test create and clean up its own data', 'Run it twice to confirm independence'],
    format: 'Submit as a PDF/DOCX or a repository link.',
    assessment: ['Unique, valid generated data', 'Data file driving a parameterised test', 'Self-cleaning, order-independent tests', 'No secrets in code'],
    resources: ['Test Data Management Template'],
    proTip: 'A reliable test passes alone or with others, in any order, any number of times. If yours pass solo but fail together, data coupling is the cause.',
  }),
  b(7, 'Framework Architecture', {
    scenario: 'Your framework needs to scale. You will refactor it into a clean, reusable structure that the 100th test is as easy to add to as the 10th.',
    objectives: ['Structure a scalable framework', 'Extract utilities and base classes', 'Add logging and reporting'],
    deliverables: ['Your framework refactored into a clear structure (tests, pages, components, fixtures, utils, data)', 'A short note explaining two architecture decisions'],
    steps: ['Organise files by concern', 'Extract helpers and a thin base/fixtures for shared setup', 'Add reporting and useful logging', 'Document your structure and two decisions'],
    format: 'Submit as a PDF/DOCX or a repository link.',
    assessment: ['Clear, scalable structure', 'Reusable utilities/fixtures (no copy-paste)', 'Logging and reporting present', 'Parallel-safe, independent tests'],
    resources: ['Test Structure & Naming Conventions Guide', 'Automation Best Practices Checklist'],
    proTip: 'Prefer composition (fixtures, components) over deep inheritance — one thin BasePage is helpful; a five-level hierarchy is a maintenance trap.',
  }),
  b(8, 'API Automation', {
    scenario: 'Not everything needs the browser. You will automate a public REST API and use API calls to set up state for a UI test.',
    objectives: ['Automate REST API tests with Playwright', 'Validate status and response bodies', 'Use the API to seed a UI test'],
    deliverables: ['At least five API tests (GET/POST and an error case), asserting status and key fields', 'One UI test that uses an API call to set up its starting state'],
    steps: ['Use the request fixture to test a public API', 'Assert status and meaningful body fields, plus an error case', 'Create data via the API to seed a UI test', 'Keep credentials in environment variables'],
    format: 'Submit as a PDF/DOCX or a repository link.',
    assessment: ['Meaningful assertions on body and status', 'A negative/error case included', 'API-driven setup for the UI test', 'No hard-coded secrets'],
    resources: ['API Testing with Playwright Template'],
    proTip: 'The fastest UI tests do their setup via the API — reserve the UI for the behaviour you are actually testing.',
  }),
  b(9, 'Git & CI/CD', {
    scenario: 'Automated tests deliver most value when they run automatically. You will connect your framework to GitHub and run it on every push via GitHub Actions.',
    objectives: ['Use Git and pull requests', 'Run Playwright in GitHub Actions', 'Upload reports as artefacts'],
    deliverables: ['A GitHub Actions workflow that installs browsers, runs the suite and uploads the report', 'A link to a successful (green) workflow run', 'A short note on your setup'],
    steps: ['Push your framework to GitHub', 'Add a workflow (checkout, setup-node, npm ci, install --with-deps, test, upload report)', 'Trigger it on push and pull_request', 'Confirm a green run and capture the link'],
    format: 'Submit a link (URL) to a successful workflow run, plus your setup note.',
    assessment: ['A working CI workflow', 'Browsers installed with --with-deps', 'Report uploaded as an artefact', 'A green run on push/PR'],
    resources: ['CI/CD Integration Guide (GitHub Actions)'],
    proTip: 'A green CI badge on a public repo is a powerful portfolio signal — it shows you can wire tests into a real pipeline, not just write them.',
  }),
  b(10, 'AI Assisted Automation', {
    scenario: 'You will use AI to improve an automation framework — generating or refactoring tests — while keeping ownership and using it responsibly.',
    objectives: ['Use AI to accelerate automation', 'Review and conform generated code', 'Apply responsible-AI practice'],
    deliverables: ['An AI-improved test or page object', 'The prompts you used, what AI produced, and what you verified or changed before trusting it', 'Your responsible-AI rules'],
    steps: ['Use AI to generate or refactor part of your framework', 'Review the output (robust locators? code understood?)', 'Conform it to your patterns and verify it runs', 'Record prompts, changes, and your safety rules'],
    format: 'Submit as a PDF or DOCX.',
    assessment: ['AI used to accelerate, with code reviewed', 'Brittle locators fixed; fixes verified', 'No secrets/proprietary code shared', 'Code you can explain'],
    resources: ['AI Prompt Library for Automation Engineers', 'Code Review Checklist for Test Automation'],
    proTip: 'Generated code that does not match your conventions creates inconsistency debt — always conform it to your patterns before it lands.',
  }),
  b(11, 'Framework Maintenance', {
    scenario: 'You are handed an intentionally poor or flaky framework. You will diagnose and fix it, proving reliability — without papering over problems with retries.',
    objectives: ['Diagnose flaky tests', 'Fix the root cause', 'Prove reliability'],
    deliverables: ['A fixed flaky/poor test', 'A before/after: the diagnosis (checklist + trace), the fix, and a repeat-each run proving stability'],
    steps: ['Reproduce the flakiness with --repeat-each', 'Use the checklist and trace to find the root cause', 'Fix it (remove sleeps/brittleness; make data independent)', 'Re-run repeatedly to confirm it is stable'],
    format: 'Submit as a PDF or DOCX, documenting before and after.',
    assessment: ['Root cause found, not masked', 'Sleeps/brittleness removed', 'Reliability proven by repeat-each', 'No retries used to hide flakiness'],
    resources: ['Flaky Test Troubleshooting Checklist'],
    proTip: 'A test you cannot make fail reliably is one you cannot prove you have fixed — run --repeat-each to expose flakiness on demand.',
  }),
  b(12, 'Portfolio Project', {
    scenario: 'Your capstone: build a complete automation framework and publish it as a public GitHub repository for self-review against the model solution.',
    objectives: ['Build an end-to-end framework', 'Document it professionally', 'Publish it with green CI'],
    deliverables: ['A public GitHub repo with BDD, feature files, step definitions, Playwright tests, page objects, utilities, configuration, reporting and a CI pipeline', 'A professional README', 'A green CI run'],
    steps: ['Build the framework to the quality bar (robust locators, web-first assertions, independent data, page objects, an API test)', 'Wire up GitHub Actions and confirm green CI', 'Write a clear README (overview, how to run, coverage, tech)', 'Publish public and prepare a 60-second walkthrough'],
    format: 'Submit your public GitHub repository URL for self-review against the model solution.',
    assessment: ['A focused, complete framework (BDD, page objects, API, CI)', 'Robust locators and reliable tests', 'A clear README and green CI', 'Ability to explain your design choices'],
    resources: ['Automation Portfolio Project Workbook', 'Playwright Command Cheat Sheet'],
    proTip: 'A public Playwright repo with green CI and a clear README does more for your job hunt than any certificate — it shows exactly how you think and code.',
  }),
];
