// 90-Day Software Testing Career Roadmap — Assignment Briefs (one per module).
import { makeBrief } from './briefs-lib.mjs';

const COURSE = '90-Day Software Testing Career Roadmap';
const b = (n, moduleTitle, spec) => makeBrief({ courseSlug: '90-day-software-testing-career-roadmap', courseTitle: COURSE, moduleNumber: n, moduleTitle, slug: `90day-m${n}-assignment-brief`, ...spec });

export default [
  b(1, 'Introduction to Software Testing', {
    scenario: 'You have joined a software team and your lead asks you to show you understand the fundamentals before you start testing — how software is built, the types of testing, and where a QA tester adds value.',
    objectives: ['Explain the six stages of the SDLC', 'Describe at least three types of testing with examples', 'Explain how a QA tester adds value across the lifecycle'],
    deliverables: ['A short written piece (1–2 pages) covering the SDLC, testing types and the QA role', 'A concrete running example (e.g. a profile-photo upload) used throughout'],
    steps: ['Pick a simple feature to use as your running example', 'Explain each SDLC stage and what happens to your feature there', 'Describe three testing types you would apply, with an example each', 'Explain where the tester adds value at each stage (especially early)'],
    format: 'Submit as a PDF or DOCX, 1–2 pages, clearly structured with headings.',
    assessment: ['Correct use of terms (SDLC, testing types) in your own words', 'A concrete example rather than only definitions', 'Testing framed as risk information, not just bug-finding', 'Clear, professional, proofread writing'],
    resources: ['SDLC Cheat Sheet', 'Software Testing Glossary'],
    proTip: 'Use one running example throughout — it shows you can connect the concepts, which reads far more convincingly than separate definitions.',
  }),
  b(2, 'Test Design Techniques', {
    scenario: 'Your team needs test cases for a new feature and your lead wants to see that you design coverage deliberately using recognised techniques — not by clicking around.',
    objectives: ['Apply equivalence partitioning and boundary value analysis', 'Use a decision table and/or state transition where relevant', 'Write clear, repeatable test cases'],
    deliverables: ['A test case pack (10+ cases) for a feature of your choice', 'Each case annotated with the technique it uses'],
    steps: ['Choose a feature with a few inputs and rules', 'Derive partitions and boundary values for each input', 'Build a decision table or state diagram if behaviour depends on combinations/states', 'Write the test cases (title, steps, data, expected result) and tag each with its technique'],
    format: 'Submit as a PDF or DOCX (or spreadsheet) — a clear, structured test case pack.',
    assessment: ['Techniques named and applied correctly', 'Both valid and invalid/edge cases covered', 'Specific, verifiable expected results', 'No vague "it works" outcomes'],
    resources: ['Test Case Template', 'Software Testing Glossary'],
    proTip: 'Annotating which technique each case uses turns a list of tests into evidence that you think about coverage — exactly what a reviewer wants to see.',
  }),
  b(3, 'Defect Management', {
    scenario: 'Testing an application, you find a series of issues and need to log them so developers can fix them quickly — clear, reproducible, and correctly prioritised.',
    objectives: ['Write professional, reproducible bug reports', 'Apply severity and priority correctly', 'Capture useful evidence'],
    deliverables: ['10 bug reports from any website or app', 'Each with title, environment, steps, expected vs actual, evidence, severity and priority'],
    steps: ['Explore a site/app and find genuine issues (or seed some)', 'For each, write a clear title (where + what) and minimal reproducible steps', 'State expected vs actual separately and attach evidence', 'Assign and justify severity and priority'],
    format: 'Submit as a PDF or DOCX. Quality over quantity — each report must be independently reproducible.',
    assessment: ['Reproducible steps and specific titles', 'Severity vs priority used correctly and justified', 'Evidence attached', 'No vague or emotional descriptions'],
    resources: ['Bug Report Template', 'Defect Severity vs Priority Guide'],
    proTip: 'Run each report through one test: "could a developer reproduce and fix this without asking me anything?" If not, it is not finished.',
  }),
  b(4, 'Agile & Scrum for Testers', {
    scenario: 'Your team works in two-week sprints. At refinement you are expected to question stories and strengthen their acceptance criteria so defects are prevented early.',
    objectives: ['Review user stories for gaps and ambiguity', 'Write strong, testable acceptance criteria', 'Show how a tester contributes across ceremonies'],
    deliverables: ['A review of 5 user stories', 'For each: missing/unclear criteria, suggested criteria, and the testing you would do in the sprint'],
    steps: ['Select or write 5 user stories', 'For each, identify ambiguity and missing scenarios (negative/edge)', 'Propose specific, testable acceptance criteria', 'Note the testing you would perform and questions you would raise at refinement'],
    format: 'Submit as a PDF or DOCX, organised story by story.',
    assessment: ['Sharp testability questions raised early', 'Strong, testable acceptance criteria', 'Awareness of the tester’s role across the sprint', 'Vague criteria challenged, not accepted'],
    resources: ['Agile Testing Cheat Sheet'],
    proTip: 'Phrase your findings as questions you would ask the team ("what happens if payment times out here?") — that is how value is added at refinement.',
  }),
  b(5, 'Jira & Test Management', {
    scenario: 'You need to show you can work the way real teams do: tracking stories, tests and defects in Jira and reporting testing status clearly.',
    objectives: ['Create well-formed stories, tasks and defects', 'Link tests, bugs and requirements', 'Report testing status clearly'],
    deliverables: ['A mock sprint board (free Jira trial or screenshots)', '3 user stories with acceptance criteria, 5 linked tasks, 5 defects, and a testing status update'],
    steps: ['Set up a board (or template) with the issue types', 'Add 3 stories with acceptance criteria and 5 linked tasks', 'Log 5 defects with full details, linked to their stories', 'Produce a short testing status update (what is tested vs not)'],
    format: 'Submit as a PDF or screenshots showing the board and items.',
    assessment: ['Clean, well-described issues', 'Correct links between stories, tests and bugs', 'Honest, current statuses', 'A status update led by risk, not raw counts'],
    resources: ['Test Plan Template', 'Requirements Traceability Matrix (RTM)'],
    proTip: 'Make every issue readable by someone who was not there — clear summaries and correct links are exactly what teams rely on day to day.',
  }),
  b(6, 'API Testing with Postman', {
    scenario: 'A feature depends on a REST API and you need to verify it directly — faster and more stable than testing only through the UI.',
    objectives: ['Test GET/POST/PUT/DELETE requests', 'Assert status and key response fields', 'Cover error/negative cases'],
    deliverables: ['10 API test cases against a public API (e.g. reqres.in, jsonplaceholder)', 'A Postman collection export (JSON)', 'Evidence of 3 successful and 2 error responses'],
    steps: ['Pick a public REST API and explore its endpoints', 'Create requests covering GET/POST/PUT/DELETE', 'Add assertions on status and key body fields, plus error cases', 'Export the collection and capture evidence'],
    format: 'Submit the Postman collection (JSON) plus test case documentation as PDF or DOCX.',
    assessment: ['Meaningful assertions on body and status', 'Negative/error cases included', 'Realistic, valid request data', 'Collection organised and exported'],
    resources: ['Test Scenario Template'],
    proTip: 'Assert the response body, not just the status — a "200 OK" with the wrong body is still a bug, and checking it shows real API-testing skill.',
  }),
  b(7, 'SQL for Testers', {
    scenario: 'A reported total looks wrong and the UI may be hiding the truth. You need SQL to verify what the system actually stored and to set up test data.',
    objectives: ['Write SELECT/WHERE/JOIN and aggregate queries', 'Use SQL to validate data', 'Explain how SQL supports testing'],
    deliverables: ['20 SQL queries covering SELECT, WHERE, ORDER BY, GROUP BY and JOIN', '5 data-validation examples', '3 short explanations of how SQL helps you as a tester'],
    steps: ['Use a sample schema (or a free SQL sandbox)', 'Write the 20 queries, each with a one-line note on what it verifies', 'Show 5 examples of validating data with SQL', 'Write 3 short reflections on SQL in testing'],
    format: 'Submit as a PDF or DOCX, queries grouped by type with their purpose.',
    assessment: ['Correct use of SELECT/WHERE/JOIN/aggregates', 'Queries tied to a testing purpose', 'At least one join and one aggregation', 'Queries that would actually run'],
    resources: ['Requirements Traceability Matrix (RTM)', 'Software Testing Glossary'],
    proTip: 'Frame each query around what it verifies (a total, data integrity, a user’s records) — that connects SQL to real QA value, not just syntax.',
  }),
  b(8, 'Automation Fundamentals', {
    scenario: 'Your team is considering automation and wants your judgement on what to automate — and what to keep manual — with clear reasoning.',
    objectives: ['Decide what to automate using sound criteria', 'Apply the test pyramid (right layer)', 'Justify each decision'],
    deliverables: ['A review of 10 tests', 'For each: automate or keep manual, the layer, and your reasoning (frequency, stability, value, maintenance)'],
    steps: ['List 10 tests from earlier modules', 'For each, decide automate/manual and at which layer', 'Justify the decision against frequency, stability, value and maintenance cost', 'Summarise your overall automation approach'],
    format: 'Submit as a PDF or DOCX using the provided template.',
    assessment: ['Sensible automate/not-automate decisions with reasons', 'Awareness of the pyramid (right layer)', 'No "automate everything" without reasoning', 'Decisions justified by risk and ROI'],
    resources: ['Test Strategy Template'],
    proTip: 'Knowing what NOT to automate (volatile, one-off, exploratory) is as important as what to automate — say so explicitly.',
  }),
  b(9, 'AI for Software Testing', {
    scenario: 'Your team is adopting AI tools. You need to show you can use AI to work faster while verifying its output and using it responsibly.',
    objectives: ['Write effective QA prompts', 'Generate and validate AI output', 'Use AI responsibly (data, verification, accountability)'],
    deliverables: ['20 prompts you used with an AI tool for testing tasks', '10 AI-generated test cases', 'A validation review of which outputs were accurate, which needed improvement, and why'],
    steps: ['Use AI to draft test cases and ideas with well-structured prompts', 'Capture the prompts and the outputs', 'Review the outputs — correct, remove hallucinations, add gaps', 'Write a short responsible-AI statement (data, verification, accountability)'],
    format: 'Submit as a PDF or DOCX, prompts and outputs followed by your review notes.',
    assessment: ['Well-structured prompts', 'Clear validation of AI output (kept/changed/rejected)', 'Hallucinations caught and removed', 'Responsible-use awareness'],
    resources: ['Test Case Template'],
    proTip: 'The validation is what proves QA skill — anyone can generate; a professional catches what is wrong or missing.',
  }),
  b(10, 'Portfolio Building', {
    scenario: 'You are ready to prove you can do the job. Assemble the work from across this course into a professional, public QA portfolio an employer can explore.',
    objectives: ['Curate strong QA artefacts', 'Structure and document them clearly', 'Explain what each demonstrates'],
    deliverables: ['A public portfolio (repo, site or document)', 'A test case pack, a bug report, an API collection, an SQL example, an AI workflow, and an about/intro section'],
    steps: ['Gather your best artefacts from each module', 'Add a 2–3 line context note to each ("what this demonstrates")', 'Organise into a clear structure with a README/intro', 'Publish it and link your CV/LinkedIn'],
    format: 'Submit a PDF summary with links to your published portfolio.',
    assessment: ['A clear introduction and structure', 'Curated, well-explained artefacts', 'Everything public and links working', 'Quality over quantity'],
    resources: ['Final Portfolio Project Workbook'],
    proTip: 'Six strong, well-explained pieces beat twenty unexplained ones. Curate ruthlessly and be ready to talk through each in 60 seconds.',
  }),
  b(11, 'CV & LinkedIn Mastery', {
    scenario: 'You are about to apply for QA roles. Your CV and LinkedIn need to get you found and make a strong first impression in seconds.',
    objectives: ['Write an achievement-led QA CV', 'Optimise LinkedIn for recruiter searches', 'Target the right roles'],
    deliverables: ['Your updated QA CV', 'Your LinkedIn summary text', 'A list of 10 target job titles', 'Your portfolio link'],
    steps: ['Write a sharp summary and skills section, leading with relevant strengths', 'Rewrite duties as quantified achievements', 'Optimise your LinkedIn headline and About with keywords', 'List 10 target roles and link your portfolio'],
    format: 'Submit as a PDF or DOCX (CV) plus your LinkedIn text and target list.',
    assessment: ['Sharp summary and skills up top', 'Achievement bullets with outcomes', 'Portfolio linked; consistent CV/LinkedIn', 'Proofread — no typos'],
    resources: ['QA Career Roadmap Poster'],
    proTip: 'A reviewer scans the top third first. Put your strongest, most relevant content there — and proofread relentlessly; a typo on a QA CV is the worst first impression.',
  }),
  b(12, 'Interview Mastery & Job Search', {
    scenario: 'This is your graduation submission: a complete, job-ready career pack that shows you can present yourself and perform in interviews.',
    objectives: ['Answer behavioural questions with STAR', 'Run a systematic job search', 'Plan your value in a new role'],
    deliverables: ['5 STAR answers for common QA questions', 'A record of 10 job applications (company, role, date, outcome)', 'A mock interview reflection', 'A final QA career action plan'],
    steps: ['Write 5 STAR answers covering common themes', 'Track 10 real applications with next actions', 'Run a mock interview and reflect (what went well, what to improve)', 'Write your career action plan (targets, skills, timeline)'],
    format: 'Submit as a PDF or DOCX — your complete final career pack.',
    assessment: ['Versatile, well-structured STAR answers', 'An organised, tracked job search', 'Honest mock-interview reflection', 'A clear, realistic action plan'],
    resources: ['QA Career Roadmap Poster', 'Final Portfolio Project Workbook'],
    proTip: 'Prepare 5–6 strong STAR stories you can adapt to almost any behavioural question — versatile examples beat a long list of half-prepared ones.',
  }),
];
