// QA Interview Accelerator — Career Toolkit, batch 1 (CV, LinkedIn, STAR, elevator pitch).
const COURSE = 'QA Interview Accelerator';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'qa-cv-template',
    title: 'QA CV / Résumé Template',
    subtitle: 'A clean, recruiter-ready CV structure tailored for testing roles.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Your CV has about six seconds to make an impression. This template gives you a clear, ATS-friendly structure that puts your QA skills and results front and centre — whether you are entering testing or moving up.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Keep it to 1–2 pages; lead with impact, not duties.',
        'Mirror the language of the job description (within honesty).',
        'Quantify results wherever you can (defects found, coverage, time saved).',
        'Save and send as PDF unless asked otherwise.',
      ] },
      { t: 'h1', text: 'Recommended Structure' },
      { t: 'table', headers: ['Section', 'What to include'], rows: [
        ['Header', 'Name, title (e.g. "QA Tester"), location, email, LinkedIn, portfolio link'],
        ['Profile', '2–3 lines: who you are, your focus, your strongest value'],
        ['Key skills', 'Test design, defect management, Agile, Jira, API/Postman, SQL, automation basics, AI-assisted testing'],
        ['Experience', 'Role, dates, and 3–5 achievement bullets each'],
        ['Projects / portfolio', 'Course and personal QA projects with links'],
        ['Education & certifications', 'Relevant qualifications (e.g. ISTQB if held)'],
      ] },
      { t: 'h1', text: 'Worked Example (achievement bullets)' },
      { t: 'ul', items: [
        'Designed and executed test cases for a checkout feature, identifying 12 defects before release including 2 critical payment bugs.',
        'Introduced a bug-report template that cut back-and-forth with developers and sped up fixes.',
        'Built an API test suite in Postman covering core endpoints, catching a data-integrity issue pre-launch.',
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: [
        '[Name] — [Target QA Title]', '[Location] · [Email] · [LinkedIn] · [Portfolio]',
        'Profile: ____', 'Key skills: ____',
        'Experience: [Role | Company | Dates] — achievement bullets',
        'Projects: [Name + link + what it demonstrates]', 'Education & certifications: ____',
      ] },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Use strong verbs (designed, identified, automated, improved).', 'Show outcomes, not just tasks.', 'Tailor the top third to each role.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Listing duties with no results.', 'Generic CV sent to every job.', 'No portfolio or project links.', 'Typos — always proofread.'] },
      proTip('A reviewer scans the top third first. Put your strongest, most relevant achievement where their eyes land — not buried on page two.'),
    ],
  },

  {
    slug: 'linkedin-optimisation-guide',
    title: 'LinkedIn Profile Optimisation Guide for Testers',
    subtitle: 'Turn your LinkedIn into a magnet for QA recruiters.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Recruiters search LinkedIn constantly for testing talent. An optimised profile gets you found and makes a strong first impression. This guide walks you through every section.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Work through each section below and update it.',
        'Use keywords recruiters search for (QA, test, automation, Agile).',
        'Keep it consistent with your CV.',
      ] },
      { t: 'h1', text: 'Section-by-Section' },
      { t: 'table', headers: ['Section', 'Make it count'], rows: [
        ['Photo', 'Friendly, professional headshot'],
        ['Headline', 'Role + value + keywords, e.g. "QA Tester | Manual & Automation | Agile | API Testing"'],
        ['About', '3–4 short paragraphs: who you are, skills, what you are looking for, a call to connect'],
        ['Experience', 'Achievements with metrics, mirroring your CV'],
        ['Skills', 'Add and pin the QA skills recruiters filter by'],
        ['Featured', 'Pin your portfolio, certificate or a strong post'],
        ['Open to work', 'Turn on (recruiter-only if discreet)'],
      ] },
      { t: 'h1', text: 'Worked Example (headline + about opener)' },
      { t: 'p', text: 'Headline: "Software Tester | Manual + Automation | Agile · Jira · API · SQL | Building a QA portfolio". About opener: "I am a detail-driven tester focused on preventing defects early and communicating quality clearly..."' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Rewrite your headline and the first two lines of your About section using the formula above. Add five QA skills and pin your portfolio to Featured.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Write in the first person — it reads warmer.', 'Post or comment occasionally to stay visible.', 'Keep keywords natural, not stuffed.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Blank or one-line About section.', 'No keywords, so you never appear in searches.', 'Profile that contradicts the CV.'] },
      proTip('Recruiters search by keyword. If "automation", "API" or "Agile" appear naturally in your headline and About, you turn up in far more searches.'),
    ],
  },

  {
    slug: 'star-answer-workbook',
    title: 'STAR Answer Framework Workbook',
    subtitle: 'Build powerful, structured answers to behavioural interview questions.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Behavioural questions ("Tell me about a time...") are where many candidates ramble. The STAR method keeps your answers structured, concise and memorable. This workbook helps you prepare a bank of strong examples.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Pick real examples from work, projects or this course.',
        'Draft each using the STAR structure below.',
        'Keep answers to 1.5–2 minutes; practise out loud.',
      ] },
      { t: 'h1', text: 'The STAR Structure' },
      { t: 'table', headers: ['Letter', 'Meaning', 'Keep it to'], rows: [
        ['S — Situation', 'Brief context', '1–2 sentences'],
        ['T — Task', 'Your responsibility / the challenge', '1 sentence'],
        ['A — Action', 'What YOU did (the core)', '3–4 sentences'],
        ['R — Result', 'The outcome, ideally measurable', '1–2 sentences'],
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: '"A release was at risk because a critical bug appeared late (S). I needed to investigate and communicate the risk fast (T). I reproduced it, narrowed it to a recent change, wrote a clear report with evidence, and flagged the business impact to the team (A). The fix shipped the same day and we avoided a customer-facing failure (R)."' },
      { t: 'h1', text: 'Question Bank to Prepare' },
      { t: 'ul', items: [
        'A defect you are proud of finding',
        'A disagreement with a developer',
        'A time you were under pressure / tight deadline',
        'A mistake you made and what you learned',
        'A time you improved a process',
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: ['Question:', 'S:', 'T:', 'A (what I did):', 'R (result/metric):'] },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Spend most of your answer on the Action.', 'Say "I" not "we" when describing your part.', 'End on a concrete result.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Too much background, no result.', 'Vague "we" answers that hide your contribution.', 'No measurable outcome.'] },
      proTip('Prepare 5–6 strong STAR stories and you can adapt them to almost any behavioural question. Versatile examples beat a long list of half-prepared ones.'),
    ],
  },

  {
    slug: 'elevator-pitch-template',
    title: '"Tell Me About Yourself" — Elevator Pitch Template',
    subtitle: 'Nail the most common opening question with a confident 60-second pitch.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: '"Tell me about yourself" opens most interviews and sets the tone. A crisp, confident pitch frames the whole conversation in your favour. This template gives you a repeatable formula.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Aim for 60–90 seconds — focused, not a life story.',
        'Tailor the ending to the specific role.',
        'Practise until it sounds natural, not memorised.',
      ] },
      { t: 'h1', text: 'The Formula (Present → Past → Future)' },
      { t: 'table', headers: ['Part', 'What to say'], rows: [
        ['Present', 'Who you are now and your focus as a tester'],
        ['Past', 'Relevant experience, projects or this course — with a highlight'],
        ['Future', 'Why this role/company, and what you want to bring'],
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: '"I am a QA tester focused on practical, risk-based testing. Over the last few months I completed a structured testing programme where I built a full portfolio — test plans, API tests in Postman, and professional bug reports. I am drawn to this role because you value quality early in the process, and I am keen to bring my eye for detail and clear communication to your team."' },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: [
        'Present: "I am a [role] focused on ____."',
        'Past: "Recently I ____, where I ____ [highlight]."',
        'Future: "I am excited about this role because ____, and I want to bring ____."',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Write your pitch using the template, then record yourself delivering it. Trim anything that takes you over 90 seconds.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Open with confidence and a clear identity.', 'Include one concrete highlight.', 'Connect the ending to the company.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Reciting your whole CV chronologically.', 'Going on too long.', 'A generic pitch that ignores the role.'] },
      proTip('The interviewer decides how the rest of the conversation feels in your first 60 seconds. A calm, structured pitch buys you goodwill for everything that follows.'),
    ],
  },
];
