// QA Interview Accelerator — Career Toolkit, batch 3 (completes the 15).
const COURSE = 'QA Interview Accelerator';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'mock-interview-practice-pack',
    title: 'Mock Interview Practice Pack',
    subtitle: 'Run realistic practice interviews and improve fast.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Practising under realistic conditions is the fastest way to build interview confidence. This pack gives you a structured mock interview you can run alone, with a friend, or with AI.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Set a timer for 30–40 minutes and treat it like the real thing.',
        'Have a partner (or AI) ask the questions and give feedback.',
        'Record yourself if you can — reviewing it is hugely valuable.',
        'Repeat weekly until your answers feel natural.',
      ] },
      { t: 'h1', text: 'Mock Interview Script' },
      { t: 'ol', items: [
        'Warm-up: "Tell me about yourself." (elevator pitch)',
        'Motivation: "Why testing? Why this role?"',
        'Fundamentals: severity vs priority; when do you stop testing?',
        'Test design: how would you test a login page?',
        'Behavioural (STAR): a defect you are proud of; a conflict with a developer.',
        'Technical: a status code question; when to automate; responsible AI use.',
        'Your questions: ask two prepared questions.',
      ] },
      { t: 'h1', text: 'Feedback Sheet (score 1–5)' },
      { t: 'table', headers: ['Area', 'Score', 'Note'], rows: [
        ['Clarity & structure', '', ''],
        ['Use of examples (STAR)', '', ''],
        ['Technical accuracy', '', ''],
        ['Confidence & pace', '', ''],
        ['Questions asked', '', ''],
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Run the full script once, score yourself, and pick the lowest-scoring area to focus on before your next mock.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Practise out loud, not just in your head.', 'Review recordings honestly.', 'Improve one area at a time.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Only practising the questions you already answer well.', 'Never timing yourself.', 'Skipping the "your questions" part.'] },
      proTip('You can run a full mock with AI: ask it to act as a QA interviewer, answer out loud, then ask for specific feedback on each answer. It is the cheapest practice partner you will ever have.'),
    ],
  },

  {
    slug: 'salary-negotiation-guide',
    title: 'Salary Negotiation Guide for QA',
    subtitle: 'Negotiate your offer professionally and confidently.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Most candidates accept the first number out of fear. A calm, professional negotiation can meaningfully increase your offer without risking it. This guide shows you how.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Research the market range for the role and location first.',
        'Let them name a number where possible.',
        'Negotiate on value, politely, once you have an offer.',
      ] },
      { t: 'h1', text: 'Before You Negotiate' },
      { t: 'ul', items: [
        'Know the typical range (job sites, levels, your network).',
        'Decide your target and your walk-away minimum.',
        'Remember total package: salary, bonus, holiday, learning budget, flexibility.',
      ] },
      { t: 'h1', text: 'Worked Example (response script)' },
      { t: 'p', text: '"Thank you, I am really excited about this role. Based on my skills and the market for this position, I was hoping for something closer to [X]. Is there flexibility on the offer?" — said warmly, then pause and let them respond.' },
      { t: 'h1', text: 'If They Cannot Move on Salary' },
      { t: 'ul', items: [
        'Ask about a review at 6 months tied to goals.',
        'Negotiate non-salary items (holiday, learning budget, remote days).',
        'Get any agreement in writing.',
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Research the range for a role you want, set your target and minimum, and write out your negotiation script in your own words.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Stay warm and collaborative, never demanding.', 'Anchor on value and market, not personal need.', 'Be ready to justify your number briefly.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Accepting instantly out of fear.', 'Giving your number first with no research.', 'Negotiating aggressively and souring the relationship.'] },
      proTip('Negotiating politely rarely loses an offer — employers expect it. The worst outcome is usually "we cannot move", which leaves you exactly where you started.'),
    ],
  },

  {
    slug: 'job-search-tracker-template',
    title: 'Job Search Tracker Template',
    subtitle: 'Stay organised and in control of your applications.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A job search has many moving parts. This tracker keeps every application, contact and follow-up in one place so nothing slips and you can see your progress.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Recreate this as a spreadsheet (or print it).',
        'Add a row per application; update the status as you go.',
        'Review it weekly and chase anything overdue.',
      ] },
      { t: 'h1', text: 'Tracker Columns' },
      { t: 'table', headers: ['Column', 'Purpose'], rows: [
        ['Company / Role', 'What you applied for'],
        ['Date applied', 'When'],
        ['Source', 'Where you found it'],
        ['Status', 'Applied / Screening / Interview / Offer / Rejected'],
        ['Contact', 'Recruiter / hiring manager'],
        ['Next action + date', 'Follow-up or prep needed'],
        ['Notes', 'Tailoring, salary, learnings'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template (one row)' },
      { t: 'ul', items: ['Company/Role:', 'Date applied:', 'Source:', 'Status:', 'Contact:', 'Next action + date:', 'Notes:'] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Set up the tracker and add your current or target applications. Identify any that need a follow-up this week.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Update it the moment something changes.', 'Always set a "next action" so nothing stalls.', 'Track learnings to improve each application.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Relying on memory across many applications.', 'Never following up.', 'No record of what you tailored or were told.'] },
      proTip('Following up politely a few days after applying or interviewing sets you apart — most candidates never do, and it signals genuine interest.'),
    ],
  },

  {
    slug: 'portfolio-presentation-guide',
    title: 'QA Portfolio Presentation Guide',
    subtitle: 'Present your portfolio so it wins interviews.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A portfolio only helps if you can talk through it well. This guide shows you how to present your QA work so an interviewer immediately sees you can do the job.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Make sure your portfolio is public and links work.',
        'Prepare a 60-second walkthrough of each key artefact.',
        'Lead with the value, not the mechanics.',
      ] },
      { t: 'h1', text: 'What to Showcase' },
      { t: 'ul', items: [
        'A test plan / strategy snapshot',
        'Well-structured test cases (showing your techniques)',
        'A professional bug report',
        'An API test collection (Postman)',
        'An exploratory charter and notes',
        'A certificate or course project',
      ] },
      { t: 'h1', text: 'The 60-Second Walkthrough Formula' },
      { t: 'table', headers: ['Step', 'Say'], rows: [
        ['What', 'What this artefact is'],
        ['Why', 'The problem/risk it addresses'],
        ['How', 'The technique or thinking you applied'],
        ['Result', 'What it demonstrates about you'],
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'p', text: '"This is a bug report I wrote for a checkout issue (what). The defect blocked payments (why). I reproduced it, narrowed it to a recent change and documented it with evidence and clear severity (how). It shows I can communicate a critical issue so it gets fixed fast (result)."' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Pick three artefacts and write a 60-second walkthrough for each using the formula. Practise them out loud.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Curate — a few strong, well-explained pieces beat many.', 'Tie each artefact to a skill the role needs.', 'Keep links tidy and accessible.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Showing work with no explanation.', 'Broken or private links.', 'Talking through mechanics instead of value.'] },
      proTip('Offer your portfolio proactively: "I have a portfolio I can walk you through" signals confidence and gives you control of the narrative.'),
    ],
  },

  {
    slug: 'follow-up-email-templates',
    title: 'Post-Interview Follow-up Email Templates',
    subtitle: 'Professional templates for thank-you notes and chasing decisions.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A short, well-judged follow-up email keeps you front of mind and shows professionalism. These templates cover the most common situations — adapt them to sound like you.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Send a thank-you within 24 hours of the interview.',
        'Keep it short, specific and warm.',
        'Personalise with something from the conversation.',
      ] },
      { t: 'h1', text: 'Template 1 — Thank-you (same day)' },
      { t: 'p', text: 'Subject: Thank you — [Role] interview. "Hi [Name], thank you for taking the time to speak with me today about the [Role] position. I enjoyed learning about [specific thing] and I am even more excited about the opportunity. Please let me know if I can provide anything further. Best regards, [You]."' },
      { t: 'h1', text: 'Template 2 — Chasing a decision' },
      { t: 'p', text: '"Hi [Name], I hope you are well. I wanted to follow up on the [Role] interview from [date]. I remain very interested and would be glad to answer any further questions. Is there an update on the timeline? Thank you, [You]."' },
      { t: 'h1', text: 'Template 3 — Responding to an offer (asking time)' },
      { t: 'p', text: '"Hi [Name], thank you so much for the offer — I am delighted. Would it be possible to have until [date] to review the details? I want to give it the consideration it deserves. Thank you, [You]."' },
      { t: 'h1', text: 'Template 4 — Polite decline / staying in touch' },
      { t: 'p', text: '"Hi [Name], thank you for the opportunity and for letting me know. I really enjoyed meeting the team and would welcome staying in touch for future roles. Wishing you all the best, [You]."' },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Personalise Template 1 for a real or mock interview, adding one specific detail from the conversation.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Be prompt, brief and specific.', 'Proofread — errors undo the good impression.', 'Keep the tone warm and professional.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Never following up.', 'Generic copy-paste with no personalisation.', 'Chasing too aggressively or too often.'] },
      proTip('A thoughtful thank-you that references a specific moment from the interview can tip a close decision in your favour. It costs two minutes.'),
    ],
  },

  {
    slug: '30-60-90-day-plan-template',
    title: '30-60-90 Day Plan Template',
    subtitle: 'Show you are ready to deliver from day one in a new QA role.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A 30-60-90 day plan shows an employer you think ahead and will add value quickly. Some interviews ask for one; even when they do not, mentioning your plan is impressive.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Adapt the phases below to the specific role.',
        'Focus on learning first, then contributing, then improving.',
        'Keep goals realistic and outcome-focused.',
      ] },
      { t: 'h1', text: 'The Three Phases' },
      { t: 'table', headers: ['Phase', 'Theme', 'Example goals'], rows: [
        ['First 30 days', 'Learn', 'Understand the product, team, tools and process; meet stakeholders; run first tests'],
        ['Days 31–60', 'Contribute', 'Own testing for stories; write clear reports; add value in ceremonies'],
        ['Days 61–90', 'Improve', 'Suggest a process or coverage improvement; deepen domain knowledge; build trust'],
      ] },
      { t: 'h1', text: 'Worked Example (30-day goals)' },
      { t: 'ul', items: [
        'Learn the product and key user journeys',
        'Set up tools and access (Jira, test management, environments)',
        'Understand the test process and where I fit',
        'Test my first stories with guidance',
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'ul', items: ['First 30 days (Learn):', 'Days 31–60 (Contribute):', 'Days 61–90 (Improve):'] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Draft a 30-60-90 plan for a role you are targeting, with three goals per phase.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Front-load learning before proposing changes.', 'Tie goals to outcomes, not activity.', 'Keep it concise — one page.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Promising big changes before understanding the team.', 'Vague goals with no outcomes.', 'A generic plan ignoring the specific role.'] },
      proTip('Even if not asked, saying "I would spend my first month learning the product and process before suggesting improvements" signals maturity and earns instant trust.'),
    ],
  },

  {
    slug: 'interview-confidence-guide',
    title: 'Interview Confidence & Nerves Guide',
    subtitle: 'Practical techniques to stay calm and perform at your best.',
    courseTitle: COURSE, category: 'Career Resources',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Nerves are normal — even welcome in small doses. The goal is not to feel no fear, but to perform well anyway. This guide gives you practical techniques used by confident candidates.' },
      { t: 'h1', text: 'Instructions' },
      { t: 'ul', items: [
        'Prepare thoroughly — confidence comes from readiness.',
        'Use the techniques below before and during the interview.',
        'Reframe nerves as energy, not a threat.',
      ] },
      { t: 'h1', text: 'Before the Interview' },
      { t: 'ul', items: [
        'Rehearse your pitch and STAR stories out loud.',
        'Prepare your space and tech early to remove last-minute stress.',
        'Do a brief warm-up; arrive (or log on) with time to spare.',
      ] },
      { t: 'h1', text: 'During the Interview' },
      { t: 'ul', items: [
        'Breathe and pause before answering — silence is fine.',
        'It is OK to say "let me think about that for a moment".',
        'Treat it as a two-way conversation, not an interrogation.',
        'If you stumble, reset calmly: "Let me start that again."',
      ] },
      { t: 'h1', text: 'Reframes That Help' },
      { t: 'table', headers: ['Instead of', 'Think'], rows: [
        ['"I must be perfect"', '"I just need to be clear and honest"'],
        ['"They are judging me"', '"We are seeing if this is a fit, both ways"'],
        ['"I am so nervous"', '"This is energy I can use"'],
      ] },
      { t: 'h1', text: 'Practical Exercise' },
      { t: 'p', text: 'Pick two techniques above and use them in your next mock interview. Note afterwards whether they helped.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Preparation beats positive thinking alone.', 'Slow down — pace drops with nerves.', 'Focus on the conversation, not on yourself.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Rushing answers when nervous.', 'Trying to hide all nerves instead of managing them.', 'Under-preparing and hoping for the best.'] },
      proTip('The most confident-sounding candidates are usually the best prepared, not the least nervous. Put your energy into rehearsal and the confidence follows.'),
    ],
  },
];
