// ISTQB Foundation Masterclass — Resource Vault, batch 2.
const COURSE = 'ISTQB Foundation Masterclass';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'test-management-cheat-sheet',
    title: 'Test Management Cheat Sheet',
    subtitle: 'The planning, monitoring, control and risk essentials for the ISTQB Foundation exam.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Test management covers how testing is planned, monitored, controlled and reported across a project. This cheat sheet condenses the syllabus Chapter 5 essentials into a quick reference you can revise in minutes.' },
      { t: 'h1', text: 'Roles' },
      { t: 'table', headers: ['Role', 'Responsibility'], rows: [
        ['Test manager', 'Plans, monitors and controls testing; leads the test team and reports progress'],
        ['Tester', 'Analyses, designs, implements and executes tests; logs defects'],
      ] },
      { t: 'h1', text: 'The Test Plan' },
      { t: 'p', text: 'A test plan documents the objectives, scope, approach, resources and schedule of testing activities. It defines what will be tested, how, by whom, and against which entry and exit criteria.' },
      { t: 'ul', items: [
        'Context and objectives of testing',
        'Scope, assumptions and constraints',
        'Test approach and techniques',
        'Entry criteria (definition of ready) and exit criteria (definition of done)',
        'Schedule, resources, roles and responsibilities',
      ] },
      { t: 'h1', text: 'Entry vs Exit Criteria' },
      { t: 'table', headers: ['Criteria', 'Meaning'], rows: [
        ['Entry criteria', 'Preconditions that must be met before a test activity can start'],
        ['Exit criteria', 'Conditions that must be met before a test activity can be declared complete'],
      ] },
      { t: 'h1', text: 'Estimation Techniques' },
      { t: 'table', headers: ['Technique', 'Basis'], rows: [
        ['Metrics-based (ratios)', 'Estimates based on data from past/similar projects'],
        ['Expert-based', 'Estimates based on the experience of task owners or experts'],
        ['Three-point / wideband Delphi', 'Combines expert estimates to reduce individual bias'],
      ] },
      { t: 'h1', text: 'Test Monitoring & Control' },
      { t: 'ul', items: [
        'Monitoring gathers information about testing progress against the plan.',
        'Control takes action to meet the plan (e.g. re-prioritising, adjusting scope).',
        'Common metrics: test cases run/passed/failed/blocked, defect density, coverage, effort.',
      ] },
      { t: 'h1', text: 'Test Progress Reporting' },
      { t: 'p', text: 'Test progress reports (interim) keep stakeholders informed during a test period; test completion (summary) reports summarise a completed test activity, its results and residual risks.' },
      { t: 'h1', text: 'Risk-Based Testing' },
      { t: 'p', text: 'Risk level = likelihood of occurrence × impact of harm. Risk-based testing uses risk to guide effort: higher-risk areas get earlier and more thorough testing.' },
      { t: 'ul', items: [
        'Product risk — a risk that the product may fail to satisfy needs (test object quality).',
        'Project risk — a risk related to management and control of the project (resources, schedule, suppliers).',
      ] },
      { t: 'h1', text: 'Configuration Management' },
      { t: 'p', text: 'Configuration management establishes and maintains the integrity of testware and the test object through versioning, so tests are repeatable and results traceable.' },
      { t: 'h1', text: 'Defect Management' },
      { t: 'p', text: 'Defects found are logged, classified (e.g. by severity and priority), analysed and tracked through to resolution. Reports feed monitoring and process improvement.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Define exit criteria before execution starts.', 'Prioritise testing by risk, not by order of features.', 'Report progress in terms stakeholders understand.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Confusing product risk with project risk.', 'Treating the test plan as a one-off document instead of updating it.', 'Reporting activity (tests run) without outcome (risk remaining).'] },
      proTip('In the exam, remember the risk formula: risk level combines the likelihood of a problem occurring with the impact if it does. Any answer that ignores one of those two dimensions is usually wrong.'),
    ],
  },

  {
    slug: 'risk-matrix-template',
    title: 'Risk Matrix Template',
    subtitle: 'Assess likelihood and impact to prioritise your testing effort.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'A risk matrix helps you turn risk-based testing from a slogan into a plan. By scoring each risk on likelihood and impact, you decide where to test first and hardest. This template gives you a reusable structure.' },
      { t: 'h1', text: 'The Core Formula' },
      { t: 'p', text: 'Risk level = likelihood × impact. Likelihood is the probability the problem occurs; impact is the harm if it does. Multiplying the two gives a comparable score across risks.' },
      { t: 'h1', text: 'Scoring Scale' },
      { t: 'table', headers: ['Score', 'Likelihood', 'Impact'], rows: [
        ['1 — Low', 'Unlikely to occur', 'Minor inconvenience, easy workaround'],
        ['2 — Medium', 'Could reasonably occur', 'Noticeable disruption to users or business'],
        ['3 — High', 'Very likely to occur', 'Severe or business-critical harm'],
      ] },
      { t: 'h1', text: 'Risk Level Matrix' },
      { t: 'table', headers: ['Likelihood \\ Impact', 'Low (1)', 'Medium (2)', 'High (3)'], rows: [
        ['High (3)', '3 — Medium', '6 — High', '9 — Critical'],
        ['Medium (2)', '2 — Low', '4 — Medium', '6 — High'],
        ['Low (1)', '1 — Low', '2 — Low', '3 — Medium'],
      ] },
      { t: 'h1', text: 'Priority Bands' },
      { t: 'table', headers: ['Score', 'Band', 'Testing response'], rows: [
        ['7–9', 'Critical', 'Test earliest, most thoroughly; consider extra techniques'],
        ['4–6', 'High', 'Test carefully within the plan'],
        ['2–3', 'Medium', 'Standard coverage'],
        ['1', 'Low', 'Light or exploratory coverage only'],
      ] },
      { t: 'h1', text: 'Worked Example' },
      { t: 'table', headers: ['Risk', 'Likelihood', 'Impact', 'Score', 'Priority'], rows: [
        ['Payment fails to process', '2', '3', '6', 'High'],
        ['Login rejects valid users', '2', '3', '6', 'High'],
        ['Cosmetic misalignment on footer', '3', '1', '3', 'Medium'],
        ['Report export corrupts data', '1', '3', '3', 'Medium'],
      ] },
      { t: 'h1', text: 'Blank Reusable Template' },
      { t: 'table', headers: ['Risk', 'Type (product/project)', 'Likelihood (1-3)', 'Impact (1-3)', 'Score', 'Owner', 'Mitigation'], rows: [
        ['', '', '', '', '', '', ''],
        ['', '', '', '', '', '', ''],
        ['', '', '', '', '', '', ''],
      ] },
      { t: 'h1', text: 'Instructions' },
      { t: 'ol', items: [
        'List each identified risk, one per row.',
        'Classify it as a product risk or a project risk.',
        'Score likelihood and impact from 1 to 3.',
        'Multiply to get the risk level and assign a priority band.',
        'Record an owner and a mitigation or test response.',
        'Re-review scores as the project progresses.',
      ] },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Involve both business and technical stakeholders in scoring.', 'Revisit the matrix at each milestone — risks change.', 'Use it to justify where testing effort goes.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Scoring impact alone and ignoring likelihood (or vice versa).', 'Treating the matrix as fixed for the whole project.', 'Confusing high severity with high risk — severity is only part of impact.'] },
      proTip('Keep the matrix visible to the whole team. When a stakeholder asks why a low-value feature was not tested exhaustively, the risk matrix is your evidence-based answer.'),
    ],
  },

  {
    slug: 'review-checklist',
    title: 'Review Checklist',
    subtitle: 'Run effective static reviews and catch defects before code runs.',
    courseTitle: COURSE, category: 'Checklists',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Reviews are static testing: they find defects in work products without executing code. This checklist helps you run reviews that are consistent, objective and genuinely useful, aligned to syllabus Chapter 3.' },
      { t: 'h1', text: 'Review Types (formality low to high)' },
      { t: 'table', headers: ['Type', 'Characteristics'], rows: [
        ['Informal review', 'No formal process; main purpose is inexpensive benefit'],
        ['Walkthrough', 'Led by the author; find defects, improve, share understanding'],
        ['Technical review', 'Led by a moderator; performed by technical peers; reach consensus'],
        ['Inspection', 'Most formal; follows rules and roles; metrics-driven'],
      ] },
      { t: 'h1', text: 'Roles in a Formal Review' },
      { t: 'table', headers: ['Role', 'Responsibility'], rows: [
        ['Author', 'Creates and fixes the work product under review'],
        ['Manager', 'Plans reviews, decides on their execution'],
        ['Facilitator (moderator)', 'Ensures the review runs effectively'],
        ['Review leader', 'Takes overall responsibility for the review'],
        ['Reviewer', 'Identifies potential defects'],
        ['Scribe (recorder)', 'Records the outcomes and defects found'],
      ] },
      { t: 'h1', text: 'Before the Review' },
      { t: 'ul', items: [
        'Objectives are clear and agreed.',
        'The right reviewers are invited for the material.',
        'The work product meets entry criteria (stable enough to review).',
        'Reference material (standards, checklists) is available.',
        'Reviewers have had adequate time to prepare individually.',
      ] },
      { t: 'h1', text: 'During the Review' },
      { t: 'ul', items: [
        'Focus on finding defects, not fixing them.',
        'Critique the work product, not the author.',
        'Every reviewer participates and raises findings.',
        'Findings are recorded objectively by the scribe.',
        'Time-box the session to keep it effective.',
      ] },
      { t: 'h1', text: 'Content Quality Checks' },
      { t: 'ul', items: [
        'Requirements are complete, consistent and unambiguous.',
        'Each requirement is testable (you can write a test for it).',
        'Terminology is used consistently throughout.',
        'No contradictions between related statements.',
        'Assumptions and dependencies are stated explicitly.',
        'Acceptance criteria are defined and measurable.',
      ] },
      { t: 'h1', text: 'After the Review' },
      { t: 'ul', items: [
        'Defects are logged and assigned for resolution.',
        'The exit decision (accept / rework) is recorded.',
        'Metrics are captured (for formal reviews).',
        'Rework is verified before closing.',
      ] },
      { t: 'h1', text: 'Why Reviews Pay Off' },
      { t: 'p', text: 'Defects found in reviews are cheaper to fix than those found in later dynamic testing or production, because the cost of fixing a defect rises the later it is found.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Match review formality to the risk of the work product.', 'Use checklists to keep reviews consistent.', 'Keep the tone constructive — reviews improve products, not blame people.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Turning the review into a fixing session.', 'Reviewing without preparation time.', 'Criticising the author instead of the artefact.'] },
      proTip('The single most valuable question in any requirements review is: "How would I test this?" If you cannot answer, the requirement is not yet testable — and that is a defect worth logging now.'),
    ],
  },

  {
    slug: 'istqb-glossary',
    title: 'ISTQB Foundation Glossary',
    subtitle: 'Forty key terms and concise definitions for the Foundation exam.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Precise vocabulary is worth easy marks in the ISTQB Foundation exam. This glossary lists forty of the most examined terms with concise, syllabus-aligned definitions. Learn to distinguish the pairs that are easy to confuse — error/defect/failure and verification/validation especially.' },
      { t: 'h1', text: 'Core Glossary' },
      { t: 'table', headers: ['Term', 'Definition'], rows: [
        ['Error (mistake)', 'A human action that produces an incorrect result.'],
        ['Defect (bug, fault)', 'A flaw in a work product that can cause a failure; the result of an error.'],
        ['Failure', 'An event in which a component or system does not perform a required function within limits.'],
        ['Root cause', 'The underlying source of a defect that, if removed, prevents recurrence.'],
        ['Quality', 'The degree to which a component or system satisfies the stated and implied needs of stakeholders.'],
        ['Verification', 'Confirmation that specified requirements have been met — "are we building the product right?"'],
        ['Validation', 'Confirmation that requirements for a specific use are fulfilled — "are we building the right product?"'],
        ['Testing', 'The set of activities to evaluate quality and reduce the risk of failure in operation.'],
        ['Debugging', 'The development activity that finds, analyses and fixes the cause of a defect (not the same as testing).'],
        ['Test object', 'The component or system to be tested.'],
        ['Test basis', 'The body of knowledge used as the basis for designing test cases (e.g. requirements).'],
        ['Test condition', 'An aspect of the test basis relevant to achieving test objectives.'],
        ['Test case', 'A set of preconditions, inputs, actions, expected results and postconditions developed to meet a test condition.'],
        ['Test scenario', 'A sequence of related actions/events, often a realistic user journey covering several test conditions.'],
        ['Test procedure (script)', 'A sequence of test cases in execution order with any preconditions to run them.'],
        ['Test suite', 'A set of test cases or procedures to be executed together.'],
        ['Test data', 'Data created or selected to satisfy the preconditions and inputs of tests.'],
        ['Expected result', 'The predicted behaviour of a test object under specified conditions, from the test basis.'],
        ['Test oracle', 'A source to determine expected results (specification, another system, or a person).'],
        ['Static testing', 'Testing a work product without executing code (reviews and static analysis).'],
        ['Dynamic testing', 'Testing that involves executing the software.'],
        ['Test level', 'A group of test activities organised and managed together (component, integration, system, acceptance).'],
        ['Test type', 'A group of test activities focused on specific quality characteristics (functional, non-functional, structural, change-related).'],
        ['Functional testing', 'Testing what the system does — its functions and features.'],
        ['Non-functional testing', 'Testing how well the system behaves — performance, usability, security, reliability, etc.'],
        ['White-box testing', 'Testing based on the internal structure of the test object (structure-based).'],
        ['Black-box testing', 'Testing based on specifications without reference to internal structure.'],
        ['Regression testing', 'Testing to detect defects introduced or uncovered by a change elsewhere in the software.'],
        ['Retesting (confirmation testing)', 'Re-running tests that previously failed to confirm a fix works.'],
        ['Smoke test', 'A subset of tests confirming the most critical functions work before deeper testing.'],
        ['Severity', 'The degree of impact a defect has on the system or its operation.'],
        ['Priority', 'The urgency with which a defect should be fixed (business-driven).'],
        ['Equivalence partitioning (EP)', 'Dividing inputs into partitions where members are expected to be treated the same; test one per partition.'],
        ['Boundary value analysis (BVA)', 'Testing at the edges of equivalence partitions, where defects cluster.'],
        ['Decision table testing', 'Deriving tests from combinations of conditions and their resulting actions.'],
        ['State transition testing', 'Testing valid and invalid transitions between states of a system.'],
        ['Coverage', 'The degree, as a percentage, to which specified items have been exercised by a test suite.'],
        ['Traceability', 'The ability to link test items (conditions, cases) back to the test basis and requirements.'],
        ['Entry criteria', 'The preconditions that must be met to start a test activity.'],
        ['Exit criteria', 'The conditions that must be met to declare a test activity complete.'],
      ] },
      { t: 'h1', text: 'The Most Confused Pairs' },
      { t: 'ul', items: [
        'Error → Defect → Failure: a person makes an error, which introduces a defect, which may cause a failure when executed.',
        'Verification vs Validation: building it right (to spec) vs building the right thing (fit for use).',
        'Severity vs Priority: how bad the defect is vs how soon it should be fixed.',
        'Retesting vs Regression: confirming a specific fix vs checking the fix broke nothing else.',
      ] },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Learn the exact ISTQB wording, not a paraphrase.', 'Practise the confused pairs until they are automatic.', 'Use the terms consistently in your own work.'] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Using "bug" loosely for error, defect and failure interchangeably.', 'Swapping verification and validation.', 'Assuming high severity always means high priority.'] },
      proTip('When an exam question mixes "error", "defect" and "failure", slow down and map the chain: human error creates a defect in the code; the defect causes a failure only when that code is executed. Most trick questions hinge on this exact sequence.'),
    ],
  },

  {
    slug: 'quick-revision-notes',
    title: 'Quick Revision Notes',
    subtitle: 'High-yield facts for every ISTQB Foundation syllabus chapter.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'This is your last-minute revision sheet: the highest-yield facts from each chapter of the ISTQB Foundation syllabus, condensed for a final read-through before the exam.' },
      { t: 'h1', text: 'Ch.1 — Fundamentals of Testing' },
      { t: 'ul', items: [
        'Testing evaluates quality and reduces the risk of failure in operation.',
        'Testing is not just execution — it includes planning, analysis, design and reporting.',
        'Error → defect → failure. A failure can also come from environmental conditions.',
        'Testing shows the presence of defects, not their absence.',
        'Verification = building it right; validation = building the right thing.',
      ] },
      { t: 'h1', text: 'The Seven Testing Principles' },
      { t: 'ol', items: [
        'Testing shows the presence of defects, not their absence.',
        'Exhaustive testing is impossible — use risk and priorities instead.',
        'Early testing saves time and money (shift left).',
        'Defects cluster together — a few modules hold most defects.',
        'Beware the pesticide paradox — repeating the same tests stops finding new defects; vary them.',
        'Testing is context dependent — you test differently in different contexts.',
        'Absence-of-errors is a fallacy — a defect-free system can still be unusable or wrong.',
      ] },
      { t: 'h1', text: 'Ch.2 — Testing Throughout the SDLC' },
      { t: 'p', text: 'Good testing fits the development model, has a matching test level for every development level, and starts as early as possible (shift-left).' },
      { t: 'h1', text: 'Test Levels' },
      { t: 'table', headers: ['Level', 'Focus'], rows: [
        ['Component (unit)', 'Individual components in isolation'],
        ['Integration', 'Interfaces and interactions between components/systems'],
        ['System', 'The behaviour of the whole system end to end'],
        ['Acceptance', 'Readiness for use / fitness for purpose (UAT, operational, contractual/regulatory, alpha, beta)'],
      ] },
      { t: 'h1', text: 'Test Types' },
      { t: 'table', headers: ['Type', 'Answers'], rows: [
        ['Functional', 'What the system does'],
        ['Non-functional', 'How well it behaves (performance, usability, security, reliability, portability)'],
        ['White-box (structural)', 'How much of the structure is exercised'],
        ['Change-related', 'Confirmation testing (retest) and regression testing after changes'],
      ] },
      { t: 'h1', text: 'Maintenance Testing' },
      { t: 'p', text: 'Triggered by modifications, migration or retirement. Impact analysis decides what to regression test.' },
      { t: 'h1', text: 'Ch.3 — Static Testing' },
      { t: 'ul', items: [
        'Static testing examines work products without executing code.',
        'Two forms: reviews (human) and static analysis (tool-based).',
        'Finds defects early and cheaply — even in requirements before code exists.',
        'Review types by formality: informal, walkthrough, technical review, inspection.',
        'Roles: author, manager, facilitator, review leader, reviewer, scribe.',
      ] },
      { t: 'h1', text: 'Ch.4 — Test Techniques' },
      { t: 'table', headers: ['Category', 'Techniques'], rows: [
        ['Black-box', 'Equivalence partitioning, boundary value analysis, decision tables, state transition'],
        ['White-box', 'Statement coverage, branch/decision coverage'],
        ['Experience-based', 'Error guessing, exploratory testing, checklist-based testing'],
      ] },
      { t: 'ul', items: [
        'EP: divide inputs into groups treated the same; test one value per partition.',
        'BVA: test at the edges of partitions where defects cluster.',
        'Decision tables: cover combinations of conditions and actions.',
        'State transition: cover valid (and sometimes invalid) transitions between states.',
        'Statement coverage < branch coverage in thoroughness (100% branch implies 100% statement).',
      ] },
      { t: 'h1', text: 'Ch.5 — Test Management' },
      { t: 'ul', items: [
        'Test plan documents objectives, scope, approach, resources and schedule.',
        'Entry criteria start an activity; exit criteria complete it.',
        'Risk level = likelihood × impact; risk-based testing prioritises effort.',
        'Product risk = the product may be faulty; project risk = management/schedule/resource issues.',
        'Monitoring measures progress; control acts to meet the plan.',
        'Reports: interim (progress) and summary (completion).',
      ] },
      { t: 'h1', text: 'Ch.6 — Tool Support for Testing' },
      { t: 'ul', items: [
        'Tools support activities across the whole test process (management, static, design, execution, performance).',
        'Benefits: reduced repetitive work, greater consistency, objective measurement, easier access to information.',
        'Risks: unrealistic expectations, underestimating effort to introduce, over-reliance, poor maintenance of the tool/scripts.',
        'Run a proof of concept and a pilot before rolling a tool out organisation-wide.',
      ] },
      { t: 'h1', text: 'Final Exam Tips' },
      { t: 'ul', items: [
        'Read every question fully — watch for "NOT" and "BEST/MOST".',
        'Eliminate obviously wrong answers first.',
        'Trust the precise ISTQB definition over everyday usage.',
        'Manage your time — do not linger on one question.',
      ] },
      { t: 'h1', text: 'Common Mistakes' },
      { t: 'ul', items: ['Mixing up the seven principles.', 'Confusing test levels (what is tested) with test types (why/how).', 'Assuming 100% statement coverage means 100% branch coverage — it does not.'] },
      proTip('If you can recite the seven principles, the four test levels, and the risk formula from memory, you have already secured a large share of the exam marks. Drill those three lists until they are effortless.'),
    ],
  },
];
