// ISTQB Foundation Masterclass — Resource Vault, batch 3 (Templates).
const COURSE = 'ISTQB Foundation Masterclass';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'sample-test-plan',
    title: 'Sample Test Plan',
    subtitle: 'A worked IEEE-829-style test plan you can adapt for any project.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'How to Use This Sample' },
      { t: 'p', text: 'This is a completed test plan for a fictional project — the "Acme Online Banking" web application, Release 2.4. Read it to see what "good" looks like, then copy the section headings and replace the example content with your own. It follows the classic IEEE-829 structure that the ISTQB syllabus references.' },
      { t: 'h1', text: '1. Test Plan Identifier' },
      { t: 'p', text: 'ACME-OLB-TP-2.4-v1.0. Approved by the Test Manager on 12 March. This identifier is referenced by every defect report and test summary produced for this release.' },
      { t: 'h1', text: '2. Introduction and Scope' },
      { t: 'p', text: 'This plan covers system and system-integration testing for Release 2.4, which adds the "Instant Payments" feature and updates the login flow to support two-factor authentication.' },
      { t: 'table', headers: ['In scope', 'Out of scope'], rows: [
        ['Instant Payments end-to-end flow', 'Legacy batch-payments engine (unchanged)'],
        ['Two-factor authentication login', 'Native mobile apps (separate plan)'],
        ['Regression of existing transfer features', 'Non-functional load testing beyond agreed thresholds'],
        ['Cross-browser testing (Chrome, Edge, Safari)', 'Internationalisation / localisation'],
      ] },
      { t: 'h1', text: '3. Test Approach' },
      { t: 'p', text: 'Risk-based testing drives prioritisation: payment-handling and authentication carry the highest business risk and receive the deepest coverage. Test design uses equivalence partitioning and boundary value analysis for input fields, and state transition testing for the two-factor login flow. Exploratory sessions supplement scripted tests for the new payments screens.' },
      { t: 'ul', items: [
        'Levels: component (developers), integration, system, and acceptance.',
        'Types: functional, security-focused, and targeted performance checks.',
        'Automation: regression suite runs in CI on every build; new features are automated after they stabilise.',
      ] },
      { t: 'h1', text: '4. Test Items and Deliverables' },
      { t: 'table', headers: ['Deliverable', 'Owner', 'When'], rows: [
        ['Test plan (this document)', 'Test Manager', 'Before test execution starts'],
        ['Test cases and test data', 'Test Analysts', 'During test analysis and design'],
        ['Defect reports', 'Whole test team', 'Throughout execution'],
        ['Test summary report', 'Test Manager', 'At end of each test cycle'],
      ] },
      { t: 'h1', text: '5. Entry and Exit Criteria' },
      { t: 'table', headers: ['Entry criteria', 'Exit criteria'], rows: [
        ['Build deployed to the test environment', 'All planned high-priority test cases executed'],
        ['Smoke test passes', 'No open critical or high-severity defects'],
        ['Test cases reviewed and approved', '95% of planned test cases passed'],
        ['Test data available', 'Known residual risks accepted by stakeholders'],
      ] },
      { t: 'h1', text: '6. Risks and Mitigations' },
      { t: 'table', headers: ['Risk', 'Likelihood', 'Mitigation'], rows: [
        ['Payments environment unstable', 'Medium', 'Daily smoke test; dedicated support contact'],
        ['Late delivery squeezes test window', 'High', 'Prioritise by risk; agree a reduced-scope fallback'],
        ['Two-factor codes expire during testing', 'Low', 'Use test accounts with extended code validity'],
      ] },
      { t: 'h1', text: '7. Schedule and Milestones' },
      { t: 'ol', items: [
        'Week 1 — Test analysis and design; environment ready.',
        'Week 2 — Cycle 1 execution (new features).',
        'Week 3 — Defect fixes and Cycle 2 (regression).',
        'Week 4 — Final regression, exit review, sign-off.',
      ] },
      { t: 'h1', text: '8. Staffing and Responsibilities' },
      { t: 'ul', items: [
        'Test Manager — planning, monitoring, control, reporting.',
        'Two Test Analysts — design and execution.',
        'One automation engineer — regression suite and CI.',
      ] },
      { t: 'callout', variant: 'best', title: 'Best Practice', text: 'A test plan is a living document. Revisit the risks and exit criteria at the start of each cycle — if the situation has changed, the plan should change with it, and the change should be visible to stakeholders.' },
      proTip('Examiners love the phrase "risk-based testing". When you write or read a test plan, always be able to answer: what is the biggest risk here, and where in the plan is it addressed? That single question ties the whole document together.'),
    ],
  },

  {
    slug: 'sample-test-strategy',
    title: 'Sample Test Strategy',
    subtitle: 'An organisation-level strategy that shapes every project test plan.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Test Plan vs Test Strategy' },
      { t: 'p', text: 'The syllabus distinguishes the two clearly, and so should you. A test strategy is a high-level, organisation-wide document describing how testing is done across projects. A test plan is project-specific and describes how a particular release will be tested. Individual test plans inherit from, and must not contradict, this strategy.' },
      { t: 'table', headers: ['Test strategy', 'Test plan'], rows: [
        ['Organisation or programme level', 'Single project or release'],
        ['Stable, changes rarely', 'Created per release, changes often'],
        ['Sets standards and principles', 'Applies those standards to real work'],
      ] },
      { t: 'h1', text: '1. Purpose' },
      { t: 'p', text: 'This strategy defines the standard testing approach for all software delivered by Acme Financial Services. Its goal is consistent, risk-appropriate quality across every product and team.' },
      { t: 'h1', text: '2. Test Levels' },
      { t: 'p', text: 'Every project applies the same four levels, tailored in depth to the risk of the product.' },
      { t: 'table', headers: ['Level', 'Owner', 'Primary objective'], rows: [
        ['Component testing', 'Developers', 'Verify units in isolation'],
        ['Integration testing', 'Developers and testers', 'Verify interfaces between components'],
        ['System testing', 'Test team', 'Verify the whole system against requirements'],
        ['Acceptance testing', 'Business and users', 'Confirm fitness for use and readiness for release'],
      ] },
      { t: 'h1', text: '3. Test Types' },
      { t: 'ul', items: [
        'Functional — behaviour matches the specification.',
        'Non-functional — performance, security, usability, reliability.',
        'Structural — coverage of code and architecture where required.',
        'Change-related — confirmation testing and regression testing after every fix.',
      ] },
      { t: 'h1', text: '4. Risk-Based Approach' },
      { t: 'p', text: 'All projects prioritise testing by product risk. Higher-risk areas (money movement, authentication, data privacy) receive deeper coverage; lower-risk areas receive lighter, mostly automated checks. Risk is reassessed at each release.' },
      { t: 'h1', text: '5. Test Automation Policy' },
      { t: 'ul', items: [
        'Regression tests are automated and run in continuous integration.',
        'New features are automated once behaviour is stable.',
        'Manual effort is reserved for exploratory testing and one-off checks.',
      ] },
      { t: 'h1', text: '6. Environments and Test Data' },
      { t: 'p', text: 'A dedicated, production-like test environment is maintained for each product. Test data is anonymised where it derives from production, in line with data-protection policy.' },
      { t: 'h1', text: '7. Standards and Roles' },
      { t: 'table', headers: ['Area', 'Standard'], rows: [
        ['Defect management', 'All defects logged in the central tracker with severity and priority'],
        ['Reporting', 'Every release produces a test summary report'],
        ['Independence', 'System testing is performed by testers independent of the developers'],
      ] },
      { t: 'h1', text: '8. Test Process Improvement' },
      { t: 'p', text: 'Each release closes with a retrospective. Lessons that apply across projects are folded back into this strategy so the whole organisation improves, not just one team.' },
      { t: 'callout', variant: 'tip', title: 'Remember for the Exam', text: 'A strategy is organisation-wide and long-lived; a plan is project-specific and short-lived. If a question asks which document defines "how the organisation tests in general", the answer is the test strategy.' },
      proTip('When you join a new employer, ask to read their test strategy on day one. It tells you the levels, types, tools and standards you are expected to work within — far faster than picking it up project by project.'),
    ],
  },

  {
    slug: 'example-defect-reports',
    title: 'Example Defect Reports',
    subtitle: 'Worked, high-quality defect reports and what makes them effective.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Why Good Defect Reports Matter' },
      { t: 'p', text: 'A defect report is only useful if a developer can reproduce and fix the problem without asking you questions. Below are three worked examples of well-written reports. Notice how each one is specific, reproducible, and separates what happened from what should have happened.' },
      { t: 'h1', text: 'Example 1 — Functional Defect' },
      { t: 'table', headers: ['Field', 'Content'], rows: [
        ['ID', 'ACME-OLB-DEF-118'],
        ['Summary', 'Transfer of exactly £0.00 is accepted instead of being rejected'],
        ['Environment', 'Release 2.4 build 812, Chrome 124, test environment'],
        ['Steps to reproduce', '1. Log in as test user. 2. Open "Make a payment". 3. Enter amount 0.00. 4. Select a payee. 5. Click "Send".'],
        ['Expected result', 'Validation error: "Amount must be greater than £0.00"'],
        ['Actual result', 'Payment is accepted and a £0.00 transaction appears in history'],
        ['Severity', 'High'],
        ['Priority', 'High'],
      ] },
      { t: 'h1', text: 'Example 2 — Boundary Defect' },
      { t: 'table', headers: ['Field', 'Content'], rows: [
        ['ID', 'ACME-OLB-DEF-124'],
        ['Summary', 'Password field accepts 129 characters; limit should be 128'],
        ['Environment', 'Release 2.4 build 812, Edge 124, test environment'],
        ['Steps to reproduce', '1. Go to "Change password". 2. Paste a 129-character password. 3. Submit.'],
        ['Expected result', 'Rejected with "Password must be 128 characters or fewer"'],
        ['Actual result', 'Password is saved; user cannot log in afterwards'],
        ['Severity', 'Medium'],
        ['Priority', 'High'],
      ] },
      { t: 'h1', text: 'Example 3 — Usability / UI Defect' },
      { t: 'table', headers: ['Field', 'Content'], rows: [
        ['ID', 'ACME-OLB-DEF-131'],
        ['Summary', 'Error message overlaps the "Send" button on small screens'],
        ['Environment', 'Release 2.4 build 812, Safari 17, viewport 375px wide'],
        ['Steps to reproduce', '1. Open payments on a 375px-wide viewport. 2. Trigger a validation error.'],
        ['Expected result', 'Error text sits above the button and both are readable'],
        ['Actual result', 'Error text overlaps the button, hiding the label'],
        ['Severity', 'Low'],
        ['Priority', 'Medium'],
      ] },
      { t: 'h1', text: 'Severity vs Priority' },
      { t: 'p', text: 'These are independent. Severity is the impact on the system; priority is how soon it should be fixed. A cosmetic logo error on the home page can be low severity but high priority if it damages the brand before a launch.' },
      { t: 'ul', items: [
        'Severity — technical/business impact of the defect.',
        'Priority — urgency of the fix relative to other work.',
      ] },
      { t: 'h1', text: 'What Makes a Good Report' },
      { t: 'ol', items: [
        'A clear, specific summary that reads like a headline.',
        'Exact environment and build so it can be reproduced.',
        'Numbered, minimal steps to reproduce.',
        'Expected and actual results stated separately.',
        'Objective severity and priority, plus evidence (screenshot or log).',
      ] },
      { t: 'callout', variant: 'best', title: 'What Makes a Good Report', text: 'Write every defect so that a developer who has never seen the feature can reproduce it from your report alone. If you find yourself needing to explain it in person, the written report is not yet complete.' },
      { t: 'callout', variant: 'mistake', title: 'Common Mistakes', text: 'Vague summaries ("payment is broken"), missing steps, combining several issues in one report, and mixing up severity and priority. Each of these forces the developer to come back to you and slows the fix.' },
      proTip('Always attach evidence. A screenshot, a short recording, or the relevant log line turns a disputed "cannot reproduce" into an accepted, actionable defect — and protects your credibility as a tester.'),
    ],
  },

  {
    slug: 'revision-planner',
    title: 'Revision Planner',
    subtitle: 'A weekly template to structure your ISTQB revision with prompts.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'How to Use This Planner' },
      { t: 'p', text: 'Copy the weekly grid below into your notebook or a document and fill it in at the start of each week. The prompts turn vague "I should revise" intentions into concrete, testable goals. Revision works best in short, active sessions rather than long passive re-reading.' },
      { t: 'h1', text: 'Weekly Planner Grid' },
      { t: 'table', headers: ['Day', 'Topic / syllabus chapter', 'Active task', 'Done?'], rows: [
        ['Monday', '', 'Read + summarise in your own words', ''],
        ['Tuesday', '', 'Make flashcards for key terms', ''],
        ['Wednesday', '', 'Answer 10 practice questions', ''],
        ['Thursday', '', 'Review yesterday’s wrong answers', ''],
        ['Friday', '', 'Teach the topic aloud to an empty room', ''],
        ['Weekend', 'Mixed review', 'Short mock across the week’s topics', ''],
      ] },
      { t: 'h1', text: 'Start-of-Week Prompts' },
      { t: 'ul', items: [
        'Which syllabus chapter am I focusing on this week?',
        'Which learning objectives (K1/K2/K3) does it contain?',
        'What did I score worst on last week, and how will I revisit it?',
        'How many practice questions will I commit to this week?',
      ] },
      { t: 'h1', text: 'End-of-Week Review Prompts' },
      { t: 'ol', items: [
        'What are the three most important things I learned this week?',
        'Which topic still feels shaky and needs another pass?',
        'Did I hit my practice-question target? If not, why?',
        'What one change will make next week more effective?',
      ] },
      { t: 'h1', text: 'Active Revision Techniques' },
      { t: 'table', headers: ['Technique', 'Why it works'], rows: [
        ['Self-testing', 'Retrieval strengthens memory far more than re-reading'],
        ['Spaced repetition', 'Revisiting over days beats cramming in one sitting'],
        ['Teaching aloud', 'Exposes the gaps you cannot yet explain'],
        ['Interleaving topics', 'Mixing chapters mirrors the real exam'],
      ] },
      { t: 'h1', text: 'Tracking Your Confidence' },
      { t: 'p', text: 'Rate each chapter red / amber / green each week. Spend most of your time on red and amber; do not over-revise the green topics you already know.' },
      { t: 'table', headers: ['Chapter', 'Week 1', 'Week 2', 'Week 3'], rows: [
        ['1. Fundamentals of testing', '', '', ''],
        ['2. Testing throughout the lifecycle', '', '', ''],
        ['3. Static testing', '', '', ''],
        ['4. Test analysis and design', '', '', ''],
        ['5. Managing test activities', '', '', ''],
        ['6. Test tools', '', '', ''],
      ] },
      { t: 'callout', variant: 'tip', title: 'Study Tip', text: 'If you cannot explain a concept in a plain sentence without notes, you do not yet know it well enough for the exam. Use the Friday "teach aloud" task to find those gaps early.' },
      proTip('Track wrong answers, not just scores. Keep a running list of every practice question you get wrong and re-attempt them a week later. Your mistakes are the single most efficient thing you can revise.'),
    ],
  },

  {
    slug: 'twelve-week-study-plan',
    title: '12-Week Study Plan',
    subtitle: 'A week-by-week route through the syllabus to exam day.',
    courseTitle: COURSE, category: 'Templates',
    blocks: [
      { t: 'h1', text: 'Overview' },
      { t: 'p', text: 'This plan spreads the ISTQB Foundation syllabus across twelve manageable weeks, roughly three to five hours each. It maps each week to a syllabus chapter, gives concrete activities, and builds in mock-exam checkpoints so you always know how ready you are. Adjust the pace to your schedule, but keep the mock checkpoints — they are how you measure progress.' },
      { t: 'h1', text: 'The 12-Week Schedule' },
      { t: 'table', headers: ['Week', 'Focus', 'Activities', 'Checkpoint'], rows: [
        ['1', 'Ch.1 Fundamentals of testing', 'Read chapter; note the seven testing principles; learn key terms', 'Define testing vs debugging in your own words'],
        ['2', 'Ch.1 continued', 'Test process and the psychology of testing; make flashcards', 'Score 70%+ on a Chapter 1 quiz'],
        ['3', 'Ch.2 Testing throughout the SDLC', 'Compare development models; learn the four test levels', 'List the test levels and their objectives from memory'],
        ['4', 'Ch.2 continued', 'Test types and maintenance testing; confirmation vs regression', 'Score 70%+ on a Chapter 2 quiz'],
        ['5', 'Ch.3 Static testing', 'Reviews, review types, and the review process', 'Explain when static testing finds defects cheaply'],
        ['6', 'Consolidation + Mock 1', 'Revise Chapters 1–3; sit a half-length mock', 'Mock 1 complete; log every wrong answer'],
        ['7', 'Ch.4 Test analysis and design', 'Black-box: equivalence partitioning and boundary value analysis', 'Design test cases for a sample input field'],
        ['8', 'Ch.4 continued', 'Decision tables, state transition, and use-case testing', 'Build a decision table for a small rule set'],
        ['9', 'Ch.4 continued', 'White-box and experience-based techniques', 'Score 70%+ on a Chapter 4 quiz'],
        ['10', 'Ch.5 Managing test activities', 'Planning, risk, monitoring, control, and defect management', 'Explain severity vs priority with an example'],
        ['11', 'Ch.6 Test tools + Mock 2', 'Tool categories and benefits/risks; sit a full mock', 'Mock 2 complete; target 65%+ overall'],
        ['12', 'Final revision + Mock 3', 'Revisit weak areas; sit a final timed full mock', 'Mock 3 at 75%+ — you are exam-ready'],
      ] },
      { t: 'h1', text: 'Mock-Exam Checkpoints' },
      { t: 'p', text: 'Three mocks are built in on purpose. Mock 1 is diagnostic — expect a modest score and use it to find gaps. Mock 2 measures real progress. Mock 3 should be under timed, exam-like conditions.' },
      { t: 'table', headers: ['Mock', 'Week', 'Purpose', 'Target'], rows: [
        ['Mock 1', '6', 'Diagnostic — find weak areas early', 'Just complete it'],
        ['Mock 2', '11', 'Measure progress across all chapters', '65%+'],
        ['Mock 3', '12', 'Final readiness under exam conditions', '75%+'],
      ] },
      { t: 'h1', text: 'Weekly Rhythm' },
      { t: 'ol', items: [
        'Read and summarise the chapter in your own words.',
        'Make flashcards for the key terms and definitions.',
        'Answer practice questions and log every wrong answer.',
        'Re-attempt last week’s wrong answers before moving on.',
      ] },
      { t: 'h1', text: 'Milestones at a Glance' },
      { t: 'ul', items: [
        'End of Week 6 — Chapters 1–3 covered; first mock sat.',
        'End of Week 9 — Test design techniques mastered.',
        'End of Week 11 — Whole syllabus covered; second mock sat.',
        'End of Week 12 — Consistently scoring 75%+; book the exam.',
      ] },
      { t: 'h1', text: 'If You Fall Behind' },
      { t: 'p', text: 'Do not abandon the plan — compress it. Combine the two lightest weeks, but never skip a mock checkpoint. The mocks are your early-warning system, and cutting them removes the one signal that tells you whether you are ready.' },
      { t: 'callout', variant: 'best', title: 'Best Practice', text: 'The pass mark is 65% (26 of 40). Aim to score consistently above 75% in your mocks before booking. That margin absorbs exam-day nerves and the occasional awkwardly worded question.' },
      proTip('Book your exam only after Mock 2. A fixed date is a powerful motivator, but booking it before you have proven your progress with a real mock risks paying to sit an exam you are not ready for.'),
    ],
  },
];
