// ISTQB Foundation Masterclass — Resource Vault, batch 1.
const COURSE = 'ISTQB Foundation Masterclass';
const proTip = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });

export default [
  {
    slug: 'boundary-value-cheat-sheet',
    title: 'Boundary Value Analysis Cheat Sheet',
    subtitle: 'Find the defects that hide at the edges of every input range.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Boundary Value Analysis (BVA) is a black-box test technique based on the observation that defects cluster at the edges of equivalence partitions. Instead of testing every value, you test the values on and around each boundary. This cheat sheet gives you the rules, a worked example and the exam traps.' },
      { t: 'h1', text: 'Why Boundaries Matter' },
      { t: 'p', text: 'Programmers make mistakes with relational operators (< versus <=), off-by-one errors and loop conditions. These bugs surface precisely at the boundaries of a range, so testing boundary values gives high defect-detection power for very few test cases.' },
      { t: 'h1', text: 'Two-Value vs Three-Value BVA' },
      { t: 'table', headers: ['Approach', 'Values tested per boundary', 'Coverage'], rows: [
        ['Two-value (2-point)', 'The boundary value and its nearest neighbour on the other side', 'Standard ISTQB Foundation approach'],
        ['Three-value (3-point)', 'The value before, on, and after the boundary', 'Stronger; recommended when risk is high'],
      ] },
      { t: 'h1', text: 'Worked Example — an integer field valid for 1 to 100' },
      { t: 'p', text: 'The valid partition is 1..100. Its boundaries are 1 (lower) and 100 (upper). Below is the full set of two-value and three-value boundary values.' },
      { t: 'table', headers: ['Boundary', 'Two-value BVA', 'Three-value BVA'], rows: [
        ['Lower (1)', '0, 1', '0, 1, 2'],
        ['Upper (100)', '100, 101', '99, 100, 101'],
      ] },
      { t: 'p', text: 'So for two-value BVA you would test 0, 1, 100 and 101. Values 0 and 101 are invalid; 1 and 100 are valid. This tiny set catches almost every off-by-one defect in the field.' },
      { t: 'h1', text: 'Step-by-Step Method' },
      { t: 'ol', items: [
        'Identify the equivalence partitions for the input (valid and invalid).',
        'Find the minimum and maximum boundary of each partition.',
        'Select the boundary value and its immediate neighbour(s).',
        'Design one test case per boundary value, noting the expected result.',
        'Remember: a valid boundary and the adjacent invalid value are both worth testing.',
      ] },
      { t: 'h1', text: 'Exam Traps & Common Mistakes' },
      { t: 'ul', items: [
        'Confusing the boundary with the whole partition — BVA tests the edges, Equivalence Partitioning tests a representative from the middle.',
        'Forgetting that boundaries exist on both valid and invalid partitions.',
        'Using the wrong increment for non-integers (for a currency field to 2 decimals, the neighbour of 100.00 is 100.01, not 101).',
        'Assuming three-value BVA is the ISTQB default — the syllabus default is two-value.',
      ] },
      { t: 'callout', variant: 'mistake', title: 'Watch Out', text: 'The neighbouring value must respect the field precision. For a field accepting one decimal place valid 0.0 to 9.9, the value just above the upper boundary is 10.0, and the value just below is 9.8 for three-value BVA — not 10 and 9.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Combine BVA with Equivalence Partitioning — they are complementary.', 'Always record the expected result for each boundary case.', 'Escalate to three-value BVA for safety-critical or high-risk boundaries.'] },
      proTip('In interviews and the ISTQB exam, if asked "how many test cases for a 1–100 field using two-value BVA", the answer is four: 0, 1, 100 and 101. Say it with confidence.'),
    ],
  },

  {
    slug: 'decision-table-cheat-sheet',
    title: 'Decision Table Testing Cheat Sheet',
    subtitle: 'Test combinations of conditions systematically, with no gaps.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Decision Table Testing is a black-box technique for systems where the outcome depends on combinations of conditions — business rules, eligibility checks, pricing logic. It guarantees you cover every meaningful combination and exposes rules that were never specified. This cheat sheet shows the structure, a worked table and the exam traps.' },
      { t: 'h1', text: 'Anatomy of a Decision Table' },
      { t: 'table', headers: ['Part', 'Meaning'], rows: [
        ['Conditions', 'The inputs or circumstances (rows in the top half)'],
        ['Actions', 'The outcomes or system responses (rows in the bottom half)'],
        ['Rules', 'Each column — a unique combination of condition values and its actions'],
        ['T / F', 'Whether a condition is true or false for that rule'],
        ['X', 'Marks which action fires for that rule'],
      ] },
      { t: 'h1', text: 'How Many Rules?' },
      { t: 'p', text: 'A full (or "complete") decision table has one rule for every combination of conditions. For N binary (true/false) conditions there are 2^N rules. Two conditions give 4 rules, three conditions give 8, and so on. You then collapse rules that produce the same action to simplify.' },
      { t: 'h1', text: 'Worked Example — online discount eligibility' },
      { t: 'p', text: 'Rule: a customer gets a 10% discount only if they are a registered member AND their basket is over 50 pounds. If they are a member but the basket is 50 or under, they get free delivery only. Non-members get nothing extra.' },
      { t: 'table', headers: ['Conditions', 'Rule 1', 'Rule 2', 'Rule 3', 'Rule 4'], rows: [
        ['Registered member?', 'T', 'T', 'F', 'F'],
        ['Basket over 50?', 'T', 'F', 'T', 'F'],
        ['Action: 10% discount', 'X', '-', '-', '-'],
        ['Action: Free delivery', '-', 'X', '-', '-'],
        ['Action: No offer', '-', '-', 'X', 'X'],
      ] },
      { t: 'p', text: 'Each column is one test case. Rules 3 and 4 both give "No offer" regardless of basket value, so they could be collapsed into a single rule with a dash ("-") for the basket condition to indicate it does not matter.' },
      { t: 'h1', text: 'Step-by-Step Method' },
      { t: 'ol', items: [
        'List all the conditions that affect the outcome.',
        'List all the possible actions.',
        'Build a column for every combination of condition values (2^N for binary conditions).',
        'Fill in which action(s) each rule triggers.',
        'Collapse redundant rules, then derive one test case per remaining rule.',
      ] },
      { t: 'h1', text: 'Exam Traps & Common Mistakes' },
      { t: 'ul', items: [
        'Miscounting rules — for 3 binary conditions it is 8 rules (2^3), not 6.',
        'Forgetting non-binary conditions multiply the combinations (2 x 3 conditions give 6 rules).',
        'Collapsing rules that look similar but actually fire different actions.',
        'Confusing conditions (inputs) with actions (outputs) when laying out the table.',
      ] },
      { t: 'callout', variant: 'tip', title: 'Coverage Tip', text: 'Minimum coverage for decision table testing is one test case per rule (column). Collapsing rules reduces the count, but every distinct combination of relevant conditions must still be exercised at least once.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Use decision tables whenever a requirement reads "if... and... then...".', 'Collapse impossible or redundant combinations to keep the table readable.', 'Review the table with a business analyst — gaps often reveal missing requirements.'] },
      proTip('Decision tables are a testing and a requirements tool. Building the full table frequently surfaces combinations the specification never mentioned — raise those as questions before you write a single test.'),
    ],
  },

  {
    slug: 'state-transition-guide',
    title: 'State Transition Testing Guide',
    subtitle: 'Test how a system behaves as it moves between states over time.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'State Transition Testing is a black-box technique for systems whose behaviour depends on their current state and the history of events — login flows, order lifecycles, media players, ATMs. It models the system as states, events and transitions, then designs tests to cover them. This guide gives you the model, a worked example and the coverage levels.' },
      { t: 'h1', text: 'Core Concepts' },
      { t: 'table', headers: ['Term', 'Meaning'], rows: [
        ['State', 'A condition the system can be in (e.g. Logged Out, Locked)'],
        ['Event', 'An input or trigger (e.g. enter password)'],
        ['Transition', 'The move from one state to another caused by an event'],
        ['Action', 'What the system does during a transition (optional)'],
        ['Guard', 'A condition that must be true for a transition to fire (optional)'],
      ] },
      { t: 'h1', text: 'Two Ways to Model It' },
      { t: 'ul', items: [
        'State diagram — a graph of states (boxes) and transitions (arrows) labelled with the triggering event; best for visualising behaviour.',
        'State table — a grid of states versus events showing the resulting state; best for spotting invalid or missing transitions.',
      ] },
      { t: 'h1', text: 'Worked Example — login with account lock (state diagram described)' },
      { t: 'p', text: 'States: Logged Out, Logged In, Locked. From Logged Out, a correct password transitions to Logged In. An incorrect password stays in Logged Out but increments a counter; after 3 failed attempts the guard fires and the system moves to Locked. From Logged In, a logout event returns to Logged Out. From Locked, only a reset event returns to Logged Out. Picture three boxes with arrows: Logged Out to Logged In (correct password), Logged Out to itself (wrong password, attempts < 3), Logged Out to Locked (wrong password, 3rd attempt), Logged In to Logged Out (logout), Locked to Logged Out (reset).' },
      { t: 'h1', text: 'The Same System as a State Table' },
      { t: 'table', headers: ['Current State', 'Event: correct pwd', 'Event: wrong pwd', 'Event: logout', 'Event: reset'], rows: [
        ['Logged Out', 'Logged In', 'Logged Out / Locked', '- (invalid)', '- (invalid)'],
        ['Logged In', '- (invalid)', '- (invalid)', 'Logged Out', '- (invalid)'],
        ['Locked', '- (invalid)', '- (invalid)', '- (invalid)', 'Logged Out'],
      ] },
      { t: 'p', text: 'The blank/"invalid" cells are gold: they are transitions the specification may not have defined. Testing them (what happens if you send "logout" while Locked?) often finds real defects.' },
      { t: 'h1', text: 'Coverage Levels' },
      { t: 'table', headers: ['Coverage', 'What it requires'], rows: [
        ['All states (0-switch, state coverage)', 'Visit every state at least once'],
        ['All valid transitions (0-switch, transition coverage)', 'Exercise every valid transition at least once — the usual ISTQB minimum'],
        ['All transitions incl. invalid', 'Also attempt every invalid event in every state'],
        ['N-switch (e.g. 1-switch)', 'Cover every sequence of N+1 successive transitions'],
      ] },
      { t: 'h1', text: 'Exam Traps & Common Mistakes' },
      { t: 'ul', items: [
        'Confusing state coverage (visit every state) with transition coverage (exercise every transition) — transition coverage is stronger.',
        'A 1-switch test covers pairs of transitions, not single ones — do not equate "1-switch" with "one transition".',
        'Ignoring invalid transitions, which is exactly where robustness defects hide.',
        'Forgetting guards — a transition may only fire when a condition (like attempts = 3) is met.',
      ] },
      { t: 'callout', variant: 'mistake', title: 'Watch Out', text: 'Achieving "all states" coverage does NOT guarantee "all transitions" coverage. You can touch every state while missing several transitions between them. Transition coverage is the more meaningful target.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Draw the diagram first, then derive the table to catch missing transitions.', 'Always include invalid-event tests for robustness.', 'Aim for at least all-valid-transition coverage as a baseline.'] },
      proTip('The invalid cells in a state table are the most valuable tests you will write. Specifications rarely define what happens when an unexpected event arrives in a given state — so that is where the defects live.'),
    ],
  },

  {
    slug: 'equivalence-partitioning-guide',
    title: 'Equivalence Partitioning Guide',
    subtitle: 'Slash your test count without losing coverage.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Equivalence Partitioning (EP) is a black-box technique that divides the input (or output) data into partitions where the system is expected to behave the same way. You then test just one representative value from each partition, on the principle that if it works for one, it works for all. This guide shows you how to partition, a worked example and how EP pairs with Boundary Value Analysis.' },
      { t: 'h1', text: 'The Core Idea' },
      { t: 'p', text: 'If every value in a group should be treated identically by the system, testing one value from that group is as good as testing them all. This dramatically reduces the number of test cases while keeping systematic coverage. Partitions can be valid (accepted values) or invalid (rejected values).' },
      { t: 'h1', text: 'Valid vs Invalid Partitions' },
      { t: 'table', headers: ['Partition type', 'Purpose', 'Expected result'], rows: [
        ['Valid', 'Values the system should accept and process', 'Accepted / processed correctly'],
        ['Invalid', 'Values the system should reject', 'Handled gracefully (error message, rejection)'],
      ] },
      { t: 'h1', text: 'Worked Example — age field valid for 18 to 65' },
      { t: 'p', text: 'The specification says an applicant must be aged 18 to 65 inclusive. That gives three partitions: too young, valid, too old. Pick one representative from each.' },
      { t: 'table', headers: ['Partition', 'Range', 'Representative value', 'Expected result'], rows: [
        ['Invalid — too young', '0 to 17', '10', 'Rejected'],
        ['Valid', '18 to 65', '40', 'Accepted'],
        ['Invalid — too old', '66 and above', '70', 'Rejected'],
      ] },
      { t: 'p', text: 'Three test cases (10, 40, 70) give full equivalence-partition coverage of this field. Note that EP picks values from the middle of each partition; the edges (17, 18, 65, 66) are the job of Boundary Value Analysis.' },
      { t: 'h1', text: 'Step-by-Step Method' },
      { t: 'ol', items: [
        'Identify the input or output under test and its specification.',
        'Divide the data into partitions where behaviour should be identical.',
        'Include both valid and invalid partitions.',
        'Choose one representative value from each partition (typically a mid-range value).',
        'Design one test case per partition, recording the expected result.',
      ] },
      { t: 'h1', text: 'Coverage & Combining with BVA' },
      { t: 'p', text: 'Minimum EP coverage is one test per partition. In practice you almost always combine EP with Boundary Value Analysis: EP tells you the partitions, BVA tests their edges. Together they give strong coverage of a numeric field for very few cases.' },
      { t: 'h1', text: 'Exam Traps & Common Mistakes' },
      { t: 'ul', items: [
        'Forgetting the invalid partitions — testers often only pick valid values.',
        'Choosing boundary values as representatives; EP wants a mid-partition value, BVA handles the edges.',
        'Assuming partitions never overlap — a well-formed partition set is mutually exclusive and covers all possible values.',
        'Partitioning only inputs — outputs and even internal data can be partitioned too.',
      ] },
      { t: 'callout', variant: 'tip', title: 'Coverage Tip', text: 'EP coverage is measured as the number of partitions covered divided by the total number of partitions. Cover every valid and invalid partition at least once to reach 100%.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Always partition both valid and invalid data.', 'Use EP to decide "which values", then BVA for "which edges".', 'Document each partition and its representative so coverage is auditable.'] },
      proTip('EP and BVA are the classic pairing in the ISTQB exam and in real test design. Whenever you see a numeric or range-based field, reach for both: EP for the partitions, BVA for the boundaries.'),
    ],
  },

  {
    slug: 'severity-vs-priority-guide',
    title: 'Severity vs Priority Guide',
    subtitle: 'Stop confusing "how bad" with "how soon" — and log defects that get actioned.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Introduction' },
      { t: 'p', text: 'Severity and priority are two of the most misunderstood attributes on a defect report. They are independent: a defect can be highly severe but low priority, or trivial but urgent. Getting them right means the team fixes the right things at the right time. This guide defines both, shows the four combinations and gives a worked matrix.' },
      { t: 'h1', text: 'Definitions' },
      { t: 'table', headers: ['Attribute', 'Answers the question', 'Usually set by'], rows: [
        ['Severity', 'How badly does this defect affect the system or user?', 'The tester (technical impact)'],
        ['Priority', 'How soon should this defect be fixed?', 'Product owner / business (business urgency)'],
      ] },
      { t: 'h1', text: 'Why They Are Independent' },
      { t: 'p', text: 'Severity is about technical impact and is relatively objective. Priority is about business urgency and depends on context — release dates, how many users hit the issue, contractual obligations. Because they answer different questions, all four combinations of high/low are possible and legitimate.' },
      { t: 'h1', text: 'The Four Combinations — worked matrix' },
      { t: 'table', headers: ['Combination', 'Example', 'Typical action'], rows: [
        ['High severity, High priority', 'Payment processing crashes for all users on checkout', 'Fix immediately — blocks release'],
        ['High severity, Low priority', 'App crashes on an obsolete browser used by 0.1% of users', 'Serious, but can wait — schedule for later'],
        ['Low severity, High priority', 'Company logo is misspelt on the home page', 'Cosmetic, but embarrassing — fix before launch'],
        ['Low severity, Low priority', 'Minor typo in a rarely visited help page', 'Fix when convenient / backlog'],
      ] },
      { t: 'p', text: 'The high-severity/low-priority and low-severity/high-priority rows are the ones that prove the two attributes are not the same thing. Expect at least one exam question probing this.' },
      { t: 'h1', text: 'Example Severity Scale' },
      { t: 'table', headers: ['Severity level', 'Meaning'], rows: [
        ['Critical / Blocker', 'System crash, data loss, or complete feature unusable with no workaround'],
        ['Major', 'Significant feature broken but a workaround exists'],
        ['Minor', 'Small functional issue with little impact'],
        ['Cosmetic / Trivial', 'UI/spelling issue not affecting function'],
      ] },
      { t: 'h1', text: 'What Else a Good Defect Report Contains' },
      { t: 'ul', items: [
        'Unique ID and clear, specific title',
        'Steps to reproduce, expected result and actual result',
        'Environment (build, browser, OS, device)',
        'Severity and priority',
        'Evidence — screenshots, logs, video',
        'Status and, where known, the root cause or affected area',
      ] },
      { t: 'h1', text: 'Exam Traps & Common Mistakes' },
      { t: 'ul', items: [
        'Treating severity and priority as the same thing — the classic error.',
        'Assuming high severity always means high priority (the obsolete-browser crash disproves this).',
        'Letting testers set priority — priority is a business decision, severity is the tester\'s call.',
        'Vague titles ("it doesn\'t work") that give triage nothing to act on.',
      ] },
      { t: 'callout', variant: 'mistake', title: 'Watch Out', text: 'A defect being severe does not entitle it to be fixed first. Priority is decided by the business against release goals. Log the severity accurately, then let priority be set separately — never conflate the two.' },
      { t: 'h1', text: 'Best Practices' },
      { t: 'ul', items: ['Set severity from technical impact; leave priority to the product owner.', 'Write titles a triager can action without opening the report.', 'Always attach evidence and reproduction steps to justify the severity you assign.'] },
      proTip('When you log a defect, ask two separate questions: "How badly does this break things?" (severity) and "How soon does the business need it fixed?" (priority). Answer them independently and your reports will be triaged far faster.'),
    ],
  },
];
