// ISTQB Foundation Masterclass — Cheat Sheets resource batch 4.
const COURSE = 'ISTQB Foundation Masterclass';
const tip = (title, text) => ({ t: 'callout', variant: 'tip', title, text });
const pro = (text) => ({ t: 'callout', variant: 'pro', title: 'Inside STLC Pro Tip', text });
const best = (text) => ({ t: 'callout', variant: 'best', title: 'Best Practice', text });
const mistake = (text) => ({ t: 'callout', variant: 'mistake', title: 'Common Mistake', text });

export default [
  {
    slug: 'flash-cards',
    title: 'Flash Cards',
    subtitle: '30 exam-ready question and answer cards, grouped by syllabus chapter.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'How to Use These Flash Cards' },
      { t: 'p', text: 'Cover the Answer column, read the Term or Question, and say the answer aloud before revealing it. Cards are grouped by the six chapters of the ISTQB Certified Tester Foundation Level (CTFL) syllabus. Aim to recall each card correctly on three separate days before the exam.' },
      { t: 'spacer' },
      { t: 'h2', text: 'Chapter 1 — Fundamentals of Testing' },
      { t: 'table', headers: ['Term / Question', 'Answer'], rows: [
        ['What is a defect (bug)?', 'A flaw in a component or system that can cause it to fail to perform its required function.'],
        ['Error vs defect vs failure?', 'An error (mistake) by a person causes a defect (fault) in code; a defect, when executed, may cause a failure (wrong external behaviour).'],
        ['What is the purpose of testing?', 'To evaluate quality and reduce the risk of failure in operation; testing gives information for decisions, it does not "prove" correctness.'],
        ['"Testing shows the presence of defects, not their absence" means?', 'Testing can reveal defects but can never prove there are none; passing tests do not guarantee a defect-free product.'],
        ['What is exhaustive testing?', 'Testing every input and precondition combination. It is impossible except for trivial cases, so we use techniques and risk to focus effort.'],
        ['What does the defect clustering principle state?', 'A small number of modules usually contain most of the defects (aligned with the Pareto principle).'],
      ] },
      { t: 'h2', text: 'Chapter 2 — Testing Throughout the SDLC' },
      { t: 'table', headers: ['Term / Question', 'Answer'], rows: [
        ['Name the four test levels.', 'Component (unit), Integration, System, and Acceptance testing.'],
        ['What is component testing?', 'Testing individual components or units in isolation, usually by developers, often with stubs and drivers.'],
        ['What is acceptance testing?', 'Validating readiness for use against user needs. Forms include UAT, operational, contractual/regulatory, alpha and beta testing.'],
        ['Name the four main test types.', 'Functional, Non-functional, White-box (structural), and Change-related (confirmation and regression) testing.'],
        ['Confirmation vs regression testing?', 'Confirmation re-tests a fixed defect to check it is resolved; regression checks that a change has not broken previously working areas.'],
        ['What is shift-left?', 'An approach that performs testing and quality activities earlier in the lifecycle to find defects sooner and cheaper.'],
      ] },
      { t: 'h2', text: 'Chapter 3 — Static Testing' },
      { t: 'table', headers: ['Term / Question', 'Answer'], rows: [
        ['Static vs dynamic testing?', 'Static testing examines work products without executing code (reviews, static analysis); dynamic testing runs the software.'],
        ['Name the review types by formality.', 'Informal review, walkthrough, technical review, and inspection (least to most formal).'],
        ['Name the key review roles.', 'Manager, Author, Moderator (facilitator), Scribe (recorder), Reviewer, and Review leader.'],
        ['A key benefit of static testing?', 'Finds defects early and cheaply, including some (e.g. requirement ambiguities) that dynamic testing cannot detect.'],
      ] },
      { t: 'h2', text: 'Chapter 4 — Test Techniques' },
      { t: 'table', headers: ['Term / Question', 'Answer'], rows: [
        ['Black-box vs white-box techniques?', 'Black-box derives tests from specifications/behaviour; white-box derives them from the internal structure/code.'],
        ['What is equivalence partitioning?', 'Dividing inputs into partitions expected to be treated the same, then testing one value per partition (valid and invalid).'],
        ['What is boundary value analysis?', 'Testing at the edges of partitions, where defects cluster (minimum, maximum and just inside/outside the boundaries).'],
        ['When are decision tables useful?', 'When behaviour depends on combinations of conditions; each column is a rule combining conditions and actions.'],
        ['What is state transition testing?', 'Testing valid and invalid transitions between the states of a system, based on a state diagram or table.'],
        ['What is experience-based testing?', 'Techniques using tester knowledge and intuition: error guessing, exploratory testing and checklist-based testing.'],
      ] },
      { t: 'h2', text: 'Chapter 5 — Managing the Test Activities' },
      { t: 'table', headers: ['Term / Question', 'Answer'], rows: [
        ['What is in a test plan?', 'Scope, objectives, approach, resources, schedule, entry/exit criteria and risks for the test activities.'],
        ['Entry vs exit criteria?', 'Entry (definition of ready) must be met to start an activity; exit (definition of done) must be met to consider it complete.'],
        ['What is a product (quality) risk?', 'A risk that the product may fail to satisfy stakeholders (e.g. a defect); addressed by test design and execution.'],
        ['What is risk-based testing?', 'Prioritising test effort by risk level (likelihood x impact), testing the highest-risk areas first and most thoroughly.'],
        ['What does a defect report contain?', 'Unique ID, summary, steps to reproduce, expected vs actual result, severity, priority and status.'],
        ['Severity vs priority?', 'Severity is the impact of the defect on the system; priority is the urgency with which it should be fixed.'],
      ] },
      { t: 'h2', text: 'Chapter 6 — Test Tools' },
      { t: 'table', headers: ['Term / Question', 'Answer'], rows: [
        ['A benefit and a risk of test automation?', 'Benefit: repeatable, fast regression runs. Risk: underestimating cost of maintaining tests and tools.'],
        ['What is a test execution (unit test) tool?', 'A tool that runs tests automatically and compares actual with expected results (e.g. xUnit frameworks).'],
      ] },
      pro('Read the card, hide the answer, and answer aloud in a full sentence. Recalling actively (not just re-reading) is what moves knowledge into long-term memory before the exam.'),
    ],
  },

  {
    slug: 'memory-aids-mnemonics',
    title: 'Memory Aids & Mnemonics',
    subtitle: 'Simple, correct mnemonics for the lists the ISTQB exam loves to test.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Why Mnemonics Work' },
      { t: 'p', text: 'The Foundation exam is full of ordered and unordered lists — the seven testing principles, the test levels, the fundamental test process, the review roles. A short, memorable phrase turns a list you would forget under pressure into one you can rebuild letter by letter.' },
      { t: 'spacer' },
      { t: 'h1', text: 'The Seven Testing Principles — "SEE-D-CAP"' },
      { t: 'p', text: 'Recall the seven principles with the phrase "SEE-D-CAP".' },
      { t: 'table', headers: ['Letter', 'Stands for', 'Principle'], rows: [
        ['S', 'Shows presence', 'Testing shows the presence of defects, not their absence.'],
        ['E', 'Exhaustive impossible', 'Exhaustive testing is impossible.'],
        ['E', 'Early testing', 'Early testing saves time and money (shift-left).'],
        ['D', 'Defects cluster', 'Defects cluster together (Pareto).'],
        ['C', 'no Cure-all (pesticide)', 'Tests wear out — the pesticide paradox; vary your tests.'],
        ['A', 'context-dependent (Adapt)', 'Testing is context dependent.'],
        ['P', 'Presence != correct (absence-of-errors)', 'The absence-of-errors fallacy — a bug-free system can still fail user needs.'],
      ] },
      { t: 'h1', text: 'Test Levels — "Can I See Accurately?"' },
      { t: 'p', text: 'The four test levels, in order from smallest to largest scope: Can (Component) I (Integration) See (System) Accurately (Acceptance).' },
      { t: 'ul', items: [
        'C — Component (unit) testing',
        'I — Integration testing',
        'S — System testing',
        'A — Acceptance testing',
      ] },
      { t: 'h1', text: 'Fundamental Test Process — "Please Make Delicious Iced Coffee, Cheers"' },
      { t: 'p', text: 'The test activities in the ISTQB test process spell PMDICC.' },
      { t: 'table', headers: ['Letter', 'Activity'], rows: [
        ['P — Please', 'Planning'],
        ['M — Make', 'Monitoring and control'],
        ['D — Delicious', 'Design (analysis and design)'],
        ['I — Iced', 'Implementation'],
        ['C — Coffee', 'Execution (Carry out the tests)'],
        ['C — Cheers', 'Completion (Closure)'],
      ] },
      { t: 'h1', text: 'Review Roles — "MAM-SR"' },
      { t: 'p', text: 'The key roles in a formal review: MAM-SR.' },
      { t: 'ul', items: [
        'M — Manager (decides on the review, allocates resources)',
        'A — Author (creator of the work product under review)',
        'M — Moderator / Facilitator (leads the meeting, keeps it objective)',
        'S — Scribe / Recorder (documents the findings)',
        'R — Reviewer (examines the work product; the Review Leader takes overall responsibility)',
      ] },
      { t: 'h1', text: 'Review Types by Formality — "I Won\'t Take It" (least to most formal)' },
      { t: 'ol', items: [
        'I — Informal review (least formal)',
        'W — Walkthrough',
        'T — Technical review',
        'I — Inspection (most formal)',
      ] },
      { t: 'h1', text: 'Black-box Techniques — "Every Boundary Deserves Structure"' },
      { t: 'ul', items: [
        'E — Equivalence Partitioning',
        'B — Boundary Value Analysis',
        'D — Decision Table testing',
        'S — State transition testing (plus use case testing)',
      ] },
      { t: 'h1', text: 'A Good Defect Report — "SES-RE"' },
      { t: 'ul', items: [
        'S — Summary (clear, unique title and ID)',
        'E — Environment and preconditions',
        'S — Steps to reproduce',
        'R — Result: expected vs actual',
        'E — Evaluation: severity, priority and status',
      ] },
      best('Write each mnemonic once from memory, then rebuild the full list it stands for. If you can expand every letter into the correct term, the list is exam-ready.'),
      mistake('Do not confuse "priority" and "severity", or "verification" and "validation". Verification = building it right (to spec); Validation = building the right thing (to user needs).'),
    ],
  },

  {
    slug: 'mind-maps',
    title: 'Syllabus Mind Maps',
    subtitle: 'Text mind maps for each syllabus chapter — central topic, branches and sub-branches.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'How to Read These Mind Maps' },
      { t: 'p', text: 'Each chapter is a central topic. Top-level bullets are the main branches; indented bullets are sub-branches. Redraw each map on blank paper from memory — the act of rebuilding the structure is what fixes the syllabus in your mind.' },
      { t: 'spacer' },
      { t: 'h1', text: 'Chapter 1 — Fundamentals of Testing' },
      { t: 'ul', items: ['Central topic: What testing is and why we do it.'] },
      { t: 'ol', items: [
        'What is testing? — objectives, testing vs debugging',
        'Why is testing necessary? — contribution to success, quality assurance vs quality control, errors/defects/failures/root causes',
        'Seven testing principles — presence not absence, exhaustive impossible, early testing, clustering, pesticide paradox, context dependent, absence-of-errors fallacy',
        'Test activities — the test process, test work products, traceability',
        'Essential skills — tester mindset, whole-team approach, independence of testing',
      ] },
      { t: 'h1', text: 'Chapter 2 — Testing Throughout the SDLC' },
      { t: 'ul', items: ['Central topic: How testing fits into software development.'] },
      { t: 'ol', items: [
        'SDLC models — sequential (waterfall, V-model), iterative/incremental, Agile; good testing practices',
        'Test levels — Component, Component integration, System, System integration, Acceptance',
        'Test types — functional, non-functional, black-box, white-box',
        'Confirmation and regression testing — after each change',
        'Maintenance testing — triggers and impact analysis',
      ] },
      { t: 'h1', text: 'Chapter 3 — Static Testing' },
      { t: 'ul', items: ['Central topic: Examining work products without running them.'] },
      { t: 'ol', items: [
        'Static testing basics — work products examinable, value, static vs dynamic testing',
        'Feedback and review process — benefits of early feedback, review activities, roles (manager, author, moderator, scribe, reviewer, leader)',
        'Review types — informal, walkthrough, technical review, inspection',
        'Success factors — for the review and for the people involved',
      ] },
      { t: 'h1', text: 'Chapter 4 — Test Analysis and Design (Test Techniques)' },
      { t: 'ul', items: ['Central topic: Deriving good test cases systematically.'] },
      { t: 'ol', items: [
        'Categories of techniques — black-box, white-box, experience-based',
        'Black-box techniques — equivalence partitioning, boundary value analysis, decision table testing, state transition testing',
        'White-box techniques — statement testing and coverage, branch testing and coverage',
        'Experience-based techniques — error guessing, exploratory testing, checklist-based testing',
        'Collaboration-based approaches — acceptance criteria, acceptance test-driven development (ATDD)',
      ] },
      { t: 'h1', text: 'Chapter 5 — Managing the Test Activities' },
      { t: 'ul', items: ['Central topic: Planning, estimating and controlling testing.'] },
      { t: 'ol', items: [
        'Test planning — purpose and content, tester contribution, entry and exit criteria, estimation techniques, test case prioritisation, test pyramid, testing quadrants',
        'Risk management — definition of risk, product vs project risk, risk-based testing, risk analysis and control',
        'Test monitoring, control and completion — metrics, test reports, communication of test status',
        'Configuration management — supporting testing',
        'Defect management — the defect workflow and defect report contents',
      ] },
      { t: 'h1', text: 'Chapter 6 — Test Tools' },
      { t: 'ul', items: ['Central topic: Supporting testing with tooling.'] },
      { t: 'ol', items: [
        'Tool support for testing — what tools can do across the test process',
        'Benefits and risks of automation — repeatability and speed vs maintenance cost and over-reliance',
      ] },
      pro('Draw each map from memory on a single sheet of paper. If a branch is missing when you compare against this sheet, that gap is exactly what the exam is most likely to catch you on.'),
    ],
  },

  {
    slug: 'printable-formula-sheets',
    title: 'Printable Formula Sheets',
    subtitle: 'The counts, coverage figures and rules testers must be able to work out.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Using This Sheet' },
      { t: 'p', text: 'The Foundation exam includes a small number of calculation-style questions. Learn these rules, then practise the worked micro-examples until you can reproduce them without hesitation. Print this sheet and keep it beside you while revising.' },
      { t: 'spacer' },
      { t: 'h1', text: 'Boundary Value Analysis (BVA)' },
      { t: 'p', text: 'For a valid range, the two-value BVA uses the minimum and maximum boundary values. The three-value BVA also adds the value just outside each boundary. Test the boundaries because defects cluster at the edges.' },
      { t: 'table', headers: ['Range', 'Two-value boundaries', 'Three-value boundaries'], rows: [
        ['1 to 100', '1 and 100', '0, 1, 2 ... 99, 100, 101'],
        ['18 to 65 (age)', '18 and 65', '17, 18, 19 ... 64, 65, 66'],
        ['0.00 to 9.99', '0.00 and 9.99', '-0.01, 0.00, 0.01 ... 9.98, 9.99, 10.00'],
      ] },
      { t: 'h1', text: 'Equivalence Partitions per Range' },
      { t: 'p', text: 'A single bounded range typically yields three partitions: one valid partition (inside the range) and two invalid partitions (below the minimum and above the maximum). Test one representative value from each.' },
      { t: 'table', headers: ['Range', 'Valid partition', 'Invalid partitions'], rows: [
        ['1 to 100', 'e.g. 50', 'below (e.g. 0) and above (e.g. 101)'],
        ['18 to 65', 'e.g. 30', 'below (e.g. 17) and above (e.g. 66)'],
      ] },
      { t: 'h1', text: 'Decision Table — Rule Count' },
      { t: 'p', text: 'Rule count = 2 raised to the number of conditions (for binary Yes/No conditions). Each rule is one column combining a state of every condition.' },
      { t: 'table', headers: ['Conditions (binary)', 'Formula 2^n', 'Number of rules (columns)'], rows: [
        ['2 conditions', '2^2', '4 rules'],
        ['3 conditions', '2^3', '8 rules'],
        ['4 conditions', '2^4', '16 rules'],
        ['5 conditions', '2^5', '32 rules'],
      ] },
      { t: 'h1', text: 'Coverage — Statement and Branch' },
      { t: 'p', text: 'Coverage = (items exercised / total items) x 100%.' },
      { t: 'table', headers: ['Metric', 'Formula', 'Worked example'], rows: [
        ['Statement coverage', '(statements executed / total statements) x 100', '7 of 10 statements run = 70%'],
        ['Branch coverage', '(branches executed / total branches) x 100', '3 of 4 branches run = 75%'],
        ['Test coverage (any item)', '(items tested / total items) x 100', '18 of 20 requirements tested = 90%'],
      ] },
      { t: 'h1', text: 'Defect Density' },
      { t: 'p', text: 'Defect density = number of defects / size of the component or system. Size is commonly expressed in thousands of lines of code (KLOC) or in function points.' },
      { t: 'table', headers: ['Defects', 'Size', 'Defect density'], rows: [
        ['40 defects', '20 KLOC', '2 defects per KLOC'],
        ['15 defects', '30 function points', '0.5 defects per function point'],
      ] },
      { t: 'h1', text: 'Pass Rate and Failure Rate' },
      { t: 'p', text: 'Pass rate = (tests passed / tests executed) x 100%. Failure rate = (tests failed / tests executed) x 100%. The two add up to 100% of executed tests.' },
      { t: 'table', headers: ['Tests executed', 'Passed', 'Failed', 'Pass rate'], rows: [
        ['200', '180', '20', '90%'],
        ['50', '45', '5', '90%'],
        ['80', '60', '20', '75%'],
      ] },
      { t: 'h1', text: 'Defect Detection Percentage (DDP)' },
      { t: 'p', text: 'DDP = (defects found by testing / (defects found by testing + defects found later)) x 100%. It measures how effective a test phase was at finding defects.' },
      { t: 'table', headers: ['Found in testing', 'Found after release', 'DDP'], rows: [
        ['90', '10', '90%'],
        ['80', '20', '80%'],
      ] },
      mistake('Coverage is not the same as quality. 100% statement coverage only proves every line ran — it does not prove every combination or requirement was tested. High coverage with weak assertions still misses defects.'),
      pro('For decision tables, always start from 2^n columns, then collapse impossible or duplicate combinations. Working out the full count first stops you from silently missing a rule.'),
    ],
  },

  {
    slug: 'summary-posters',
    title: 'Summary Posters',
    subtitle: 'One-page visual summaries of each syllabus chapter for the wall above your desk.',
    courseTitle: COURSE, category: 'Cheat Sheets',
    blocks: [
      { t: 'h1', text: 'Poster 1 — Fundamentals of Testing' },
      { t: 'p', text: 'The seven principles at a glance, plus the core vocabulary.' },
      { t: 'ul', items: [
        'Testing shows presence of defects, not their absence',
        'Exhaustive testing is impossible',
        'Early testing saves time and money',
        'Defects cluster together',
        'Beware the pesticide paradox — vary your tests',
        'Testing is context dependent',
        'Absence-of-errors is a fallacy',
      ] },
      { t: 'table', headers: ['Term', 'One-line meaning'], rows: [
        ['Error', 'A human mistake'],
        ['Defect', 'The resulting flaw in the work product'],
        ['Failure', 'The wrong behaviour when the defect is executed'],
      ] },
      { t: 'spacer' },
      { t: 'h1', text: 'Poster 2 — Testing Throughout the SDLC' },
      { t: 'ul', items: [
        'Test levels: Component, Integration, System, Acceptance',
        'Test types: Functional, Non-functional, White-box, Change-related',
        'Confirmation testing re-checks a fix; Regression testing guards against side effects',
        'Maintenance testing follows changes, migrations and retirements',
      ] },
      { t: 'table', headers: ['Level', 'Who / focus'], rows: [
        ['Component', 'Developers — units in isolation'],
        ['Integration', 'Interfaces and interactions between components/systems'],
        ['System', 'End-to-end behaviour of the whole system'],
        ['Acceptance', 'Validation against user needs (UAT, alpha, beta)'],
      ] },
      { t: 'spacer' },
      { t: 'h1', text: 'Poster 3 — Static Testing' },
      { t: 'ul', items: [
        'Static testing examines work products without executing code',
        'Finds defects early, when they are cheapest to fix',
        'Review roles: Manager, Author, Moderator, Scribe, Reviewer, Leader',
      ] },
      { t: 'table', headers: ['Review type', 'Formality'], rows: [
        ['Informal review', 'Lowest — cheap, quick feedback'],
        ['Walkthrough', 'Led by the author'],
        ['Technical review', 'Led by trained reviewers/peers'],
        ['Inspection', 'Highest — formal, metrics-driven'],
      ] },
      { t: 'spacer' },
      { t: 'h1', text: 'Poster 4 — Test Techniques' },
      { t: 'table', headers: ['Category', 'Techniques'], rows: [
        ['Black-box', 'Equivalence partitioning, boundary value analysis, decision tables, state transition'],
        ['White-box', 'Statement coverage, branch coverage'],
        ['Experience-based', 'Error guessing, exploratory testing, checklist-based'],
      ] },
      { t: 'ul', items: [
        'Black-box derives tests from behaviour/specifications',
        'White-box derives tests from internal structure/code',
        'Experience-based leans on tester knowledge and intuition',
      ] },
      { t: 'spacer' },
      { t: 'h1', text: 'Poster 5 — Managing the Test Activities' },
      { t: 'ul', items: [
        'Test plan: scope, approach, resources, schedule, entry/exit criteria, risks',
        'Risk-based testing prioritises by likelihood x impact',
        'Product risk = product may fail stakeholders; Project risk = project management risk',
        'Defect report: ID, summary, steps, expected vs actual, severity, priority, status',
      ] },
      { t: 'table', headers: ['Concept', 'Quick contrast'], rows: [
        ['Entry vs exit criteria', 'Ready to start vs done'],
        ['Severity vs priority', 'Impact on system vs urgency to fix'],
        ['Verification vs validation', 'Build it right vs build the right thing'],
      ] },
      { t: 'spacer' },
      { t: 'h1', text: 'Poster 6 — Test Tools' },
      { t: 'ul', items: [
        'Tools support activities across the whole test process',
        'Benefits: repeatable, fast regression; consistent, objective execution',
        'Risks: underestimated maintenance cost, over-reliance, unrealistic expectations',
      ] },
      best('Print one poster per chapter and put them where you actually sit. Passive, repeated exposure to the same tight summaries builds recall with almost no effort.'),
    ],
  },
];
