// Generates an idempotent, slug-based quiz seed for one course from a structured
// content file. Each module gets ONE quiz (the module page reads quizzes with
// .single(), so exactly one per module). Re-running inserts nothing if the
// module already has a quiz — it never deletes existing quizzes or attempts.
//
// Content file default-exports:
//   { courseSlug, passMark?, quizzes: [ { moduleNumber, title?, questions: [
//       { text, answers: [ { text, correct } ] } ] } ] }
//
// Usage: node scripts/content/build-quizzes.mjs qa-leadership-quizzes
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');

const name = process.argv[2];
if (!name) { console.error('Usage: build-quizzes.mjs <content-file>'); process.exit(1); }

const data = (await import(`./${name}.mjs`)).default;
const { courseSlug, quizzes } = data;
const defaultPass = data.passMark ?? 70;
const outFile = data.outFile ?? `seed-${courseSlug}-quizzes.sql`;

const T = '$qz$'; // dollar-quote delimiter for text
const txt = (s) => {
  const v = s == null ? '' : String(s);
  if (v.includes(T)) throw new Error(`Delimiter ${T} clash: ${v.slice(0, 40)}`);
  return `${T}${v}${T}`;
};

let sql = `-- ============================================================
-- Knowledge-check quizzes for "${courseSlug}".
-- Generated by scripts/content/build-quizzes.mjs — do not hand-edit;
-- edit scripts/content/${name}.mjs and regenerate. Run AFTER the course,
-- modules and schema exist. Idempotent: a module that already has a quiz
-- is skipped (no quizzes or attempts are ever deleted).
-- ============================================================\n\n`;

for (const quiz of quizzes) {
  const title = quiz.title ?? 'Reflection & Knowledge Check';
  const pass = quiz.pass ?? defaultPass;
  const ctes = [
    `m as (select mo.id from public.modules mo join public.courses c on c.id = mo.course_id where c.slug = '${courseSlug}' and mo.module_number = ${quiz.moduleNumber})`,
    `newq as (insert into public.quizzes (module_id, title, pass_mark) select id, ${txt(title)}, ${pass} from m where not exists (select 1 from public.quizzes where module_id = (select id from m)) returning id)`,
  ];
  quiz.questions.forEach((q, i) => {
    const n = i + 1;
    ctes.push(`q${n} as (insert into public.quiz_questions (quiz_id, question_text, question_type, sort_order) select id, ${txt(q.text)}, 'multiple_choice', ${n} from newq returning id)`);
    const vals = q.answers.map((a) => `(${txt(a.text)}, ${a.correct ? 'true' : 'false'})`).join(', ');
    ctes.push(`a${n} as (insert into public.quiz_answers (question_id, answer_text, is_correct) select q${n}.id, v.t, v.c from q${n}, (values ${vals}) as v(t, c) returning question_id)`);
  });
  sql += `with ${ctes.join(',\n')}\nselect 1;\n\n`;
}

writeFileSync(join(ROOT, 'supabase', outFile), sql);
console.log(`wrote ${quizzes.length} quizzes -> supabase/${outFile}`);
