// Generates BOTH the base-lessons SQL and the enhancements SQL for one module of
// the API Testing Masterclass from a single structured content file, so the SQL is
// always valid (no hand-escaping). Each module file default-exports:
//   { courseSlug, moduleNumber, lessons: [{ lessonNumber, title, estimatedTime,
//     lessonOverview, learningObjectives[], lessonNotes, workedExample,
//     commonMistakes, realWorldTip, exercise, reflectionQuestion, knowledgeCheck,
//     completionChecklist[], enhancements{} }] }
//
// Usage: node scripts/content/build-module.mjs api-module2
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');

const name = process.argv[2];
if (!name) { console.error('Usage: build-module.mjs <content-file, e.g. api-module2>'); process.exit(1); }

const data = (await import(`./${name}.mjs`)).default;
const { courseSlug, moduleNumber, lessons } = data;

// Output filename prefixes (default to the API course's legacy naming).
const LP = data.lessonsPrefix ?? 'api-testing'; // seed-<LP>-module-<n>-lessons.sql
const EP = data.enhPrefix ?? 'api';             // seed-<EP>-module<ES><n>-enhancements.sql
const ES = data.enhSep ?? '';

const L = '$L$';   // dollar-quote delimiter for text columns
const E = '$ench$'; // dollar-quote delimiter for the enhancements JSON

const txt = (s) => {
  const v = s == null ? '' : String(s);
  if (v.includes(L)) throw new Error(`Delimiter ${L} clash in module ${moduleNumber}`);
  return `${L}${v}${L}`;
};
const arr = (a) => `array[${(a || []).map(txt).join(', ')}]`;

// ── base lessons ──
let base = `-- ============================================================
-- API Testing Masterclass — Module ${moduleNumber} lessons (base fields).
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/${name}.mjs and regenerate. Run AFTER lessons-schema.sql,
-- add-api-testing-course.sql and seed-api-testing-modules.sql. Idempotent.
-- ============================================================\n\n`;

for (const l of lessons) {
  base += `insert into public.lessons (module_id, lesson_number, title, estimated_time, lesson_overview, learning_objectives, lesson_notes, worked_example, common_mistakes, real_world_tip, exercise, reflection_question, knowledge_check, completion_checklist)
select m.id, ${l.lessonNumber}, ${txt(l.title)}, ${txt(l.estimatedTime)}, ${txt(l.lessonOverview)}, ${arr(l.learningObjectives)}, ${txt(l.lessonNotes)}, ${txt(l.workedExample)}, ${txt(l.commonMistakes)}, ${txt(l.realWorldTip)}, ${txt(l.exercise)}, ${txt(l.reflectionQuestion)}, ${txt(l.knowledgeCheck)}, ${arr(l.completionChecklist)}
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = '${courseSlug}' and m.module_number = ${moduleNumber}
on conflict (module_id, lesson_number) do nothing;\n\n`;
}
writeFileSync(join(ROOT, 'supabase', `seed-${LP}-module-${moduleNumber}-lessons.sql`), base);

// ── enhancements ──
let ench = `-- ============================================================
-- Lesson enhancements for "${courseSlug}" Module ${moduleNumber}.
-- Generated by scripts/content/build-module.mjs — do not hand-edit;
-- edit scripts/content/${name}.mjs and regenerate. Run AFTER
-- lesson-enhancements-schema.sql and the lesson seeds. Idempotent.
-- ============================================================\n\n`;

for (const l of lessons) {
  const json = JSON.stringify(l.enhancements || {});
  if (json.includes(E)) throw new Error(`Delimiter ${E} clash in module ${moduleNumber} lesson ${l.lessonNumber}`);
  ench += `update public.lessons l set enhancements = ${E}${json}${E}::jsonb
from public.modules m join public.courses c on c.id = m.course_id
where l.module_id = m.id and c.slug = '${courseSlug}'
  and m.module_number = ${moduleNumber} and l.lesson_number = ${l.lessonNumber};\n\n`;
}
writeFileSync(join(ROOT, 'supabase', `seed-${EP}-module${ES}${moduleNumber}-enhancements.sql`), ench);

console.log(`module ${moduleNumber}: wrote ${lessons.length} lessons (base + enhancements)`);
