// ISTQB Foundation (CTFL v4.0) practice questions - Module 10: Agile Testing.
// 25 questions covering agile principles for testing, the whole-team approach,
// the tester's role and mindset, agile test approaches (risk-based, exploratory,
// automation, ATDD/BDD), iteration and release planning, test independence,
// CI/CD impact on testing, and regression/confirmation pressure in short iterations.
// Scope is limited to what the CTFL v4.0 Foundation syllabus expects.
export default {
  courseSlug: 'istqb-foundation-masterclass',
  moduleNumber: 10,
  syllabusTopic: 'Agile Testing',
  questions: [
    {
      kLevel: 'K1',
      question: 'In agile software development, how often is working software typically expected to be delivered?',
      options: [
        { text: 'Frequently, in short iterations of a few weeks or less', correct: true, why: 'Agile favours frequent delivery of working software over short timescales, which shapes how and when testing happens.' },
        { text: 'Only once, at the very end of the project', correct: false, why: 'That describes a sequential (waterfall) delivery, not an agile approach.' },
        { text: 'Whenever the full set of requirements is finally signed off', correct: false, why: 'Agile does not wait for a complete, frozen requirement set before delivering value.' },
        { text: 'Every few years as part of a major release cycle', correct: false, why: 'Multi-year cycles are the opposite of the short, frequent iterations agile promotes.' },
      ],
      explanation: 'A core agile principle is the frequent delivery of working software in short iterations. This compresses the time available for testing each increment and pushes teams toward continuous, integrated testing rather than a separate end-of-project test phase.',
      workplaceExample: 'A team delivers a potentially shippable increment every two-week sprint, so testers plan, execute and report on tests within each sprint rather than saving verification for a final test stage.',
    },
    {
      kLevel: 'K2',
      question: 'Why does the agile emphasis on responding to change (over following a fixed plan) affect testers?',
      options: [
        { text: 'Requirements and priorities can evolve each iteration, so test work must adapt continuously', correct: true, why: 'Because scope can change between iterations, testers must re-assess risks and update or add tests frequently rather than working to a frozen test plan.' },
        { text: 'It means testers no longer need any form of test planning', correct: false, why: 'Planning still happens; it becomes lighter and more frequent, not absent.' },
        { text: 'It removes the need to prioritise tests because everything is tested equally', correct: false, why: 'Change increases the need to prioritise by risk, not remove it.' },
        { text: 'It guarantees requirements will never change once an iteration starts', correct: false, why: 'Agile explicitly embraces change; it does not guarantee stability.' },
      ],
      explanation: 'Agile values responding to change over rigidly following a plan. For testers this means test conditions, priorities and coverage must be revisited each iteration as the product and backlog evolve, so testing stays aligned with current risk.',
      workplaceExample: 'When the product owner reprioritises the backlog mid-project, the tester re-evaluates which features carry the most risk and adjusts the test focus for the next iteration accordingly.',
    },
    {
      kLevel: 'K1',
      question: 'What does the whole-team approach in agile mean for quality?',
      options: [
        { text: 'The entire team shares responsibility for product quality', correct: true, why: 'In the whole-team approach, developers, testers and business roles are collectively accountable for quality, not just a separate test group.' },
        { text: 'Only the testers are accountable for quality', correct: false, why: 'Making testers solely responsible contradicts the whole-team idea.' },
        { text: 'Only the product owner decides whether quality is good enough', correct: false, why: 'The product owner sets priorities but does not hold sole responsibility for quality.' },
        { text: 'Quality is the responsibility of a separate quality assurance department outside the team', correct: false, why: 'The whole-team approach keeps quality responsibility inside the cross-functional team.' },
      ],
      explanation: 'The whole-team approach means anyone with the necessary knowledge and skill contributes to quality, and the whole cross-functional team owns quality collectively. This is a defining feature of testing in agile.',
      workplaceExample: 'When a defect escapes to production, the team reviews it together in a retrospective and improves their process, rather than blaming the testers alone.',
    },
    {
      kLevel: 'K2',
      question: 'Which is a genuine benefit of the whole-team approach for testing?',
      options: [
        { text: 'Testers, developers and business representatives collaborate closely, improving communication and shared understanding', correct: true, why: 'Close collaboration and direct communication reduce misunderstandings and let defects be prevented or found earlier.' },
        { text: 'It removes the need for any testing activities', correct: false, why: 'Collaboration does not replace testing; it strengthens it.' },
        { text: 'It means developers never need to talk to testers', correct: false, why: 'The whole-team approach increases, not removes, developer-tester interaction.' },
        { text: 'It guarantees a completely defect-free product', correct: false, why: 'No approach can guarantee zero defects; that is an unrealistic expectation.' },
      ],
      explanation: 'Benefits of the whole-team approach include enhanced communication and collaboration, drawing on the full range of skills for the benefit of the project, and making testing and development complementary activities. It does not eliminate testing or guarantee perfection.',
      workplaceExample: 'A tester joins the developers at a three-amigos discussion so ambiguous acceptance criteria are clarified before coding starts, preventing a defect rather than finding it later.',
    },
    {
      kLevel: 'K2',
      question: 'What is a potential risk of the whole-team approach that a team should watch for?',
      options: [
        { text: 'Testing knowledge can be diluted or overlooked if no one champions a rigorous test perspective', correct: true, why: 'When everyone is responsible, specialist test thinking can be lost unless it is deliberately maintained within the team.' },
        { text: 'It always makes the team too large to communicate', correct: false, why: 'Whole-team working typically favours small teams, so size is not the inherent risk.' },
        { text: 'It forces the team to abandon automation', correct: false, why: 'The whole-team approach is compatible with, and often encourages, automation.' },
        { text: 'It prevents developers from ever writing tests', correct: false, why: 'The approach encourages developers to contribute to testing, not the reverse.' },
      ],
      explanation: 'A recognised risk of shared responsibility is that when "everyone" owns quality, specialist testing skills and a critical test mindset can be under-applied. Teams mitigate this by ensuring test expertise is present and valued.',
      workplaceExample: 'A team where developers write only happy-path checks realises negative and edge-case testing is being skipped, and asks the tester to coach the team on stronger test design.',
    },
    {
      kLevel: 'K2',
      question: 'Which statement best describes a tester\'s mindset on an agile team?',
      options: [
        { text: 'Curious, collaborative and quality-focused, providing rapid feedback throughout the iteration', correct: true, why: 'Agile testers work closely with the team, question assumptions and give fast feedback so the increment stays on quality track.' },
        { text: 'A gatekeeper who works in isolation and only reports at the end', correct: false, why: 'Working in isolation and testing only at the end is contrary to agile ways of working.' },
        { text: 'Someone who avoids talking to developers to stay independent', correct: false, why: 'Independence in agile does not mean avoiding communication; collaboration is essential.' },
        { text: 'A role that only executes scripted tests written months in advance', correct: false, why: 'Agile testing relies heavily on adaptable, exploratory and just-in-time test design, not only long-dated scripts.' },
      ],
      explanation: 'An agile tester is collaborative and communicative, brings a questioning and quality-focused mindset, and provides continuous, rapid feedback. This differs from a traditional isolated end-of-cycle gatekeeper role.',
      workplaceExample: 'During a sprint the tester pairs with a developer, raises questions about an unclear rule immediately, and demonstrates a failing scenario the same day rather than logging it for a later phase.',
    },
    {
      kLevel: 'K2',
      question: 'On an agile team, which activities is a tester likely to be involved in beyond executing tests?',
      options: [
        { text: 'Clarifying user stories, defining acceptance criteria and helping automate tests', correct: true, why: 'Agile testers contribute across the lifecycle, including refining stories, shaping acceptance criteria and supporting test automation.' },
        { text: 'Only running a final regression pass before release and nothing else', correct: false, why: 'That is a narrow, phase-based view that does not reflect the agile tester\'s broader involvement.' },
        { text: 'Writing the production code for every feature', correct: false, why: 'Testers may pair with developers, but writing all production code is not their role.' },
        { text: 'Approving the budget and staffing for the project', correct: false, why: 'Budget and staffing are management responsibilities, not testing tasks.' },
      ],
      explanation: 'Agile testers participate throughout the iteration: helping to define and clarify acceptance criteria, contributing to backlog refinement, designing and executing tests, and supporting automation. Their role is broad and collaborative.',
      workplaceExample: 'In backlog refinement the tester spots a missing acceptance criterion for an error case, and the team adds it before the story is pulled into a sprint.',
    },
    {
      kLevel: 'K2',
      question: 'Why is exploratory testing especially valuable within short agile iterations?',
      options: [
        { text: 'It provides fast feedback on new features when there is little time for extensive scripted test preparation', correct: true, why: 'Exploratory testing combines learning, design and execution simultaneously, giving quick coverage of newly built features.' },
        { text: 'It removes the need to think about test conditions at all', correct: false, why: 'Exploratory testing is structured thinking on the fly, not the absence of thought.' },
        { text: 'It replaces the need for any automated regression testing', correct: false, why: 'Exploratory testing complements automation; it does not replace regression automation.' },
        { text: 'It guarantees complete coverage of every possible input', correct: false, why: 'No technique guarantees complete coverage; exhaustive testing is impractical.' },
      ],
      explanation: 'Exploratory testing suits agile because tester learning, test design and execution happen together, giving rapid feedback on freshly delivered functionality when there is limited time to prepare detailed scripts. It works alongside, not instead of, automation.',
      workplaceExample: 'As soon as a developer finishes a checkout feature, the tester runs a timeboxed exploratory session using a charter, quickly surfacing an issue with an unusual discount code.',
    },
    {
      kLevel: 'K2',
      question: 'How does test automation support testing in an agile team working in short iterations?',
      options: [
        { text: 'It runs regression checks quickly and repeatedly, freeing testers for exploratory and new-feature testing', correct: true, why: 'Automated regression provides fast, repeatable feedback so people can focus on judgement-based and new-feature testing each iteration.' },
        { text: 'It means manual and exploratory testing are no longer needed', correct: false, why: 'Automation handles repetitive checks but does not replace human exploratory testing.' },
        { text: 'It removes the need to maintain any tests over time', correct: false, why: 'Automated tests require ongoing maintenance as the product changes.' },
        { text: 'It guarantees the product has no defects once the suite passes green', correct: false, why: 'A passing suite reduces risk but never guarantees a defect-free product.' },
      ],
      explanation: 'Automation is central to agile testing because short iterations demand frequent regression checking. Automating repetitive regression tests gives fast feedback and lets testers spend their time on exploratory testing and testing new features, though automation still needs maintenance.',
      workplaceExample: 'The team automates its core regression suite so it runs on every build overnight, leaving the tester free to explore the new features added during the sprint.',
    },
    {
      kLevel: 'K1',
      question: 'In Acceptance Test-Driven Development (ATDD), when are acceptance tests typically defined?',
      options: [
        { text: 'Collaboratively, before development of the feature begins', correct: true, why: 'ATDD defines acceptance tests up front through collaboration, so the tests express the agreed expected behaviour before coding.' },
        { text: 'Only after the feature has been released to production', correct: false, why: 'Defining acceptance tests only post-release defeats the purpose of driving development with them.' },
        { text: 'By the testers alone with no input from other roles', correct: false, why: 'ATDD is collaborative, involving business, development and test perspectives together.' },
        { text: 'Never, because ATDD does not use acceptance tests', correct: false, why: 'Acceptance tests are the central artefact of ATDD.' },
      ],
      explanation: 'ATDD is a collaborative, test-first approach in which acceptance tests are created together (business, developer and tester) before development starts. The tests capture the agreed criteria and guide the implementation.',
      workplaceExample: 'Before coding a login feature, the product owner, developer and tester agree concrete acceptance tests, such as the behaviour after three failed attempts, and those tests drive the work.',
    },
    {
      kLevel: 'K2',
      question: 'How does Behaviour-Driven Development (BDD) support communication about expected behaviour?',
      options: [
        { text: 'It expresses expected behaviour in structured, readable scenarios that business and technical people can share', correct: true, why: 'BDD scenarios use a common, structured natural-language style so all roles understand and agree on the intended behaviour.' },
        { text: 'It hides the expected behaviour in code only developers can read', correct: false, why: 'BDD deliberately makes behaviour readable to non-technical stakeholders.' },
        { text: 'It removes the need to agree on requirements', correct: false, why: 'BDD is a way of agreeing and expressing requirements, not avoiding them.' },
        { text: 'It applies only to performance testing', correct: false, why: 'BDD describes functional behaviour and is not limited to performance testing.' },
      ],
      explanation: 'BDD encourages collaboration by describing desired behaviour in a structured, human-readable scenario format. This shared language helps business and technical team members build a common understanding of what the system should do.',
      workplaceExample: 'The team writes scenarios in a Given/When/Then style so the product owner can read and confirm the intended behaviour of a refund rule before it is built.',
    },
    {
      kLevel: 'K2',
      question: 'Why is a risk-based approach useful when prioritising testing in an agile iteration?',
      options: [
        { text: 'Limited time means testing effort should focus first on the areas of highest risk', correct: true, why: 'Short iterations rarely allow testing everything, so aligning effort with risk maximises the value of the time available.' },
        { text: 'It lets the team test every path exhaustively within the sprint', correct: false, why: 'Exhaustive testing is not feasible; risk-based prioritisation exists precisely because time is limited.' },
        { text: 'It means low-risk items must always be tested first', correct: false, why: 'Risk-based prioritisation focuses on higher-risk items first, not lower-risk ones.' },
        { text: 'It removes the need to test high-risk features', correct: false, why: 'Risk-based testing directs more effort to high-risk features, not less.' },
      ],
      explanation: 'Because agile iterations are short and time is constrained, testers use risk to decide what to test and how thoroughly. Focusing on the highest-risk areas first ensures the most important defects are more likely to be found early.',
      workplaceExample: 'With only a few days of testing left in the sprint, the tester concentrates on the payment flow (high business risk) before spending time on a cosmetic settings screen.',
    },
    {
      kLevel: 'K2',
      question: 'From a testing viewpoint, what is a key value of iteration planning in agile?',
      options: [
        { text: 'The team agrees the scope of the iteration so testers can plan test effort and identify risks for those items', correct: true, why: 'Knowing which stories are in the iteration lets testers estimate test effort, spot risks and prepare test conditions for that scope.' },
        { text: 'It fixes the entire project scope so no change is ever possible', correct: false, why: 'Iteration planning covers one iteration and does not freeze the whole project.' },
        { text: 'It is where all detailed test scripts for the whole release are finalised', correct: false, why: 'Test design in agile is done just-in-time, not all finalised at one planning event.' },
        { text: 'It excludes testers because it is only for developers', correct: false, why: 'Testers participate in iteration planning to raise testability and risk concerns.' },
      ],
      explanation: 'Iteration (sprint) planning defines the goal and the set of backlog items for the coming iteration. For testers this is where they help assess testability, estimate testing effort, and identify risks in the selected stories.',
      workplaceExample: 'During sprint planning the tester flags that one story lacks clear acceptance criteria, so the team refines it before committing, avoiding wasted effort later.',
    },
    {
      kLevel: 'K2',
      question: 'From a testing perspective, how does release planning differ from iteration planning?',
      options: [
        { text: 'Release planning looks further ahead across multiple iterations, helping testers anticipate broader test and regression needs', correct: true, why: 'Release planning takes a longer horizon, so testers can foresee end-to-end and regression scope spanning several iterations.' },
        { text: 'Release planning is identical to iteration planning with a different name', correct: false, why: 'They operate at different horizons and levels of detail.' },
        { text: 'Release planning replaces the need for iteration planning', correct: false, why: 'Both coexist; each serves a different planning horizon.' },
        { text: 'Release planning never involves testers', correct: false, why: 'Testers contribute to release planning to inform release-level test and risk considerations.' },
      ],
      explanation: 'Release planning looks ahead across several iterations to shape the overall release, while iteration planning focuses on the immediate iteration. Testers use release planning to anticipate broader concerns such as end-to-end testing and cumulative regression scope.',
      workplaceExample: 'At release planning the tester highlights that a large cross-cutting feature will need a coordinated end-to-end test near the end of the release, so time is reserved for it.',
    },
    {
      kLevel: 'K2',
      question: 'What does independence of testing provide, even when testing is embedded in an agile team?',
      options: [
        { text: 'A fresh, less biased perspective that can find defects the author might overlook', correct: true, why: 'Independent eyes bring different assumptions, so they detect failures and false assumptions the original author may miss.' },
        { text: 'A guarantee that testers will find every defect', correct: false, why: 'Independence improves defect detection but never guarantees finding all defects.' },
        { text: 'Proof that the developers wrote poor-quality code', correct: false, why: 'Independent testing is about perspective, not an accusation about code quality.' },
        { text: 'The ability to skip involving developers entirely', correct: false, why: 'Independence does not mean cutting off collaboration with developers.' },
      ],
      explanation: 'Independence of testing brings a different viewpoint and reduces author bias, helping to reveal defects and incorrect assumptions. This benefit applies even when a tester is a full member of an agile team.',
      workplaceExample: 'A tester questions an assumption the developer took for granted about how dates roll over at year end, uncovering a defect the developer had not considered.',
    },
    {
      kLevel: 'K2',
      question: 'What is a recognised drawback of relying solely on developers to test their own work in an agile team?',
      options: [
        { text: 'Author bias can make people less likely to spot problems in their own work', correct: true, why: 'People tend to be blind to their own assumptions and mistakes, so self-testing alone can miss defects.' },
        { text: 'Developers are technically incapable of writing any tests', correct: false, why: 'Developers can and do write tests; the issue is bias, not capability.' },
        { text: 'It always makes testing faster and more thorough', correct: false, why: 'Self-testing alone can reduce thoroughness because of bias, not increase it.' },
        { text: 'It removes all need for automation', correct: false, why: 'The point concerns independence of perspective, not automation.' },
      ],
      explanation: 'A drawback of testing only by the author is author bias: it is hard to see one\'s own errors and assumptions. This is why some degree of independent testing is valuable even within a collaborative agile team.',
      workplaceExample: 'A developer\'s unit tests all pass because they mirror the same misunderstanding in the code, and only an independent tester exercising the requirement uncovers the gap.',
    },
    {
      kLevel: 'K1',
      question: 'What is continuous integration (CI)?',
      options: [
        { text: 'Frequently merging code changes and automatically building and testing them', correct: true, why: 'CI integrates changes often and runs an automated build with tests each time, giving rapid feedback on integration problems.' },
        { text: 'Deploying to production manually once per year', correct: false, why: 'That is neither continuous nor integration-focused.' },
        { text: 'Writing all code first and integrating it only at the very end', correct: false, why: 'Late one-off integration is the opposite of continuous integration.' },
        { text: 'A manual process with no automated tests', correct: false, why: 'Automated build and test are what make CI valuable.' },
      ],
      explanation: 'Continuous integration means developers integrate their changes frequently, triggering an automated build and a suite of automated tests each time. This provides fast feedback so integration defects are caught early.',
      workplaceExample: 'Every time a developer pushes code, the CI server compiles the build and runs unit and integration tests, alerting the team within minutes if something breaks.',
    },
    {
      kLevel: 'K2',
      question: 'How does continuous integration benefit testing in an agile context?',
      options: [
        { text: 'It gives rapid feedback on the quality of each change, so integration defects are found early', correct: true, why: 'Automated build and test on each integration surface problems quickly, reducing the cost of fixing them.' },
        { text: 'It removes the need for any regression testing', correct: false, why: 'CI actually relies on and runs regression tests; it does not remove the need for them.' },
        { text: 'It guarantees that the build will never fail', correct: false, why: 'CI often surfaces failures; that early detection is the benefit, not a promise of no failures.' },
        { text: 'It means testers no longer need to design tests', correct: false, why: 'Someone must design the automated tests CI runs; test design remains essential.' },
      ],
      explanation: 'CI benefits testing by executing automated tests on every integration, providing fast feedback and enabling early detection of integration and regression defects. It reduces integration risk but depends on well-designed automated tests.',
      workplaceExample: 'A change that breaks an existing feature is caught by the CI regression suite within minutes of being pushed, so the developer fixes it before it reaches the tester.',
    },
    {
      kLevel: 'K2',
      question: 'What does continuous delivery (CD) require in order to release changes safely and frequently?',
      options: [
        { text: 'A high level of automated testing so each change can be validated quickly and reliably', correct: true, why: 'Frequent, safe releases depend on automated tests giving trustworthy, fast confirmation that changes are sound.' },
        { text: 'A long manual test phase before every release', correct: false, why: 'A long manual gate would prevent the frequent, fast releases CD aims for.' },
        { text: 'Removing testing from the pipeline to speed things up', correct: false, why: 'CD increases reliance on automated testing rather than removing it.' },
        { text: 'Releasing only once the whole product is complete', correct: false, why: 'CD is about releasing changes frequently, not waiting for a finished product.' },
      ],
      explanation: 'Continuous delivery aims to keep software in a releasable state so changes can be delivered frequently and safely. This depends heavily on extensive, reliable automated testing in the pipeline to validate each change quickly.',
      workplaceExample: 'Because the pipeline runs a trusted automated test suite on every change, the team can release small updates several times a week with confidence.',
    },
    {
      kLevel: 'K1',
      question: 'What is the purpose of confirmation testing (re-testing) after a defect is fixed?',
      options: [
        { text: 'To confirm that the original defect has actually been resolved', correct: true, why: 'Confirmation testing re-runs the failing test on the fixed build to verify the defect no longer occurs.' },
        { text: 'To check that unrelated areas still work after the change', correct: false, why: 'That describes regression testing, not confirmation testing.' },
        { text: 'To measure how fast the system responds under load', correct: false, why: 'That is performance testing, unrelated to confirming a fix.' },
        { text: 'To gather new requirements for the next iteration', correct: false, why: 'Requirements gathering is not a testing activity of this kind.' },
      ],
      explanation: 'Confirmation testing (re-testing) verifies that a previously failing test now passes after the corresponding defect has been fixed. It confirms the specific fix worked.',
      workplaceExample: 'After a developer fixes a rounding error in an invoice total, the tester re-runs the exact scenario that failed to confirm the total is now correct.',
    },
    {
      kLevel: 'K1',
      question: 'What is the purpose of regression testing when changes are made in an iteration?',
      options: [
        { text: 'To detect whether the changes have unintentionally broken previously working functionality', correct: true, why: 'Regression testing checks that existing features still work after code has changed.' },
        { text: 'To confirm that a specific fixed defect is now resolved', correct: false, why: 'That is confirmation testing, which targets the specific fix.' },
        { text: 'To define the acceptance criteria for a new story', correct: false, why: 'Defining acceptance criteria is a planning activity, not regression testing.' },
        { text: 'To measure code coverage of unit tests only', correct: false, why: 'Coverage measurement is a different concern from regression testing.' },
      ],
      explanation: 'Regression testing aims to find unintended side effects, verifying that changes such as fixes or new features have not broken existing functionality. In agile, frequent changes make regression testing a constant need.',
      workplaceExample: 'After adding a new discount type, the tester runs the regression suite to make sure existing pricing and checkout behaviour is unaffected.',
    },
    {
      kLevel: 'K2',
      question: 'Why is regression testing under particular pressure in short agile iterations?',
      options: [
        { text: 'Frequent changes each iteration mean the regression scope keeps growing while the time available stays short', correct: true, why: 'Every iteration adds functionality that must keep working, so the regression burden accumulates against a fixed, short timebox.' },
        { text: 'Because regression testing is never needed in agile', correct: false, why: 'Regression testing is more, not less, important in agile due to frequent change.' },
        { text: 'Because agile forbids automating regression tests', correct: false, why: 'Agile actively encourages automating regression tests to cope with the pressure.' },
        { text: 'Because requirements never change, making regression trivial', correct: false, why: 'Requirements do change in agile, which is exactly why regression pressure grows.' },
      ],
      explanation: 'Because agile delivers changes every iteration, the body of functionality that must be re-verified grows continually while the iteration timebox stays short. This creates strong pressure to automate regression testing so it can keep pace.',
      workplaceExample: 'By sprint eight the manual regression checklist is too large to run by hand each sprint, so the team invests in automating the most critical regression cases.',
    },
    {
      kLevel: 'K2',
      question: 'How does automating the regression suite help a team cope with short iterations?',
      options: [
        { text: 'It lets the growing set of regression tests run quickly and often, keeping feedback fast as functionality accumulates', correct: true, why: 'Automation runs the accumulating regression tests rapidly and repeatedly, so the team keeps fast feedback despite the short timebox.' },
        { text: 'It permanently removes the need for confirmation testing', correct: false, why: 'Confirmation testing of specific fixes is still required regardless of regression automation.' },
        { text: 'It means new features never need any testing', correct: false, why: 'New features still require fresh testing; automation targets repeatable regression checks.' },
        { text: 'It ensures the regression suite never needs updating', correct: false, why: 'Automated regression tests must be maintained as the product changes.' },
      ],
      explanation: 'Automating regression tests allows the ever-growing suite to run quickly and frequently, for example on every build, so the team retains fast feedback within short iterations. The suite still needs maintenance and does not replace testing of new features.',
      workplaceExample: 'The automated regression pack runs on each nightly build, so the team learns by morning whether any existing behaviour was broken, without spending days on manual re-checking.',
    },
    {
      kLevel: 'K3',
      question: 'A two-week iteration is nearly over. A high-risk payment defect was just fixed, several stories changed shared code, and there is only one day of testing left. What is the most appropriate testing response?',
      options: [
        { text: 'Confirmation-test the payment fix, then run automated regression focused on the highest-risk changed areas', correct: true, why: 'This confirms the specific fix and uses risk-based, automated regression to cover the most important side effects within the limited time.' },
        { text: 'Skip confirmation testing and manually re-test every feature in the product from scratch', correct: false, why: 'Manually re-testing everything is infeasible in one day and skipping the fix check leaves the key risk unverified.' },
        { text: 'Do nothing extra because continuous integration already guarantees correctness', correct: false, why: 'CI provides fast feedback but does not guarantee correctness, and the high-risk fix still needs confirming.' },
        { text: 'Run only the cosmetic UI checks and defer all payment testing to next iteration', correct: false, why: 'Deferring the high-risk payment area contradicts risk-based prioritisation.' },
      ],
      explanation: 'With limited time, the tester should first confirm the high-risk fix works (confirmation testing), then apply risk-based regression, using automation, to the areas most likely affected by the shared-code changes. This combines confirmation testing, regression testing, risk-based prioritisation and automation appropriately.',
      workplaceExample: 'On the last day of the sprint the tester re-runs the failing payment scenario to confirm the fix, then triggers the automated regression suite against the payment and checkout modules that shared the changed code.',
    },
    {
      kLevel: 'K2',
      question: 'How can a tester best maintain independence of perspective while still being a fully collaborative member of an agile team?',
      options: [
        { text: 'Collaborate closely on stories while still critically questioning assumptions and designing independent tests', correct: true, why: 'Independence in agile is about perspective and questioning, which can coexist with close day-to-day collaboration.' },
        { text: 'Refuse to talk to developers so as not to be influenced by them', correct: false, why: 'Avoiding communication harms collaboration and is not how agile independence works.' },
        { text: 'Only test after leaving the team so there is no contact', correct: false, why: 'Agile testers are embedded in the team; leaving it is not the goal.' },
        { text: 'Accept the developers\' assumptions without challenge to keep harmony', correct: false, why: 'Accepting assumptions unquestioned surrenders the independent perspective entirely.' },
      ],
      explanation: 'Independence of testing in agile is preserved through mindset, not isolation. A tester stays collaborative yet keeps a questioning, critical perspective and designs tests that challenge assumptions, gaining the benefits of independence without sacrificing teamwork.',
      workplaceExample: 'The tester pairs happily with developers all sprint, yet still designs negative and boundary tests that deliberately challenge the assumptions built into the code.',
    },
  ],
}
