// ISTQB Foundation Masterclass (CTFL v4.0) — Module 9 practice questions.
// Syllabus topic: Test Tools (Chapter 6). 25 questions, mixed K1/K2/K3.
// Covers tool support for testing, categories of test tools, benefits and
// risks of test automation, tool selection and introduction, and test
// automation in a CI/CD pipeline.
export default {
  courseSlug: "istqb-foundation-masterclass",
  moduleNumber: 9,
  syllabusTopic: "Test Tools",
  questions: [
    {
      kLevel: "K1",
      prompt: "What is the primary purpose of test tools in the software testing process?",
      options: [
        { text: "To support and improve test activities, making them more efficient or enabling activities that would be hard to do manually", correct: true, why: "ISTQB describes tool support as improving the efficiency and effectiveness of testing and enabling activities (such as large-scale regression) that are impractical by hand." },
        { text: "To remove the need for testers by fully replacing human judgement", correct: false, why: "Tools support testers; they do not replace the human skill, judgement and analysis that testing requires." },
        { text: "To guarantee that the software is completely free of defects", correct: false, why: "No tool can guarantee defect-free software; testing shows the presence of defects, not their absence." },
        { text: "To automatically write the requirements and design the system", correct: false, why: "Test tools support testing activities, not the authoring of product requirements or system design." },
      ],
      explanation: "Test tools exist to support test activities. They can make work more efficient (for example automating repetitive checks), improve consistency and repeatability, and enable activities such as high-volume performance testing that are impractical manually. They complement, not replace, tester skill.",
      workplaceExample: "A team spends two days each release running the same 300 regression checks by hand. Introducing an execution tool lets those checks run overnight, freeing testers to explore new features - a classic case of a tool supporting, not replacing, the testers.",
    },
    {
      kLevel: "K2",
      prompt: "Which of the following is the BEST example of a test activity that tool support makes practical when it would be nearly impossible manually?",
      options: [
        { text: "Simulating thousands of concurrent users to measure performance under load", correct: true, why: "Generating and coordinating thousands of virtual users is impractical by hand, so performance tools are essential for this activity." },
        { text: "Deciding which risks are most important to the business", correct: false, why: "Prioritising business risk is a human judgement activity, not something a tool performs for you." },
        { text: "Reviewing a requirements document for ambiguous wording", correct: false, why: "Understanding ambiguous natural language is a human review skill; tools assist but cannot replace the reviewer's judgement." },
        { text: "Choosing an appropriate test design technique for a feature", correct: false, why: "Selecting techniques relies on tester analysis and experience rather than automated tooling." },
      ],
      explanation: "Some activities are simply not feasible manually - generating load from thousands of simultaneous users is the textbook example. Tools shine where volume, repetition or precise measurement exceed human capacity, whereas judgement-heavy activities stay with people.",
      workplaceExample: "Before a Black Friday sale, an e-commerce team uses a load tool to simulate 20,000 concurrent shoppers. No manual team could reproduce that traffic, so the tool is the only realistic way to expose the slow checkout under peak load.",
    },
    {
      kLevel: "K1",
      prompt: "Which category of test tool is designed to support test planning, monitoring, scheduling, and traceability of test cases to requirements?",
      options: [
        { text: "Test management tools", correct: true, why: "Test management tools support planning, monitoring, control and traceability across the test process." },
        { text: "Performance testing tools", correct: false, why: "Performance tools generate load and measure behaviour under load, not manage the overall test process." },
        { text: "Static analysis tools", correct: false, why: "Static analysis tools examine code or artefacts without executing them; they do not manage the test process." },
        { text: "Test data preparation tools", correct: false, why: "Data preparation tools create or mask test data; they do not handle planning or traceability." },
      ],
      explanation: "Test management (and application lifecycle management) tools coordinate the test process: planning, scheduling, monitoring progress, managing test cases and providing traceability from requirements through to results and defects.",
      workplaceExample: "A test lead uses a test management tool to link each of 40 requirements to its test cases, so that when a requirement changes she can instantly see which tests need re-running and report coverage to stakeholders.",
    },
    {
      kLevel: "K2",
      prompt: "A tool examines source code for coding-standard violations and potential defects without running the program. Into which category does this tool fall?",
      options: [
        { text: "Static testing tools (static analysis)", correct: true, why: "Analysing code without executing it, to find violations and potential defects, is exactly what static analysis tools do." },
        { text: "Test execution tools", correct: false, why: "Execution tools run tests against a running system; this tool does not execute the program." },
        { text: "Coverage measurement tools", correct: false, why: "Coverage tools measure which parts of code were exercised during dynamic execution, not standards compliance without running." },
        { text: "Monitoring tools", correct: false, why: "Monitoring tools observe a running system in operation, not static source examination." },
      ],
      explanation: "Static analysis tools inspect code and other artefacts without execution, flagging standards violations, complexity issues, security weaknesses and suspicious constructs. Because they run early, they catch defects cheaply before code is ever executed.",
      workplaceExample: "A developer commits code and a static analysis tool immediately flags an unused variable and a potential null-pointer path. The issue is fixed in minutes, long before any test is executed against a build.",
    },
    {
      kLevel: "K1",
      prompt: "Which type of tool is used specifically to generate, populate, or mask realistic inputs so that tests have appropriate data to run against?",
      options: [
        { text: "Test data preparation tools", correct: true, why: "These tools create, select, generate or anonymise data so tests can execute against representative inputs." },
        { text: "Defect management tools", correct: false, why: "Defect tools track and manage reported defects, not the preparation of test data." },
        { text: "Coverage tools", correct: false, why: "Coverage tools measure what was exercised, not prepare data." },
        { text: "Continuous integration tools", correct: false, why: "CI tools orchestrate build and test pipelines, not specifically prepare or mask test data." },
      ],
      explanation: "Test data preparation tools support building or provisioning the data a test needs - generating volumes of records, selecting subsets, or masking production data so it can be used safely. Good data is often the bottleneck, so these tools remove a common obstacle.",
      workplaceExample: "To test a loan-approval rule, a tester needs 5,000 customer records across many credit bands. A data preparation tool generates and masks them from production so no real personal data is exposed while still giving realistic coverage.",
    },
    {
      kLevel: "K2",
      prompt: "During dynamic test execution a tool reports that 78% of the code statements were exercised by the test suite. Which category of tool produced this figure?",
      options: [
        { text: "Coverage measurement tools", correct: true, why: "Coverage tools instrument code and measure which statements, branches or paths were exercised during execution." },
        { text: "Static analysis tools", correct: false, why: "Static analysis does not execute code, so it cannot report exercised statements." },
        { text: "Test management tools", correct: false, why: "Management tools track the process; they do not instrument code to measure coverage." },
        { text: "Performance testing tools", correct: false, why: "Performance tools measure response and load behaviour, not structural coverage." },
      ],
      explanation: "Coverage tools measure the degree to which code structures (statements, branches, decisions) are exercised by tests during execution. This helps a team see untested areas, though high coverage alone never proves the tests are meaningful.",
      workplaceExample: "After a test run, a coverage tool shows an error-handling block was never executed. The team adds a negative test to reach it and discovers the block actually logs to the wrong file - a defect that would otherwise have shipped.",
    },
    {
      kLevel: "K1",
      prompt: "Which category of tool observes a system in operation and raises alerts when metrics such as response time, memory, or error rates exceed thresholds?",
      options: [
        { text: "Monitoring tools", correct: true, why: "Monitoring tools continuously observe a running system and alert when defined thresholds are breached." },
        { text: "Test design tools", correct: false, why: "Test design tools help derive test cases from a basis, not observe a running system." },
        { text: "Static analysis tools", correct: false, why: "Static analysis does not observe a running system; it inspects artefacts without execution." },
        { text: "Test data preparation tools", correct: false, why: "Data preparation tools provision inputs; they do not monitor a live system's metrics." },
      ],
      explanation: "Monitoring tools watch live or test systems and report on resource use, throughput, response times and errors, often raising alerts. They are closely related to performance tooling and are important for operational and reliability testing.",
      workplaceExample: "A monitoring tool alerts an on-call tester that API error rates jumped to 4% after a deploy. The team rolls back within minutes, well before most users notice - the alert turned a potential outage into a non-event.",
    },
    {
      kLevel: "K2",
      prompt: "Which of the following tools is MOST directly associated with a DevOps / continuous integration approach to testing?",
      options: [
        { text: "A pipeline tool that automatically builds the software and triggers automated tests on every code commit", correct: true, why: "CI tools automatically integrate, build and test on each commit, which is central to DevOps delivery." },
        { text: "A spreadsheet used to record manual exploratory session notes", correct: false, why: "A manual notes spreadsheet is not a CI/DevOps automation tool." },
        { text: "A tool that only masks personal data in a database", correct: false, why: "Data masking is a data-preparation activity, not the defining tool of a CI pipeline." },
        { text: "A whiteboard used during a risk workshop", correct: false, why: "A whiteboard supports human collaboration, not automated continuous integration." },
      ],
      explanation: "Continuous integration and DevOps toolchains automatically build and test software whenever code changes, giving fast feedback. Automated tests wired into the pipeline are what make continuous integration deliver value.",
      workplaceExample: "Every time a developer pushes code, the CI server builds the app and runs the unit and API test suites. A broken login flow is caught within eight minutes of the commit, so the developer fixes it while the context is still fresh.",
    },
    {
      kLevel: "K2",
      prompt: "Which of the following is a genuine BENEFIT of test automation as described by ISTQB?",
      options: [
        { text: "Reduction of repetitive manual work, freeing testers for activities that need human insight", correct: true, why: "Automating repetitive execution reduces tedious manual effort and lets testers focus on judgement-based work." },
        { text: "Complete elimination of the need for any test maintenance", correct: false, why: "Automated tests require ongoing maintenance; automation does not remove that need - it adds it." },
        { text: "A guarantee that no defects will reach production", correct: false, why: "No automation can guarantee zero defects; that is an unrealistic expectation." },
        { text: "Removal of the need for testers to understand the system under test", correct: false, why: "Automation still requires deep understanding to design and interpret the tests correctly." },
      ],
      explanation: "Real benefits of automation include less repetitive manual effort, greater consistency and repeatability, faster feedback, better coverage of certain areas, and objective measurement. These are concrete gains - not promises of perfection.",
      workplaceExample: "After automating the nightly regression suite, a team's manual testers stop spending Mondays re-running the same checks and instead do exploratory testing on new features, finding subtle usability defects the scripts would never catch.",
    },
    {
      kLevel: "K2",
      prompt: "Which statement about the benefits of test automation is OVERSTATED and therefore incorrect?",
      options: [
        { text: "Automation will find all the important defects that manual testing would miss", correct: true, why: "This is an unrealistic expectation; automated tests only check what they were written to check and often miss defects a human would notice." },
        { text: "Automation can provide more consistent and repeatable test execution", correct: false, why: "Consistency and repeatability are genuine, well-documented benefits of automation." },
        { text: "Automation can give faster feedback on regression issues", correct: false, why: "Faster regression feedback is a real benefit of automation." },
        { text: "Automation can enable objective measurement, such as coverage figures", correct: false, why: "Objective measurement is a legitimate benefit of tool-supported testing." },
      ],
      explanation: "A common trap is expecting automation to find defects manual testing misses. Automated tests only verify the specific conditions they encode; they rarely notice the unexpected. Overstated benefits like this create unrealistic expectations and later disappointment.",
      workplaceExample: "A manager promises the board that automation will 'catch everything'. Two releases later a glaring layout bug ships because no script checked visual appearance - a human tester would have spotted it in seconds. The over-promise damaged trust in the whole automation effort.",
    },
    {
      kLevel: "K2",
      prompt: "Which of the following is a well-recognised RISK of test automation according to ISTQB?",
      options: [
        { text: "The ongoing cost of maintaining automated tests can be underestimated", correct: true, why: "Maintenance effort - updating scripts as the software changes - is a major and frequently underestimated cost of automation." },
        { text: "Automated tests never need to change once written", correct: false, why: "That is false; changing software forces automated tests to be updated, which is the source of maintenance cost." },
        { text: "Automation always costs nothing to set up", correct: false, why: "Setting up automation requires real up-front investment in tools, frameworks and skills." },
        { text: "Automation removes all reliance on tester skill", correct: false, why: "Automation increases, rather than removes, the need for skilled people to build and maintain it." },
      ],
      explanation: "Key automation risks include underestimated maintenance cost, unrealistic expectations, over-reliance on automation at the expense of human testing, up-front setup effort, and dependence on the tool vendor. Maintenance is often the one that quietly sinks automation initiatives.",
      workplaceExample: "A team automates 800 UI tests, then a redesign changes every screen. Suddenly hundreds of tests fail and must be rewritten. The maintenance burden consumes more effort than the manual testing ever did - a cost nobody had budgeted for.",
    },
    {
      kLevel: "K2",
      prompt: "A team stops doing any exploratory or manual testing because they believe their automated suite covers everything. Which automation risk does this illustrate?",
      options: [
        { text: "Over-reliance on automation", correct: true, why: "Trusting automation to cover everything and abandoning human testing is the classic over-reliance risk." },
        { text: "Under-investment in the automation tool licence", correct: false, why: "The problem here is behavioural over-trust, not a licensing shortfall." },
        { text: "Excessive manual regression effort", correct: false, why: "The team has reduced manual effort; the issue is that they have reduced it too far." },
        { text: "Lack of any test data", correct: false, why: "Test data is not the issue described; the issue is misplaced confidence in automation." },
      ],
      explanation: "Over-reliance means treating a green automated suite as proof of quality and dropping the human testing that catches the unexpected. Automation checks known conditions; exploratory testing finds the unknowns. Both are needed.",
      workplaceExample: "Because the automated suite was always green, a team dropped exploratory testing. A confusing new checkout flow shipped that technically worked but frustrated users - no script questioned the user experience, and no human was looking any more.",
    },
    {
      kLevel: "K2",
      prompt: "Why is it risky to set an expectation that automation will 'pay for itself immediately' in the first release?",
      options: [
        { text: "Automation requires significant up-front investment, so returns typically appear over multiple cycles, not instantly", correct: true, why: "Setup, framework and scripting effort are paid up front; the payback accrues as tests are re-run across many cycles." },
        { text: "Automated tests can only ever run once", correct: false, why: "Automated tests are valuable precisely because they can be re-run many times." },
        { text: "Automation makes the software slower to build", correct: false, why: "Automation does not inherently slow the build; that is not the reason returns are delayed." },
        { text: "Automation reduces test coverage on purpose", correct: false, why: "Automation aims to support coverage, not deliberately reduce it." },
      ],
      explanation: "Unrealistic expectations - like instant payback - are a named automation risk. The initial investment in tools, frameworks and scripting is high; value comes from repeated re-execution over time. Setting expectations correctly protects the initiative from being judged a failure too early.",
      workplaceExample: "A team's first automated release actually costs more than manual testing because of framework setup. By the fifth release the same scripts have run twenty times for near-zero effort, and the cumulative saving is large - the payback was real but not immediate.",
    },
    {
      kLevel: "K3",
      prompt: "A company evaluating whether to adopt a new test execution tool wants to reduce the risk of a bad organisation-wide rollout. Which action BEST addresses this concern?",
      options: [
        { text: "Run a pilot project on a limited scope to learn the tool and assess fit before wider deployment", correct: true, why: "A pilot lets the organisation gain experience, evaluate fit and uncover issues on a small scale before committing widely." },
        { text: "Deploy the tool to every team on day one to maximise adoption speed", correct: false, why: "Big-bang deployment amplifies the impact of any problem and skips the learning a pilot provides." },
        { text: "Buy the most expensive tool available on the assumption it must be best", correct: false, why: "Cost is not a reliable proxy for fit; selection should be based on evaluation against needs." },
        { text: "Automate all existing manual tests before evaluating the tool at all", correct: false, why: "Mass automation before any evaluation risks large wasted effort if the tool proves unsuitable." },
      ],
      explanation: "ISTQB recommends introducing a tool via a pilot project. A pilot builds hands-on knowledge, evaluates how well the tool fits existing processes and technology, identifies needed process changes, and assesses the true cost and benefit - all before a risky full-scale rollout.",
      workplaceExample: "Before committing, a QA manager pilots a new automation tool on one low-risk product for six weeks. The pilot reveals the tool struggles with the company's legacy desktop app - a finding that saves the organisation from a costly mistake across ten teams.",
    },
    {
      kLevel: "K2",
      prompt: "Which of the following is a key GOAL of running a pilot project when introducing a new test tool?",
      options: [
        { text: "To gain experience with the tool and learn how it fits the organisation's processes and technology", correct: true, why: "A pilot's central aims are learning the tool, assessing fit, and identifying process changes and realistic costs and benefits." },
        { text: "To immediately replace all testers with the tool", correct: false, why: "Tools support testers; a pilot does not aim to eliminate the test team." },
        { text: "To avoid ever having to change existing processes", correct: false, why: "A pilot often reveals that processes must adapt to use the tool effectively." },
        { text: "To lock in a purchase before any evaluation is done", correct: false, why: "The pilot is part of the evaluation; it exists to inform, not bypass, the decision." },
      ],
      explanation: "A pilot project evaluates the tool against real needs, builds skills, determines how ways of working must adapt, and assesses whether expected benefits are realistic. Its findings drive a well-informed decision about full deployment.",
      workplaceExample: "During a pilot, a team discovers the new tool needs test cases written in a specific format. Rather than abandon the tool, they adapt their test-authoring process - a change they would never have identified without the pilot.",
    },
    {
      kLevel: "K2",
      prompt: "When introducing a test tool across an organisation, why is coaching and mentoring of staff considered important?",
      options: [
        { text: "It helps testers build the skills and confidence to use the tool effectively, improving adoption and return on investment", correct: true, why: "Coaching and mentoring support new users, spread good practice and are a recognised success factor for tool introduction." },
        { text: "It removes the need to ever adapt existing processes", correct: false, why: "Successful introduction usually requires process changes; coaching supports those changes rather than avoiding them." },
        { text: "It guarantees the tool will find every defect", correct: false, why: "No amount of coaching makes a tool find every defect; that is an unrealistic expectation." },
        { text: "It makes the tool free to license", correct: false, why: "Coaching addresses skills and adoption, not licensing cost." },
      ],
      explanation: "Introducing a tool is an organisational change, not just an installation. Providing coaching, mentoring and support helps staff use the tool well, encourages consistent good practice, and is central to realising the tool's expected benefits.",
      workplaceExample: "After buying an automation tool, a company pairs each team with an experienced mentor for a month. Adoption jumps because testers get help over the first hurdles, instead of quietly giving up and reverting to manual work.",
    },
    {
      kLevel: "K2",
      prompt: "Which factor is a legitimate SPECIAL CONSIDERATION when SELECTING a test tool for an organisation?",
      options: [
        { text: "Assessing how well the tool fits the organisation's existing processes, technology and skills", correct: true, why: "Fit with current processes, technology and team maturity is a core selection consideration in ISTQB." },
        { text: "Choosing whichever tool a competitor happens to use, without evaluating fit", correct: false, why: "Copying a competitor without evaluating fit ignores the organisation's own context and needs." },
        { text: "Selecting a tool purely because it has the largest feature list", correct: false, why: "A long feature list does not mean the tool fits the organisation's actual needs and constraints." },
        { text: "Assuming any tool will integrate perfectly with all existing systems", correct: false, why: "Integration must be assessed, not assumed; poor integration is a common cause of failed adoption." },
      ],
      explanation: "Tool selection considers the organisation's maturity, strengths and weaknesses; how the tool fits existing processes and technology; the vendor and support arrangements; integration needs; licensing model; and a clear cost-benefit case - not just feature counts.",
      workplaceExample: "A team assesses two tools against a checklist: fit with their CI pipeline, support quality, licence cost and required skills. The flashier tool loses because it cannot integrate with their existing pipeline - fit beat features.",
    },
    {
      kLevel: "K1",
      prompt: "When introducing a new test tool, why should an organisation often adapt or improve its processes rather than expect the tool to slot in unchanged?",
      options: [
        { text: "Because effective tool use frequently requires supporting processes to change so the tool delivers real value", correct: true, why: "ISTQB stresses that introducing a tool usually requires adapting and improving processes to fit the new way of working." },
        { text: "Because tools legally require documented process rewrites", correct: false, why: "There is no legal requirement; the reason is practical effectiveness, not regulation." },
        { text: "Because processes must always be discarded when a tool arrives", correct: false, why: "Processes are adapted and improved, not necessarily discarded wholesale." },
        { text: "Because the tool vendor forbids using existing processes", correct: false, why: "Vendors do not forbid existing processes; adaptation is driven by fit and effectiveness." },
      ],
      explanation: "A tool imposed on unsuitable processes rarely delivers. Successful introduction adapts and improves ways of working so the tool fits - for example changing how test cases are written or when tests are triggered - to unlock the intended benefits.",
      workplaceExample: "A team adopts a tool that runs tests automatically on each commit. To benefit, they change their process so tests are committed alongside code - a small workflow change that turns the tool from shelfware into a fast feedback engine.",
    },
    {
      kLevel: "K1",
      prompt: "In a CI/CD pipeline, when are automated tests typically triggered?",
      options: [
        { text: "Automatically, when code is committed or integrated into the shared codebase", correct: true, why: "Continuous integration runs automated builds and tests on each commit or integration, giving rapid feedback." },
        { text: "Only once, manually, at the very end of the project", correct: false, why: "That describes late manual testing, the opposite of continuous integration's frequent automated runs." },
        { text: "Only when a customer reports a defect in production", correct: false, why: "CI runs proactively on changes, not reactively only after production defects." },
        { text: "Never - CI pipelines do not run tests", correct: false, why: "Running automated tests is a core purpose of a CI pipeline." },
      ],
      explanation: "In continuous integration, committing code triggers an automated build followed by automated tests. This gives fast feedback so integration problems are caught early, while the change is still fresh in the developer's mind.",
      workplaceExample: "A developer merges a branch at 2pm; by 2:07pm the pipeline has built the app and reported a failing unit test. The developer fixes it before leaving for the day, avoiding a bug that would otherwise surface a week later in system testing.",
    },
    {
      kLevel: "K2",
      prompt: "What is a primary benefit of wiring automated tests into a CI/CD pipeline at the foundation level?",
      options: [
        { text: "Fast, frequent feedback on the impact of code changes, so defects are found soon after they are introduced", correct: true, why: "Automated tests on every change provide rapid feedback, enabling early detection close to when defects are introduced." },
        { text: "It removes the need for any test design or planning", correct: false, why: "CI still relies on well-designed tests; the pipeline runs them, it does not design them." },
        { text: "It guarantees that the released software has zero defects", correct: false, why: "No pipeline can guarantee zero defects; it improves feedback speed, not perfection." },
        { text: "It eliminates the need for developers to write code carefully", correct: false, why: "Fast feedback supports careful development; it does not excuse poor coding." },
      ],
      explanation: "The value of automation in CI/CD is speed and frequency of feedback. Because tests run on every integration, defects surface early and cheaply, integration risk stays low, and the team can release changes with greater confidence.",
      workplaceExample: "A team releases small changes several times a day. Because every change is auto-tested in the pipeline, a regression in the pricing rule is caught within minutes of being introduced, not discovered by a customer weeks later.",
    },
    {
      kLevel: "K2",
      prompt: "Which of the following BEST describes the relationship between automated tests and manual testing in a mature test approach?",
      options: [
        { text: "Automation handles repeatable, high-volume checks while manual testing focuses on exploration and human judgement", correct: true, why: "Automation and manual testing are complementary: each is suited to different tasks, and both are needed." },
        { text: "Automation should always completely replace manual testing", correct: false, why: "Full replacement causes over-reliance and misses defects only humans notice." },
        { text: "Manual testing should always completely replace automation", correct: false, why: "That discards automation's real benefits in speed, consistency and volume." },
        { text: "The two are interchangeable and it never matters which you use", correct: false, why: "They have different strengths, so the choice does matter for effectiveness." },
      ],
      explanation: "Automation and manual testing are complementary. Automation excels at repeatable, high-volume, precise checks; manual and exploratory testing excel at judgement, usability and the unexpected. A balanced approach uses each for what it does best.",
      workplaceExample: "A team automates its 400-check regression suite for speed and consistency, but keeps exploratory sessions for each new feature. The scripts guard against regressions while the human sessions catch the confusing workflows automation would never question.",
    },
    {
      kLevel: "K3",
      prompt: "A team has a stable, rarely changing set of core business rules that must be re-verified on every release, plus a brand-new experimental feature whose UI changes daily. How should they apply automation MOST sensibly?",
      options: [
        { text: "Automate the stable core rules for reliable regression, and test the volatile new feature mainly manually for now", correct: true, why: "Automation pays off on stable, repeatedly executed tests; automating a daily-changing UI would incur crippling maintenance cost." },
        { text: "Automate the volatile new feature first because it is the newest", correct: false, why: "A daily-changing UI would break scripts constantly, generating high maintenance cost for little return." },
        { text: "Automate nothing, since some parts of the system change", correct: false, why: "The stable core rules are ideal automation candidates; avoiding all automation wastes a clear opportunity." },
        { text: "Automate everything immediately regardless of how often it changes", correct: false, why: "Automating volatile areas ignores the maintenance-cost risk and is likely to backfire." },
      ],
      explanation: "Automation gives the best return on stable tests that are re-executed many times, because maintenance stays low and re-runs are cheap. Volatile, fast-changing areas are poor automation candidates - the maintenance cost of constantly fixing scripts outweighs the benefit, so manual testing is more sensible until they stabilise.",
      workplaceExample: "A team automates its unchanging tax-calculation rules, which run green on every release for months. They test the daily-shifting new dashboard by hand, waiting until its design settles before writing scripts - saving themselves from rewriting broken tests every single day.",
    },
    {
      kLevel: "K2",
      prompt: "An organisation reports that its automation project failed because 'the tool did not deliver the massive savings promised in the sales demo'. Which underlying cause does this MOST likely reflect?",
      options: [
        { text: "Unrealistic expectations were set about what the tool would achieve", correct: true, why: "Judging a tool against exaggerated, unrealistic promises is a named automation risk and a common cause of perceived failure." },
        { text: "The tool was too cheap to be useful", correct: false, why: "Price is not the issue; the failure stems from mismatched expectations versus reality." },
        { text: "Automation inherently cannot save any effort", correct: false, why: "Automation genuinely can save effort over time; the problem is the scale and speed that were promised." },
        { text: "The organisation used the tool for regression testing", correct: false, why: "Regression is a sound use of automation; it is not the cause of the perceived failure." },
      ],
      explanation: "Setting unrealistic expectations - often fuelled by polished vendor demos - is a classic reason automation is judged a failure. The tool may deliver real, gradual value, but if it is measured against impossible promises it will always seem to fall short. Honest expectation-setting is a key success factor.",
      workplaceExample: "A vendor demo promised '90% effort reduction from day one'. A year in, automation had cut regression effort by a solid 40% over time - a genuine win - yet management called it a failure because it never matched the demo's inflated claim.",
    },
    {
      kLevel: "K1",
      prompt: "Which of the following is a recognised risk of depending heavily on a single test tool from one vendor?",
      options: [
        { text: "Dependence on the tool vendor, who may raise prices, drop support, or discontinue the product", correct: true, why: "Vendor dependence - including price rises, withdrawn support or a discontinued product - is a named risk of tool adoption." },
        { text: "The tool becomes impossible to license under any circumstances", correct: false, why: "Licensing remains possible; the risk is reliance on the vendor's continued goodwill and support." },
        { text: "The organisation is legally barred from testing manually", correct: false, why: "There is no such legal bar; manual testing remains available." },
        { text: "The tool will automatically improve without any maintenance", correct: false, why: "Tools and their tests still need maintenance; this is not a benefit that offsets vendor risk." },
      ],
      explanation: "Relying on a proprietary tool ties the organisation to its vendor. If the vendor increases prices, reduces support, changes direction or discontinues the product, the organisation is exposed. This is why vendor stability and support are part of tool selection.",
      workplaceExample: "A team built its entire regression suite in a proprietary tool. When the vendor doubled the licence fee and dropped support for the team's platform, they faced an expensive migration - a painful lesson in vendor dependence.",
    },
    {
      kLevel: "K2",
      prompt: "Which category of tool helps testers systematically derive test cases or generate expected results from a specified test basis such as a model or set of rules?",
      options: [
        { text: "Test design tools", correct: true, why: "Test design tools support deriving test cases, and sometimes expected results, from a test basis such as requirements or models." },
        { text: "Monitoring tools", correct: false, why: "Monitoring tools observe a running system's metrics; they do not derive test cases from a basis." },
        { text: "Defect management tools", correct: false, why: "Defect tools track reported defects; they do not generate test cases from a test basis." },
        { text: "Performance testing tools", correct: false, why: "Performance tools generate load and measure behaviour, not derive test cases from a specification." },
      ],
      explanation: "Test design tools support the creation of test cases (and sometimes expected results) from a test basis such as requirements, models or interfaces. They help apply techniques consistently and can improve coverage of the specified conditions.",
      workplaceExample: "Given a decision table of business rules, a test design tool generates the full set of rule combinations as draft test cases. The tester reviews and refines them, ensuring no rule combination is accidentally left untested.",
    },
  ],
};
