// ISTQB Foundation Masterclass -- Module 11: Real World QA (APPLIED).
// Scenario-based practice questions. Each question sets up a realistic
// workplace situation but the single best answer is always justifiable
// from the ISTQB Foundation (CTFL v4.0) syllabus: principles, techniques,
// risk-based testing, defect management, the test process, and tools.
// ASCII quotes/apostrophes only. Default export only, no imports.
export default {
  courseSlug: "istqb-foundation-masterclass",
  moduleNumber: 11,
  syllabusTopic: "Real World QA",
  questions: [
    {
      questionText: "Two days before release, a developer says: \"The login module has passed every test for three sprints, so let's stop testing it and reassign the tester.\" As the QA lead, which ISTQB principle most directly warns against relying on this reasoning to declare the module defect-free?",
      kLevel: "K2",
      options: [
        { text: "Testing shows the presence of defects, not their absence", correct: true, why: "Passing tests can only demonstrate that defects were not found by those tests; they can never prove the module has no remaining defects, so 'defect-free' is an unsupportable claim." },
        { text: "Exhaustive testing is impossible", correct: false, why: "True as a principle, but it addresses why we cannot test everything, not why passing tests fail to prove absence of defects in what was tested." },
        { text: "Tests wear out", correct: false, why: "This is not an ISTQB principle. The pesticide paradox describes repeated tests finding fewer new defects, which is a different point from proving absence of defects." },
        { text: "Testing is context dependent", correct: false, why: "This principle says testing differs by context; it does not address the logical limit of what passing tests can prove." },
      ],
      explanation: "The principle 'testing shows the presence of defects, not their absence' directly rebuts any claim that a clean test run proves a component is bug-free. You can reduce the probability of undiscovered defects, but never guarantee their absence. The right response is to base any stop-testing decision on risk and exit criteria, not on the false conclusion that no failures means no defects.",
      workplaceExample: "The same trap appears when a manager says 'the smoke test is green, so we're good to ship.' A green smoke test covers a thin slice of behaviour; it is evidence of the absence of the failures you looked for, not evidence of overall correctness. On the job, phrase status as 'no known blocking defects in the areas we tested,' never as 'no defects.'",
    },
    {
      questionText: "Your regression pack takes eleven hours to run and has grown for two years, yet it now catches almost no new defects while new bugs keep slipping through in recently changed areas. Which ISTQB principle best explains this, and what is the aligned response?",
      kLevel: "K2",
      options: [
        { text: "The pesticide paradox applies; review and revise the tests, adding new cases for changed and risky areas", correct: true, why: "Repeating the same tests stops finding new defects over time; the syllabus response is to regularly review and update the test cases to exercise different paths and newly changed code." },
        { text: "Defect clustering applies; delete the regression pack because defects are elsewhere", correct: false, why: "Clustering is real, but deleting an entire regression pack discards protection; the paradox here calls for revising tests, not removing coverage." },
        { text: "Early testing applies; move all tests to the start of the project", correct: false, why: "Early testing is valuable but does not explain why an existing repeated suite stops finding defects." },
        { text: "Exhaustive testing is impossible; therefore stop maintaining the suite", correct: false, why: "That principle justifies prioritisation, not abandoning maintenance of a suite that is going stale." },
      ],
      explanation: "The pesticide paradox states that running the same tests repeatedly eventually stops revealing new defects. The syllabus remedy is to review and revise tests regularly and write new ones to exercise different parts of the software, especially changed and higher-risk areas. That, combined with defect-clustering insight to aim effort where bugs concentrate, keeps the suite effective instead of merely long.",
      workplaceExample: "A team I worked with had a four-hour suite that was 90 percent duplicate assertions and never touched the payment refactor shipped last quarter. Pruning stale cases and adding targeted tests for the changed code cut runtime and immediately caught two refund defects. Longer suites are not safer suites; relevance beats volume.",
    },
    {
      questionText: "In a defect triage meeting, a cosmetic typo on the internal admin dashboard is logged, and separately a checkout total miscalculates VAT for one rare currency used by a single high-value client shipping next week. How should you classify these using severity and priority?",
      kLevel: "K3",
      options: [
        { text: "Typo: low severity, low priority. VAT bug: high severity, high priority", correct: true, why: "Severity reflects impact on the system (wrong money is high impact; a typo is low), and priority reflects business urgency (the VAT bug blocks an imminent high-value shipment, the typo does not)." },
        { text: "Both are high priority because all defects must be fixed before release", correct: false, why: "The zero-defect fallacy: not every defect must be fixed, and treating all as equally urgent ignores risk-based prioritisation." },
        { text: "Typo: high priority because it is visible; VAT bug: low priority because it is rare", correct: false, why: "Visibility on an internal screen is not urgency, and rarity does not lower the impact of miscalculating money for an imminent client." },
        { text: "Severity and priority are the same, so rank both as medium", correct: false, why: "Severity (technical impact) and priority (business urgency) are distinct attributes and can differ for the same defect." },
      ],
      explanation: "Severity measures the impact of the defect on the system or its users; priority measures how urgently it should be addressed from a business standpoint. They are independent: a wrong-money defect is high severity, and because it affects an imminent high-value shipment it is also high priority. The internal typo is low on both. Risk-based thinking, not visibility or gut feel, drives the ordering.",
      workplaceExample: "A classic split is a crash in a feature nobody uses (high severity, low priority) versus a misspelled company name on the landing page before a press launch (low severity, high priority). On the job, always record the two attributes separately so triage can argue urgency without re-arguing impact.",
    },
    {
      questionText: "A product owner asks you to sign off that the release has 'no bugs.' The team has run risk-based testing, met the agreed exit criteria, and has three known low-severity defects deferred with sign-off. What is the most ISTQB-aligned way to report status?",
      kLevel: "K2",
      options: [
        { text: "Report that exit criteria are met and there are no known blocking defects, listing the three deferred low-severity defects and residual risk", correct: true, why: "This is honest, evidence-based, and reflects that testing cannot prove the absence of defects; it communicates coverage, known issues, and residual risk for an informed release decision." },
        { text: "Confirm there are no bugs because all planned tests passed", correct: false, why: "Claiming 'no bugs' violates the principle that testing shows the presence, not the absence, of defects, and hides the known deferred defects." },
        { text: "Refuse to report anything until every possible test has been executed", correct: false, why: "Exhaustive testing is impossible, so waiting for it is never a valid basis for a status report." },
        { text: "Say the release is fine because the customer has not complained yet", correct: false, why: "Absence of complaints is not test evidence and says nothing about coverage or residual risk." },
      ],
      explanation: "Test status should communicate what was covered, which exit criteria were met, what defects are known and deferred, and what residual risk remains. That gives stakeholders the information to make a release decision. Signing off 'no bugs' is both technically false, given the principle on absence of defects, and dishonest given the known deferred issues.",
      workplaceExample: "In a release readiness review, a strong test summary reads: 'Priority-1 and Priority-2 risks covered, exit criteria met, three Priority-4 cosmetic defects deferred with PO approval, residual risk low in reporting exports.' That lets the business own the go decision. 'No bugs' invites blame the first time production hiccups.",
    },
    {
      questionText: "You are testing a new subscription pricing field that accepts a whole number of seats from 1 to 100. Time is tight. Which technique gives strong defect-finding coverage of this input with the fewest cases?",
      kLevel: "K3",
      options: [
        { text: "Boundary value analysis around 0/1 and 100/101, combined with equivalence partitioning for a valid mid-range value", correct: true, why: "Defects cluster at boundaries; testing just inside and just outside each edge plus one representative valid value covers the likely failure points efficiently." },
        { text: "Test every integer from 1 to 100 to be certain", correct: false, why: "This approaches exhaustive testing for the field, adding little value over boundary and partition cases while wasting scarce time." },
        { text: "Pick three random numbers and move on", correct: false, why: "Random values may all fall inside one partition and miss the boundaries where defects concentrate." },
        { text: "Use a state transition diagram of the pricing field", correct: false, why: "A single numeric input field has no meaningful states to transition between; state transition testing fits event-driven behaviour, not this range check." },
      ],
      explanation: "Equivalence partitioning divides inputs into classes expected to behave the same, so one value per class suffices. Boundary value analysis targets the edges of those classes, where off-by-one and comparison-operator defects concentrate. Together they give high coverage of a bounded numeric field with a handful of cases, ideal under time pressure.",
      workplaceExample: "Age fields, quantity fields, and date ranges are the everyday home of boundary defects: '>=' written as '>', or a max of 100 that actually rejects 100. Testing 0, 1, 100, and 101 plus one middle value finds these in minutes, where testing all 100 values would find nothing extra.",
    },
    {
      questionText: "A feature lets a support ticket move through states: New -> Open -> Pending -> Resolved -> Closed, with some transitions forbidden (for example you cannot go from New straight to Closed). Which black-box technique is the best fit to design tests for this behaviour?",
      kLevel: "K3",
      options: [
        { text: "State transition testing", correct: true, why: "The feature is defined by states and the allowed and forbidden transitions between them, which is exactly what state transition testing is designed to cover." },
        { text: "Boundary value analysis", correct: false, why: "BVA targets edges of ordered input ranges, not transitions between named states." },
        { text: "Decision table testing", correct: false, why: "Decision tables model combinations of conditions producing actions; they do not naturally capture sequences of states over time." },
        { text: "Use case testing only", correct: false, why: "Use case testing captures end-to-end business flows but is weaker at systematically covering each valid and invalid state transition." },
      ],
      explanation: "State transition testing models a system as states, events, transitions, and resulting states. It is ideal when behaviour depends on history and on which moves are permitted. It also prompts you to test invalid transitions (New -> Closed) that developers often forget to block, which is where many workflow defects hide.",
      workplaceExample: "Order lifecycles, approval workflows, and media players (playing/paused/stopped) are all natural state machines. The high-value cases are usually the forbidden transitions: can a refunded order be shipped? Testers who draw the state diagram routinely find gaps the requirements never mentioned.",
    },
    {
      questionText: "A loan-approval screen grants or denies credit based on combinations of three conditions: applicant employed (yes/no), credit score above threshold (yes/no), and existing customer (yes/no). Which technique best ensures every relevant combination of conditions is covered?",
      kLevel: "K3",
      options: [
        { text: "Decision table testing", correct: true, why: "Decision tables systematically enumerate combinations of conditions and their resulting actions, which is exactly what a rules-driven approval decision requires." },
        { text: "State transition testing", correct: false, why: "There are no evolving states here, just a set of conditions evaluated together to produce a decision." },
        { text: "Boundary value analysis", correct: false, why: "BVA would test the score threshold edge but ignores the combinatorial logic across the three yes/no conditions." },
        { text: "Error guessing", correct: false, why: "Error guessing is experience-based and unsystematic; it cannot guarantee coverage of all rule combinations." },
      ],
      explanation: "When output depends on combinations of conditions, a decision table captures each combination as a column with the expected action, exposing missing or contradictory business rules. It gives systematic coverage of the logic that ad hoc testing would leave patchy. You can still add boundary tests for the score threshold within the same effort.",
      workplaceExample: "Insurance eligibility, discount rules, and access-control matrices are prime decision-table territory. Building the table frequently surfaces a combination the business never specified ('employed, low score, existing customer') and forces a real decision before it becomes a production dispute.",
    },
    {
      questionText: "Under heavy deadline pressure, you can only test part of a new banking app. The team has a risk analysis showing the funds-transfer flow is high likelihood and high impact, while the help-page footer is low on both. How should risk-based testing shape your plan?",
      kLevel: "K3",
      options: [
        { text: "Allocate most effort and depth to the funds-transfer flow and only light checks to the footer", correct: true, why: "Risk-based testing prioritises test effort by the level of risk, concentrating depth where the likelihood and impact of failure are greatest." },
        { text: "Split effort equally across every feature so nothing is neglected", correct: false, why: "Equal effort ignores the risk analysis and wastes scarce time on low-risk areas at the expense of critical ones." },
        { text: "Test the easiest features first to maximise the pass count", correct: false, why: "Optimising for a high pass rate is vanity; it does not reduce the risk that matters to the business." },
        { text: "Test the footer thoroughly first because it is quick to finish", correct: false, why: "Finishing low-risk work first leaves the highest risk untested if time runs out." },
      ],
      explanation: "Risk is the combination of the likelihood of a failure and its impact. Risk-based testing uses that assessment to prioritise, sequence, and set the depth of testing, so the most important risks get the most attention and are addressed earliest. Under time pressure this ensures the residual risk at release is as low as possible for the effort available.",
      workplaceExample: "Before a fintech launch we ranked flows by money-at-risk and legal exposure: transfers and statements got deep testing, the marketing footer got a glance. When time was cut further, we still shipped confident about the flows that could lose real money. Prioritise by risk, and a shortened window costs you the least-important coverage first.",
    },
    {
      questionText: "Mid-sprint, the acceptance criteria for a story you are testing are ambiguous, and two developers interpret them differently. Applying the ISTQB principle of early testing, what is the highest-value action?",
      kLevel: "K2",
      options: [
        { text: "Raise the ambiguity now as a static-testing finding so the requirement is clarified before more code is built on it", correct: true, why: "Early testing means test and review activities begin as early as possible; finding a requirement defect via review is far cheaper than finding it after coding and integration." },
        { text: "Wait until the code is complete, then log any mismatch as a defect", correct: false, why: "Delaying makes the fix more expensive and lets the ambiguity propagate into code and tests." },
        { text: "Pick one interpretation yourself and test only that", correct: false, why: "Guessing hides the ambiguity and risks validating the wrong behaviour." },
        { text: "Skip the story since it is unclear", correct: false, why: "Skipping abandons a high-risk item rather than resolving the root cause cheaply." },
      ],
      explanation: "The early testing principle (shift left) holds that testing activities, including static reviews of requirements, should start as early as possible because the cost of fixing a defect rises the later it is found. An ambiguous requirement is a defect in a work product; catching it in review costs a conversation, whereas catching it after release costs a redesign.",
      workplaceExample: "A requirement reading 'the report shows recent orders' hid a disagreement: recent meant 30 days to one dev and this-quarter to another. Raising it in refinement cost five minutes; discovering it after the report shipped would have cost a hotfix and an angry client. Ambiguity is a defect, and review is the cheapest place to kill it.",
    },
    {
      questionText: "Your team debates whether to run a formal requirements review or just let testers find issues later during test execution. Which statement best captures the ISTQB rationale for the static review?",
      kLevel: "K2",
      options: [
        { text: "Static testing finds defects in work products directly and earlier, without executing code, reducing later rework", correct: true, why: "Reviews and other static techniques examine requirements, designs, and code without execution, catching defects at their source before they become costly runtime failures." },
        { text: "Static testing replaces the need for any dynamic testing", correct: false, why: "Static and dynamic testing are complementary; reviews cannot verify runtime behaviour, performance, or integration." },
        { text: "Reviews are only useful for finding coding standard violations", correct: false, why: "Reviews find ambiguities, omissions, inconsistencies, and requirement defects, not just style issues." },
        { text: "Dynamic testing always finds defects earlier than reviews", correct: false, why: "Dynamic testing requires executable code, so it necessarily happens later than a review of the requirement." },
      ],
      explanation: "Static testing examines work products such as requirements, user stories, and code without executing them, using reviews and static analysis. It can find defects, especially in requirements and design, earlier and more cheaply than dynamic testing, and it finds certain defects (ambiguities, omissions) that dynamic testing cannot easily reveal. It complements rather than replaces execution-based testing.",
      workplaceExample: "A one-hour spec review before a payments project caught a missing rule for partial refunds that no test case would have thought to exercise, because the behaviour simply was not built. Reviews find the defects of omission that dynamic testing, which can only test what exists, will never surface.",
    },
    {
      questionText: "A stakeholder pushes to skip a planned test level entirely to hit a date, saying 'the unit tests are green so integration testing is redundant.' Which ISTQB-aligned point best challenges this?",
      kLevel: "K2",
      options: [
        { text: "Different test levels target different defect types; integration testing finds interface and interaction defects that unit tests by design do not", correct: true, why: "Each test level (component, integration, system, acceptance) has distinct objectives; passing unit tests says nothing about how components behave together." },
        { text: "Integration testing is always more important than unit testing", correct: false, why: "The syllabus does not rank levels as universally more important; each targets different risks." },
        { text: "Green unit tests prove the whole system is defect-free", correct: false, why: "This repeats the false 'absence of defects' claim and ignores what unit tests scope out." },
        { text: "Test levels are interchangeable, so any one is enough", correct: false, why: "Levels are not interchangeable; they have different objectives and reveal different defects." },
      ],
      explanation: "Component (unit) testing checks parts in isolation, often with mocks. Integration testing specifically targets defects in the interfaces and interactions between components and systems, which unit tests deliberately stub out. Skipping a level does not remove its risk; it just moves the discovery of those defects to production. The decision should be framed as accepting integration risk, not as removing redundancy.",
      workplaceExample: "Two teams each shipped perfectly unit-tested services, but their date formats disagreed at the boundary, and every order timestamp was off by a day. No unit test could catch it because the mock spoke the 'correct' format. Integration testing exists precisely for the seams between green components.",
    },
    {
      questionText: "You inherit a flaky end-to-end regression suite: about 8 percent of runs fail intermittently for reasons unrelated to real defects, so the team now ignores red builds. What is the most ISTQB-aligned first step?",
      kLevel: "K3",
      options: [
        { text: "Investigate and stabilise or quarantine the flaky tests so a red result reliably signals a real defect", correct: true, why: "Automated tests are only valuable if their results are trustworthy; unreliable tests undermine the whole feedback loop, so restoring signal integrity comes first." },
        { text: "Delete all failing tests to make the build green", correct: false, why: "Deleting tests removes coverage and hides risk rather than restoring a trustworthy signal." },
        { text: "Tell the team to keep ignoring red builds since most failures are false", correct: false, why: "Habitually ignoring red results means a genuine defect will also be ignored, defeating the purpose of the suite." },
        { text: "Add more end-to-end tests to outnumber the flaky ones", correct: false, why: "Adding volume to an unreliable suite worsens runtime and does nothing to fix trust in the results." },
      ],
      explanation: "A key value of test automation is a fast, reliable feedback signal. When results are non-deterministic, people stop trusting them and real regressions slip through. The disciplined response is to diagnose the flakiness (timing, test data, environment), fix or quarantine the offenders, and restore a state where red means a real problem. Only a trustworthy suite supports automated regression decisions.",
      workplaceExample: "A suite that cried wolf every third run trained a team to click 'rerun' on red, and they cheerfully reran past a genuine login regression into production. We quarantined 12 timing-dependent tests and fixed the waits; within a sprint a red build meant something again. An ignored test is worse than no test, because it costs runtime and gives false comfort.",
    },
    {
      questionText: "Management wants to automate 100 percent of your manual test cases, including exploratory sessions and one-off usability checks, expecting to eliminate manual testing. Which response best reflects the ISTQB view on automation trade-offs?",
      kLevel: "K2",
      options: [
        { text: "Automate stable, repetitive, high-value regression checks, but keep human testers for exploratory, usability, and rapidly changing areas", correct: true, why: "Automation excels at repeatable, stable checks and frees testers for work requiring judgement and exploration; it complements rather than replaces human testing." },
        { text: "Automate everything, since automated tests are always cheaper and better", correct: false, why: "Automation has build and maintenance costs and cannot replicate exploratory or usability judgement, so 'always cheaper and better' is false." },
        { text: "Refuse to automate anything because tests need human judgement", correct: false, why: "This ignores the real benefits of automating stable, repetitive regression checks." },
        { text: "Automate only the newest, most volatile features first", correct: false, why: "Volatile features change constantly, making automation expensive to maintain; stable regression is the better first target." },
      ],
      explanation: "Test automation offers benefits (repeatability, speed, coverage of regression, freeing testers for higher-value work) and costs (initial development, ongoing maintenance, tool and skill needs). It suits stable, repetitive, objectively verifiable checks. Exploratory testing and usability assessment rely on human judgement and are poor automation candidates. The goal is the right mix, not total automation.",
      workplaceExample: "A team automated a screen that changed every sprint and spent more time fixing tests than testing; meanwhile nobody explored the new checkout, which shipped with a baffling error message a script would happily have marked 'pass.' Automate what is stable and repetitive; let humans explore what is new and subjective.",
    },
    {
      questionText: "During a release-readiness meeting, one test suite is at 92 percent pass rate but the 8 percent of failures are all in the payment gateway. Another suite is at 78 percent pass but all failures are trivial cosmetic issues. Which suite's failures should most influence a hold-the-release decision, and why?",
      kLevel: "K3",
      options: [
        { text: "The 92 percent suite, because the failing 8 percent are high-risk payment defects regardless of the headline pass rate", correct: true, why: "Release decisions should weigh the risk and severity of the failing cases, not the raw pass percentage; failing payments are high impact." },
        { text: "The 78 percent suite, because a lower pass rate is always worse", correct: false, why: "Raw pass rate ignores severity; many trivial cosmetic failures may carry far less risk than a few payment failures." },
        { text: "Neither, because any suite above 75 percent passes the release gate", correct: false, why: "A fixed pass-rate threshold with no regard for what failed is not risk-based and can ship critical defects." },
        { text: "Whichever suite ran more test cases, since volume signals thoroughness", correct: false, why: "Case count is not a measure of residual risk or of which failures matter." },
      ],
      explanation: "Exit criteria and go/no-go decisions must be risk-weighted, not driven by a headline pass percentage. A high pass rate hiding critical failures is more dangerous than a lower pass rate whose failures are trivial. Evaluate what failed, its severity and business impact, and the residual risk, then decide. This is the practical face of risk-based testing at the release gate.",
      workplaceExample: "A dashboard glowing '95 percent green' once reassured everyone into shipping, until someone noticed the red 5 percent was the tax calculation for the largest market. Always ask 'what is in the red?' before 'how much is green?' A single critical failure can outweigh a hundred cosmetic passes.",
    },
    {
      questionText: "A new payments feature reuses a shared checkout library. The change is small, but the library is used across many flows. How should regression testing be scoped in an ISTQB-aligned way?",
      kLevel: "K3",
      options: [
        { text: "Run targeted regression across the flows that depend on the shared library, guided by impact analysis and risk", correct: true, why: "Change-related regression testing should cover areas affected by the change; impact analysis identifies which dependent flows carry the most risk and need re-testing." },
        { text: "Re-run the entire test suite for every flow in the product regardless of dependency", correct: false, why: "Full re-runs of unaffected areas waste time; regression should be scoped by what the change can affect and by risk." },
        { text: "Only re-test the exact line changed and nothing else", correct: false, why: "A shared library change can ripple into many flows, so testing only the changed line misses side effects, which is what regression aims to catch." },
        { text: "Skip regression because the code change was small", correct: false, why: "Small changes to widely shared code are precisely where regressions hide; change size does not equal change risk." },
      ],
      explanation: "Regression testing checks that a change has not adversely affected previously working functionality. Impact analysis determines which parts of the system the change could affect, so regression can be scoped to dependent, higher-risk areas rather than either everything or nothing. This balances confidence against effort, which matters when suites are large and time is short.",
      workplaceExample: "A one-line tweak to a shared currency-formatting helper broke every invoice, receipt, and export in the product, none of which the author thought to test. A dependency map turned a scary 'test everything' into a focused list of the flows that actually consume that helper. Small diff, wide blast radius: regression follows dependencies, not line counts.",
    },
    {
      questionText: "A junior tester logs a defect as: 'Login broken. Doesn't work.' The developer bounces it back as not reproducible. Which ISTQB-aligned improvement to defect reporting best addresses this?",
      kLevel: "K2",
      options: [
        { text: "Provide clear steps to reproduce, expected vs actual results, environment, and severity/priority", correct: true, why: "A useful defect report includes reproduction steps, expected and actual behaviour, environment details, and severity/priority so it can be understood, reproduced, and prioritised." },
        { text: "Escalate to the manager so the developer is forced to accept it", correct: false, why: "Escalation does not supply the information the developer needs to reproduce and fix the defect." },
        { text: "Re-log the same wording but mark it critical to get attention", correct: false, why: "Inflating priority without evidence damages trust and still lacks the details needed to act." },
        { text: "Attach only a screenshot with no text", correct: false, why: "A screenshot alone rarely conveys steps, environment, or expected behaviour needed to reproduce the issue." },
      ],
      explanation: "Effective defect management depends on reports that let others reproduce and assess the issue: a clear summary, precise steps to reproduce, expected versus actual results, the environment and build, and severity and priority. Vague reports waste cycles bouncing between tester and developer. Good reports shorten the fix loop and support objective triage.",
      workplaceExample: "Rewriting 'login broken' as 'On build 4.2, Chrome 120, enter valid email + wrong password, click Sign In: expected inline error, actual blank page and 500 in console' turned a rejected ticket into a fix within the hour. The report is the interface between finding a defect and getting it fixed; ambiguity there taxes everyone.",
    },
    {
      questionText: "The team has met its agreed exit criteria (risk coverage targets hit, no open high-severity defects, test tasks complete), but a nervous stakeholder wants 'just a few more days of testing to be safe.' What does the ISTQB test process say about deciding to stop?",
      kLevel: "K2",
      options: [
        { text: "Completion is judged against defined exit criteria and residual risk, not against an open-ended feeling of safety", correct: true, why: "Test completion (the exit criteria) provides an objective, agreed basis for stopping; testing can never be exhaustive, so open-ended 'more to be safe' has no defined end." },
        { text: "Keep testing indefinitely until the stakeholder feels comfortable", correct: false, why: "Comfort is subjective and unbounded; exhaustive testing is impossible, so there is no natural end to 'more to be safe.'" },
        { text: "Stop the moment the calendar date arrives, ignoring criteria", correct: false, why: "A date alone, without checking exit criteria and residual risk, is not a sound completion decision." },
        { text: "Continue only if new defects are found, otherwise stop immediately", correct: false, why: "The stop decision is based on exit criteria and residual risk, not solely on whether the last run found a defect." },
      ],
      explanation: "The test process defines exit or completion criteria (for example coverage of identified risks, defect thresholds, and completion of planned test tasks) that provide an objective basis for deciding when testing is done. Because exhaustive testing is impossible, there is no state of certainty; the criteria and the residual-risk picture are what let you stop responsibly and communicate the decision.",
      workplaceExample: "When a stakeholder asks for 'a bit more testing to be safe,' the productive reply is 'here are the exit criteria we agreed and where we stand; adding days targets which specific risk?' Often there is no named risk, just anxiety. Exit criteria turn an emotional debate into a factual, decidable one.",
    },
    {
      questionText: "Analysis of last quarter's defects shows 70 percent came from two of the twelve modules: the reporting engine and the import parser. With limited time this release, how should this shape test planning?",
      kLevel: "K3",
      options: [
        { text: "Concentrate additional test effort on the reporting engine and import parser, applying the defect-clustering insight", correct: true, why: "Defects tend to cluster; a small number of modules often contain most defects, so focusing effort there is an efficient, risk-based use of limited time." },
        { text: "Spread effort evenly across all twelve modules to be fair", correct: false, why: "Even spreading ignores the evidence that risk is concentrated and dilutes effort away from the modules most likely to fail." },
        { text: "Ignore those two modules since they were already tested last quarter", correct: false, why: "Past testing does not immunise a defect-prone module; clustering suggests it will likely keep producing defects." },
        { text: "Test only the modules with zero past defects to confirm they stay clean", correct: false, why: "This inverts the risk, spending scarce time where defects are least likely and starving the high-risk modules." },
      ],
      explanation: "The defect-clustering principle observes that a small number of modules usually contain most of the defects found before release, or are responsible for most operational failures. Using historical defect data to focus testing on those clusters is a practical application of risk-based testing and makes limited effort go furthest. Pair it with the pesticide paradox by varying the tests you run there.",
      workplaceExample: "A defect heat-map showed the import parser lit up red quarter after quarter while eight modules stayed cold. Doubling down on the parser (with fresh test data, not the same old cases) caught three more bugs before release. Past defect density is one of the best predictors of where the next defect lives.",
    },
    {
      questionText: "A developer argues that automated checks give '100 percent confidence' because code coverage is 95 percent. As a tester, which ISTQB point most accurately tempers this claim?",
      kLevel: "K2",
      options: [
        { text: "High coverage measures which code was exercised, not whether the tests assert correct behaviour or find all defect types", correct: true, why: "Coverage shows structural exercise of code; it does not guarantee meaningful assertions, correct expected results, or that non-functional and requirement defects are caught, so it cannot equal 100 percent confidence." },
        { text: "Coverage of 95 percent proves the software is defect-free", correct: false, why: "This again violates the absence-of-defects principle and overstates what a coverage number means." },
        { text: "Coverage is meaningless and should be ignored entirely", correct: false, why: "Coverage is a useful metric for gaps; the point is not to over-interpret it, not to discard it." },
        { text: "Only manual testing provides any real confidence", correct: false, why: "Automated tests do provide confidence; the issue is interpreting coverage as total assurance." },
      ],
      explanation: "Coverage metrics tell you what proportion of a coverage item (statements, branches) was exercised, which is valuable for finding untested gaps. But exercising code is not the same as verifying it behaves correctly, and coverage says nothing about missing requirements, usability, or performance. High coverage plus weak assertions can pass while defects remain. It informs confidence; it does not equal it.",
      workplaceExample: "A test that calls every line but asserts nothing beyond 'no exception thrown' can hit 95 percent coverage and still miss that the total is calculated wrong. Coverage answers 'did we run this code?' not 'did we check it does the right thing?' Treat the number as a gap-finder, not a guarantee.",
    },
    {
      questionText: "A tester relies on gut feel to probe a new API, quickly finding crashes on empty payloads and huge inputs that the scripted tests missed. Which ISTQB technique is being used, and how should it fit the overall approach?",
      kLevel: "K2",
      options: [
        { text: "Experience-based testing (such as error guessing and exploratory testing), used to complement, not replace, systematic techniques", correct: true, why: "Experience-based techniques draw on the tester's knowledge to find defects that systematic cases miss; they add value alongside specification-based techniques rather than substituting for them." },
        { text: "Decision table testing, since the tester considered combinations", correct: false, why: "The tester used intuition and experience, not a structured enumeration of condition combinations." },
        { text: "This is not a real technique and should not be counted as testing", correct: false, why: "Experience-based testing is a recognised category in the syllabus with genuine defect-finding value." },
        { text: "Boundary value analysis, because empty and huge inputs are boundaries", correct: false, why: "BVA is a systematic specification-based technique; here the tester relied on experience and guessing rather than deriving boundaries from a spec." },
      ],
      explanation: "Experience-based techniques, including error guessing and exploratory testing, use the tester's skill, intuition, and knowledge of likely failure points to design and run tests, often uncovering defects that formal techniques overlook. They are strongest as a complement to black-box and white-box techniques, adding adaptive, human insight on top of systematic coverage.",
      workplaceExample: "An experienced tester 'just knows' to send an emoji into a name field, paste 10,000 characters, or double-click submit, and these hunches catch defects no acceptance criterion listed. Pair that instinct with systematic boundary and decision-table cases and you get both breadth and depth.",
    },
    {
      questionText: "Your team practises testing throughout the sprint rather than in a phase at the end, and testers review stories during refinement. A new manager calls this 'wasteful' and wants a single test phase before each release. Which ISTQB idea best defends the current approach?",
      kLevel: "K2",
      options: [
        { text: "Early and continuous testing lowers the cost of defects by catching them closer to their introduction", correct: true, why: "The early testing (shift-left) principle holds that starting test activities early, including static reviews, reduces rework because defects cost more the later they are found." },
        { text: "Testing at the end is always cheaper because it happens once", correct: false, why: "A single late phase concentrates defect discovery when fixes are most expensive, contradicting the early testing principle." },
        { text: "Continuous testing removes the need for any release testing", correct: false, why: "Early testing does not eliminate later test activities; it complements them by reducing the defects that reach them." },
        { text: "The timing of testing makes no difference to defect cost", correct: false, why: "The cost of fixing a defect rises the later it is found, so timing matters significantly." },
      ],
      explanation: "The principle of early testing states that test activities should start as early as possible in the lifecycle and continue throughout, because the cost of finding and fixing defects grows the later they are discovered. Reviewing stories in refinement and testing continuously catches defects near their source. A single end phase batches discovery into the most expensive window.",
      workplaceExample: "One team measured it: bugs caught in refinement cost minutes, bugs caught in the end-phase cost days of rework and re-testing, and bugs caught in production cost a hotfix plus a customer apology. 'Test at the end' is not one cheap phase; it is a pile of expensive late fixes wearing a trench coat.",
    },
    {
      questionText: "A stakeholder says: 'We tested this thoroughly last release and it was fine, so we can reuse those exact results and skip testing the changed areas this time.' Which combination of ISTQB principles best explains why this is unsafe?",
      kLevel: "K3",
      options: [
        { text: "Testing is context dependent and defects can be introduced by changes, so prior results do not cover new or modified behaviour", correct: true, why: "Testing depends on context (including the current build and changes), and any change can introduce regressions; last release's results say nothing about this release's changes." },
        { text: "Exhaustive testing is possible, so last time's tests already covered everything", correct: false, why: "Exhaustive testing is impossible, and even if prior testing were thorough it did not exercise the new changes." },
        { text: "The pesticide paradox means old results are always still valid", correct: false, why: "The paradox says repeating the same tests finds fewer new defects; it does not validate reusing old results for changed code." },
        { text: "Testing shows the absence of defects, so a clean past result proves current safety", correct: false, why: "This misstates the principle; testing shows presence, not absence, of defects, and cannot certify unchanged safety across a new build." },
      ],
      explanation: "Testing is context dependent: results are tied to a specific build, configuration, and set of risks. When code changes, regression risk is introduced, so previously passing results do not certify the modified system. The safe response is change-based regression testing scoped by impact analysis. Reusing old results wholesale ignores both the context principle and the reality of regression.",
      workplaceExample: "A team once shipped by re-attaching last quarter's green test report, having 'only refactored the database layer.' The refactor broke sorting on every list in the app. Test evidence has a shelf life measured in builds; a change resets the clock on the areas it touches.",
    },
    {
      questionText: "You must choose a technique to test a discount rule: orders over 500 get 10 percent off, over 1000 get 20 percent off, and loyalty members get an extra 5 percent, with the tiers not stacking beyond the highest. Which approach gives the most reliable coverage?",
      kLevel: "K3",
      options: [
        { text: "Decision table testing for the discount combinations, plus boundary value analysis at 500 and 1000", correct: true, why: "The outcome depends on combinations of conditions (amount tier and membership), suiting a decision table, while the tier thresholds are boundaries where off-by-one defects appear." },
        { text: "Boundary value analysis alone at 500 and 1000", correct: false, why: "BVA covers the thresholds but not the combinations with loyalty membership and the non-stacking rule." },
        { text: "State transition testing of the discount states", correct: false, why: "There is no sequence of states over time here, just conditions evaluated to select a discount." },
        { text: "Error guessing based on past discount bugs", correct: false, why: "Error guessing may help but cannot systematically cover the rule combinations and boundary thresholds on its own." },
      ],
      explanation: "When behaviour depends on combinations of conditions, a decision table captures each condition set and its expected discount, exposing the non-stacking rule and any missing combination. Boundary value analysis then verifies the exact tier thresholds (499/500, 1000/1001) where comparison-operator defects cluster. Combining specification-based techniques covers both the logic and the edges, which either alone would miss.",
      workplaceExample: "A promotions engine once stacked a 20 percent tier with a 20 percent coupon to give 40 percent off, refunding money the business never intended, because nobody tabulated the 'do these combine?' rules. A decision table forces those questions before launch, and boundary tests catch the 'over 1000' that quietly excluded exactly 1000.",
    },
    {
      questionText: "A tester says: 'I found zero defects in this feature, so my testing was low value this sprint.' Which ISTQB-aligned reframing is most accurate?",
      kLevel: "K2",
      options: [
        { text: "Finding no defects is a valid result; testing also builds confidence and evidence, provided the tests were well designed for the risks", correct: true, why: "Testing has multiple objectives including gaining confidence and providing information for decisions; a well-designed test run that finds nothing still reduces uncertainty about risk." },
        { text: "Zero defects proves the feature is defect-free and testing succeeded fully", correct: false, why: "This overstates the result; testing shows presence, not absence, of defects, so zero found does not equal zero present." },
        { text: "Testing that finds no defects was wasted and should not be reported", correct: false, why: "It still provides information and confidence about the tested risks, which is a legitimate objective of testing." },
        { text: "The tester must have missed defects, so the run is invalid", correct: false, why: "No defects found does not automatically mean poor testing; it depends on whether the tests targeted the relevant risks." },
      ],
      explanation: "Testing objectives include finding defects but also evaluating quality, building confidence, and providing information to support decisions. A well-designed test session that exercises the real risks and finds nothing genuinely lowers uncertainty. The caveat is the design: if the tests were weak, 'zero found' is uninformative. Value comes from covering the risks, not from a body count of defects.",
      workplaceExample: "Two testers report 'zero defects': one ran three trivial happy-path clicks, the other ran boundary, negative, and error-path cases across the risky flows. Same defect count, very different value. Judge a test run by the risk it covered, not only by the bugs it happened to find.",
    },
    {
      questionText: "A team wants to buy a test automation tool. A vendor demo dazzles everyone, and a manager wants to purchase immediately and automate the whole suite next week. What does the ISTQB guidance on introducing a tool recommend?",
      kLevel: "K2",
      options: [
        { text: "Run a proof of concept or pilot to evaluate fit against real needs before rolling out, and account for maintenance and skills", correct: true, why: "The syllabus advises assessing organisational maturity and needs, piloting the tool to evaluate it against reality, and recognising ongoing costs such as maintenance and training, rather than buying on a demo." },
        { text: "Buy immediately, because a polished vendor demo proves the tool will work in your context", correct: false, why: "A demo runs in an ideal setting; tool success is context dependent, so a pilot against your own needs is required." },
        { text: "Automate the entire suite in the first week to maximise return", correct: false, why: "A big-bang rollout ignores the learning curve, maintenance burden, and the need to prove value incrementally." },
        { text: "Choose whichever tool is cheapest, since all automation tools are equivalent", correct: false, why: "Tools differ in fit, integration, and maintainability; price alone ignores whether the tool meets the actual need." },
      ],
      explanation: "Introducing a tool into an organisation is a project in itself. The syllabus recommends assessing the organisation's maturity and needs, evaluating the tool against those needs (often via a proof of concept or pilot), planning for the learning curve, and budgeting for ongoing maintenance and support. Success factors are about fit and adoption, not the polish of a sales demo.",
      workplaceExample: "A company bought a flashy record-and-playback tool on the strength of a demo; six months later the brittle scripts cost more to maintain than the manual tests they replaced, and it was shelved. A two-week pilot on a real, representative flow would have exposed that before the purchase order. Pilot first, buy second.",
    },
  ],
};
