export default {
  courseSlug: "istqb-foundation-masterclass",
  moduleNumber: 3,
  syllabusTopic: "Static Testing",
  questions: [
    {
      kLevel: "K1",
      questionText: "Which of the following BEST describes static testing?",
      options: [
        { text: "Examining work products such as requirements, code, and design without executing them", correct: true, why: "Static testing evaluates work products manually or with tools but never runs the software under test." },
        { text: "Running the software with test data and comparing actual to expected results", correct: false, why: "That describes dynamic testing, where the code is executed." },
        { text: "Measuring code coverage during test execution", correct: false, why: "Coverage measurement requires executing the code, so it is a dynamic activity." },
        { text: "Deploying the build to a production-like environment for a smoke test", correct: false, why: "A smoke test executes the software, making it dynamic testing." },
      ],
      explanation: "Static testing assesses work products through examination (reviews) or tool-based analysis without executing the code. Dynamic testing, by contrast, requires running the software.",
      workplaceExample: "Before any code is written, a business analyst has the team review the requirements document to catch ambiguities early.",
    },
    {
      kLevel: "K1",
      questionText: "Which work product CANNOT normally be examined by static testing?",
      options: [
        { text: "The runtime memory-leak behavior of a running application", correct: true, why: "Runtime behavior only appears while the software executes, so it requires dynamic testing." },
        { text: "A requirements specification document", correct: false, why: "Requirements are a classic candidate for static review." },
        { text: "Source code and its comments", correct: false, why: "Source code can be reviewed and statically analyzed without execution." },
        { text: "Test cases and test scripts", correct: false, why: "Test cases are work products that can and should be reviewed statically." },
      ],
      explanation: "Almost any readable work product (requirements, design, code, models, test cases, user guides, contracts) can be statically tested. What cannot is behavior that only emerges during execution, such as memory leaks, performance, or timing.",
      workplaceExample: "A team reviews their Gherkin feature files for clarity, but must actually run the app to see a memory leak surface after an hour of use.",
    },
    {
      kLevel: "K2",
      questionText: "Why does static testing often provide a better return on investment than finding the same defects later?",
      options: [
        { text: "Defects found early are cheaper to fix because they have not yet propagated into downstream work products", correct: true, why: "Early removal avoids the compounding cost of a defect that flows into design, code, and tests before discovery." },
        { text: "Static testing always finds more defects than dynamic testing", correct: false, why: "Neither technique universally finds more; they find different kinds of defects." },
        { text: "Static testing eliminates the need for any dynamic testing", correct: false, why: "The two are complementary; static testing does not replace execution-based testing." },
        { text: "Static testing removes the need to write test cases", correct: false, why: "Test cases are still needed; in fact they are themselves reviewed statically." },
      ],
      explanation: "The cost of a defect rises the longer it stays undetected. Static testing can find defects in requirements before code exists, preventing expensive rework downstream.",
      workplaceExample: "A reviewer spots a contradictory acceptance criterion in a story, saving the team from building and later re-building a feature the wrong way.",
    },
    {
      kLevel: "K1",
      questionText: "Which of the following is a typical benefit of static testing?",
      options: [
        { text: "Detecting and correcting defects earlier and improving communication among stakeholders", correct: true, why: "Early defect detection and better shared understanding are recognized benefits of static testing." },
        { text: "Measuring the actual response time of the system under load", correct: false, why: "Response time under load is measured by dynamic performance testing." },
        { text: "Confirming that the deployed system behaves correctly for end users", correct: false, why: "Confirming runtime behavior requires executing the system." },
        { text: "Producing code coverage metrics for the test suite", correct: false, why: "Coverage metrics come from executing the code, a dynamic activity." },
      ],
      explanation: "Static testing benefits include early defect detection, reduced development cost and time, improved product quality, and better communication and shared understanding among participants.",
      workplaceExample: "During a design review, developers and testers reach a shared understanding of an interface, avoiding integration surprises later.",
    },
    {
      kLevel: "K2",
      questionText: "A defect that is NOT easily found by dynamic testing but often surfaces in static testing is:",
      options: [
        { text: "Unreachable or dead code and deviations from coding standards", correct: true, why: "Dead code may never execute, so dynamic tests miss it, while a static review or analyzer flags it directly." },
        { text: "A performance bottleneck under heavy concurrent load", correct: false, why: "Concurrency and load issues generally require executing the system." },
        { text: "A crash triggered by a specific runtime input value", correct: false, why: "A runtime crash on specific input is found by executing the software." },
        { text: "Incorrect calculation results at run time", correct: false, why: "Wrong runtime results are typically exposed by dynamic testing." },
      ],
      explanation: "Static testing can find defects that are hard or impossible to detect dynamically, such as unreachable code, coding standard violations, and inconsistencies, because they may never be exercised at run time.",
      workplaceExample: "A static analysis tool flags a block of code after a return statement that can never run, which no functional test would ever have reached.",
    },
    {
      kLevel: "K2",
      questionText: "How are static and dynamic testing BEST characterized in relation to each other?",
      options: [
        { text: "They are complementary, finding different types of defects and together improving quality", correct: true, why: "Each targets defects the other tends to miss, so using both gives the broadest coverage." },
        { text: "Dynamic testing makes static testing unnecessary", correct: false, why: "Dynamic testing cannot find requirements ambiguities or dead code as effectively as static testing." },
        { text: "They find exactly the same defects, so only one is needed", correct: false, why: "They find different kinds of defects, so they are not interchangeable." },
        { text: "Static testing must always be performed after dynamic testing", correct: false, why: "Static testing is typically done earlier, often before any code is executable." },
      ],
      explanation: "Static and dynamic testing share the goal of supporting quality but are complementary. Static testing finds defects directly in work products; dynamic testing observes failures caused by defects during execution.",
      workplaceExample: "A team reviews requirements statically to remove ambiguity, then runs functional tests dynamically to confirm the built feature behaves as agreed.",
    },
    {
      kLevel: "K2",
      questionText: "Which statement about the relationship between static and dynamic testing is TRUE?",
      options: [
        { text: "Static testing finds defects directly, while dynamic testing observes failures caused by defects", correct: true, why: "Static testing locates the defect itself in the work product; dynamic testing sees a failure and the defect must then be traced." },
        { text: "Both static and dynamic testing require executing the software", correct: false, why: "Only dynamic testing executes the software." },
        { text: "Static testing can only be done manually, never with tools", correct: false, why: "Static analysis tools support static testing without human execution of code." },
        { text: "Dynamic testing directly identifies the exact line of code that is defective", correct: false, why: "Dynamic testing reveals a failure; locating the causing defect requires further debugging." },
      ],
      explanation: "In static testing the defect is identified directly. In dynamic testing a failure is caused by a defect when the code runs, and additional analysis is needed to find the underlying defect.",
      workplaceExample: "A reviewer points at the exact faulty condition in the code, whereas a failing test only shows the wrong output on screen until a developer debugs it.",
    },
    {
      kLevel: "K1",
      questionText: "In the context of static testing, what is the primary purpose of feedback from reviews?",
      options: [
        { text: "To provide early, frequent feedback on quality problems so they can be addressed promptly", correct: true, why: "Frequent early feedback is a core value of static testing, enabling fast correction and process improvement." },
        { text: "To assign blame for defects to individual authors", correct: false, why: "Reviews focus on the work product, not on blaming people." },
        { text: "To replace the need for stakeholder communication", correct: false, why: "Feedback improves communication rather than removing the need for it." },
        { text: "To measure the execution speed of the software", correct: false, why: "Execution speed is unrelated to static feedback and requires dynamic testing." },
      ],
      explanation: "Static testing enables early and frequent feedback, allowing quality problems to be identified and corrected quickly and helping the team learn and improve its process.",
      workplaceExample: "Frequent pull-request reviews give developers quick feedback, so recurring mistakes get corrected before they become team-wide habits.",
    },
    {
      kLevel: "K2",
      questionText: "Beyond finding defects, which of the following is an additional value provided by the review process?",
      options: [
        { text: "Building shared understanding and increasing participant knowledge of the work product", correct: true, why: "Reviews spread knowledge and create a common understanding among stakeholders, a recognized benefit beyond defect finding." },
        { text: "Guaranteeing that no defects remain in the product", correct: false, why: "No testing activity can guarantee the absence of defects." },
        { text: "Automatically fixing the defects it identifies", correct: false, why: "Reviews identify issues; fixing is a separate activity performed by the author." },
        { text: "Removing the need for a test plan", correct: false, why: "Reviews do not eliminate planning; test planning remains necessary." },
      ],
      explanation: "Reviews add value by evaluating quality, building consensus, improving communication, and increasing shared understanding, in addition to detecting and correcting defects early.",
      workplaceExample: "A walkthrough of a new module brings junior developers up to speed on the architecture while also surfacing a design flaw.",
    },
    {
      kLevel: "K1",
      questionText: "Which sequence correctly lists the main activities of the review process according to the ISTQB syllabus?",
      options: [
        { text: "Planning; review initiation; individual review; communication and analysis; fixing and reporting", correct: true, why: "This is the five-activity sequence defined for the generic review process in the syllabus." },
        { text: "Planning; execution; debugging; regression; closure", correct: false, why: "These are execution-oriented steps, not the review process activities." },
        { text: "Initiation; coding; testing; deployment; monitoring", correct: false, why: "This describes a development lifecycle, not the review activities." },
        { text: "Design; build; integrate; verify; validate", correct: false, why: "These are general engineering phases, not the defined review activities." },
      ],
      explanation: "The review process consists of planning, review initiation, individual review, communication and analysis, and fixing and reporting.",
      workplaceExample: "A review leader schedules the review (planning), sends out the document and objectives (initiation), lets reviewers work alone, then holds a meeting to analyze findings before the author fixes them.",
    },
    {
      kLevel: "K2",
      questionText: "During which review activity does each reviewer individually assess the work product and note potential defects, questions, and comments?",
      options: [
        { text: "Individual review", correct: true, why: "In individual review each reviewer examines the work product on their own and records findings." },
        { text: "Planning", correct: false, why: "Planning defines scope, effort, and criteria before any reviewing happens." },
        { text: "Review initiation", correct: false, why: "Initiation distributes the work product and ensures reviewers understand the objectives." },
        { text: "Fixing and reporting", correct: false, why: "Fixing and reporting happens after analysis, when the author corrects agreed defects." },
      ],
      explanation: "In the individual review activity, each reviewer examines the work product independently and logs anomalies, recommendations, and questions.",
      workplaceExample: "Each team member reads the design spec alone and adds inline comments before the group meeting.",
    },
    {
      kLevel: "K2",
      questionText: "What primarily happens during the communication and analysis activity of a review?",
      options: [
        { text: "Findings are communicated and analyzed to decide their status, ownership, and whether they are true defects", correct: true, why: "This activity consolidates findings, discusses them, and classifies each as a defect or not with an owner and status." },
        { text: "The scope and entry criteria of the review are defined", correct: false, why: "Scope and criteria are set during planning." },
        { text: "The author corrects the confirmed defects", correct: false, why: "Correction belongs to the fixing and reporting activity." },
        { text: "Reviewers first receive the work product to examine", correct: false, why: "Distribution of the work product occurs during review initiation." },
      ],
      explanation: "In communication and analysis, the anomalies found are discussed and analyzed. Each is decided on: its status, owner, and required actions, and whether it is a genuine defect.",
      workplaceExample: "In the review meeting, the team debates whether a flagged item is a real defect or a misunderstanding, then assigns each confirmed defect to the author.",
    },
    {
      kLevel: "K2",
      questionText: "In the fixing and reporting activity, who is typically responsible for fixing the identified defects?",
      options: [
        { text: "The author of the work product", correct: true, why: "The author owns the work product and makes the agreed corrections." },
        { text: "The scribe who recorded the findings", correct: false, why: "The scribe documents findings but does not correct the work product." },
        { text: "The facilitator who ran the meeting", correct: false, why: "The facilitator manages the review process, not the fixing of the product." },
        { text: "The manager who requested the review", correct: false, why: "Management decides on execution and resources but does not fix the defects." },
      ],
      explanation: "During fixing and reporting, defects that require changes are fixed by the author. Review metrics are recorded and exit criteria are checked.",
      workplaceExample: "After the review meeting, the developer who wrote the module updates the code to resolve each confirmed defect and reports completion.",
    },
    {
      kLevel: "K1",
      questionText: "Who is responsible for creating the work product being reviewed and for fixing defects found in it?",
      options: [
        { text: "The author", correct: true, why: "The author creates the work product and is responsible for correcting its defects." },
        { text: "The scribe", correct: false, why: "The scribe records information during the review but does not own the work product." },
        { text: "The reviewer", correct: false, why: "Reviewers identify potential defects but do not fix the work product." },
        { text: "The manager", correct: false, why: "The manager manages resources and decisions but is not the author." },
      ],
      explanation: "The author is the person who created the work product under review and is responsible for fixing the defects found in it.",
      workplaceExample: "The developer who wrote the API spec attends the review and takes on the corrections identified by the reviewers.",
    },
    {
      kLevel: "K1",
      questionText: "Which review role is responsible for running the review meeting, mediating between people, and ensuring effective conduct of the review?",
      options: [
        { text: "The facilitator (moderator)", correct: true, why: "The facilitator ensures the review runs effectively, mediates differing opinions, and often is the pivot on which the review succeeds." },
        { text: "The author", correct: false, why: "The author owns the work product but does not run or mediate the meeting." },
        { text: "The scribe", correct: false, why: "The scribe records findings rather than facilitating the discussion." },
        { text: "The reviewer", correct: false, why: "Reviewers examine the product; they do not mediate the meeting." },
      ],
      explanation: "The facilitator, sometimes called the moderator, ensures the effective running of review meetings, mediates between different viewpoints, and is often key to a review's success.",
      workplaceExample: "When two developers argue over a flagged issue in an inspection, the moderator keeps the discussion productive and on schedule.",
    },
    {
      kLevel: "K1",
      questionText: "What is the main responsibility of the review leader?",
      options: [
        { text: "Taking overall responsibility for the review, deciding who is involved, and organizing when and where it takes place", correct: true, why: "The review leader owns the review overall, selecting participants and organizing the logistics." },
        { text: "Recording all defects and decisions during the meeting", correct: false, why: "That is the scribe's responsibility." },
        { text: "Creating the work product under review", correct: false, why: "Creating the work product is the author's role." },
        { text: "Deciding on the execution of reviews and allocating budget", correct: false, why: "Broad decisions on review execution and resources belong to management." },
      ],
      explanation: "The review leader takes overall responsibility for the review, deciding who will be involved and organizing the timing and location of the review.",
      workplaceExample: "The test lead decides which stakeholders should attend the requirements inspection and books the room and time slot.",
    },
    {
      kLevel: "K1",
      questionText: "Which role records the anomalies, decisions, and new defects identified during a review meeting?",
      options: [
        { text: "The scribe (recorder)", correct: true, why: "The scribe collates and records anomalies and decisions from the individual reviews and the meeting." },
        { text: "The facilitator", correct: false, why: "The facilitator runs the meeting rather than recording the details." },
        { text: "The author", correct: false, why: "The author owns the product and fixes defects but does not act as recorder." },
        { text: "The review leader", correct: false, why: "The review leader organizes the review overall, not the moment-to-moment recording." },
      ],
      explanation: "The scribe, or recorder, collates and records anomalies from the individual reviews and documents the decisions and new anomalies raised during the review meeting.",
      workplaceExample: "One team member is assigned to log every issue and its agreed status in the tracker while the group discusses the document.",
    },
    {
      kLevel: "K2",
      questionText: "Which of the following BEST describes the responsibility of management with respect to reviews?",
      options: [
        { text: "Deciding on the execution of reviews, allocating time in schedules, and determining whether review objectives were met", correct: true, why: "Management makes go decisions on reviews, provides schedule and resources, and evaluates outcomes against objectives." },
        { text: "Recording each defect raised during the review meeting", correct: false, why: "Recording defects is the scribe's job, not management's." },
        { text: "Examining the work product line by line to find defects", correct: false, why: "Detailed examination is the reviewers' responsibility." },
        { text: "Fixing the defects found in the work product", correct: false, why: "Fixing defects is the author's responsibility." },
      ],
      explanation: "Management is responsible for review planning decisions such as whether reviews happen, allocating time in project schedules, and determining whether the review objectives have been achieved.",
      workplaceExample: "A project manager reserves two hours each sprint for design reviews and later checks the review metrics to confirm the effort is paying off.",
    },
    {
      kLevel: "K1",
      questionText: "Which review type is the LEAST formal, has no defined process, and is often not documented?",
      options: [
        { text: "Informal review", correct: true, why: "The informal review has no formal process and may leave no documented results, making it the least formal type." },
        { text: "Inspection", correct: false, why: "Inspection is the most formal review type, driven by rules and metrics." },
        { text: "Technical review", correct: false, why: "A technical review follows a defined process and involves technical experts." },
        { text: "Walkthrough", correct: false, why: "A walkthrough follows a process led by the author and can be quite structured." },
      ],
      explanation: "An informal review does not follow a defined process and does not require a formal documented output. Its main purpose is detecting potential defects cheaply and quickly.",
      workplaceExample: "A developer asks a colleague to glance over a small function at their desk, with no template or logged results.",
    },
    {
      kLevel: "K2",
      questionText: "Which review type is characterized by being led by the author, who may guide participants through the work product, and can include scenarios or dry runs?",
      options: [
        { text: "Walkthrough", correct: true, why: "In a walkthrough the author typically leads participants through the work product, often using scenarios or dry runs." },
        { text: "Inspection", correct: false, why: "Inspection is led by a trained moderator, not the author, and follows formal rules." },
        { text: "Informal review", correct: false, why: "An informal review has no defined leadership or process." },
        { text: "Technical review", correct: false, why: "A technical review is led by a moderator or facilitator and focuses on technical decisions by peers." },
      ],
      explanation: "A walkthrough is led by the author of the work product and can serve many purposes such as evaluating quality, building understanding, and educating participants, often using scenarios and dry runs.",
      workplaceExample: "The author of a new algorithm walks the team through it step by step using a worked example so everyone understands the logic and can spot issues.",
    },
    {
      kLevel: "K2",
      questionText: "Which statement BEST distinguishes a technical review from other review types?",
      options: [
        { text: "It is performed by technically qualified reviewers and led by a moderator to reach consensus on technical decisions", correct: true, why: "Technical reviews rely on peers with technical expertise and a moderator, aiming to make technical decisions and reach consensus." },
        { text: "It is always undocumented and requires no preparation", correct: false, why: "That describes an informal review, not a technical review." },
        { text: "It is led by the author who walks participants through the product", correct: false, why: "Author-led walkthroughs describe a walkthrough, not a technical review." },
        { text: "It is the most formal type, driven by strict entry and exit criteria and metrics", correct: false, why: "The most formal, metric-driven type is the inspection." },
      ],
      explanation: "A technical review is conducted by technically qualified reviewers and led by a moderator or facilitator. Its objectives include gaining consensus and making technical decisions, and it may detect defects.",
      workplaceExample: "Senior engineers meet to evaluate two proposed architectures and reach consensus on which technical approach to adopt.",
    },
    {
      kLevel: "K1",
      questionText: "Which review type is the MOST formal, follows a defined process with rules and checklists, and collects metrics?",
      options: [
        { text: "Inspection", correct: true, why: "Inspection is the most formal review type, following a defined process with roles, rules, checklists, and metrics." },
        { text: "Walkthrough", correct: false, why: "A walkthrough is less formal and led by the author." },
        { text: "Informal review", correct: false, why: "An informal review has no defined process at all." },
        { text: "Technical review", correct: false, why: "A technical review is formal but less rigorous than an inspection and does not require the full metric collection." },
      ],
      explanation: "An inspection is the most formal type of review. It follows a complete, defined process, uses roles such as moderator and scribe, applies rules and checklists, and gathers metrics to support process improvement.",
      workplaceExample: "For a safety-critical requirements document, the team runs a full inspection with a trained moderator, entry and exit criteria, and logged defect metrics.",
    },
    {
      kLevel: "K2",
      questionText: "Which of the following is a recognized success factor for reviews?",
      options: [
        { text: "Choosing the review type and techniques suitable for the objectives, type of work product, and participants", correct: true, why: "Fitting the review approach to the objectives and context is an organizational success factor for reviews." },
        { text: "Ensuring reviews always find the maximum possible number of defects regardless of effort", correct: false, why: "Reviews should be efficient and purpose-driven, not maximize defect counts at any cost." },
        { text: "Focusing feedback on the personality of the author", correct: false, why: "Reviews should focus on the work product, not on the person, to keep them constructive." },
        { text: "Keeping the review objectives secret from participants", correct: false, why: "Clear, shared objectives are needed; hiding them undermines the review." },
      ],
      explanation: "Success factors include having clear objectives, choosing the appropriate review type, conducting reviews on small chunks, giving feedback constructively, and recognizing the effort as part of process improvement.",
      workplaceExample: "A lead picks a lightweight walkthrough for a small script but a full inspection for a critical interface spec, matching the review type to the risk.",
    },
    {
      kLevel: "K2",
      questionText: "Which people-related factor most helps reviews succeed?",
      options: [
        { text: "Conducting reviews in an atmosphere of trust, with results not used to evaluate the participants", correct: true, why: "A blame-free, trusting atmosphere encourages honest participation and keeps focus on the work product." },
        { text: "Making the author defend every comment to prove competence", correct: false, why: "Defensiveness discourages open discussion and undermines the review's value." },
        { text: "Using review findings in individual performance appraisals", correct: false, why: "Using results to evaluate people damages trust and discourages participation." },
        { text: "Excluding testers so developers are not criticized", correct: false, why: "Excluding relevant stakeholders reduces the range of defects that can be found." },
      ],
      explanation: "People-related success factors include participants with adequate knowledge, an atmosphere of trust, avoiding using results to evaluate participants, and constructive handling of comments and defects.",
      workplaceExample: "A team agrees that review comments never appear in appraisals, so members raise concerns freely and the reviews find more real issues.",
    },
    {
      kLevel: "K3",
      questionText: "A team must review a large, safety-critical requirements specification that will drive contracts and downstream design, and management wants defect metrics to improve the process. Which review type should they apply?",
      options: [
        { text: "Inspection, because it provides the most formal, metric-driven process suited to a critical, high-impact document", correct: true, why: "The high risk, contractual impact, and need for metrics point to the most formal type, an inspection." },
        { text: "Informal review, because it is quick and requires no documentation", correct: false, why: "An informal review lacks the rigor and metrics needed for a safety-critical, contract-driving document." },
        { text: "Walkthrough, because the author can simply explain the document", correct: false, why: "An author-led walkthrough does not provide the formal rules, roles, and metrics management requires." },
        { text: "No review, because dynamic testing will catch the issues later", correct: false, why: "Requirements cannot be dynamically tested and late discovery would be very costly for a critical document." },
      ],
      explanation: "Selecting a review type means matching formality to risk, objectives, and the need for metrics. A safety-critical, contract-relevant specification with a metrics goal calls for an inspection, the most formal review type.",
      workplaceExample: "For a medical-device requirements set feeding supplier contracts, the QA lead schedules a full inspection with a moderator, checklists, entry and exit criteria, and logged defect data.",
    },
  ],
};
