export default {
  courseSlug: "istqb-foundation-masterclass",
  moduleNumber: 1,
  syllabusTopic: "Fundamentals of Testing",
  questions: [
    {
      kLevel: "K1",
      questionText: "Which statement best describes what software testing is?",
      options: [
        { text: "A set of activities to discover defects and evaluate the quality of software work products", correct: true, why: "The syllabus defines testing as a set of activities to discover defects and evaluate the quality of software artifacts, not just running code." },
        { text: "A process that runs only after the code is complete to prove the software has no defects", correct: false, why: "Testing is not confined to post-coding execution and can never prove the absence of defects; both ideas are common misconceptions." },
        { text: "The activity of correcting the defects found in the source code", correct: false, why: "Correcting defects is debugging, a development activity, not testing." },
        { text: "A purely administrative process of writing documents that describe the software", correct: false, why: "Testing includes many non-documentation activities such as analysis, design, and execution, and its purpose is evaluation, not documentation." },
      ],
      explanation: "The ISTQB syllabus (Fundamentals of Testing) explains that testing is more than executing tests; it is a set of activities that both discover defects and evaluate the quality of work products. This includes static activities such as reviews as well as dynamic execution.",
      workplaceExample: "On an e-commerce checkout project, a tester reviews the requirements document for ambiguities and later executes payment scenarios, both of which count as testing.",
    },
    {
      kLevel: "K2",
      questionText: "A team believes that once testing is finished the software will be guaranteed defect-free. Why is this belief incorrect?",
      options: [
        { text: "Testing can show the presence of defects but cannot prove their absence", correct: true, why: "This is one of the seven testing principles: exhaustive testing is impossible, so passing tests reduce risk but cannot guarantee a defect-free product." },
        { text: "Testing always finds every defect if enough test cases are written", correct: false, why: "This contradicts the exhaustive-testing-is-impossible principle; you cannot test all inputs and paths." },
        { text: "Defects are only introduced during maintenance, not during testing", correct: false, why: "Defects can be introduced at any stage; this statement misstates when defects arise and does not explain the guarantee misconception." },
        { text: "Debugging removes all remaining defects automatically after testing", correct: false, why: "Debugging only addresses defects that have already been found and localized, and it can introduce new defects." },
      ],
      explanation: "The principle Tests show the presence of defects, not their absence means testing reduces the probability of undiscovered defects but never proves that none remain. Combined with the impossibility of exhaustive testing, no amount of passing tests guarantees a defect-free product.",
      workplaceExample: "A banking API passes its full regression suite before release, yet a rare currency-rounding defect surfaces in production, illustrating that passing tests did not prove absence of defects.",
    },
    {
      kLevel: "K2",
      questionText: "Which of the following is a typical objective of testing?",
      options: [
        { text: "To prevent defects by evaluating work products such as requirements and user stories", correct: true, why: "Reviewing requirements and designs early is a recognized test objective because it prevents defects from being built into later work products." },
        { text: "To assign blame to the developers who introduced defects", correct: false, why: "Assigning blame is not a test objective and contradicts the constructive, whole-team psychology of testing." },
        { text: "To guarantee that the system will never fail in operation", correct: false, why: "No test activity can guarantee a system never fails; testing reduces risk rather than eliminating it." },
        { text: "To replace the need for requirements analysis entirely", correct: false, why: "Testing complements analysis; it does not remove the need to define requirements." },
      ],
      explanation: "The syllabus lists typical test objectives including evaluating work products, preventing defects, finding failures, reducing risk, and verifying and validating the product. Preventing defects through early evaluation is one of these core objectives.",
      workplaceExample: "Before coding a mobile login screen, the QA team reviews the acceptance criteria and spots a missing account-lockout rule, preventing a defect before any code is written.",
    },
    {
      kLevel: "K2",
      questionText: "What is the key difference between testing and debugging?",
      options: [
        { text: "Testing identifies failures caused by defects, while debugging finds, analyzes, and fixes those defects", correct: true, why: "The syllabus distinguishes dynamic testing (which triggers failures) from debugging (locating the cause and correcting the defect)." },
        { text: "Debugging identifies failures, while testing fixes the underlying code", correct: false, why: "This reverses the two activities; fixing code is debugging, not testing." },
        { text: "Testing and debugging are two names for the same activity", correct: false, why: "They are distinct activities performed for different purposes and often by different roles." },
        { text: "Debugging can only be done after all testing is fully complete", correct: false, why: "Debugging happens whenever a failure is investigated, often interleaved with testing, not strictly afterward." },
      ],
      explanation: "According to Fundamentals of Testing, dynamic testing can show failures caused by defects, whereas debugging is the development activity that finds, analyzes, and removes the cause of those failures. Confirmation testing then checks that the fix resolved the failure.",
      workplaceExample: "A tester reports that a shopping cart shows the wrong total (a failure); a developer then debugs the pricing function, finds an incorrect tax calculation, and fixes it.",
    },
    {
      kLevel: "K1",
      questionText: "In the sequence that leads to a failure, which order of concepts is correct?",
      options: [
        { text: "A person makes an error, which introduces a defect, which may cause a failure", correct: true, why: "This is the exact error-defect-failure chain defined in the syllabus." },
        { text: "A failure introduces a defect, which causes an error", correct: false, why: "This reverses the causal chain; failures are the observable result, not the origin." },
        { text: "A defect creates an error, which produces a failure by itself", correct: false, why: "An error is the human mistake that precedes the defect, not something a defect creates." },
        { text: "A root cause is the same thing as a failure", correct: false, why: "A root cause is the fundamental reason a defect was introduced, which is different from an observable failure." },
      ],
      explanation: "The syllabus defines an error (mistake) as a human action that produces an incorrect result, a defect (fault or bug) as the flaw introduced in the work product, and a failure as the observable incorrect behavior when the defect is executed. Not every defect leads to a failure.",
      workplaceExample: "A developer misreads a spec (error) and codes a discount as 15 percent instead of 50 percent (defect), which a customer sees as an overcharge at checkout (failure).",
    },
    {
      kLevel: "K2",
      questionText: "How do quality assurance and testing relate to each other?",
      options: [
        { text: "Quality assurance is process-oriented and improves how work is done, while testing is product-oriented and evaluates the work products", correct: true, why: "The syllabus contrasts QA (process focus, prevention through good process) with testing (product focus, detecting failures and evaluating quality)." },
        { text: "Testing and quality assurance are identical terms with no difference", correct: false, why: "They are related but distinct: QA targets the process, testing targets the product." },
        { text: "Quality assurance replaces the need for testing when processes are mature", correct: false, why: "Good processes reduce defects but do not remove the need to evaluate the product through testing." },
        { text: "Testing focuses on the process while quality assurance focuses on the product", correct: false, why: "This reverses the two: QA is process-oriented and testing is product-oriented." },
      ],
      explanation: "In Fundamentals of Testing, quality assurance focuses on adherence to proper processes to provide confidence that quality will be achieved, whereas testing is one form of quality control that evaluates actual work products. Both contribute to overall quality management.",
      workplaceExample: "A QA lead defines a mandatory code-review checklist for the whole team (process), while testers execute integration tests against the banking service to find failures (product).",
    },
    {
      kLevel: "K1",
      questionText: "Which of the following is NOT one of the seven testing principles?",
      options: [
        { text: "Exhaustive testing guarantees a defect-free product", correct: true, why: "This is the opposite of the real principle, which states that exhaustive testing is impossible; so it is not a valid principle." },
        { text: "Early testing saves time and money", correct: false, why: "This is a genuine principle: finding defects early reduces the cost of fixing them." },
        { text: "Defects cluster together", correct: false, why: "This is a genuine principle: a small number of modules usually contain most defects." },
        { text: "Testing is context dependent", correct: false, why: "This is a genuine principle: testing is done differently depending on the context." },
      ],
      explanation: "The seven principles are: testing shows presence not absence of defects; exhaustive testing is impossible; early testing saves time and money; defects cluster together; tests wear out (the pesticide paradox); testing is context dependent; and absence-of-defects is a fallacy. A claim that exhaustive testing guarantees quality contradicts these.",
      workplaceExample: "A test manager for a mobile banking app prioritizes risk-based tests instead of trying every possible input combination, applying the principle that exhaustive testing is impossible.",
    },
    {
      kLevel: "K2",
      questionText: "A regression suite that once found many defects now rarely finds any, even though the product still has bugs. Which principle explains this?",
      options: [
        { text: "The pesticide paradox: repeating the same tests stops finding new defects", correct: true, why: "The pesticide paradox states that reusing identical tests loses effectiveness over time, so tests must be reviewed and updated." },
        { text: "Defects cluster together in a few modules", correct: false, why: "Defect clustering explains where defects concentrate, not why repeated tests stop finding them." },
        { text: "Testing is context dependent", correct: false, why: "Context dependence explains that approaches differ by situation, not the declining yield of unchanged tests." },
        { text: "Early testing saves time and money", correct: false, why: "Early testing addresses when to test, not the diminishing returns of repeated identical tests." },
      ],
      explanation: "The pesticide paradox principle says that running the same tests repeatedly eventually stops revealing new defects, so tests need to be regularly reviewed, revised, and augmented with new ones. This keeps the suite effective as the product evolves.",
      workplaceExample: "A team refreshes its e-commerce regression tests each quarter, adding scenarios for new promo-code rules, because the old fixed tests had stopped catching defects.",
    },
    {
      kLevel: "K2",
      questionText: "Why does the principle early testing saves time and money hold true?",
      options: [
        { text: "Defects found early, for example during requirements review, are cheaper to fix than those found in production", correct: true, why: "The cost of fixing a defect rises the later it is found, so early static and dynamic testing reduces overall cost." },
        { text: "Early testing means fewer testers are needed on the project", correct: false, why: "The principle concerns defect-fix cost and timing, not staffing levels." },
        { text: "Testing early proves the software has no defects", correct: false, why: "No testing proves absence of defects; this confuses two separate ideas." },
        { text: "Early testing removes the need for later test levels", correct: false, why: "Early testing complements later levels such as system and acceptance testing; it does not replace them." },
      ],
      explanation: "Fundamentals of Testing teaches that starting test activities early, including static testing of requirements and designs, catches defects before they propagate. Because the cost of correcting a defect grows the later it is detected, early testing lowers total cost and rework.",
      workplaceExample: "Reviewing a payment API specification uncovers a missing timeout requirement; fixing the spec costs minutes, whereas catching it after go-live would mean an emergency production patch.",
    },
    {
      kLevel: "K1",
      questionText: "Which principle warns that a small number of modules typically contain most of the defects?",
      options: [
        { text: "Defects cluster together", correct: true, why: "Defect clustering states that a minority of components usually accounts for the majority of defects, guiding where to focus testing." },
        { text: "Tests show the presence of defects, not their absence", correct: false, why: "This principle concerns what a passing test can conclude, not the distribution of defects." },
        { text: "Testing is context dependent", correct: false, why: "This principle concerns adapting the approach to the situation, not defect distribution." },
        { text: "The pesticide paradox", correct: false, why: "This principle concerns the fading effectiveness of repeated tests, not where defects concentrate." },
      ],
      explanation: "The defect clustering principle observes that defects are not evenly spread; a small number of modules often contains most of them, frequently reflecting complexity or churn. Testers use this to focus effort where failures are most likely.",
      workplaceExample: "Analysis of a logistics system shows that 80 percent of production incidents trace to the route-optimization module, so testers concentrate additional scenarios there.",
    },
    {
      kLevel: "K1",
      questionText: "The test process includes several activities. Which activity is concerned with checking progress against the plan and taking corrective action?",
      options: [
        { text: "Test monitoring and control", correct: true, why: "Monitoring compares actual progress to the plan, and control takes the corrective actions needed to meet objectives." },
        { text: "Test planning", correct: false, why: "Planning defines objectives and the approach up front, but does not track ongoing progress." },
        { text: "Test completion", correct: false, why: "Completion collects data from finished activities and reports results at the end, rather than steering progress during the work." },
        { text: "Test design", correct: false, why: "Design creates test cases and test data from the test conditions; it is not a progress-tracking activity." },
      ],
      explanation: "In the test process, test monitoring gathers information to assess progress against the plan using metrics and exit criteria, while test control directs corrective actions. Together they keep testing aligned with its objectives.",
      workplaceExample: "A test lead notices the daily pass rate for the checkout module is falling behind the plan and reallocates two testers to that area, an example of monitoring and control.",
    },
    {
      kLevel: "K2",
      questionText: "During which test activity are test conditions defined by analyzing the test basis to identify what should be tested?",
      options: [
        { text: "Test analysis", correct: true, why: "Test analysis examines the test basis to determine testable features and define test conditions (the what to test)." },
        { text: "Test design", correct: false, why: "Design turns those conditions into concrete test cases and data (the how), which happens after analysis." },
        { text: "Test implementation", correct: false, why: "Implementation prepares testware such as test procedures and environments, after design." },
        { text: "Test execution", correct: false, why: "Execution runs the tests and compares actual to expected results, well after conditions are identified." },
      ],
      explanation: "Test analysis evaluates the test basis (such as requirements or user stories) to identify testable features and establish test conditions, answering what to test. This is distinct from test design, which specifies how to test by creating test cases.",
      workplaceExample: "Reading a user story for a password-reset feature, a tester derives test conditions such as expired reset links and reused passwords before writing any concrete test cases.",
    },
    {
      kLevel: "K2",
      questionText: "Which pair correctly matches a test activity to its primary output?",
      options: [
        { text: "Test design produces test cases; test implementation produces test procedures and test data readiness", correct: true, why: "Design yields test cases from conditions, while implementation organizes them into executable procedures and prepares the environment and data." },
        { text: "Test analysis produces the final test summary report", correct: false, why: "The test summary report is an output of test completion, not analysis." },
        { text: "Test execution produces the test plan", correct: false, why: "The test plan is produced during planning; execution produces test results and incident reports." },
        { text: "Test planning produces defect fixes", correct: false, why: "Defect fixes come from debugging by developers, not from the planning activity." },
      ],
      explanation: "In the test process, test design creates test cases and coverage items from test conditions, and test implementation prepares the testware needed to run them, including test procedures, test suites, and a ready test environment. Each activity has characteristic work products.",
      workplaceExample: "For a mobile wallet, testers design cases for insufficient-balance transfers, then implement them into an automated suite with seeded test accounts and a staging environment.",
    },
    {
      kLevel: "K1",
      questionText: "What is testware?",
      options: [
        { text: "The work products produced during the test activities, such as test plans, test cases, test data, and test reports", correct: true, why: "Testware is the collective term for artifacts created and used during testing across the whole process." },
        { text: "Only the automated test scripts used to run tests", correct: false, why: "Scripts are one part of testware, but the term covers plans, cases, data, environments, and reports too." },
        { text: "The production software under test", correct: false, why: "The software under test is the test object, not testware." },
        { text: "The hardware on which the software runs in production", correct: false, why: "Production hardware is part of the operational environment, not testware." },
      ],
      explanation: "The syllabus defines testware as the work products created during the test process, including test plans, test conditions, test cases, test data, test scripts, test environments, and test reports. Managing testware and its versions is part of good test practice.",
      workplaceExample: "The test repository for a banking portal holds the test plan, 300 test cases, seeded customer data, and nightly execution reports, all of which are testware.",
    },
    {
      kLevel: "K2",
      questionText: "Why is traceability between the test basis and test work products valuable?",
      options: [
        { text: "It supports impact analysis and coverage measurement, so teams can see which requirements are tested and what a change affects", correct: true, why: "Traceability links requirements to tests and results, enabling coverage evaluation and assessment of the impact of changes." },
        { text: "It automatically fixes defects that are linked to requirements", correct: false, why: "Traceability provides visibility and links; it does not perform fixes." },
        { text: "It removes the need to write test cases because links replace them", correct: false, why: "Traceability connects test cases to the basis; it does not replace the cases themselves." },
        { text: "It guarantees that every requirement is defect-free once linked", correct: false, why: "Linking a requirement to a test does not guarantee the requirement or the test is free of defects." },
      ],
      explanation: "Fundamentals of Testing highlights traceability between the test basis, test conditions, test cases, and results as a way to measure coverage, assess the impact of changes, and support audits and reporting. It makes testing transparent and controllable.",
      workplaceExample: "When a regulator asks which tests cover a new anti-fraud requirement, the team follows traceability links from the requirement to its test cases and their latest pass/fail results.",
    },
    {
      kLevel: "K1",
      questionText: "Which two generic roles in testing does the syllabus describe?",
      options: [
        { text: "A test management role and a testing role", correct: true, why: "The syllabus describes a test management role (organizing and directing) and a testing role (performing the technical testing work)." },
        { text: "A debugging role and a coding role", correct: false, why: "These are development activities and are not the generic testing roles described." },
        { text: "A marketing role and a sales role", correct: false, why: "These are unrelated to the testing roles defined in the syllabus." },
        { text: "A requirements role and a deployment role", correct: false, why: "While related to the lifecycle, these are not the two generic testing roles the syllabus names." },
      ],
      explanation: "The syllabus identifies two principal roles: the test management role, responsible for the overall test process and leadership of the test team, and the testing role, responsible for the engineering aspects such as analysis, design, implementation, and execution. One person may perform both depending on context.",
      workplaceExample: "On a small startup team building a booking app, one senior engineer plans and reports on testing (management role) while also writing and running the test cases (testing role).",
    },
    {
      kLevel: "K2",
      questionText: "Why is a degree of independence of testing generally considered beneficial?",
      options: [
        { text: "Independent testers are more likely to recognize different kinds of failures due to differing assumptions and cognitive biases", correct: true, why: "Independence brings a fresh perspective and reduces author bias, so independent testers often find defects the author overlooked." },
        { text: "Independent testers can approve their own code faster", correct: false, why: "Independence is about separation from the author, not self-approval, which would reintroduce bias." },
        { text: "Independence removes the need for developers to test at all", correct: false, why: "Developers still test their own work; independence complements rather than replaces that." },
        { text: "Independence guarantees that all defects will be found", correct: false, why: "No level of independence guarantees finding all defects; it improves the chance of finding some, not all." },
      ],
      explanation: "The psychology of testing section explains that independence increases the effectiveness of finding defects because independent testers hold different assumptions than the authors and are less subject to author bias. Independence can range from developers testing their own code to a separate external test organization.",
      workplaceExample: "A separate QA team testing a checkout flow spots an edge case the original developer assumed could never happen, illustrating the value of independent perspective.",
    },
    {
      kLevel: "K2",
      questionText: "A tester must report a serious defect to a developer who is proud of the feature. Which approach best reflects good testing psychology?",
      options: [
        { text: "Communicate findings objectively and factually, focusing on the product and shared goals rather than blaming the person", correct: true, why: "Constructive, fact-based communication that focuses on the work product preserves collaboration and keeps the whole team aligned on quality." },
        { text: "Emphasize how many mistakes the developer made to make the severity clear", correct: false, why: "Blaming individuals damages relationships and undermines the collaborative goal of improving the product." },
        { text: "Avoid reporting the defect to keep the peace", correct: false, why: "Withholding defect information conflicts with the tester's objective of providing accurate quality information." },
        { text: "Report the defect only to management to bypass the developer", correct: false, why: "Bypassing the developer erodes trust and hinders the whole-team approach; direct, respectful communication is preferred." },
      ],
      explanation: "The psychology of testing emphasizes communicating defects constructively: stay objective, focus on the product and facts, and frame findings around shared quality goals to avoid triggering defensiveness. This supports collaboration between testers and the rest of the team.",
      workplaceExample: "A tester tells a developer that the funds-transfer screen accepts negative amounts, showing the reproduction steps and the requirement, rather than criticizing the developer's competence.",
    },
    {
      kLevel: "K2",
      questionText: "What does the whole-team approach to quality imply?",
      options: [
        { text: "Everyone on the team shares responsibility for quality, with testers and developers collaborating throughout", correct: true, why: "The whole-team approach means quality is a collective responsibility, with team members bringing their skills to testing tasks together." },
        { text: "Only the dedicated test team is responsible for quality", correct: false, why: "This contradicts the whole-team idea, which spreads responsibility across all roles." },
        { text: "Developers should never participate in any testing activity", correct: false, why: "In a whole-team approach developers actively contribute to testing, for example through unit tests and pairing." },
        { text: "Quality is guaranteed simply because the whole team is involved", correct: false, why: "Shared responsibility improves quality but does not guarantee a defect-free product." },
      ],
      explanation: "Fundamentals of Testing describes the whole-team approach, common in Agile, where any team member with the necessary knowledge participates in testing and quality is a shared responsibility. Collaboration between testers, developers, and business representatives strengthens outcomes.",
      workplaceExample: "On an insurance-quote feature, developers write unit tests, testers design end-to-end scenarios, and the product owner reviews acceptance criteria, all sharing responsibility for quality.",
    },
    {
      kLevel: "K1",
      questionText: "Which activity closes out testing by evaluating whether objectives were met and archiving useful testware?",
      options: [
        { text: "Test completion", correct: true, why: "Test completion checks that work is finished, archives reusable testware, reports results, and captures lessons learned." },
        { text: "Test analysis", correct: false, why: "Analysis happens early to identify what to test, not to close out testing." },
        { text: "Test monitoring and control", correct: false, why: "Monitoring and control run throughout to steer progress, but completion is the specific closing activity." },
        { text: "Test implementation", correct: false, why: "Implementation prepares testware to run, which precedes execution and completion." },
      ],
      explanation: "Test completion occurs at milestones such as a release or iteration end. It ensures activities are finished or documented, archives testware for reuse, produces a test summary report, and feeds lessons learned into future improvement.",
      workplaceExample: "After a mobile release, the team archives the automated suite, writes a test summary report, and records that flaky network tests should be stabilized next iteration.",
    },
    {
      kLevel: "K3",
      questionText: "A team has limited time to test a large payments release. Given the defect clustering and risk-based principles, which strategy is most appropriate?",
      options: [
        { text: "Focus deeper testing on the historically defect-prone and high-risk transaction modules first", correct: true, why: "Defect clustering and risk-based prioritization direct effort to areas most likely to fail and most costly if they do, maximizing value under time constraints." },
        { text: "Distribute the same shallow test effort evenly across every module regardless of risk", correct: false, why: "Uniform effort ignores clustering and risk, wasting time on low-risk areas while under-testing critical ones." },
        { text: "Attempt exhaustive testing of all input combinations to be safe", correct: false, why: "Exhaustive testing is impossible and infeasible in limited time, so it is not a viable strategy." },
        { text: "Skip testing and rely solely on the developers' confidence in their code", correct: false, why: "Author confidence is subject to bias and does not substitute for independent, risk-focused testing." },
      ],
      explanation: "Applying the defect clustering principle and risk-based prioritization, testers concentrate effort where failures are most probable and most impactful. This is a practical application of the principles that exhaustive testing is impossible and that testing is context dependent.",
      workplaceExample: "With two days before a payments release, the lead schedules intensive testing of the settlement and refund modules that caused past incidents, and only smoke tests for stable areas.",
    },
    {
      kLevel: "K3",
      questionText: "A new requirement is added late to a project. Using traceability, how should the test team respond most effectively?",
      options: [
        { text: "Trace the requirement to identify new test conditions and check which existing tests are affected, then update coverage", correct: true, why: "Traceability enables impact analysis: linking the new requirement to conditions and existing tests shows exactly what must be added or revised." },
        { text: "Rerun the entire old test suite unchanged and assume it covers the new requirement", correct: false, why: "The unchanged suite predates the requirement, so it cannot cover it; this misses new conditions." },
        { text: "Ignore the requirement because tests already exist for the feature area", correct: false, why: "Existing tests do not necessarily cover the new behavior; ignoring it leaves a coverage gap." },
        { text: "Delete all existing tests and start the test basis from scratch", correct: false, why: "Discarding valid tests wastes effort; traceability lets you extend coverage without starting over." },
      ],
      explanation: "Traceability between the test basis and test work products supports impact analysis when requirements change. The team follows links to determine which new test conditions are needed and which existing tests require updates, keeping coverage accurate and efficient.",
      workplaceExample: "When a new strong-authentication rule is added to a banking app, testers trace it to affected login tests, add multi-factor scenarios, and update the coverage matrix.",
    },
    {
      kLevel: "K2",
      questionText: "Which statement about verification and validation is correct?",
      options: [
        { text: "Verification checks whether the product is built according to specifications, while validation checks whether it meets user needs", correct: true, why: "Verification confirms conformance to specified requirements; validation confirms the product satisfies the actual needs of users and stakeholders." },
        { text: "Verification and validation both only occur after release", correct: false, why: "Both can occur throughout the lifecycle, including early static checks, not only after release." },
        { text: "Validation checks conformance to the specification and verification checks user needs", correct: false, why: "This reverses the definitions of the two terms." },
        { text: "Verification and validation mean exactly the same thing", correct: false, why: "They are related but distinct objectives, one focused on specifications and one on user needs." },
      ],
      explanation: "Among the typical test objectives, the syllabus distinguishes verification (are we building the product right, per the specification) from validation (are we building the right product, per user needs). Both contribute to confidence in the product.",
      workplaceExample: "A team verifies that a search API returns results in the specified JSON format, and validates that the search actually helps shoppers find the products they want.",
    },
    {
      kLevel: "K1",
      questionText: "Which of the following is an example of testing being context dependent?",
      options: [
        { text: "A safety-critical medical device is tested far more rigorously than an internal prototype dashboard", correct: true, why: "Adjusting rigor and approach based on the domain and risk is exactly what the context-dependent principle describes." },
        { text: "Every project uses the identical fixed set of test cases regardless of domain", correct: false, why: "Using identical tests everywhere ignores context, contradicting the principle." },
        { text: "Testing always requires the same amount of time on every project", correct: false, why: "Fixed time regardless of context contradicts context dependence." },
        { text: "The same tester must always perform every test on all projects", correct: false, why: "Staffing consistency is unrelated to and does not illustrate context dependence." },
      ],
      explanation: "The principle testing is context dependent states that testing is carried out differently in different contexts, driven by factors such as risk level, domain, regulations, and development approach. Higher-risk contexts warrant more thorough testing.",
      workplaceExample: "The same company tests a pacemaker firmware release with formal, documented, exhaustive risk analysis, but tests an internal marketing dashboard with quick exploratory checks.",
    },
    {
      kLevel: "K1",
      questionText: "Which statement correctly distinguishes a defect from its root cause?",
      options: [
        { text: "A defect is a flaw in a work product, while a root cause is the underlying reason the defect was introduced", correct: true, why: "The syllabus defines the root cause as the fundamental reason for a problem, which is deeper than the individual defect it produced." },
        { text: "A defect and a root cause are two names for the same failure", correct: false, why: "A defect is a specific flaw; the root cause explains why that and often other defects arose, so they are not the same." },
        { text: "A root cause is always a single line of incorrect code", correct: false, why: "A root cause is frequently a process or knowledge gap, not merely one line of code." },
        { text: "A defect is the human mistake and a root cause is the observable failure", correct: false, why: "The human mistake is an error and the observable behavior is a failure; this option mislabels both terms." },
      ],
      explanation: "Fundamentals of Testing distinguishes defects from their root causes: a root cause is the fundamental reason a defect was introduced, and analyzing it can prevent whole classes of similar defects. Root cause analysis targets process improvement, not just fixing the single defect.",
      workplaceExample: "Several checkout defects trace to one root cause: developers lacked a shared definition of how to handle currency rounding, so fixing the standard prevents future rounding defects.",
    },
  ],
};
