export default {
  courseSlug: "istqb-foundation-masterclass",
  moduleNumber: 2,
  syllabusTopic: "Software Development Lifecycle",
  questions: [
    {
      kLevel: "K1",
      questionText: "In a sequential development model such as Waterfall, when does the majority of formal test execution typically take place?",
      options: [
        { text: "After development is largely complete, in a dedicated later phase", correct: true, why: "Sequential models complete phases one after another, so most dynamic testing is concentrated late, after the code is built." },
        { text: "Continuously, in short overlapping cycles alongside every increment", correct: false, why: "That describes iterative or incremental delivery, not a strict sequential Waterfall model." },
        { text: "Only during the requirements phase, before any code exists", correct: false, why: "Reviews of requirements happen early, but dynamic test execution needs a test object, so most execution is later." },
        { text: "It is optional and usually skipped entirely in Waterfall", correct: false, why: "Testing is a defined phase in Waterfall; it is not skipped, merely positioned late." },
      ],
      explanation: "In sequential SDLC models like Waterfall, phases follow one another and dynamic test execution is concentrated in a distinct testing phase after coding. This is a defining characteristic of how the chosen SDLC model shapes the timing of test activities.",
      workplaceExample: "A banking core-system project using Waterfall builds all modules first, then runs a three-month system test phase before go-live, finding many integration defects late.",
    },
    {
      kLevel: "K2",
      questionText: "The V-model is often preferred over classic Waterfall for testing because it does which of the following?",
      options: [
        { text: "Pairs each development level with a corresponding test level, encouraging early test design", correct: true, why: "The V-model maps each specification or design activity to a matching test level, promoting early verification and validation." },
        { text: "Removes the need for a separate acceptance test level", correct: false, why: "The V-model retains acceptance testing; it does not remove any test level." },
        { text: "Guarantees that no defects reach production", correct: false, why: "No model can guarantee zero defects; testing reduces risk, it does not eliminate it." },
        { text: "Replaces all dynamic testing with static reviews", correct: false, why: "The V-model uses both static and dynamic testing; it does not replace one with the other." },
      ],
      explanation: "The V-model extends the sequential approach by associating each development phase with a corresponding test level, so test design starts as the matching specification is written. This early involvement is a key testing advantage of the V-model within sequential SDLCs.",
      workplaceExample: "On a medical-device project, testers draft system test cases from the system requirements while developers are still coding, so tests are ready the moment a build arrives.",
    },
    {
      kLevel: "K2",
      questionText: "Which statement best distinguishes iterative development from incremental development?",
      options: [
        { text: "Iterative refines the product through repeated cycles; incremental delivers the product in separately usable pieces", correct: true, why: "Iterative development revisits and refines functionality over cycles, while incremental development adds and delivers functionality piece by piece." },
        { text: "Iterative has no testing; incremental tests only at the end", correct: false, why: "Both approaches include testing throughout; neither omits it." },
        { text: "They are identical terms with no practical difference", correct: false, why: "They are related but distinct: one emphasizes refinement, the other emphasizes staged delivery of pieces." },
        { text: "Incremental is only used in Waterfall projects", correct: false, why: "Incremental delivery is characteristic of Agile and other non-sequential models, not Waterfall." },
      ],
      explanation: "Iterative models develop the system through cycles that refine features, whereas incremental models build and deliver the system in increments, each adding usable functionality. Understanding this distinction is part of recognizing how different SDLC models organize development and testing.",
      workplaceExample: "A retail app team ships a basic checkout increment first, then in later iterations refines the same checkout with saved cards and coupon logic based on user feedback.",
    },
    {
      kLevel: "K2",
      questionText: "How does an iterative, incremental SDLC most directly affect testing compared with a sequential model?",
      options: [
        { text: "Regression testing becomes more frequent because each iteration can affect previously working features", correct: true, why: "Repeated integration of new increments risks breaking existing behavior, so regression testing must run often." },
        { text: "Test levels are no longer needed", correct: false, why: "Test levels still apply; they are simply exercised within each iteration." },
        { text: "Regression testing becomes unnecessary because features are small", correct: false, why: "Smaller changes still risk regressions; frequent change actually increases regression need." },
        { text: "Only manual testing can be used", correct: false, why: "Frequent iterations typically increase reliance on automation, not manual-only testing." },
      ],
      explanation: "Because iterative and incremental models integrate change repeatedly, each iteration can disturb previously validated functionality, making frequent regression testing essential. This is a clear example of how the chosen SDLC influences testing effort and scope.",
      workplaceExample: "A SaaS team runs its full automated regression suite every sprint, because adding a new reporting feature last month accidentally broke an existing export function.",
    },
    {
      kLevel: "K1",
      questionText: "Which of the following is a good testing practice that applies regardless of the SDLC model in use?",
      options: [
        { text: "For every development activity there is a corresponding testing activity", correct: true, why: "This principle holds in any SDLC: testing should shadow development throughout, not appear only at the end." },
        { text: "Testing should always be performed only by developers", correct: false, why: "Who tests varies by context; this is not a universal good practice." },
        { text: "Test design should start only after all code is complete", correct: false, why: "Early test design is encouraged in every model; waiting for all code delays feedback." },
        { text: "Each SDLC needs a completely different set of testing principles", correct: false, why: "Core good practices are common across SDLCs; they are not reinvented per model." },
      ],
      explanation: "A recognized good testing practice for any SDLC is that each development activity has a corresponding test activity, so verification and validation accompany development throughout. These practices are model-independent and support early feedback in any lifecycle.",
      workplaceExample: "Whether a team runs Scrum or Waterfall, its test lead ensures every requirement written has an associated test condition drafted at the same time.",
    },
    {
      kLevel: "K1",
      questionText: "Which good testing practice states that testers should be involved in requirement and design reviews as early as possible?",
      options: [
        { text: "Early testing, often described as shift-left", correct: true, why: "Shift-left promotes involving testing activities, including reviews, as early as feasible in the lifecycle." },
        { text: "Late testing to conserve effort", correct: false, why: "Delaying testing raises the cost of fixing defects; it is not a good practice." },
        { text: "Testing only after user acceptance", correct: false, why: "Acceptance is the last level; restricting testing to it ignores earlier defect detection." },
        { text: "Avoiding tester involvement in reviews", correct: false, why: "Testers add value in reviews by spotting testability and ambiguity issues early." },
      ],
      explanation: "The shift-left approach embodies the early-testing principle by involving testers in reviews of requirements and designs before code exists. Finding defects early through static testing is cheaper than finding them during later dynamic execution.",
      workplaceExample: "A tester joining sprint refinement flags an ambiguous acceptance criterion for a login timeout, preventing a costly misunderstanding before any code is written.",
    },
    {
      kLevel: "K2",
      questionText: "In Test-Driven Development (TDD), what is the correct order of the core cycle?",
      options: [
        { text: "Write a failing test, write just enough code to pass it, then refactor", correct: true, why: "TDD follows red-green-refactor: a failing test first, minimal code to pass, then cleanup." },
        { text: "Write all production code, then write tests to match it", correct: false, why: "That is test-after development, the opposite of TDD's test-first approach." },
        { text: "Write documentation, then code, then delete the tests", correct: false, why: "TDD keeps its tests as a living regression safety net; it does not delete them." },
        { text: "Write acceptance tests only, with no unit tests", correct: false, why: "That resembles ATDD; TDD is driven by fine-grained developer tests." },
      ],
      explanation: "TDD is a test-first approach where a failing test is written before production code, enough code is added to make it pass, and the design is then refactored. It is one of the approaches in which testing drives development, as covered in the SDLC syllabus area.",
      workplaceExample: "A developer building a discount calculator writes a failing unit test for a 10 percent rule, codes just enough to pass it, then cleans up the method before adding the next rule.",
    },
    {
      kLevel: "K2",
      questionText: "Which approach centers on collaboratively defining acceptance tests, often expressed as concrete examples, before the corresponding functionality is implemented?",
      options: [
        { text: "Acceptance Test-Driven Development (ATDD)", correct: true, why: "ATDD derives acceptance tests collaboratively from requirements and examples before implementation." },
        { text: "Exploratory testing", correct: false, why: "Exploratory testing is unscripted learning during execution, not upfront acceptance-test derivation." },
        { text: "Load testing", correct: false, why: "Load testing is a non-functional activity, unrelated to deriving acceptance tests from examples." },
        { text: "Boundary value analysis", correct: false, why: "That is a black-box test technique for choosing values, not a development-driving approach." },
      ],
      explanation: "ATDD is a test-first approach in which acceptance tests are created collaboratively from requirements before functionality is built, guiding development toward agreed outcomes. It is one of the ways testing acts as a driver for development.",
      workplaceExample: "Before coding a refund feature, a business analyst, developer, and tester agree on example refund scenarios and turn them into acceptance tests that define done.",
    },
    {
      kLevel: "K2",
      questionText: "Behaviour-Driven Development (BDD) primarily aims to do which of the following?",
      options: [
        { text: "Express desired system behaviour in a readable, shared notation so business and technical stakeholders agree", correct: true, why: "BDD uses accessible given-when-then style scenarios so all stakeholders share one understanding of behaviour." },
        { text: "Replace all unit tests with performance tests", correct: false, why: "BDD is about shared behavioural understanding, not swapping test types." },
        { text: "Remove business stakeholders from the testing conversation", correct: false, why: "BDD deliberately includes business stakeholders through readable scenarios." },
        { text: "Guarantee full code coverage automatically", correct: false, why: "BDD improves shared understanding; it does not by itself guarantee coverage." },
      ],
      explanation: "BDD expresses intended behaviour in a natural, structured language that both business and technical people understand, improving communication and turning examples into executable tests. Like TDD and ATDD, it is a test-first approach that drives development.",
      workplaceExample: "A team writes given-when-then scenarios for a password reset so the product owner can confirm the expected behaviour before developers automate those scenarios.",
    },
    {
      kLevel: "K2",
      questionText: "In a DevOps environment, what is a primary benefit of continuous integration for testing?",
      options: [
        { text: "Fast, automated feedback on code quality because tests run on every integration", correct: true, why: "CI triggers automated builds and tests on each change, giving rapid feedback and catching defects early." },
        { text: "It removes the need for any automated tests", correct: false, why: "DevOps relies heavily on automated testing; it increases, not removes, that need." },
        { text: "It defers all testing until a manual release gate", correct: false, why: "DevOps aims to test continuously, not defer testing to a single late gate." },
        { text: "It eliminates the need for version control", correct: false, why: "Continuous integration depends on version control; it does not eliminate it." },
      ],
      explanation: "DevOps and continuous integration provide rapid automated feedback by building and testing on every change, so defects are surfaced quickly. This continuous, automated testing is central to how DevOps shapes testing activities in the SDLC.",
      workplaceExample: "Each time a developer pushes to the shared branch, the CI pipeline runs unit and integration tests within minutes and blocks the merge if any fail.",
    },
    {
      kLevel: "K1",
      questionText: "Which of the following is a recognized risk or limitation of relying on DevOps and heavy test automation?",
      options: [
        { text: "It may require significant setup and can shift, rather than remove, the need for skilled testing", correct: true, why: "DevOps demands tooling investment and skilled people; automation supports but does not replace human testing insight." },
        { text: "It makes all manual and exploratory testing pointless", correct: false, why: "Exploratory and other human testing remain valuable; automation cannot cover everything." },
        { text: "It guarantees defect-free releases", correct: false, why: "No approach guarantees defect-free software; DevOps reduces but cannot remove risk." },
        { text: "It prevents any feedback from reaching developers", correct: false, why: "The opposite is true: DevOps improves and speeds developer feedback." },
      ],
      explanation: "While DevOps improves feedback and consistency, it introduces setup and tooling costs and still depends on skilled testers for activities automation cannot cover, such as exploratory testing. Recognizing both benefits and risks is part of understanding DevOps and testing.",
      workplaceExample: "A startup adopts DevOps but still schedules exploratory test sessions each release, because automated checks missed a confusing but technically valid checkout flow.",
    },
    {
      kLevel: "K2",
      questionText: "What is the main idea behind the shift-left approach to testing?",
      options: [
        { text: "Perform testing activities earlier in the lifecycle to find defects sooner", correct: true, why: "Shift-left moves testing tasks earlier so defects are detected and corrected when they are cheaper to fix." },
        { text: "Move all testing to the final release stage", correct: false, why: "That is shift-right or late testing, the opposite of shift-left." },
        { text: "Assign testing exclusively to the operations team", correct: false, why: "Shift-left is about timing, not about reassigning testing to operations." },
        { text: "Test only the left-hand modules of the architecture", correct: false, why: "Left here refers to earlier in time on the timeline, not a physical part of the system." },
      ],
      explanation: "Shift-left means starting testing activities earlier in the SDLC, including static testing and early test design, to catch defects when correction is least expensive. It is a widely recommended good practice across modern lifecycles.",
      workplaceExample: "A team introduces static code analysis and requirement reviews in the first sprint, catching a null-handling flaw during design rather than in a later system test.",
    },
    {
      kLevel: "K1",
      questionText: "What is the purpose of a retrospective in an iterative or Agile SDLC?",
      options: [
        { text: "To reflect on what went well and what to improve, feeding process improvement", correct: true, why: "Retrospectives are structured reflection points used to identify improvements to process, tools, and collaboration." },
        { text: "To assign blame for defects found in the last release", correct: false, why: "Retrospectives are blameless improvement sessions, not blame assignment." },
        { text: "To write the detailed test cases for the next release", correct: false, why: "Test-case writing is a separate activity; retrospectives focus on process improvement." },
        { text: "To approve the production deployment", correct: false, why: "Deployment approval is a release decision, not the purpose of a retrospective." },
      ],
      explanation: "Retrospectives give the team a regular opportunity to review the completed iteration and agree improvements, which can strengthen test effectiveness and efficiency. They are a common good practice that supports continuous improvement across the SDLC.",
      workplaceExample: "In a sprint retrospective the team notices flaky automated tests wasted time, and they agree to stabilize the test environment before the next sprint.",
    },
    {
      kLevel: "K1",
      questionText: "Which test level focuses on testing individual components or modules in isolation?",
      options: [
        { text: "Component (unit) testing", correct: true, why: "Component testing verifies individual units or modules separately, often by developers, against their detailed design." },
        { text: "System testing", correct: false, why: "System testing evaluates the whole integrated system, not isolated units." },
        { text: "Acceptance testing", correct: false, why: "Acceptance testing validates fitness for use by the business, not isolated components." },
        { text: "Integration testing", correct: false, why: "Integration testing checks interactions between components, not a single component alone." },
      ],
      explanation: "Component (unit) testing is the test level that examines individual modules in isolation, typically using the detailed design or code as its test basis. Distinguishing the objectives and test basis of each level is core to the SDLC syllabus.",
      workplaceExample: "A developer writes unit tests for a single date-parsing function, mocking its dependencies so only that function's logic is exercised.",
    },
    {
      kLevel: "K2",
      questionText: "What is the primary objective of integration testing?",
      options: [
        { text: "To expose defects in the interfaces and interactions between integrated components or systems", correct: true, why: "Integration testing targets the interfaces and data exchange between parts, where component testing cannot reach." },
        { text: "To confirm the system meets business needs for release", correct: false, why: "That is the objective of acceptance testing, not integration testing." },
        { text: "To test a single component fully in isolation", correct: false, why: "Isolated single-component testing is component testing, not integration testing." },
        { text: "To measure only the response time of the whole system", correct: false, why: "Response time is a non-functional concern typically evaluated at system testing." },
      ],
      explanation: "Integration testing concentrates on the interfaces and interactions between components (component integration) or between systems (system integration), using interface and architectural specifications as its test basis. Its objective differs from testing components alone or the whole system.",
      workplaceExample: "After unit-testing the payment module and the order module separately, the team tests that an order correctly triggers and receives a payment confirmation across the two.",
    },
    {
      kLevel: "K2",
      questionText: "Which of the following is the typical test basis for system testing?",
      options: [
        { text: "System and software requirement specifications and use cases", correct: true, why: "System testing verifies end-to-end behaviour against system-level requirements and specified behaviour." },
        { text: "The detailed low-level design of a single class", correct: false, why: "Detailed design of one unit is the basis for component testing, not system testing." },
        { text: "Only the user's informal verbal expectations", correct: false, why: "Acceptance testing may lean on user needs, but system testing uses specified requirements." },
        { text: "The database index configuration file", correct: false, why: "A single configuration file is not the defined test basis for system-level behaviour." },
      ],
      explanation: "System testing evaluates the behaviour of the whole integrated system, using system and software requirement specifications, use cases, and risk analyses as its test basis. Knowing the test basis and test object for each level is central to this syllabus topic.",
      workplaceExample: "The team runs end-to-end scenarios for an insurance quote system against the documented system requirements, covering the full quote-to-policy flow in a production-like environment.",
    },
    {
      kLevel: "K2",
      questionText: "Who most commonly performs acceptance testing, and what is its main objective?",
      options: [
        { text: "Customers or users, to establish confidence that the system is fit for purpose and ready for use", correct: true, why: "Acceptance testing validates readiness and fitness for use, typically from the perspective of users or customers." },
        { text: "Developers, to check the internal logic of each function", correct: false, why: "Internal-logic checking by developers is component testing, not acceptance testing." },
        { text: "Testers, to expose interface defects between modules", correct: false, why: "Interface defect detection is the aim of integration testing." },
        { text: "Operations staff, to measure code coverage percentages", correct: false, why: "Coverage measurement is a technique used earlier; it is not the objective of acceptance testing." },
      ],
      explanation: "Acceptance testing focuses on building confidence that the system is fit for purpose and ready for deployment, and is often performed by or on behalf of customers and users. Its objective and typical actors distinguish it from earlier test levels.",
      workplaceExample: "Before rolling out a new HR portal, a group of HR staff run user acceptance tests against real business processes to confirm the system supports their daily work.",
    },
    {
      kLevel: "K2",
      questionText: "Which of the following best describes functional testing?",
      options: [
        { text: "Evaluating what the system does against specified functional requirements", correct: true, why: "Functional testing checks the functions the system should perform, based on functional requirements." },
        { text: "Evaluating how well the system performs, such as speed and capacity", correct: false, why: "That describes non-functional testing, which addresses quality characteristics like performance." },
        { text: "Examining internal code structure to derive test cases", correct: false, why: "That is white-box (structure-based) testing, a technique category, not functional testing." },
        { text: "Testing only after the system is retired from service", correct: false, why: "Functional testing occurs during development and maintenance, not after retirement." },
      ],
      explanation: "Functional testing assesses what the system does, verifying behaviour against functional requirements and specifications. It is contrasted with non-functional testing and with structure-based (white-box) approaches in the test types section of the syllabus.",
      workplaceExample: "A tester verifies that a search feature returns the correct products for various keywords, confirming the function behaves as the requirements state.",
    },
    {
      kLevel: "K2",
      questionText: "Which of the following is an example of non-functional testing?",
      options: [
        { text: "Performance testing that measures response time under expected load", correct: true, why: "Performance is a quality characteristic, so measuring response under load is non-functional testing." },
        { text: "Verifying that a login accepts valid credentials", correct: false, why: "Checking correct login behaviour is functional testing of what the system does." },
        { text: "Checking that a calculation returns the right total", correct: false, why: "Confirming correct results is functional testing, not a quality-characteristic test." },
        { text: "Confirming a menu item opens the correct screen", correct: false, why: "Navigation to the correct screen is functional behaviour, not a non-functional attribute." },
      ],
      explanation: "Non-functional testing evaluates quality characteristics such as performance, usability, reliability, and security, describing how well the system behaves rather than what it does. Performance testing under load is a classic non-functional example from the test types syllabus area.",
      workplaceExample: "Before a ticket-sales launch, the team runs a load test simulating 10,000 concurrent buyers to confirm the site stays responsive under peak demand.",
    },
    {
      kLevel: "K2",
      questionText: "White-box (structure-based) testing derives test cases primarily from which source?",
      options: [
        { text: "The internal structure or implementation of the test object, such as code and control flow", correct: true, why: "White-box testing uses knowledge of internal structure, like code and paths, to design and measure tests." },
        { text: "Only the external requirements, with no knowledge of the code", correct: false, why: "Deriving tests solely from external behaviour is black-box testing." },
        { text: "User complaints gathered after release", correct: false, why: "Post-release complaints are not the structural basis for white-box test design." },
        { text: "The marketing brochure for the product", correct: false, why: "A brochure is not a technical basis for structure-based test derivation." },
      ],
      explanation: "White-box testing is based on the internal structure of the test object, such as code, control flow, and architecture, and can measure structural coverage. It contrasts with black-box testing, which is based on external behaviour, in the test types syllabus content.",
      workplaceExample: "A developer inspects the branches of a pricing algorithm and designs tests to ensure every decision path, including the rarely hit discount branch, is executed at least once.",
    },
    {
      kLevel: "K2",
      questionText: "Which pair correctly matches the testing type to its basis?",
      options: [
        { text: "Black-box testing is based on external behaviour; white-box testing is based on internal structure", correct: true, why: "Black-box derives tests from specifications and behaviour, while white-box derives them from internal structure." },
        { text: "Black-box testing is based on source code; white-box testing is based on requirements", correct: false, why: "This reverses the definitions; black-box uses behaviour, white-box uses code." },
        { text: "Both black-box and white-box testing are based only on the source code", correct: false, why: "Black-box does not require code knowledge; it works from external behaviour." },
        { text: "Both are based only on user manuals", correct: false, why: "White-box specifically relies on internal structure, not user manuals." },
      ],
      explanation: "Black-box (behaviour-based) testing designs tests from specifications and external behaviour, whereas white-box (structure-based) testing designs and measures tests from internal structure. Correctly distinguishing these is a core objective of the test types syllabus area.",
      workplaceExample: "A tester uses black-box equivalence classes to check a form's validation from the outside, while a developer uses white-box coverage to ensure each validation branch executes.",
    },
    {
      kLevel: "K2",
      questionText: "A defect was fixed in the checkout module. Running the previously failing test again to verify the fix is an example of which activity?",
      options: [
        { text: "Confirmation testing", correct: true, why: "Confirmation testing re-runs the tests that failed to confirm the original defect is now resolved." },
        { text: "Regression testing", correct: false, why: "Regression testing checks that the fix has not broken other, previously working areas." },
        { text: "System testing", correct: false, why: "System testing is a test level; the activity described is specifically re-testing a fix." },
        { text: "Load testing", correct: false, why: "Load testing evaluates performance under load, unrelated to verifying a specific fix." },
      ],
      explanation: "Confirmation testing (re-testing) executes the test cases that previously failed to confirm that the defect has been successfully fixed. It is distinct from regression testing, which looks for unintended side effects elsewhere.",
      workplaceExample: "After developers patch a bug where discount codes were ignored, the tester re-runs the exact failing scenario and confirms the discount now applies correctly.",
    },
    {
      kLevel: "K3",
      questionText: "A team fixes one defect late in a release with very limited time before deployment. Which combination of activities best manages the risk introduced by the change?",
      options: [
        { text: "Confirmation testing of the fix plus a risk-based selection of regression tests around the affected areas", correct: true, why: "You confirm the fix works and then run targeted regression tests where the change is most likely to have side effects, given time limits." },
        { text: "Confirmation testing only, skipping any regression testing", correct: false, why: "Skipping regression ignores the risk that the change broke other functionality." },
        { text: "Re-running the entire regression suite manually with no confirmation test", correct: false, why: "Without confirmation you have not verified the fix, and a full manual rerun is impractical in limited time." },
        { text: "No testing, because only one line changed", correct: false, why: "Even small changes can cause regressions; testing the change is still required." },
      ],
      explanation: "Confirmation testing verifies the specific fix, while regression testing detects unintended side effects; under time pressure a risk-based selection of regression tests focuses effort where side effects are most likely. Applying both, prioritized by risk, is the recommended response to a late change.",
      workplaceExample: "With one day before release, a tester re-runs the failed order-total test to confirm the fix, then runs the automated regression tests covering orders, payments, and invoicing rather than the entire suite.",
    },
    {
      kLevel: "K1",
      questionText: "What is maintenance testing?",
      options: [
        { text: "Testing performed on an existing operational system after changes, migration, or retirement", correct: true, why: "Maintenance testing evaluates changes to a system in operation and the impact of those changes on the unchanged parts." },
        { text: "Testing done only before a system is first released", correct: false, why: "That is initial development testing; maintenance testing occurs after the system is in operation." },
        { text: "A synonym for component testing", correct: false, why: "Component testing is a test level; maintenance testing is triggered by changes to a live system." },
        { text: "Testing that is only ever performed manually", correct: false, why: "Maintenance testing can be manual or automated; the defining trait is that it follows changes to an operational system." },
      ],
      explanation: "Maintenance testing is carried out on an existing operational system whenever it is modified, migrated, or retired, and includes both testing the change and regression testing the parts that were not changed. Its scope depends on the risk and size of the change.",
      workplaceExample: "After a live payroll system is patched for a new tax rule, the team tests the new rule and regression-tests existing pay calculations to ensure nothing else broke.",
    },
    {
      kLevel: "K2",
      questionText: "Which of the following is a typical trigger for maintenance testing?",
      options: [
        { text: "Migration of the operational system to a new platform or environment", correct: true, why: "Migration is a recognized maintenance trigger, requiring operational and conversion testing on the moved system." },
        { text: "Writing the first line of code for a brand-new product", correct: false, why: "Initial development is not maintenance; maintenance applies to systems already in operation." },
        { text: "Choosing which SDLC model to adopt for a new project", correct: false, why: "Selecting an SDLC model is a planning decision, not a maintenance-testing trigger." },
        { text: "Drafting the original requirements specification", correct: false, why: "Initial requirements work precedes operation; maintenance testing follows changes to a live system." },
      ],
      explanation: "Maintenance testing is triggered by modifications such as enhancements and corrective fixes, by environment changes like migration or upgrades, and by planned retirement of a system. Recognizing these triggers is part of understanding maintenance testing in the SDLC syllabus.",
      workplaceExample: "When an insurer moves its policy system from on-premise servers to the cloud, the team runs maintenance tests to confirm the migrated system still processes claims correctly.",
    },
  ],
};
